### PR TITLE
elpreqpr added

### PR DESCRIPTION
**Pull request by sctfn**

### CODE REVIEW

**Comment by benjub** [comment]
Worth proving these biconditional versions ? (sorry for the annoyance!)

elpreqprlem $p |- ( ( A e. _V \\/ B e. _V ) <-> E. x { A , B } = { A , x } ) $=

elpreqpr $p |- ( A e. { B , C } <-> ( E. x { B , C } = { A , x } /\ A e. _V ) ) $=

**Comment by nmegill** [comment]
> Worth proving these biconditional versions ? (sorry for the annoyance!)
> 
> elpreqprlem $p |- ( ( A e. _V \\/ B e. _V ) <-> E. x { A , B } = { A , x } ) $=
> 
> elpreqpr $p |- ( A e. { B , C } <-> ( E. x { B , C } = { A , x } /\ A e. _V ) ) $=

Personally I think the A,B e. _V terms make them a little inelegant, and I don't see them being useful in proofs.  I think they should be postponed until an actual need arises for them (unless you want to put them in your mathbox, which is ok).

@sctfn There are some tab/space issues causing the CI checks to fail.

@avekens Is your proof bigger or smaller?  I think it would be interesting to have both for a while (say for a year by using \*OLD for the longer one) to see different proof techniques.

**Comment by benjub** [comment]
Note for the record: a nicer form for the biconditional of elpreqpr is
|- ( A e. V -> ( A e. { B , C } <-> E. x { B , C } = { A , x } ) )

**Comment by avekens** [comment]
@benjub I'll provide your proposed biconditional form with PR #1903.

**Pull request merged**
