### PR TITLE
Added metakunt's mathbox

### LINKED ISSUE #3908: Newbie here, I created a proof with mmj2. How do I add the proof to the database
So the mmp file format looks different than the mm file format. And for the love of god I couldn't find any utility to convert it.
The mmj2 repo help says that there is no functionality to add a proof automatically.

In the attachment there is a file of a subproof I am hoping is helpful. What I want to show is that a function is a permutation.
[proofsandsupproofs.zip](https://github.com/metamath/set.mm/files/14890283/proofsandsupproofs.zip)

In the zip archive there are three files. One is a subproof that mmj2 already says is correct. (File: noideahowtonameit.mmp)
The second and third one is the actual proof .
Here I am still debating if I can generalize to include the case ( 1 ... 0 ) --> ( 1 ... 0 ) which is a map from the empty to the empty set.
This is a map, which should also be bijective, so it should work.
I want to show that the function defined by F is a permutation. The domain is ( 1 ... N ) where N is in NN0 (here I am debating if NN0 is better than NN, it might make more sense to define it that way, but the only use case will be N in NN). Let the domain be A.
I want to show that F: A->A  is a function from A to A.
Then I planned to use the fact that A is finite together with an injection/surjection (I still don't know which one is easier) -> F bijective.

Let i \in \{1,...,m\}
The function F is defined by two if statements. In Latexlike it would be something like
\{1,...,m\} -> \{1,...,m\}
j |-> m-i+j+\chi(m-i+j,i) if 1 \leq j \leq i-1
j |-> j if i=j
j |-> j-i+\chi(j-i,i) i+1 \leq j \leq m

Eventually I want to show that this is a permutation. For now, I'd be more than happy to show that it is a function with dom=cod=\{1,...,m\}

This is why I developed this new lemma. My hope is that I can show 
(x e. ( 1 ... M ) -> bla)
by showing 
(x e. (1 ... M ) and x = I ) -> bla
(x e. (1 ... M ) and x \neq I  and  x < l) -> bla
(x e. (1 ... M ) and x \neq I  and not ( x < l )) -> bla

where bla is the fact that the evaluation of F(x) is in (1...m)
Then I can use my theorem to eliminate all, such that the unification works. But I didn't find a good way. The only thing I've found is a syllogism rule, which is quite helpful, but I didn't find how I can move antecedents inside and outside of the if statements.

### PR DESCRIPTION
**Pull request by metakunt**
Fixes #3908

### CODE REVIEW

**Comment by tirix** [comment]
The mathbox is empty right now, if you'd like to keep this PR open until there are contents, you can convert it to "Draft".
If you prefer to have this change merged (e.g. to try out the review and submission process), I'd be fine with that too.

**Comment by wlammen** [comment]
It should also be noted that mathboxes are kept in alphabetical order.  This raises the question whether you want to appear under your real name, or rather under the pseudonym metakunt.  In any case, register with the list of contributors starting at line 36 of set.mm.
And above all, you first have to get the syntax right.  Note the red alert "Some checks were not successful".  4 verifiers refused to accept your suggestion.  Look up the details by clicking on the link to the right of a failed check.  For example, the first one indicates you either nested comments, or forgot to add a closing $) tag.

**Comment by metakunt** [comment]
Ah yeah, thanks @wlammen I have fixed the issues (hopefully),

To be honest, my goal is to prove a result from my work, and move it in the permanent section once complete. For now, a pseudonym should suffice, as I can later on insert my real name, if I so desire.

Also @tirix I've added a lemma I'll hopefully use. I was astonished that such a simple lemma stands unproven in the database.

**Comment by tirix** [comment]
It's quite natural to not find the theorems we want, or not written the way we wished, in the database. This happens all the time (to me too).

Typically for that case I would use [`~impbida`](https://us.metamath.org/mpeuni/impbida.html), with the $\varphi$ of `~impbida` being a conjunction itself, if needed.

The thing with first order logic is that there are so many ways to combine terms that there is a huge number of possible theorems to build. Those in the database are considered enough, even if more could be built using 2 or 3 steps. I think Norm said somewhere at the time, that by default, he would not accept additions to the FOL part of the database (someone might find the link?).

But your mathbox is your own drawing board / experiment field, so you are free to add anything you want there and play with new concepts anyway (as long as the CI is not broken of course)

**Comment by metakunt** [comment]
Ah @tirix while we're at it. My original issue would by this pr be closed https://github.com/metamath/set.mm/issues/3908
As I've then successfully added a proof.

Shall I close the issue and reopen a new one?

**Comment by metakunt** [comment]
Also I have no idea why the last one is failing. I assume it is this line 
?Warning: the last line in file "set.mm" is incomplete.
But I don't know what is missing there, as all I've done is add a mathbox

Edit: I think I've solved it.

**Comment by tirix** [comment]
> I assume it is this line
> ```
> ?Warning: the last line in file "set.mm" is incomplete.
> ```

I think you've ended up deleting the newline at the end of the file's last line.
TBH I did not know this was a requirement!

**Comment by metakunt** [comment]
Should I squash the commits or is it done automatically?

**Comment by tirix** [comment]
Normally, the conditions are:
- all tests have passed,
- the PR's got a few approvals.

Then someone merges the commits.

For the first condition the tests need to be rerun (just to be sure). This is your first contribution, so it seems tests are not run automatically, and some member need to approve the runs. I'll approve it but don't see the button appearing yet.

For the second condition, I usually wait at least one day or two if there's no emergency (like, build is broken on the `develop` branch). You can continue to work with your local revision in the mean time anyway.

**Comment by metakunt** [comment]
Ugh, what is the script called which autoformats set.mm accordingly? So that I can test it locally?

**Comment by tirix** [comment]
> Ugh, what is the script called which autoformats set.mm accordingly? So that I can test it locally?

That's `scripts/rewrap`.

It's mentioned in the "[contributing](https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md#formatting-recommendation-prior-to-submitting-a-pull-request)" page.

**Comment by tirix** [comment]
> Ah @tirix while we're at it. My original issue would by this pr be closed #3908 As I've then successfully added a proof.
> 
> Shall I close the issue and reopen a new one?

I realize considering #3908's title is "_how do I add a proof to the database?_", the correct (and shorter) answer may maybe have been "check out [CONTRIBUTING.md](https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md)"!

If by merging a PR an existing issue is fixed, one can simply add a line:

Fixes #3908 

In ~~the conversation~~ the pull request's description or in a commit message, and the issue will [automatically be closed by GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when the PR is merged.

Anyway it's also easy to close an issue by hand, once you're happy with the answers you got (or reluctantly accepted the community's differing majority opinion!..)

More generally about "where should I post questions?":

- Generally GitHub issues are maybe not the best suited for "getting support" about writing new proofs, I think them rather as pointing out issues with the database, or exploring suggestions on how to enhance it.
- There is also the "[Proof Assistant Stack Exchange](https://proofassistants.stackexchange.com/questions/tagged/metamath)" which might better fit the question/answer format, should be highly searchable, and some adds visibility to Metamath.
- I remember at some time there was a suggestion to use Zulip Chat, and also a GitHub-based chat, but none really took off. Github has some discussion feature but we're also not using it currently.
- There is of course the mailing list, but a modern messaging app would be better.

Anyway I think everybody will be glad to help through any medium you use!

**Review by tirix — APPROVED** [review]
Approved.

As mentioned in the discussion, I'd rather suggest using `~impbida` than adding a new FOL theorem, but no problem with having this in a mathbox.

**Comment by metakunt** [comment]
Fixes #3908

**Comment by metakunt** [comment]
Alright, if I want to use the mailing list? Can I just write an email to the mailing list? Because I don't want to use a google account.

**Comment by wlammen** [comment]
The closest we have for your theorem andiff in the current set.mm is impbid21d, then followed by either an imp or impcom, depending on how the conjunct is ordered.

**Comment by tirix** [comment]
I'll merge this, since I see no more remarks.
Congratulations for your first contribution, @metakunt !

**Pull request merged**
