### PR TITLE
Initial version of "conventions" as a theorem

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
I believe the failures are because the symbol tarball upstream doesn't have some new symbols.

The errors are:

~~~~
MM> verify markup *
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
?Warning:  The file "_finvbar.gif", which is referenced in an htmldef
statement, was not found.
?Warning:  The file "_dlbrack.gif", which is referenced in an htmldef
statement, was not found.
?Warning:  The file "_drbrack.gif", which is referenced in an htmldef
statement, was not found.
~~~~

**Comment by nmegill** [comment]
On 12/27/16 10:03 PM, David A. Wheeler wrote:
> I believe the failures are because the symbol tarball upstream doesn't
> have some new symbols.

That's correct.  I am running a new build right now that will go to the 
us.metamath.org site sometime tomorrow, so this should go away.

Norm

>
> The errors are:
>
> |MM> verify markup * Checking statement label conventions... Checking
> latexdef, htmldef, althtmldef... ?Warning: The file "_finvbar.gif",
> which is referenced in an htmldef statement, was not found. ?Warning:
> The file "_dlbrack.gif", which is referenced in an htmldef statement,
> was not found. ?Warning: The file "_drbrack.gif", which is referenced in
> an htmldef statement, was not found.

**Comment by digama0** [comment]
Don't worry about failing Travis as long as the error log shows that they are not issues you created. We can always re-run Travis on the same commit after metamath.org is updated.

**Comment by david-a-wheeler** [comment]
No problem, I thought that was the case.  Also, don't worry if something is missing - we can add those later.

Key questions: Does the proposed location make sense?  Are there any serious errors?

I'd like to merge this into the "develop" branch, add a hyperlink to it from the main MPE page, and then we can all tweak it to taste.

**Comment by digama0** [comment]
I will defer to Norm on this one; the means by which we generate web pages depends on `metamath.exe` having the proper support. Merging should not be a problem since the change is localized.

**Comment by nmegill** [comment]
Hi David,

Could you do the following:

1. 'write source set.mm /rewrap' - this will put 7 spaces of indentation 
in front of each line.  But because of the <HTML> tag, it will not 
rewrap lines (even outside of the <HTML>...</HTML>) but just break them 
as needed to obtain =< 79 chars per line.  We run /rewrap routinely, so 
it should survive that if it stays in set.mm.

2. The <HTML> tag (case sensitive) is crudely implemented in 
metamath.exe, originally as an experiment for theorem inf3 and later 
adopted for many theorems in AS's mathbox.  Use 'show statement 
conventions/alt_html' to make sure it renders as you expect.  Also check 
that it passes validator.w3c.org.  The code basically just sets an 
internal flag that "there is an <HTML> in this comment" for the whole 
comment and outputs everything as-is (I think after removing "<HTML>" 
and "</HTML>") except for ~ label, ` math `, and [bib], which are 
processed normally.

I can't think of anything else at the moment, so after that it should be 
OK to merge into develop.

Norm

**Comment by david-a-wheeler** [comment]
Ok, I did a "write source set.mm /rewrap" (#1), and re-checked the generated HTML output (#2).  Looks okay to me.

I'm going to wait for the Travis tests to see if there are any new problems.

If there are no new problems, I plan to merge.

**Comment by nmegill** [comment]
It is posted on us2 now, with a mention on the mmrecent page.

Norm

**Comment by david-a-wheeler** [comment]
Excellent, thanks!

**Pull request merged**
