### PR TITLE
wl-nfd, conditions when df-nf and nf2 semantically coincide

### PR DESCRIPTION
**Pull request by wlammen**
1. precise conditions when nf2 follows from df-nf and vice versa;
2. wl-nfd is the first theorem depending on more theorems than the original;
3. remove some outdated old theorems.

### CODE REVIEW

**Comment by wlammen** [comment]
The mm2 verifier fails, because it cannot setup a graphics environment. Sorry, I cannot help it. This server-side misconfiguration is beyond my scope and responsability.

No, the error was on my side. The crucial message was hidden above the range of my screen.  Once I learned how to scroll the message pane, I was able to understand the error type and fixed the reason for it.

**Comment by wlammen** [comment]
fixed a grammar error

**Comment by benjub** [comment]
>     1. precise conditions when nf2 follows from df-nf and vice versa;

Indeed, this is in the comments of wl-nf-nf2 and wl-nf2-nf of this PR, which give the conditions that I gave in the comment of ~df-bj-nf. It's a good thing that I wrote yesterday in the discussion group https://groups.google.com/g/metamath/c/oh4-Z2mMKBE/m/RsMoVTpRBwAJ, I quote, "see the comment of ~df-bj-nf".  By the way: in that google group discussion, I was giving some links to earlier discussions and mathbox additions on that precise topic.

**Comment by wlammen** [comment]
@benjub I read that comment, but I could not figure out its meaning.  In hindsight, I understand your words.
Maybe this is the time to start a true collaboration.  My time is limited, and I can dedicate at most an hour a day to Metamath.  I hereby grant you contribution/modification rights to the section tagged wl-section-nf.  Lets see how this pans out.

**Comment by benjub** [comment]
Thanks @wlammen. Time permitting, I may add some theorems to your mathbox (maybe move some of the theorems following df-bj-nf to your mathbox).

**Pull request merged**
