### PR TITLE
 Graph theory: neighbors, complete graphs, universal vertices

### PR DESCRIPTION
**Pull request by avekens**
Enhancement of Graph theory (in my Mathbox):

- Definition of neighbors (of a vertex), complete (undirected simple) graphs and universal vertices and basic theorems for these definitions. The definition of and theorems for neighbors were already discussed with Mario in the Google Group
- Corrections according to remarks of Gerard Lang.

### CODE REVIEW

**Comment by avekens** [comment]
@david-a-wheeler : Hi David, why did you close my pull request without merging my changes into the development branch of set.mm (without any comment)? Was there anything wrong with it? From my point of view, everything seemed to be fine...

**Comment by david-a-wheeler** [comment]
I'm sorry! I was reading it from my phone, and somehow must have accidentally closed it.  I look forward to seeing this capability get added.

**Comment by david-a-wheeler** [comment]
I don't see any issues on a quick skim.

**Comment by david-a-wheeler** [comment]
Looked further. Looks good to me!

**Pull request merged**
