### PR TITLE
#2128 one instance of equvelv

### PR DESCRIPTION
**Pull request by wlammen**
This PR emulates a move of equvelv from Andrew Salmon's mathbox to Main about 2 years ago.

### CODE REVIEW

**Review by avekens — APPROVED** [review]

**Comment by avekens** [comment]
Since I have the permissions now, I want to merge this (relatively small) PR. I wonder, however, which is the merge policy we agreed on (see discussion in #2517): "Squash and merge", or "Rebase and merge". As I understand correctly, Mario was in favour of the first, but David of the second. @wlammen @benjub how do you merge? Can we see after a PR is merged which option was used?

**Comment by wlammen** [comment]
Squash and merge.  The individual commits are eliminated (2 in this case), and just 1 entry remains.  In git log the commit messages still appear with an * in front of them.  I don't see a reason why someone would checkout a state in between my 2 commits.

**Comment by avekens** [comment]
> Squash and merge. The individual commits are eliminated (2 in this case), and just 1 entry remains. In git log the commit messages appear with an * in front of them.

Thanks a lot, Wolf. Now I try to "squash and merge"...

**Comment by wlammen** [comment]
Just to add this aspect: I think (but have not confirmed) that a squashed merge is more space efficient, something that becomes more and more important over time.  Downloading the whole repository takes already quite some time.

**Pull request merged**
