### PR TITLE
Fixes link to structured typesetting version of the HTML pages

### PR DESCRIPTION
**Pull request by tirix**
This should fix issue https://github.com/tirix/metamath-web/issues/24.

### CODE REVIEW

**Review by GinoGiotto — APPROVED** [review]

**Comment by GinoGiotto** [comment]
Since the old structured pages used to occupy 12GB of data we can live without them for now. Some time in the future I hope https://github.com/metamath/metamath-exe/pull/9 will be merged, even though I acknowledge that solving merge conflicts there looks like a nightmare.

**Comment by digama0** [comment]
I'd rather not add more web site generation stuff to metamath-exe; I'm really close to being able to replace metamath-exe with mm-web-rs for the main theorem page generation, pending a fix for https://github.com/metamath/metamath-knife/issues/141, which will result in a 400x performance improvement.

**Comment by tirix** [comment]
Oh I was not aware that https://github.com/metamath/metamath-knife/issues/141 was blocking that project, I should have another look/another try at it.

But your objection is about https://github.com/metamath/metamath-exe/pull/9, not this PR, right?

**Comment by digama0** [comment]
> But your objection is about https://github.com/metamath/metamath-exe/pull/9, not this PR, right?

Right. More specifically, I would like to make that PR obsolete before it even lands, although I am not objecting to the PR contents itself

**Pull request merged**
