### PR TITLE
Preparatory theorems 1/2: the 11 el*v* theorems

### PR DESCRIPTION
**Pull request by mazsa**
I submit my Preparatory theorems in 2 parts: this is the controversial one. I think these 11 theorems are ok in my Mathbox, and they would decrease the size of set.mm with hundreds of theorems with  ` $e |- A e. _V ` , but I’m quite sure I can’t see the playing field completely. I’ll just write here what I did:
When I met with a ` $e |- A e. _V ` , I found the general version and I included only this general version in my Mathbox. I didn’t use the ` g ` suffix at all because the general version is the default form in my Mathbox (of course I used ` d ` and ` f ` versions). In proofs, I used the default general version this way: ` elv.1 $e |- ( x e. _V -> ph ) $. `  ` elv $p |- ph $= ` . Of course, exceptions exist, and 
` A ` is not always  ` x ` in proofs (for example, I used inference form ~ elqs with ~ 0ex and not the general form ~ elqsg in my ~ n0elqs in order to minimize it),
and if you need the same ` $e |- x e. _V ` in a proof several times, the proof can be longer,
but I find this approach by and large simpler and more economical.

### CODE REVIEW

**Review by jkingdon — APPROVED** [review]

**Comment by avekens** [comment]
@david-a-wheeler Why are most of the checks skipped? As long as these checks are not performed successfully, it makes no sense to review this PR, and it cannot be accepted and merged of course.

**Comment by mazsa** [comment]
@avekens (cc @david-a-wheeler ) because github seems to have a deduplication process; actually, this is of the first of our 9 verifiers and it resulted https://github.com/metamath/set.mm/runs/4988743702?check_suite_focus=true in this: ` Run fkirc/skip-duplicate-actions@master
Skip execution because the exact same files have been successfully checked in https://github.com/metamath/set.mm/actions/runs/1764004854 ` The explanation is that I submitted exactly this file as a PR yesterday before this PR, all 9 checks performed then, but I revoked the submission.

**Comment by jkingdon** [comment]
> github seems to have a deduplication process

Yeah, exactly. If you click through to https://github.com/metamath/set.mm/actions/runs/1764004854 you'll see all the tests ran and passed there.

So we can count this as a successful check.

**Comment by mazsa** [comment]
Jim´s @jkingdon comment belongs here: https://github.com/metamath/set.mm/pull/2453/#issuecomment-1024328717 (because I closed PR 2453 and this 2457 version was merged).

**Pull request merged**
