### PR TITLE
Theorems for matrices consisting of polynomials

### PR DESCRIPTION
**Pull request by avekens**
Main part:
* theorems about monoid/ring homomorphisms

AV's Mathbox:
* The product of two polynomials expressed as group sum of scaled monomials
* Matrices consisting of polynomials: Isomorphism between the ring of matrices having polynomials as entries and the ring of polynomials having matrices as coefficients

### CODE REVIEW

**Comment by avekens** [comment]
Something went wrong with the trevis jobs! Could anybody have a look at it?

**Comment by david-a-wheeler** [comment]
The Travis jobs are unusually slow to execute right now. I'm not seeing any particular symptom as to why. Hopefully this is just a transient problem. If the problem persists then we may have to investigate further.

**Comment by david-a-wheeler** [comment]
The jobs took a ridiculously long time, but they completed normally.

**Comment by avekens** [comment]
At least it worked now ;-).

**Pull request merged**
