### PR TITLE
New Mathbox: amgmwlem, amgmlemALT, amgmw2d

### PR DESCRIPTION
**Pull request by DyeKuu**
Hello, following my last PR https://github.com/metamath/set.mm/pull/1995, I would like to contribute as follows:

- I created my Mathbox and add a weighted version of [amgmlem](http://us.metamath.org/mpeuni/amgmlem.html), I call it `amgmwlem`.

- I tried to rewrite the proof of `amgmlem` based on `amgmwlem`, I name it `amgmlemALT` in my mathbox.

- I also rewrote the proof of `amgmw2d` and moved it in my Mathbox: it is now based on `amgmwlem`. I changed a bit the position of the statements to make them aligned with `amgmwlem`.

I've encountered some warnings by referencing the theorems in other mathboxes, is it a big deal? Your suggestions and helps are welcome!
```
?Warning: The proof of "amgmwlem" in the mathbox for Kunhao Zheng references
    "dfrp2" in the mathbox for Thierry Arnoux.
?Warning: The proof of "amgmwlem" in the mathbox for Kunhao Zheng references
    "rrpsscn" in the mathbox for Glauco Siliprandi.
?Warning: The proof of "amgmw2d" in the mathbox for Kunhao Zheng references
    "ofs2" in the mathbox for Thierry Arnoux.
```

### CODE REVIEW

**Comment by nmegill** [comment]
> I've encountered some warnings by referencing the theorems in other mathboxes, is it a big deal?

Our convention is that mathboxes should not be dependent on each other, so if theorems are needed from another mathbox, they should be promoted to the main part of set.mm.  @tirix since you did 2 of these, could you suggest where they should be moved?

This may require moving more than just these 3, in case they in turn depend on other theorems in their mathbox (as indicated using e.g. "show trace_back" in metamath.exe).

**Comment by wlammen** [comment]
?Warning: The proof of "amgmwlem" in the mathbox for Kunhao Zheng references
    "dfrp2" in the mathbox for Thierry Arnoux.

Only theorems placed in the Main part are considered to be stable, so referencing those theorems will not pose problems in future.  All theorems depending on Main only are automatically updated to reflect any breaking change.

This does not hold for theorems placed in mathboxes.  Their owner may change "their" theorems without prior notice, and maybe will not be amused to have to update other people's stuff to get their changes done.

So what is your way to go? It seems you have two options: 1. copy the needed theorem to your own mathbox under a modifierd name and perhaps a comment clarifying the origin. 2. Move the desired theorem to Main, so that it is maintained without disturbing your results.  I think, this will be acknowledged only, if it looks matured and general enough.  Following the second path means you have to update a registry in the beginning of set.mm, where such movements are listed.

**Comment by tirix** [comment]
- ~ ofs2 is about operations on words, so it would be placed into the "Words over a set" section. It requires word literals, so it could go into that chapter, at the end. Both ~ ofs1 and ~ ofccat will also have to be moved. I believe the fact that they found a use outside of my mathbox shows that they are generally useful. The other neighbouring theorems which use ` oFC ` shall not be moved, since I don't think ` oFC ` is used outside my mathbox.
- Concerning ~ dfrp2, I notice that ~ ioorp exists in the main part of set.mm, which is exactly the same statement, with terms swapped (~ eqcomi). So ~ ioorp shall be used instead. I should remove the single use of ~ dfrp2 in ~ omssubadd and delete it!

Feel free to move them outside of my mathbox - I can help if you prefer me to do the move, but it might take some time!

**Comment by DyeKuu** [comment]
Thank you for your help and clear explanation! I will modify my proof to make it not depend on ~ dfrp2 and ~ rrpsscn, as they have some substitutions. 

@tirix could you please help me move ~ ofs2 out to the Main part? I would like to observe the process and see where should be modified properly.

**Comment by DyeKuu** [comment]
I tried to move ~ ofccat  ~ ofs2 ~ ofs1 into Main part, but I found that ~ofccat refers to a theorem ~ ifbieq12d2 which is also in your mathbox, do you have any suggestion on that @tirix ? Shall I also move it?

**Comment by wlammen** [comment]
Replace the proof of ifbieq12d2 with
  ${
    ifbieq12d2.1 $e |- ( ph -> ( ps <-> ch ) ) $.
    ifbieq12d2.2 $e |- ( ( ph /\ ps ) -> A = C ) $.
    ifbieq12d2.3 $e |- ( ( ph /\ -. ps ) -> B = D ) $.
    $( Equivalence deduction for conditional operators.  (Contributed by
       Thierry Arnoux, 14-Feb-2017.) $)
    ifbieq12d2 $p |- ( ph -> if ( ps , A , B ) = if ( ch , C , D ) ) $=
      ( cif wceq ifeq1da iftrue eqtr4d sylan9eq wn ifeq2da iffalse pm2.61dan
      ifbid eqtrd ) ABDEKZBFGKZCFGKABUCUDLABUCBFEKZUDABDFEIMBUEFUDBFENBFGNOPABQ
      ZUCBDGKZUDABEGDJRUFUGGUDBDGSBFGSOPTABCFGHUAUB $.
  $}

which reduces the proof size by roughly a third.

Alternative:

Since the final step is a simple application of ifbid, I'd slightly prefer the following simpler form. Its proof is a replay of the previous one with the final two steps left out. (To be placed after ifeq2da)
  ${
    ifeq12da.1 $e |- ( ( ph /\ ps ) -> A = C ) $.
    ifeq12da.2 $e |- ( ( ph /\ -. ps ) -> B = D ) $.
    $( Equivalence deduction for conditional operators. (Contributed by
    Wolf Lammen, 24-Jun-2021.) $)
    ifeq12da $p |- ( ph -> if ( ps , A , B ) = if ( ps , C , D ) ) $=
      ( cif wceq ifeq1da iftrue eqtr4d sylan9eq wn ifeq2da iffalse pm2.61dan )
      ABBCDIZBEFIZJABSBEDIZTABCEDGKBUAETBEDLBEFLMNABOZSBCFIZTABDFCHPUBUCFTBCFQB
      EFQMNR $.
  $}
This is a more direct extension of ifeq1da and ifeq2da without flourish.

Here are the necessary adaptions then:

(Leave where it is but replace the proof)
  ${
    ifbieq12d2.1 $e |- ( ph -> ( ps <-> ch ) ) $.
    ifbieq12d2.2 $e |- ( ( ph /\ ps ) -> A = C ) $.
    ifbieq12d2.3 $e |- ( ( ph /\ -. ps ) -> B = D ) $.
    $( Equivalence deduction for conditional operators.  (Contributed by
       Thierry Arnoux, 14-Feb-2017.) $)
    ifbieq12d2 $p |- ( ph -> if ( ps , A , B ) = if ( ch , C , D ) ) $=
      ( cif ifeq12da ifbid eqtrd ) ABDEKBFGKCFGKABDEFGIJLABCFGHMN $.
  $}

(Place this before ofs2)
  ${
    $d i E $.  $d i F $.  $d i G $.  $d i H $.  $d i R $.  $d i S $.  $d i T $.
    $d i ph $.
    ofccat.1 $e |- ( ph -> E e. Word S ) $.
    ofccat.2 $e |- ( ph -> F e. Word S ) $.
    ofccat.3 $e |- ( ph -> G e. Word T ) $.
    ofccat.4 $e |- ( ph -> H e. Word T ) $.
    ofccat.5 $e |- ( ph -> ( # ` E ) = ( # ` G ) ) $.
    ofccat.6 $e |- ( ph -> ( # ` F ) = ( # ` H ) ) $.
    $( Letterwise operations on word concatenations.  (Contributed by Thierry
       Arnoux, 28-Sep-2018.) $)
    ofccat $p |- ( ph -> ( ( E ++ F ) oF R ( G ++ H ) ) =
      ( ( E oF R G ) ++ ( F oF R H ) ) ) $=
      ( vi cc0 co cfzo wcel cvv chash cfv caddc cv cof cmin cif cmpt cconcat wa
      wfn wceq cword wrdf ffn 3syl ad2antrr oveq2d fneq2d mpbird ovex a1i inidm
      offn hashfn syl cn0 cfn wrdfin hashcl hashfzo0 eqtrd adantr eleq2d biimpa
      wf fnfvof syl22anc wn fveq2d simpr neleqtrd nn0zd fzocatel ifeq12da ifbid
      simplr mpteq2dva ccatfval oveq12d mpteq1d syl5eq fvex ifex syl2anc eqtr4d
      cz mp2an offval2 ifbieq2d ovif12 mpteq2i syl6eq 3eqtr4rd ) AOPEUAUBZFUAUB
      ZUCQZRQZOUDZPEGBUEZQZUAUBZRQZSZXIXKUBZXIXLUFQZFHXJQZUBZUGZUHZOXHXIPXERQZS
      ZXIEUBZXIGUBZBQZXIXEUFQZFUBZYFHUBZBQZUGZUHZXKXQUIQZEFUIQZGHUIQZXJQZAOXHXS
      YJAXIXHSZUJZXSXNYEYIUGYJYQXNXOXRYEYIYQXNUJZEYAUKZGYAUKZYATSZYBXOYEULAYSYP
      XNAECUMZSZYACEVPYSICEUNYACEUOUPZUQAYTYPXNAYTGPGUAUBZRQZUKZAGDUMZSZUUFDGVP
      UUGKDGUNUUFDGUOUPAYAUUFGAXEUUEPRMURUSUTZUQUUAYRPXERVAZVBYQXNYBYQXMYAXIYQX
      LXEPRAXLXEULZYPAXLYAUAUBZXEAXKYAUKXLUUMULAYAYABYAEGTTUUDUUJUUAAUUKVBZUUNY
      AVCVDYAXKVEVFAXEVGSZUUMXEULAUUCEVHSUUOICEVIEVJUPZXEVKVFVLZVMURZVNZVOYABEG
      TXIVQVRYQXNVSZUJZXRYFXQUBZYIUVAXPYFXQUVAXLXEXIUFAUULYPUUTUUQUQURVTUVAFPXF
      RQZUKZHUVCUKZUVCTSZYFUVCSZUVBYIULAUVDYPUUTAFUUBSZUVCCFVPUVDJCFUNUVCCFUOUP
      ZUQAUVEYPUUTAUVEHPHUAUBZRQZUKZAHUUHSZUVKDHVPUVLLDHUNUVKDHUOUPAUVCUVKHAXFU
      VJPRNURUSUTZUQUVFUVAPXFRVAZVBUVAYPYBVSXEWQSXFWQSUVGAYPUUTWGUVAXMYAXIYQUUT
      WAYQXMYAULUUTUURVMWBUVAXEAUUOYPUUTUUPUQWCUVAXFAXFVGSZYPUUTAUVHFVHSUVPJCFV
      IFVJUPZUQWCXIXEXFWDVRUVCBFHTYFVQVRVLWEYQXNYBYEYIUUSWFVLWHAYLOPXLXQUAUBZUC
      QZRQZXSUHZXTXKTSXQTSYLUWAULEGXJVAFHXJVAOXKXQTTWIWRAOUVTXHXSAUVSXGPRAXLXEU
      VRXFUCUUQAUVRUVCUAUBZXFAXQUVCUKUVRUWBULAUVCUVCBUVCFHTTUVIUVNUVFAUVOVBZUWC
      UVCVCVDUVCXQVEVFAUVPUWBXFULUVQXFVKVFVLWJURWKWLAYOOXHYBYCYGUGZYBYDYHUGZBQZ
      UHZYKAYOOXHUWDXIUUFSZYDXIUUEUFQZHUBZUGZBQZUHUWGAOXHUWDUWKBYMYNTTTXHTSAPXG
      RVAVBUWDTSYQYBYCYGXIEWMYFFWMWNVBUWKTSYQUWHYDUWJXIGWMUWIHWMWNVBAUUCUVHYMOX
      HUWDUHULIJOEFUUBUUBWIWOAYNOPUUEUVJUCQZRQZUWKUHZOXHUWKUHAUUIUVMYNUWOULKLOG
      HUUHUUHWIWOAOXHUWNUWKAXGUWMPRAXEUUEXFUVJUCMNWJURWKWPWSAOXHUWFUWLYQUWEUWKU
      WDBYQYBUWHYHUWJYDYQYAUUFXIYQXEUUEPRAXEUUEULYPMVMZURVNYQYFUWIHYQXEUUEXIUFU
      WPURVTWTURWHWPOXHUWFYJYBYCYGYDYHBXAXBXCXD $.
  $}

**Comment by tirix** [comment]
Indeed, thank you Wolf!
@DyeKuu this deserves a ` (Proof shortened by Wolf Lammen, 24-Jun-2021.) ` !

Since they seem useful, these new proofs (related to `if`) could go just after ~ ifeq2da in set.mm.

**Comment by DyeKuu** [comment]
Thank you so much for your guidance and help through this PR! To sum up:

- moves ~ ifbieq12d2 ~ ofccat ~ ofs2 ~ ofs1 to Main part, with ~ fbieq12d2 and ~ ofccat shortened.
- adds ~ ifeq12da to Main part.

I think this PR is ready. 👍

**Comment by wlammen** [comment]
Almost done so far, but a couple of lines are still missing:
Add the following between line 96 and 97:
 2-Jul-21 ofccat    [same]      moved from TA's mathbox to main set.mm
 2-Jul-21 ofs2      [same]      moved from TA's mathbox to main set.mm
 2-Jul-21 ofs1      [same]      moved from TA's mathbox to main set.mm
 2-Jul-21 ifbieq12d2  [same]      moved from TA's mathbox to main set.mm

**Pull request merged**
