### PR TITLE
Changed the definition of angle congruence in geometry.

### PR DESCRIPTION
**Pull request by tirix**
Also, added rings of sets, and made progress towards Caratheodory's Extension Theorem.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
I primarily looked at iscgra. It seems to be fine to me & ready for a merge.

That said, its expression is so different from Schaubhauser's that I really had to look at it multiple times. Don't slavishly follow Schaubhauser, I think that would be a bad idea!  But where definitions ($a) differ, you might want to explain a little more in a comment about what the differences are & why. So I think it'd be really helpful to add comments, especially in definitions, about the differences & why. For example, the original used 4 "there exists"; why the variation, why does that not matter, etc?

**Comment by tirix** [comment]
Indeed, I took some liberties. Like in other areas of set.mm, we could certainly prove the exact statement of Schwabhäuser's 11.2 / 11.3 / 11.4, in order to show that the definition I chose is equivalent.

And explanations are nice, of course, but I'm not always comfortable with being very verbose.

**Comment by tirix** [comment]
For the third congruence theorem, SSS, Schwabhäuser has 3 versions, and I have provided all three, even though the second and third ones follow trivially from the first. Shall we keep them anyway?

**Comment by david-a-wheeler** [comment]
> Indeed, I took some liberties. Like in other areas of set.mm, we could certainly prove the exact statement of Schwabhäuser's 11.2 / 11.3 / 11.4, in order to show that the definition I chose is equivalent.

I think that'd be a good idea in those cases (and several others). Metamath is *excellent* for showing that a proof of an expression follows from definitions, but it's a very valid complaint to say "these definitions are different, how do I know that they express the same thing?". That would completely eliminate that kind of complaint.

> And explanations are nice, of course, but I'm not always comfortable with being very verbose.

It's easier to simplify statements that are there than to come up with the statements in the first place. So where there's a risk that the expression might be unclear or where it's (non-trivially) different from the source, a sentence or two of explanation would be great. I'd be happy to propose edits to such text if that would be helpful.

> For the third congruence theorem, SSS, Schwabhäuser has 3 versions, and I have provided all three, even though the second and third ones follow trivially from the first. Shall we keep them anyway?

Yes, I think we should. SSS is *tremendously* important. Besides, since this formalizes Schwabhäuser, the easiest way to show that all versions are covered is to actually prove them :-).

**Pull request merged**
