### PR TITLE
Add short proofs of extremely common intermediate results

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This includes proofs for intermediate theorems that are used at least 42 times in set.mm.

**Comment by david-a-wheeler** [comment]
Obviously feel free to rename and move.

**Comment by digama0** [comment]
@nmegill Can you do a minimize run using just these theorems and push it to this branch? I want to see just how many characters are shaved off.

**Comment by nmegill** [comment]
I'll do this and let you know.

**Comment by nmegill** [comment]
First, I cleaned up set.mm to prevent distortion e.g. the proof of the 
new theorems was placed on the same line as the theorem, using fewer 
bytes total.  This is the first commit, which is my "starting" set.mm:

[short-proofs 58e11ae] rewrap comments and resave lines
(I meant resave proofs)

Next, I did the minimizations on all of set.mm without saving proofs so 
I could collect the results in the log file.  Then I ran each 
minimization individually in the starting set.mm to see what the 
individual impact was.  Finally, I ran all minimizations together on the 
staring set.mm, which is the second commit:

[short-proofs fb80295] minimize all w/ 
c0ex,1ex,neg1cn,1m1e0,4cn,0le0,0p1e1,1t1e1,base0

Here are the results:

set.mm bytes
29415009      <- before minimizing
29413442      minimizing with neg1cn (181 cases)   reduction: 1567 bytes
29413914      minimizing with c0ex   (136 cases)   reduction: 1095 bytes
29414325      minimizing with 0le0   (100 cases)   reduction:  684 bytes
29414427      minimizing with 4cn     (79 cases)   reduction:  582 bytes
29414453      minimizing with 1m1e0   (72 cases)   reduction:  556 bytes
29414496      minimizing with 1ex     (70 cases)   reduction:  513 bytes
29414526      minimizing with 0p1e1   (58 cases)   reduction:  483 bytes
29414650      minimizing with 1t1e1   (50 cases)   reduction:  359 bytes
29414249      minimizing with base0   (46 cases)   reduction:  760 bytes
29408225      minimizing with all of them together reduction: 6784 bytes

Notes:
1. The size of the 9 theorems totals 1496 bytes with comments or 542 
bytes with all comments stripped (an average of 166 or 60 bytes per 
theorem).
2. Curiously, the 9 theorems individually save 
1567+1095+684+582+556+513+483+359+760=6599 bytes but all together save 
6784 bytes.
3. The final actual set.mm size reduction (with new theorem comments) 
was 6784-1496=5288 bytes.
4. The sizes are for Windows, with CR/LF line endings
5. Each individual minimization saves about 8 bytes (6.8 worst case), so 
a rule of thumb we need about 21 uses (24 worst case) to overcome the 
size of the added theorem + comment.

Norm

**Comment by nmegill** [comment]
I minimized the proof of 0le0, given us an additional 25-byte set.mm 
reduction.  (The other 8 proofs did not get smaller.)

commit:
[short-proofs 54557f9] minimize 0le0 proof

Note, by the way, from my previous email there were 
181+136+100+79+72+70+58+50+46=792 individual minimizations.  However, 
only 677 proofs were affected, because some proofs were shortened by 
more than one minimization (as one might expect given the similarity 
among many of the 9 theorems).

Norm

**Comment by david-a-wheeler** [comment]
Awesome! My back-of-envelope estimate was that 18 replicas was the break-even number of replicas for space.  With a bigger sample the number is 21.  All of these have 42 or more replications, so just from a file size point of view I think this is justified. In addition, this makes automation easier, and visually shortens a number of proofs.

Pull?

**Comment by nmegill** [comment]
On 7/14/16 9:17 PM, David A. Wheeler wrote:
> Awesome! My back-of-envelope estimate was that 18 replicas was the
> break-even number of replicas for space. With a bigger sample the number
> is 21. All of these have 42 or more replications, so just from a file
> size point of view I think this is justified. In addition, this makes
> automation easier, and visually shortens a number of proofs.
>
> Pull?

I see no reason why this can't be merged w/ the develop branch.  BTW the 
set.mm in the short-proofs branch starts with an older set.mm.  For 
example, "( Met ` X )" near the top wasn't changed to "(Met`X)".  So I 
hope there will be no merge conflicts.

Norm

**Comment by david-a-wheeler** [comment]
@nmegill : That's weird, I thought I was on the current version. Let me know if there are any merge conflicts. I don't think they would be hard to fix, these theorems are trivial.

**Comment by nmegill** [comment]
On 7/14/16 10:05 PM, David A. Wheeler wrote:
> @nmegill <https://github.com/nmegill> : That's weird, I thought I was on
> the current version. Let me know if there are any merge conflicts. I
> don't think they would be hard to fix, these theorems are trivial.

The theorems are trivial, but they affect 677 proofs and over 15000 
lines.  I'm not very expert at git when it comes to possible problematic 
scenarios and would be more comfortable if @Mario did it.  If necessary 
I can easily re-create everything on the current set.mm from my 
temporary scripts but I don't keep them forever.

Norm

**Pull request merged**
