### PR TITLE
Revert "Right and left modules"

### PR DESCRIPTION
**Pull request by nmegill**
Reverts metamath/set.mm#2345

### CODE REVIEW

**Comment by nmegill** [comment]
That didn't do what I expected.  It seems that if I merge this reversion, it will make AV's PR "disappear" rather than simply be "unmerged" and reopened.  So I will wait for further advice before merging or abandoning it.  Any suggestions?

**Comment by benjub** [comment]
@nmegill : do not revert: we'll deal with my minor remarks in a forthcoming PR; I was happy with the previous merge, and @avekens's work on rmodislmod should not wait to be on mpeuni !

**Comment by nmegill** [comment]
GitHub seems to lack the ability to unmerge and reopen a merged pull request:

https://stackoverflow.com/questions/12674304/github-reopening-a-merged-pull-request

So I'm closing this reversion PR, and PR #2345 will remain merged as is.

Looking at PR #2345 again, I don't see any pending reviews.  @benjub where did you add them and what did I miss?

**Comment by david-a-wheeler** [comment]
@nmegill - right, you can't really "unmerge". You can "revert", which is a commit the applies the reversed operation, but that doesn't reopen the original pull request. You can *refer* to the merged pull request.

**Comment by benjub** [comment]
From the above discussion, I conclude I can delete this branch.

**Pull request closed without merging**
