### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by benjub**
Switched equsex and equsexALT according to #1776

### CODE REVIEW

**Comment by benjub** [comment]
@nmegill : I checked that the following OLD theorems can be deleted safely (the proofs do not have special properties or offer additional insight which makes them worth keeping).  Most, if not all, are shortenings due to @wlammen.  If you agree, I can remove them in this or my next PR:

CAN BE DELETED:
a2andOLD, nbiorOLD, otnldOLD, rbaibOLD, rbaibrOLD, rnlemOLD, bianirOLD
nancomOLD, nanOLD, nanbiOLD, nanbiOLDOLD
xorassOLD, xorneg1OLD, xorneg2OLD, truanOLD, dfnotOLD
stoic1aOLD
eximOLD, aleximiOLD, 19.35OLD, 19.21vOLDOLD, 19.21vOLD, stdpc5vOLD
ax12vOLD (essentially same proof)
19.8aOLD
nexdvOLD (requires more axioms)
19.9tOLD, 19.9hOLD, 19.9dOLD, 19.9OLD (essentially same proofs)
19.23vOLD, 19.36vOLD, 19.36aivOLD (require more axioms)
sb8euOLD (essentially same proof)
mopickOLD
2moOLD (essentially same proof)
2eu1OLD
2eu4OLD
2eu6OLD
euequ1OLD (requires more axioms)

**Comment by nmegill** [comment]
> @nmegill : I checked that the following OLD theorems can be deleted safely (the proofs do not have special properties or offer additional insight which makes them worth keeping). Most, if not all, are shortenings due to @wlammen. If you agree, I can remove them in this or my next PR:

Some of these OLDs are not yet a year old, e.g. ax12v vs. ax12vOLD, which was obsolete as of 8-Dec-2019.  I think @wlammen's next PR #1785 removes the right OLDs (I didn't check in detail).

**Comment by benjub** [comment]
> > @nmegill : I checked that the following OLD theorems can be deleted safely (the proofs do not have special properties or offer additional insight which makes them worth keeping). Most, if not all, are shortenings due to @wlammen. If you agree, I can remove them in this or my next PR:
> 
> Some of these OLDs are not yet a year old, e.g. ax12v vs. ax12vOLD, which was obsolete as of 8-Dec-2019. I think @wlammen's next PR #1785 removes the right OLDs (I didn't check in detail).

Ok. Then it's ready to merge. Maybe save the list somewhere ? So that when their time comes, one does not have to carefully check all the proofs again.

**Comment by nmegill** [comment]
It looks like GS didn't do a rewrap in his last PR, so when BJ did it, a 6000-line diff resulted that is somewhat confusing.  I would guess that this also puts an unnecessary disk space burden on the git tracking (although I don't know the details of how it stores diffs).  So maybe we should implement the suggestion in the 1st paragraph of https://github.com/metamath/set.mm/pull/1779#issuecomment-678657876 to have Travis do a local rewrap ('write souce.../rewrap' and 'save proof */c/f') and fail if it is different from the submitted set.mm.

@david-a-wheeler Could you put this on your list to look into this when you have some time?  I don't think it's high priority but it would make it easier to see the real changes.  set.mm is probably the only db we care about initially; the others haven't been a problem.  Thanks.

**Comment by nmegill** [comment]
> > Some of these OLDs are not yet a year old, e.g. ax12v vs. ax12vOLD, which was obsolete as of 8-Dec-2019. I think @wlammen's next PR #1785 removes the right OLDs (I didn't check in detail).
> 
> Ok. Then it's ready to merge. Maybe save the list somewhere ? So that when their time comes, one does not have to carefully check all the proofs again.

Having a separate list means it has to be kept updated, which probably won't be done consistently because people forget.

Maybe I'm misunderstanding, but checking the proofs isn't necessary.  All that matters is the date in the "Obsolete..." comment and whether a year has elapsed.

Instead, we've been keeping the the "Obsolete..." comment formatted so that it ends with "dd-mmm-yyyy. " with a space after the period.  Since this format is otherwise very rare in comments, we can search for e.g. "-Jul-2019. " to identify all the ones that expired in July 2020.  Of course we have to check visually that it really is an "Obsolete..." comment, but I've done that many times in the past and it takes very little time and effort even though it's a manual procedure.

**Pull request merged**
