### PR TITLE
Add canth to iset.mm

### PR DESCRIPTION
**Pull request by jkingdon**
This is a proof from Noah R Kingdon, written using Lamp and sent to me by email. I put it in pull request form, updated it for one recent rename in iset.mm, ran the minimizer, added a theorem comment based on the one in set.mm, and wrote the git commit messages.

I'll email him the link to this pull request so he can take a look.

In the process of investigating I also noticed that `elpwi2` could be copied from set.mm to iset.mm but that isn't required for the proof.

### CODE REVIEW

**Review by icecream17 — APPROVED** [review]
for easy future followups, I looked for barriers for proving the dropped links:

+ canth2 (only, but nontrivial barrier: df-sdom not defined)
+ ncanth (can be copied)

**Comment by jkingdon** [comment]
I wouldn't always say this in so much detail, but in case it is helpful to be more explicit about the minimize step, I ran

```
scripts/minimize canth iset.mm
```

and the output was

```
Bytes refer to compressed proof size, steps to uncompressed length.
Scanning forward through statements...
Proof of "canth" decreased from 581 to 571 bytes using "jctird".
Proof of "canth" decreased from 571 to 555 bytes using "baib".
Proof of "canth" decreased from 555 to 543 bytes using "elrab3".
Proof of "canth" decreased from 543 to 528 bytes using "elpwi2".
Scanning backward through statements...
Proof of "canth" decreased from 581 to 566 bytes using "elpwi2".
Proof of "canth" decreased from 566 to 538 bytes using "elrab3".
Proof of "canth" decreased from 538 to 528 bytes using "jctird".
The forward scan results were used.
```

Of course, anyone wanting to reproduce this will need to first have `elpwi2` in iset.mm (taken from this pull request or from set.mm, they are the same).

**Comment by jkingdon** [comment]
> for easy future followups, I looked for barriers for proving the dropped links:
> 
>     * canth2 (only, but nontrivial barrier: df-sdom not defined)
> 
>     * ncanth (can be copied)

Heh, yeah, I did want to encourage a new contributor as best as I could rather than take over every task myself, but these are good notes for follow ups at some point.

As for the strict dominance, see the entry for `df-sdom` at https://us.metamath.org/ileuni/mmil.html . I'm not sure what, if anything, can be done in iset.mm but at least based on what I know so far I don't have high hopes.

**Comment by jkingdon** [comment]
NRK said he'd send me a shortened version of this proof (anticipated for tomorrow).

**Review by avekens — APPROVED** [review]

**Comment by avekens** [comment]
I am curious: how is Noah related to you?

**Comment by nkingdon** [comment]
Jim is my dad's cousin

**Comment by jkingdon** [comment]
I've updated the pull request with the latest from Noah. I also squashed the commits, because I guess that's going to be more clear than seeing the exact steps I took in git history.

This time the minimizer output was:

```
Proof of "canth" decreased from 421 to 408 bytes using "elrab3".
```

**Comment by nkingdon** [comment]
Oh nice, after the minimizer it's the same number of steps as the proof in set.mm.

**Review by nkingdon — APPROVED** [review]

**Comment by nkingdon** [comment]
> Oh nice, after the minimizer it's the same number of steps as the proof in set.mm.

I wonder if it's fewer bytes than the set.mm proof, because that one felt slightly convoluted.

**Comment by jkingdon** [comment]
> > Oh nice, after the minimizer it's the same number of steps as the proof in set.mm.
> 
> I wonder if it's fewer bytes than the set.mm proof, because that one felt slightly convoluted.

If you really want to dive into this rabbit hole, there are many thoughts and rules of engagement at https://us.metamath.org/mpeuni/conventions.html (the word "short" appears no fewer than 18 times on that page, most of which are about shortening proofs)).

Most standard way to measure the length of a proof is `show proof canth/compressed`, which currently (after this pull request) shows 399 bytes for set.mm and 408 for iset.mm.

**Pull request merged**
