### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by avekens**
Theorems of TA's and AV's Mathox moved, esp. for ring of integers (see also #866):
* ress0g, mul2lt0rlt0, mul2lt0rgt0, mul2lt0llt0, mul2lt0lgt0, mul2lt0bi moved from TA's mathbox to main set.mm
* zzsinvg/zrnginvg, zrngrng moved from AV's mathbox to main set.mm
* zzsbase, zzsplusg, zzsmulg, zzsmulr, zzs0, zzs1 renamed and moved from TA's mathbox to main set.mm

### CODE REVIEW

**Comment by nmegill** [comment]
@avekens A merge conflict arose, could you look at it?  Thanks.

**Comment by avekens** [comment]
Puh, there was an accepted pull request from Wolf Lammen, in which a lot of reformattings within my Mathbox were perfomed! Since I also did a rewrap before my pull request, I fear a lot of conflicts are caused by this. I try to find an easy solution to merge these changes, but maybe I have to through away (and redo them in a clean repository) my changes and discard this pull request at worst.

But maybe someone with write access to metamath/set.mm could do it more easily (directly) than I can do (going via a fork).

**Comment by wlammen** [comment]
I am awfully sorry for this. For rewrapping I use

./metamath 'read set.mm' 'write source set.mm /rewrap' \
  erase 'read set.mm' 'save proof */compressed/fast' \
  'verify markup */file_skip' 'verify proof *' \
  'write source set.mm' quit

I thought this is a standard procedure, maybe I am not quite up-to-date here. Hints are welcome.
git allows reverting a particular commit by
git revert d8e06f4
(the number refers to the rewrap commit)

**Comment by avekens** [comment]
@wlammen it's not you fault - the rewrapping you performed is absolutely fine (I do it the same way). I think the general problem is that we are working on one big file (set.mm) in parallel, and this time there were 3-4 parallel pull requests (usually we have 1-2 at the same time). I do not now how this problem can be solved in general...

**Comment by benjub** [comment]
@avekens It might be safer to specify that \Z is the initial object in the category of *unital* rings (you didn't write "unital") Remark: in the category of non-necessarily unital rings, the zero ring is the zero object (i.e. both initial and terminal).

**Comment by nmegill** [comment]
@wlammen @avekens I'm not sure just where the conflicts arose, but if we were to accept set.mm only if it is rewrapped - i.e. have Travis do a local rewrapping and make sure no differences arose - would that have solved this problem?

**Comment by avekens** [comment]
Although there were several places with merge conflicts (about 5-10? I didn't count them), it was relatively easy to solve them. However, the whole procedure cost me mor than half an hour...

@nmegill My assumption was false, most of the conflicts didn't come from the rewrapped comments, but had seveersal causes (conflicts in proves, headers, etc.). So I think from this case we cannot derive an improvement.  To check for rewrappings, as you suggested, might be counterproductive (many rejections because of inconsostent rewraps).

Fortunately, everything loks fine now.

**Pull request merged**
