### PR TITLE
Shorten oaabs2

### PR DESCRIPTION
**Pull request by GinoGiotto**
I found an 8 bytes shorter proof for `oaabs2` expressed in the compressed format. This is the first time I put my hands on the theorems themselves so I'm not sure I addressed all conventions correctly, let me know in the comments.

### CODE REVIEW

**Comment by GinoGiotto** [comment]
Hmm I'm trying to understand what went wrong, but I'm not sure I understand what I'm supposed to do

**Comment by GinoGiotto** [comment]
Ok, I fixed one check

**Comment by GinoGiotto** [comment]
Nice, I fixed all checks

**Comment by wlammen** [comment]
a sylanbrc is replaced with a sylanblrc, saving a proof line.  The list of axioms has not changed, so this is a valid shortening.

**Review by wlammen — APPROVED** [review]

**Pull request merged**
