### PR TITLE
Alternative denial

### PR DESCRIPTION
**Pull request by benjub**
Commit messages say it all.

### CODE REVIEW

**Comment by benjub** [comment]
Converted to draft because I realized @wlammen has similar theorems in his mathbox. I'll merge them to night.

**Comment by benjub** [comment]
Latest commit: use shortenings from WL's mathbox (and attribute ~nanimn to him). @wlammen: your ~wl-nanbi2 was identical to ~wl-nanbi1, so I removed it.

By the way: ~nanass can probably be shortened.

**Comment by wlammen** [comment]
wl-nanbi2: I guess I wanted to add the new operand to the left, but somehow forgot to finish it.  The proof is easy, use nancom.

**Review by wlammen — APPROVED** [review]

**Comment by benjub** [comment]
> wl-nanbi2: I guess I wanted to add the new operand to the left, but somehow forgot to finish it. The proof is easy, use nancom.

Yes, that's the original proof of nanbi2 (by AH and SF) so I left it that way.

**Pull request merged**
