### PR TITLE
Replaced latexdef rm -> \mathrm

### PR DESCRIPTION
**Pull request by GinoGiotto**
These latexdefs are in the form <code>{rm text}</code>. I suppose they were meant to be <code>{\rm text}</code>, so I replaced them with <code>\mathrm{text}</code>

### CODE REVIEW

**Comment by GinoGiotto** [comment]
Hmm were they used for testing? It says something went wrong.

**Comment by benjub** [comment]
@GinoGiotto could you run the check `MM>v m */fi` on commits [95e5696](https://github.com/metamath/set.mm/pull/3058/commits/95e5696325b75ab38c0f739313cd6be09343ea1b) and [01c3aeb](https://github.com/metamath/set.mm/pull/3058/commits/01c3aebd0b0c82e6228486a3d4069be35851c009) ?

**Comment by benjub** [comment]
That's weird, because there was a problem scanning iset.mm which is not modified in this PR.

Can you do `git merge upstream/develop` ?

**Comment by GinoGiotto** [comment]
For commit 01c3aeb it says:
<pre>
Metamath - Version 0.198 7-Aug-2021           Type HELP for help, EXIT to exit.
MM> r set.mm
Reading source file "set.mm"... 42963157 bytes
42963157 bytes were read into the source buffer.
The source has 204044 statements; 2726 are $a and 40688 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> v m */fi
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
?Warning: There is no "Version of " comment at the top of the file "set.mm".
Checking section header comments...
Checking bibliographic references...
Checking mathbox independence...
MM>
</pre>

while for commit 95e5696 it says:
<pre>
Metamath - Version 0.198 7-Aug-2021           Type HELP for help, EXIT to exit.
MM> r set.mm
Reading source file "set.mm"... 42963005 bytes
42963005 bytes were read into the source buffer.
The source has 204044 statements; 2726 are $a and 40688 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> v m */fi
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
?Warning: There is no "Version of " comment at the top of the file "set.mm".
Checking section header comments...
Checking bibliographic references...
Checking mathbox independence...
MM>
</pre>

I'm going to answer your second question soon

**Comment by GinoGiotto** [comment]
@benjub Running <code>git merge upstream/develop</code> in my repository folder just returns <code>merge: upstream/develop - not something we can merge</code>

**Comment by benjub** [comment]
try
```
git checkout develop
git pull upstream develop
git checkout YOUR_BRANCH
git merge develop
```
Can you also run the check on the previous commit, https://github.com/metamath/set.mm/pull/3058/commits/686e263f619a05782835eac3874033ab1a2979b8 ?

**Comment by GinoGiotto** [comment]
Command <code>git checkout develop</code>
returns:
<pre>
Already on 'develop'
Your branch is up to date with 'origin/develop'.
</pre>

Command <code>git pull upstream develop</code>
returns:
<pre>
From https://github.com/metamath/set.mm
 * branch              develop    -> FETCH_HEAD
 * [new branch]        develop    -> upstream/develop
Already up to date.
</pre>

Command <code>git checkout set.mm</code> (I named my folder set.mm)

returns:
<pre>
Updated 0 paths from the index
</pre>

Command <code>git merge develop</code> 

returns : 
<pre>
Already up to date.
</pre>

For commit 686e263 it says:
<pre>
Metamath - Version 0.198 7-Aug-2021           Type HELP for help, EXIT to exit.
MM> read set.mm
Reading source file "set.mm"... 42962997 bytes
42962997 bytes were read into the source buffer.
The source has 204044 statements; 2726 are $a and 40688 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> v m */fi
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
?Warning: There is no "Version of " comment at the top of the file "set.mm".
Checking section header comments...
Checking bibliographic references...
Checking mathbox independence...
MM>
</pre>

**Comment by benjub** [comment]
So the commit that introduced the problem seems to be https://github.com/metamath/set.mm/pull/3058/commits/95e5696325b75ab38c0f739313cd6be09343ea1b which is a merge from develop which says "This merge commit was added into this branch cleanly." I do not understand. @david-a-wheeler ?

**Comment by wlammen** [comment]
See #3060 .  Merge again with current version of the develop branch.

**Review by benjub — APPROVED** [review]

**Pull request merged**
