### PR TITLE
READY FOR MERGE: If regen-from-raw finds warnings, report as a failure

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This fixes our detection mechanism - it now reports failures on problems it didn't report before.  Now we need to fix the problems it reports...!

**Comment by david-a-wheeler** [comment]
I fixed our mechanism for detecting problems when generating HTML from raw html files, and then fixed all the new errors it was reporting.  In mmil.raw.html I changed "prnadd: prnaddl" (which is clearly wrong) to "prnmadd: prnmaddl" (which I think is what was intended).  The "email quoting" table in mmdeduction.raw.html should in the long term be rewritten, but that would be a lot more work - I instead tweaked it so it at least displays better than before without errors.

**Comment by benjub** [comment]
Maybe it's safer to keep the page mmdeduction.raw.html ascii, in which case, replacing ¬ with &not; or &#172; is enough.

**Comment by david-a-wheeler** [comment]
> Maybe it's safer to keep the page mmdeduction.raw.html ascii, in which case, replacing ¬ with & not ; or & # 172 ; is enough (spaces added to prevent markdown).

I'm not sure that's true any more, since in HTML5 the default character encoding is UTF-8. (This has not always been the case.)

But better safe than sorry. I'll add a commit switch to & not ; - and for good measure, change the character encoding to UTF-8 so that if a UTF-8 character *does* slip through it should be interpreted correctly.

**Comment by david-a-wheeler** [comment]
I think it's all set to go! Let me know of any other issues.

**Comment by nmegill** [comment]
> I'm not sure that's true any more, since in HTML5 the default character encoding is UTF-8. (This has not always been the case.)

The standard we've been using for all web pages is HTML 4.01 Transitional, as indicated in the DOCTYPE at the top of each page.  This does everything that we have needed so far, and I don't see any reason to change as long as validator.w3.org accepts it.

I don't know what 4.01 says about UTF-8, but personally I strongly prefer to have ASCII in the source code so I know what I'm looking at.  I can also type ASCII from the keyboard. :)

Anyway, the most important criterion for me is that our pages pass validator.w3.org.  It has caught many careless errors that would have led to corrupted tables etc. that otherwise would have gone unnoticed .   Most of our pages have a link to it in the lower right corner.  [BTW iset.mm and nf.mm need ALT tags (as in set.mm) in their htmldefs to pass, a low priority thing to fix someday.]

**Comment by nmegill** [comment]
FYI 'markup ... /labels' will treat ~~ as an escape for ~ and convert it to a single tilde.
Your solution is fine too.

**Comment by jkingdon** [comment]
Thanks for fixing mmil.raw.html, @david-a-wheeler . Your fix is indeed correct (if you look at e3d3b29f2dc2ab594bc539688b2fc89e0c9bb34e you'll even see that the git commit message had the correct name, even if mmil.raw.html didn't).

**Pull request merged**
