### PR TITLE
Reduced axiom usage

### PR DESCRIPTION
**Pull request by GinoGiotto**
* Drop ax-10 and ax-13 from `sbco4lem`
* Drop ax-10 and ax-13 from `sbco4`
* Drop ax-13 from `sbbib`
* Drop ax-10 and ax-11 from `csbgfi`

Full axiom dependencies here: 1252b00

### CODE REVIEW

**Review by icecream17 — APPROVED** [review]
nfal alrimi --> hbal alrimih seems to be pretty common

I think https://github.com/metamath/set.mm/issues/2710 is potentially more useful/general, as it provides an easy way to find such sequences. Another example is replacing "bicomi exbii bitri" with "exbii bitr4i"

**Comment by GinoGiotto** [comment]
> I think #2710 is potentially more useful/general, as it provides an easy way to find such sequences.

That list seems very interesting indeed, is it available a script to regenerate an updated one?

**Review by avekens — APPROVED** [review]
proofs become shorter or not much longer.

**Comment by benjub** [comment]
Shouldn't some theorems be moved earlier to follow the rule that a theorem should be in the earliest possible $a-interval (except possibly for specific lemmas) ?

**Review by benjub — APPROVED** [review]

**Pull request merged**
