### PR TITLE
matrices over a polynomial ring

### PR DESCRIPTION
**Pull request by avekens**
Main part:
* expired obsolete ~ csbopabgOLD , ~ csbcnvgOLD removed
* ~ csbmpt12 , ~ csbmpt2 added
* ~ ply1coe revised (previous version as ply1coeOLD still available)
* ~ ply1coefsupp and ~ mptscmfsuppd moved from AV's mathbox to main set.mm
* proof of ~ ply1coe and ~ plypf1 shortened

AV's Mathbox:
* theorems for matrices in general
* theorems for matrices over a polynomial ring

### CODE REVIEW

**Comment by benjub** [comment]
I'm not sure about the removal of csbopabgOLD. Its comment says to use csbopab instead, but the latter depends on ax-sep, ax-nul, ax-pr, contrary to csbopab. I would propose to relabel csbopabgOLD to csbopabgALT and comment "Version of csbopab with a sethood antecedent but depending on fewer axioms." and a similar comment for csbopab.
Idem with csbcnvgOLD.

**Comment by avekens** [comment]
On resolving merge conflicts, I removed the entries for ~ brabsbOLD and ~ opelresiOLD from the history - I think removing OLD theorems needs not and should not be reported here (anymore)...

**Comment by benjub** [comment]
Similarly as in my previous comment, opelopabsbOLD is less general than opelopabsb but has a much shorter proof; keep it as ALT ?
brabsbOLD: OK to remove (even though it depends on fewer definitions)
opelresiOLD: OK to remove
@avekens @nmegill I agree that it's not necessary to signal the removals at the top of set.mm, but on the other hand, one should be sure before remove them that the proofs do not add anything in terms of: proof length, dependency on axioms (and df-clab, df-cleq, df-clel), interest of alternate proofs... And maybe give a "final call before deletion" to give some time for contributors to check the above.

**Comment by avekens** [comment]
The three OLD theorems mentioned by Benoit are now (again) available as ALT theorems.

@benjub I think as soon as a theorem is declared OLD with "obsolete as of" within the comment, it is marked to be deleted after one year. This should be enough time to decide if this theorem should be kept (and then renamed again!) or not. I recently created a lot of OLD theorems introducing "supp" and "finSupp", and all these theorems should/will be deleted next year - I see no relevance for them to live any longer...

**Comment by benjub** [comment]
@avekens Agreed, and thanks for the ALT theorems.

**Comment by nmegill** [comment]
> On resolving merge conflicts, I removed the entries for ~ brabsbOLD and ~ opelresiOLD from the history - I think removing OLD theorems needs not and should not be reported here (anymore)...

That's right, theorems with the suffix OLD should be never be listed in the history.  For one thing, they aren't (or shouldn't be) used, so no one is affected by their removal.

In case brabsb was "deleted" by renaming it OLD with no newer version, the history should say: "dd-mmm-yy brabsb  --- deleted; use xyz instead" where "use xyz instead" is an (optional) hint for the user.  If brabsb was replaced by a newer version that isn't directly compatible (e.g. swapped biconditional or reordered hypotheses), say: "dd-mmm-yy brabsb  [--same--] revised".  If brabsb was replaced by one with a shorter proof but no other changes, no history entry is needed.

It does seem there are some *OLDs in the history in 2015 and before.  Not sure what happened.  Sometimes people do a global change of a label to *OLD without remembering it may also change the history listing.  This is probably what happened here.  It's not worth worrying about too much though.  I think the string "OLD" can be deleted from the history as part of a cleanup someday.

**Comment by nmegill** [comment]
> Similarly as in my previous comment, opelopabsbOLD is less general than opelopabsb but has a much shorter proof; keep it as ALT ?
> brabsbOLD: OK to remove (even though it depends on fewer definitions)
> opelresiOLD: OK to remove
> @avekens @nmegill I agree that it's not necessary to signal the removals at the top of set.mm, but on the other hand, one should be sure before removing them that the proofs do not add anything in terms of: proof length, dependency on axioms (and df-clab, df-cleq, df-clel), interest of alternate proofs... And maybe give a "final call before deletion" to give some time for contributors to check the above.

I think this is carrying things too far.  A year is plenty of time for a grace period, and it would be rather inconvenient for someone cleaning out *OLDs to have to announce each one, wait another month or whatever, then finally delete them.  If someone is really concerned, they can periodically check the *OLDs due for deletion in the next month or two.  Even in the worst case, the old work is still available on github.

We normally use the comment "Obsolete [version/proof of ~ xxx] as of dd-mmm-yyyy. " to indicate the start of the grace period.   For most theorems I can find the ones due for deletion in e.g. Oct 2019 by grepping for "Oct-2018" followed by period and space, since contribution dates are followed by period and parenthesis.

**Pull request merged**
