### PR TITLE
Symmetric groups/transpositions enhanced

### PR DESCRIPTION
**Pull request by avekens**
- References to book [Rotman]
- Section comment on Symmetric Groups enhanced
- Example for a permutation group as subgroup of a symmetric group
- Section comment on Transpositions added
- non commutative transpositions
- symmetric groups on sets with more than 2 elements are not abelian
- rspn0, nelprd from AV's Mathbox to main part
- classes are sets for functions and equinumerousity (fovv, f1vv, f1ovv, encv)
- sets with size greater than 2 have at least 3 different elements
- minor improvements/corrections in comments

### CODE REVIEW

**Comment by nmegill** [comment]
@david-a-wheeler There is something strange going on.  Travis did not show an error for this set.mm:

```
$ scripts/verify --date_skip --extra 'write bibliography mmbiblio.html' set.mm
Metamath - Version 0.175 8-Mar-2019           Type HELP for help, EXIT to exit.
MM> Reading source file "set.mm"... 34213976 bytes
34213976 bytes were read into the source buffer.
The source has 154618 statements; 2224 are $a and 32192 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> 0 10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
..................................................
All proofs in the database were verified in 4.79 s.
MM> The old file will be renamed mmbiblio.html~1.
Reading definitions from $t statement of set.mm...
1400 typesetting statements were read from "set.mm".
3810 references were processed.
2031 table rows were written.
MM> Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
Checking section header comments...
Checking bibliographic references...
No errors were found.
The command "scripts/verify --date_skip --extra 'write bibliography mmbiblio.html' set.mm" exited with 0.


Yet when I run the markup check locally I get:

$ metamath set.mm
Metamath - Version 0.175 8-Mar-2019           Type HELP for help, EXIT to exit.
MM> READ "set.mm"
Reading source file "set.mm"... 34213976 bytes
34213976 bytes were read into the source buffer.
The source has 154618 statements; 2224 are $a and 32192 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> v m *
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
?Warning:  There is no "(Contributed by...)" in the comment above statement
    154561, label "f1otrgds".
?Warning:  There is no "(Contributed by...)" in the comment above statement
    154563, label "f1otrgitv".
?Warning:  There is no "(Contributed by...)" in the comment above statement
    154565, label "f1otrg".
Checking section header comments...
Checking bibliographic references...
MM> q 

Does this make any sense to you?

BTW @avekens Please don't fix this until we figure out the Travis problem.

Norm

**Comment by nmegill** [comment]
Followup:  I repeated the same command sequence as Travis (verify proof, write bib, verify markup) and my local run still gives the same comment warnings.  So it isn't a problem of interaction between say write bib and verify markup.

Norm

**Comment by nmegill** [comment]
1. Just to eliminate another possibility, I'll mention that all output on the screen, including errors and warnings, is from stdio and not stderr.

2. Travis doesn't seem to be using an old cached version of a good set.mm because the character count 34213976 is the same for both the Travis set.mm and my local set.mm.

3. I tried reproducing it on the us2 server (which has the exact metamath.exe source that Travis pulls over), and it correctly gave the missing contributor warnings.

Norm

**Comment by nmegill** [comment]
> 1. Just to eliminate another possibility, I'll mention that all output on the screen, including errors and warnings, is from stdio and not stderr.

I meant stdout and not stderr.

**Comment by avekens** [comment]
I also became suspicious as I saw this warning running "verify markup" locally, but since I didn't add these theorems (with the missing "(Contributed by...)") - I think they are from Thierry - I created the pull request and was happy that it was accepted without errors. However, I strongly agree that Travis should check this, and that a pull request should be rejected if  "(Contributed by...)" is missing.

**Comment by nmegill** [comment]
ping @david-a-wheeler - do you have any idea at all of what to look for?  I've tried everything I can think of and can't reproduce the Travis log.  This seems pretty serious.

Although it doesn't make sense to me it could be a gcc bug, I did look at versions:

The gcc version on Travis is:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4    (2013) -    set.mm markup errors not detected

The gcc versions I have available are:
gcc (Debian 4.9.2-10+deb8u1) 4.9.2   (2014) -   set.mm markup errors detected
gcc (GCC) 7.3.0   (2017) -  set.mm markup errors detected

I don't have gcc 4.8.4 to try locally, and wouldn't be sure how to install it without dependency issues.  Does anyone know how to do this quickly to try it?

Norm

**Comment by david-a-wheeler** [comment]
Not sure what's up. Perhaps it is running an old cached version of the executable? I will try to look into it later today.

**Comment by nmegill** [comment]
> Perhaps it is running an old cached version of the executable?

It seems unlikely, since the run log says "Metamath - Version 0.175 8-Mar-2019", and there weren't incremental updates after 0.174.  Anyway this check has been in since 2016, many versions ago, I think.

**Comment by david-a-wheeler** [comment]
I'm moving "contributing" problem to issue #794.

**Comment by david-a-wheeler** [comment]
It appears that the latest version of the Metamath program has a problem with the /date_skip option of verify markup.  See #794 for more discussion...

**Pull request merged**
