### PR TITLE
Categories of ext. structures, non-unital rings and unital rings

### PR DESCRIPTION
**Pull request by avekens**
See also issue #1507.

AV's mathbox:
* the category of sets as extensible structures
* the category of non-unital rings revised (previoud definitions and theorems marked with OLD)
* the category of unital rings revised (previoud definitions and theorems marked with OLD)

### CODE REVIEW

**Comment by avekens** [comment]
Why is the travis check not performed?

**Comment by arpie-steele** [comment]
> Why is the travis check not performed?

Travis is under maintenance : https://travis-ci.org/metamath/set.mm

**Comment by avekens** [comment]
All Travis jobs are finished successfully, but Travis seems to be hanging somehow...

**Comment by david-a-wheeler** [comment]
I cannot be certain, but it looks to me that the Travis job completed, but the message about the completion got dropped. So the system is waiting for the completion that has already occurred. The obvious solution is to restart the job, but I can't see a way to restart a job that Travis believes has completed. The whole thing is in a funky state.

I recommend that you make a completely innocuous change, commit that, and push. Then there will be an actual change, which will trigger the whole thing again. Hopefully that will unstick everything. If it doesn't, then we'll have to start figuring things out for real.

**Comment by avekens** [comment]
OK, I added another section header comment (which I've planned anyway), so let's wait and see...

**Comment by david-a-wheeler** [comment]
That seems to have worked! Hopefully we won't have to do that often.

**Pull request merged**
