### PR TITLE
replace "PART 16 GRAPH THEORY" - step 2

### PR DESCRIPTION
**Pull request by avekens**
Task 2 of issue #2265: Sections of "Graph theory (revised)" moved from AV's mathbox to main set.mm:

* Undirected simple graphs
* Examples for graphs
* Subgraphs
* Finite undirected simple graphs
* Neighbors, complete graphs and universal vertices
* Vertex degree
* Regular graphs

Additional changes:
* moved from AV's mathbox: ~clel5, ~sssseq, ~dfss7 -> ~dfss5, ~n0rex, ~ssn0rex, ~ralnralall, ~falseral0, ~elpwdifsn, ~prcssprc, ~resresdm, ~f1ssf1, ~riotaeqimp, ~opabn1stprc, ~resfnfinfin, ~residfi, ~nfile, ~hash1n0
* Maintenance of history (also from last PR)
* empty lines inserted/deleted according to the (new) conventions

### CODE REVIEW

**Comment by avekens** [comment]
Remark: Although only one big block (sections of "Graph theory (revised)" mentioned above) and some auxiliary theorems were moved, the "diff" mixes up evertything starting within the new Part "Graph theory". Therefore, the differences are not shown here with the message "diff is too large". I am sorry about that...

**Comment by avekens** [comment]
If there are any doubts about this PR: I have split the current set.mm and the set.mm to be merged into smaller *.mm-files (using write source set.mm /split) and compared the single files. The result is as expected (details see below). Maybe it was no good idea to combine the adjustments of blank lines according to the (new) convention with my changes concerning graph theory in one PR ... 

Result of comparison:

Writing "set-header.mm"...: blank lines
Writing "set-pred.mm"...: blank lines
Writing "set-class.mm"...: major changes as expected: (blocks added)
Writing "set-tarskigeom.mm"...: NO CHANGES
Writing "set-graphth.mm"... major changes as expected: (blocks added; blank lines)
Writing "set-main.mm"...: major changes as expected: (blocks added; blank lines)
Writing "set-deprec.mm"...: blank lines
Writing "set-typeset.mm"...: blank lines
Writing "set-hilsp.mm"...: blank lines
Writing "set-mbox-ta-basics.mm"...: NO CHANGES
Writing "set-mbox-ta-xdiv.mm"...: NO CHANGES
Writing "set-mbox-ta-prime.mm"...: blank lines
Writing "set-mbox-ta-algtop.mm"...: NO CHANGES
Writing "set-mbox-ta-ucm.mm"...: NO CHANGES
Writing "set-mbox-ta-rrhom.mm"...: blank lines
Writing "set-mbox-ta-man.mm"...: NO CHANGES
Writing "set-mbox-ta-logb.mm"...: NO CHANGES
Writing "set-mbox-ta-ind.mm"...: NO CHANGES
Writing "set-mbox-ta-esum.mm"...: NO CHANGES
Writing "set-mbox-ta-ofc.mm"...: NO CHANGES
Writing "set-mbox-ta-meas.mm"...: blank lines
Writing "set-mbox-ta-itgm.mm"...: NO CHANGES
Writing "set-mbox-ta-eulerpart.mm"...: NO CHANGES
Writing "set-mbox-ta-fibonacci.mm"...: NO CHANGES
Writing "set-mbox-ta-proba.mm"...: blank lines
Writing "set-mbox-ta-ballot.mm"...: NO CHANGES
Writing "set-mbox-ta-signum.mm"...: NO CHANGES
Writing "set-mbox-ta-signs.mm"...: NO CHANGES
Writing "set-mbox-ta-geom.mm"...: blank lines
Writing "set-mbox-ta.mm"...: blank lines
Writing "set-mbox-ai.mm"...: NO CHANGES
Writing "set-mbox-bj.mm"...: NO CHANGES
Writing "set-mbox-ml.mm"...: NO CHANGES
Writing "set-mbox-so.mm"...: NO CHANGES
Writing "set-mbox-jp.mm"...: blank lines
Writing "set-mbox-av-2reu.mm"...: NO CHANGES
Writing "set-mbox-av-afv_aov.mm"... blank lines
Writing "set-mbox-av-aux.mm"... blank lines
Writing "set-mbox-av-nt.mm"...: blank lines
Writing "set-mbox-av-even-odd.mm"... blank lines
Writing "set-mbox-av-graph-aux.mm"...: major changes as expected: (blocks removed)
Writing "set-mbox-av-graph.mm"...: major changes as expected: (blocks removed)
Writing "set-mbox-av-matrix.mm"...: blank lines
Writing "set-mbox-av.mm"...: blank lines
Writing "set-mbox-ew.mm"...: NO CHANGES
Writing "set-mbox.mm"...: blank lines
Writing "set.mm"...: blank lines

**Comment by nmegill** [comment]
This is very weird that over 500K set.mm lines (the majority of set.mm) are flagged as having changed.  Is this a bug in git?  That makes no sense.  I'm a little nervous merging this, fearing it might break something.  I can't even see what the differences are.

Is there any way you can do separate PRs for the blank lines and the graph theory move, from your intermediate local versions, if that is what is causing this problem?

**Comment by avekens** [comment]
I would have to revert the changes about the blank lines manually, because there is no intermediate commit I could revert to automatically. This would be quite a lot of work, but I would do it if required. It is not guaranteed, however, that this is the reason for the problem that tools cannot identify the changes correctly (I had the same problem with WinMerge comparing the whole set.mm) - it could also be caused by the changes for graph theory themselves (because the new and the old version are very similar).  

As I wrote 6 hours ago, I am quite sure that there schould be no problem with a merge, because comparing the single files produced by splitting set.mm. @nmegill I wonder if you have the chance/possibility to do this by yourself to alleviate your concerns.

**Comment by avekens** [comment]
PS: With WinMerge and with GitHub Desktop, the changes are shown at least, although starting with part 16 graph theory the changes are not aligned meaningfully. But maybe this would be sufficient.

**Comment by david-a-wheeler** [comment]
I don't know if it would help, but you could use `git diff` to compare various commits (trees) in ways that ignore whitespace. Here are some options that might be useful:

~~~~
       --ignore-space-at-eol
           Ignore changes in whitespace at EOL.

       -b, --ignore-space-change
           Ignore changes in amount of whitespace. This ignores whitespace at
           line end, and considers all other sequences of one or more
           whitespace characters to be equivalent.

       -w, --ignore-all-space
           Ignore whitespace when comparing lines. This ignores differences
           even if one line has whitespace where the other line has none.

       --ignore-blank-lines
           Ignore changes whose lines are all blank.
~~~~

**Comment by nmegill** [comment]
@david-a-wheeler My main concern is whether this is going to break something.  If your opinion is that there will be no problems, I will be happy to merge.

**Comment by avekens** [comment]
I reverted all/most of the adjustments of blank lines, starting at Part 16 GRAPH THEORY up to the end of set.mm (I do not know if I got them all), but it seems that this had no effect - a comparison is still not possible within this PR. Then the reason is actually the structural change by revising the graph theory...

**Comment by glacode** [comment]
Probably a stupid question (I'm sure you've already tried):

does

git diff --patience

return the same large amount of diffs ?

Glauco

**Comment by avekens** [comment]
Yes, within a GIT shell like GIT Bash, the follwowing command creates a text file changelog.txt (in the current repository location) with the differences: 

git diff 64fda7cc 18507ba31e24771db6ff1437d0326c208eb96d4b > changelog.txt 

(the first number is the short SHA of the latest commit in metamath/set.mm, the second number is the full SHA of my latest commit I want to be merged). 

The text file is huge (35 MB) and its content is not easy to read, but it contains all differences.

**Comment by avekens** [comment]
Using the option --patience (which I did not know before) as proposed by Glauco, the text file is much shorter, and the indication of differences better to understand. I attach this file to this PR: 
[changelog3.txt](https://github.com/metamath/set.mm/files/7428297/changelog3.txt)

**Pull request merged**
