### PR TITLE
New approach for graph theory (continued)

### PR DESCRIPTION
**Pull request by avekens**
Main set.mm:
* ~rmoeq  revised and moved from TA's mathbox to main set.mm
* theorems ~opeliunxp2f, ~mpt2xeldm,  ~mpt2xneldm added

AV's Mathbox (see also #1418):
* theorems ~ ssprss,  ~ssprsseq added
* theorems ~ssrelrn, ~uhgredg, ~usgrnloop1 added
* value of slot .ef changed to 18 (16 was already used)
* ~incistruhgr added: a graph is a special incident structure
* new section "Neighbors, complete graphs and universal vertices" (including new definitions for NeighbVtx, ComplGraph, ComplUSGraph, UnivVtx)

### CODE REVIEW

**Comment by nmegill** [comment]
A shorter proof for rmoeq is
```
      ( cv wceq wrmo wcel wa wmo moeq moani df-rmo mpbir ) ADZBEZACFNCGZOHAIOPA
      ABJKOACLM $.
```
and doesn't need the dummy y.

**Comment by nmegill** [comment]
And doesn't need $d x B $.

**Comment by avekens** [comment]
Thanks, Norm, for your hint. I provide the improvement with this PR already.

**Comment by avekens** [comment]
@david-a-wheeler Problems with Travis?
`The command "scripts/download-metamath" failed and exited with 3 during .`

**Comment by avekens** [comment]
@david-a-wheeler seemed to be a temporary problem - everything is fine now ...

**Comment by david-a-wheeler** [comment]
I'm glad it was temporary. I'm annoyed that we have this sporatic problem, but I don't see how to fix it short of switching to a different system like GitHub actions.

**Pull request merged**
