### PR TITLE
Reduced axiom usage

### PR DESCRIPTION
**Pull request by GinoGiotto**
This is the PR that I anticipated in https://github.com/metamath/set.mm/issues/3183 + some extra:

* Edited proof of `nfccdeq` -> drops `ax-11`

* Edited proof of `dfss2f` -> drops `ax-13` and automatically drops `ax-13` for these 264 theorems too: https://github.com/metamath/set.mm/commit/70740cdfa56528de67ae2cc7bedeb7c7500ae1b5

* Edited proof of `iunxsngf` -> drops `ax-13`

* Edited proof of `issmo` -> drops `ax-13`

Also I show that `eqsb3v` is identical to `eqsb3lem`, so one of them can be removed.

### CODE REVIEW

**Review by tirix — APPROVED** [review]

**Comment by tirix** [comment]
Nice!
Proofs are not much longer.
The one which should go is `eqsb3lem`, and `eqsb3v` would stay.
You could also add attributions to yourself for those changes.

**Comment by wlammen** [comment]
Rename eqsb3lem as eqsb3v (keep its proof), delete the current eqsb3v, and replace all occurrences of the text 'eqsb3lem' in set.mm with 'eqsb3v'.  Reformat set.mm.  That's it.  No need to reprove anything.

**Review by tirix — APPROVED** [review]

**Comment by GinoGiotto** [comment]
btw @tirix I opened an issue on your metamath-web repository, you may be interested in it.

**Comment by tirix** [comment]
> BTW @tirix I opened an issue on your metamath-web repository, you may be interested in it.

Yes I saw that! I'll try to fix it ASAP, sorry I did not react there directly.

**Pull request merged**
