### PR TITLE
Fix misc markup

### PR DESCRIPTION
**Pull request by tirix**
Similarly to #3247, `metamath-knife` is stricter than the current CI in terms of markup checks.
This fixes the issues found my `metamath-knife`, namely:
- missing spaces between `~` and `thm` in a `~ thm` internal reference
- dates not in chronological order in attributions.

### CODE REVIEW

**Review by wlammen — APPROVED** [review]
I verified that "Obsolete version of ~ isclwwlkn as of 22-Mar-2022." is in fact present in a version of set.mm from Nov-2022.

**Comment by tirix** [comment]
Oh thanks! I was unsure about that one, and did not know how to check it.

**Comment by wlammen** [comment]
git checkout 'develop@{2021-04-10 00:00:00}', but I can only go back as far as 30-Nov-2022

**Comment by icecream17** [comment]
I found clwwlkn and issclwwlkn in a pr from 1-Apr-2022
https://github.com/metamath/set.mm/pull/2561/

but no idea on reuccatpfxs1v

**Comment by wlammen** [comment]
>     $( Obsolete proof of ~ reuccatpfxs1v as of 12-Oct-2022.  (Contributed by
       Alexander van der Vekens, 6-Oct-2018.)  (Proof shortened by AV,
       21-Jan-2022.)  (Proof modification is discouraged.)
       (New usage is discouraged.) $)
    reuccats1vOLD $p |- ( ( W e. Word V /\ A. x e. X ( x e. Word V
                                           /\ ( # ` x ) = ( ( # ` W ) + 1 ) ) )
                  -> ( E! v e. V ( W ++ <" v "> ) e. X
                       -> E! x e. X W = ( x substr <. 0 , ( # ` W ) >. ) ) ) $=
      ( nfcv reuccats1OLD ) ABCDEBEFG $.
  $}

It is still in set.mm.  One should perhaps look for reuccats1v instead.

**Review by icecream17 — APPROVED** [review]

**Pull request merged**
