### PR TITLE
Fix `...` comment

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by digama0** [comment]
The head comment is not rendered, so there's no point in using math quotes there.

**Comment by david-a-wheeler** [comment]
It *is* rendered if you use a vim mode that checks that, which I just created yesterday.  It looks terrible, and it's not consistent.

**Comment by digama0** [comment]
This requires a larger proposal, because set.mm is *full* of such things. The math notation used in set.mm comments only uses the formal math quotes when metamath.exe will render them (which means immediately before `$a $p`). Everywhere else (including after `$c`, in section headers, and the head comment) they are written informally, with the assumption that they will not be rendered.

**Comment by david-a-wheeler** [comment]
Oh I'm not trying to do anything like that. It's just in a few places, the back quote is used  in a comment for something else other than to start an expression. I've only found four places it occurs.  I have embedded a workaround in the mode, but it would be better to fix those 4 places.

**Comment by david-a-wheeler** [comment]
It's true that if someone wanted to force special metamath rendering in a comment, and didn't already use a back quote, they would have to put in a lot of back quotes. But that is not my point. I agree with you, I don't see the need for that.  But any good editor mode might want to process back quotes inside comments, so it's important to always have the same semantics for back quotes inside comments.

**Comment by digama0** [comment]
How about taking the spaces out instead? I.e. change this line to

    2-Nov-15 df-met    [--same--]  changed "D e. Met" to "D e. (Met`X)",

which should make it clear that it's not intended to be rendered. The `` ` `` in math quotes is required to have whitespace around it.

If this occurs in a few other places, you should add them to this PR.

**Comment by david-a-wheeler** [comment]
On July 6, 2016 9:14:15 PM EDT, Mario Carneiro <notifications@github.com> wrote:
>How about taking the spaces out instead? I.e. change this line to
>
>   2-Nov-15 df-met    [--same--]  changed "D e. Met" to "D e. (Met`X)",
>
>which should make it clear that it's not intended to be rendered. The
>`` ` `` in math quotes is required to have whitespace around it.
>
>If this occurs in a few other places, you should add them to this PR.
>
>---
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/metamath/set.mm/pull/55#issuecomment-230952949

Sure, taking the spaces out works just as well.
--- David A.Wheeler

**Comment by david-a-wheeler** [comment]
The latest commit on this branch tweaks the early comments so that grave accents are connected with other characters, and thus can't be misinterpeted as surrounding an expression.

**Comment by digama0** [comment]
@nmegill Could you review this change and assess if it is a reasonable compromise for interpreting backquotes inside non-rendered comments? (FYI, I prefer to call these "backquotes" instead of "grave accents" because they are not being used as accents.)

**Comment by nmegill** [comment]
Taking out the space is fine with me.

BTW the metamath program will parse this correctly in MM-PA expression 
input, using the C-language rule of longest string of characters that 
could constitute a defined token.  This could provide one way to recover 
the space if necessary.

4      dummylink.2=?   $? |- $2
MM-PA> let var $2 = "D e. (Met`X)"
2 substitutions were made in 2 steps.
...
4      dummylink.2=?   $? |- D e. ( Met ` X )

Norm

**Pull request merged**
