### PR TITLE
Revert "Prove fineqvrep and fineqvpow", do not merge

### PR DESCRIPTION
**Pull request by wlammen**
Reverts metamath/set.mm#4205
Note the comments and approvals given there.
The CI build failed, see https://github.com/metamath/set.mm/actions/runs/10953351907.  Reason: usage of abeq2 is discouraged.
For notification @BTernaryTau Your commits are still merged.  Your options: Rewrite the proofs in a new pull request, or accept its usage here.  Depending on your choice, this pull request is merged, or deleted.

DO NOT MERGE !

### CODE REVIEW

**Comment by BTernaryTau** [comment]
I think #4215 is the right way to fix this. Reverting one of the conflicting changes just so it can be merged again along with the update to discouraged just adds an extra step.

**Comment by wlammen** [comment]
So this PR will be deleted after #4215 is merged (some time later, for others to have a look at it, and wait for another merge modifying set.mm, so the full CI workflow gets triggered again).

**Comment by wlammen** [comment]
#4218 has all checks passed, so I assume the database is in a consistent state now

**Comment by wlammen** [comment]
Revert is not needed, since an update of the discouraged file solves the issue with #4205

**Pull request closed without merging**
