### PR TITLE
Run travis on iset.mm too

### PR DESCRIPTION
**Pull request by jkingdon**
I'm going to first make this pull request with an intentional error, to make sure that travis finds it.

Assuming that works correctly, I'll then revise the pull request to just have the `.travis.yml` changes.

### CODE REVIEW

**Comment by nmegill** [comment]
@jkingdon 'verify proof' fails in Travis, so I didn't merge this.
Norm

**Comment by jkingdon** [comment]
Yeah, don't merge it until it runs travis successfully. I'll figure out what is going on and revise it.

**Comment by jkingdon** [comment]
Looking at the failures in https://travis-ci.org/metamath/set.mm/builds/339915938 it is failing as desired - there is an (intentional) invalid proof in that revision and all four verifiers are displaying an error in the logs.

I've revised the branch to remove the invalid proof and it can be merged if travis passes.

**Comment by jkingdon** [comment]
@nmegill this is now passing Travis and is ready to merge.

**Pull request merged**
