### PR TITLE
New approach for graph theory (continued)

### PR DESCRIPTION
**Pull request by avekens**
AV's Mathbox (see also #1418):
* new general theorems added: ~fdisjdmun (formerly ~uhgrunlem), ~elpr2elpr, ~riotaeqimp
* rearrangements of theorems
* new theorems ~uhgredgiedgb, ~upgredg2vtx, ~uspgredg2vtxeu, ~uspgridx2vlem, ~uspgridx2v, ~uspgredgaleord, ~uhgr0vusgr, ~uspgr1v1eop added
* some proofs shortened
* some comments improved

### CODE REVIEW

**Comment by benjub** [comment]
@avekens Funny note regarding elpr2elpr: one also has
|- ( A e. { B , C } -> E. x { B , C } = { A , x } )
Worth formalizing ?

**Comment by avekens** [comment]
> @avekens Funny note regarding elpr2elpr: one also has
> |- ( A e. { B , C } -> E. x { B , C } = { A , x } )
> Worth formalizing ?

Yes, that's really interesting: it does not require to assume that B and C are sets: if both are proper classes , then { B , C } = (/), and therefore A e. { B , C } is always false. If one of them is a proper class, say C, then  { B , C } = { B }. It follows that A = B, and with x = A it follows that { B , C } = { B } = { A } = { A , x }. I would appreciate that this theorem becomes part of main set.mm.

**Comment by benjub** [comment]
Actually, I was not volunteering ;-) Too much case-handling ! So it's up to you (and of course all credit would go to the person who formalizes).

**Comment by nmegill** [comment]
> I would appreciate that this theorem becomes part of main set.mm.

That would be fine.

**Comment by sctfn** [comment]
I just proved it in my branch. I'll make a PR including it when I get home.

**Comment by avekens** [comment]
@sctfn I have a proof, too! But make your PR, and we'll see which proof is shorter.

**Pull request merged**
