### PR TITLE
Add BTernaryTau to contributors list

### PR DESCRIPTION
**Pull request by jkingdon**
This is intended to fulfill the suggestion at https://github.com/metamath/set.mm/pull/3439#issuecomment-1694728667 about noting this contribution

### CODE REVIEW

**Comment by jkingdon** [comment]
I guess ideally this would get an approval from @BTernaryTau

The pull request just changes a comment where we list the contributors to metamath's set.mm

**Comment by wlammen** [comment]
In his PR #3433 he requested having his own mathbox.  Instead of adding him elsewhere and wondering whether he might like it, why not follow his suggestions directly and create that mathbox with a copy of 9p10ne21 in it?

It seems my remark about the value of his contribution in #3439 triggers some sort of protest here.  Before we lower the standard of officially recognizing someone as a new contributor to close to zero, can we please open an issue in this regard first?  I am against adding this PR without a prior discussion.

**Comment by jkingdon** [comment]
Not a protest, I thought we just listed everyone in the contributors list.

If you are saying we should slow down and think a bit about where to put this theorem, that sounds like good advice. We went pretty fast from #3433 to #3434 and #3439 and I think a certain amount of confusion or lack of ability to deliberate may have crept in.

In the interests of "slow down" I'll mark this as a draft pull request and suggest that it not be merged or closed or otherwise acted on for at least, say 2 days I guess (or some suitable amount of time).

I mean, this whole thing is supposed to be fun, so hopefully we can figure out how to get ourselves back to that mindset.

**Comment by digama0** [comment]
Agreed with @jkingdon , the rule for the contributors list is very straightforward: if you have contributed a theorem to set.mm you are in the list. If grepping for `Contributed by <name>` returns any result then `<name>` should be in the list (although there is perhaps some discussion to be had about whether Loof Lirpa should be represented there).

**Comment by wlammen** [comment]
We are free to reinterpret our rules and exclude that fun section from the contributors list.  This solves the Loof Lirpa problem, and requires nothing more than adding a comment in this respect to that section.

**Comment by digama0** [comment]
> We are free to reinterpret our rules and exclude that fun section from the contributors list.

What are you talking about? What rules are you referencing? I'm just describing the rules we have always applied with respect to the contributor list, which is quite maximalist and does not have any "quality bar" beyond inclusion in set.mm itself. If you think that this was a poor quality contribution which should not exist, then you should have argued this point before merging it into set.mm. (I think it was also not good that you took someone else's contribution and re-published it yourself without keeping the contributor as author of the commit, because now they will not get credits in the github contribution tracking.)

**Comment by wlammen** [comment]
I just added an opinion, I do not expect it to be shared by everyone.

**Comment by icecream17** [comment]
I think BTernaryTau should be added (and also credited) (edit: Oh, github commit instead of 9p10ne21. Less import there)
But Loop Lirpa is not actually a person (it's "April Fool" backwards), and it's similar to "the Metamath team" in conventions.

**Comment by avekens** [comment]
> Agreed with @jkingdon , the rule for the contributors list is very straightforward: if you have contributed a theorem to set.mm you are in the list. If grepping for `Contributed by <name>` returns any result then `<name>` should be in the list (although there is perhaps some discussion to be had about whether Loof Lirpa should be represented there).

I agree with @digama0 (and @jkingdon) that the rule for the contributors list should be as straightforward as explaind. Then we should add Loof Lirpa also to it (initials LL are still available). We have already several acronyms/synonyms in the list (Drahflow, M L, Mel L. O'Cat, OpenAI, etc.), and even BTernaryTau seems to be a synonym.

**Review by wlammen — APPROVED** [review]
I worked in the past a lot with standards, and every now and then I found an error or a shortcoming in them.  I used to notify the standards committee of it, and at the next scheduled version/release I could read my name among say 20 other contributors written in that document.  I usually was proud of it, and showed it to my friends.  This marks my mindset.

If correcting a typo is enough, and no commitment to our goals is required to make it on our lists, well, where is the honor then? It seems to be a list of acronyms used to keep tags short (my entry is removable then BTW).  But of course the majority rules.

Lessons learned.  I did not (dis-)approve, merge or close a single line of BTs contribution.  What I did was summarizing the then state of affairs in PR #3439, spinning the story a bit, along with a comment pinpointing what I thought was worth considering.  This discussion was admittedly short lived.  I should have used the draft mode to give it more time.

Murky waters.  BTs contribution adds a mathbox to the database.  He did not update his PR according to the evolving discussion.  Are we really obliged to merge his PR, only to edit its contents and move that to a final place right afterwards?

**Comment by digama0** [comment]
> If correcting a typo is enough, and no commitment to our goals is required to make it on our lists, well, where is the honor then? It seems to be a list of acronyms used to keep tags short (my entry is removable then BTW). But of course the majority rules.

Correcting a typo is not enough. (It is enough for github contribution, though.) You need to have contributed a theorem, in the sense of having a theorem with (Contributed by &lt;you>) in the file.

One of the original reasons for the contributor list is because it serves as a key for when people (especially NM) choose to sign using their initials instead of the full name. For this purpose, it is clear we want something to disambiguate those names, and it makes sense to put it in the context of all the other names you are likely to see in the file. In fact, I believe the same reasoning implies that it should include any (Revised by &lt;you>) credits, so if the "typo" is in a proof then that is also a way to get your name in the contribution list. But for the most part typo corrections in comments are not sufficient to get one of these credits, so it also doesn't get your name in the contribution list. If you write a significant amount of textual material in e.g. a section header, it might be a more complex matter, but so far that has never come up, generally only people who have already authored theorems write section headers.

I think we should make an exception for Loof Lirpa, as putting people who are not real in the header could be perceived as artificially counting sock-puppets and the like, which is not a direction I want to go. Let us just leave it as an unacknowledged easter egg to be discovered by those that stumble on the theorem itself.

**Comment by digama0** [comment]
> Murky waters. BTs contribution adds a mathbox to the database. He did not update his PR according to the evolving discussion. Are we really obliged to merge his PR, only to edit its contents and move that to a final place right afterwards?

Of course not. If the author is not responsive then the PR should languish or not be merged, we are not obligated to accept it. Accepting it and then performing fixes afterward (even in the same PR by another author) is also okay. But closing the original PR and making a new one with the fixes is tantamount to plagiarism, and I have seen this exact thing cause a lot of hurt feelings in other projects. This situation was not quite as bad as that because the "Contributed by" comment was preserved, but the git author was not.

**Comment by BTernaryTau** [comment]
Alright, I suppose I should explain my viewpoint and clarify my actions.

After browsing MPE for a while, I decided I wanted to try creating some proofs of my own. The [contributing page](https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md#how-can-i-contribute) says that "You should start small and try to reprove what's already proven with Metamath before you try to prove something new," so I started out by following some of [David Wheeler's tutorials](https://www.youtube.com/@DavidAWheeler). After that, I decided to go a little bigger and prove something new but still quite simple. I remembered the 9 + 10 = 21 meme and thought that disproving it would be an appropriate next step . At the same time, it seemed notable enough to be worth submitting, which was convenient since it would allow me to test the waters here sooner rather than later (more about that later on). I [referred to the contributing page](https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md#what-are-the-requirements-for-acceptance-merging) again, which says

> Many contributors have or create a personal "mathbox" - a sandbox of work that is visible to others. Changes to someone's own mathbox still go through a review, but usually it's cursory - we generally just want to ensure that those changes don't interfere with or confuse others.

Since this was a meme proof, I figured a mathbox would be the perfect place for it. Just to be sure, I looked for similar proofs, and found [2p2ne5](https://us.metamath.org/mpeuni/2p2ne5.html), which was indeed in a mathbox. So I created #3433, only to be surprised when it was suggested that it might fit better elsewhere. I hadn't realized that the humor section existed when I created the PR, but I had no objections to moving it there. Since I was busy that day and saw that no action had yet been requested of me, I waited to respond until tomorrow.

Sunday morning, I checked my notifications and saw [this comment](https://github.com/metamath/set.mm/pull/3439#issuecomment-1694658491). I get anxious pretty easily, and this comment immediately had me concerned that I had unintentionally started some drama. I ended up procrastinating on responding again. While that was happening, this PR was created, and the comments on it created yet another barrier to me wanting to respond. While my fears of drama had been overblown, there was still talk of "protests" and "lowering standards" which I wanted nothing to do with. There was also some misgendering (I go by she/her pronouns) which stung a bit as well. You can likely guess how I responded to all of that...

Anyway, that brings us to now, when I'm finally typing this all up. I'm not sure how I feel about engaging with this community further. I imagine my initial experience here was unusually bad, and certainly much of that was my own fault. But I nonetheless feel justified in saying that this was not a welcoming approach to handling my submission. I mentioned earlier that one reason I made it was to test the waters early on, and I'm glad I did so, because I would really hate to have sunk a lot more time and effort into creating a more involved proof to submit, only for something like this to happen.

I would like to thank those who argued that it was important for me to be credited. It was a bright spot in an otherwise disappointing interaction, and I appreciate that. I'd also like to mention that I am happy so many people are working hard on this project, as I really admire it.

**Review by BTernaryTau — APPROVED** [review]

**Comment by digama0** [comment]
Thanks @BTernaryTau for sharing your perspective. I think it is quite clear that your contributions were just fine for a first theorem, especially if they are in a mathbox, and your bad first impression of us is exactly what I was afraid of happening as a result of jumping on a new contributor in this way. I have a question for you: do you mind sharing your real name to be used here in the contributor list and in set.mm? We generally prefer using real names in the database, although it's fine if you prefer to use your github handle instead. (Also apologies for the misgendering issue.)

EDIT: Based on your github profile and blog, it seems you prefer to go by your handle. In which case I think this PR is good to go.

**Comment by wlammen** [comment]
First of all my apologies for using the wrong gender, too.

Second, welcome on board.  Yes, you started a drama, discussion, whatever, but I do not blame you for that. The contention is a sort of internal affair in my eyes, a chance to improve on our processes.

Lets start with my [comment](https://github.com/metamath/set.mm/pull/3439#issuecomment-1694658491) .  In hindsight I would change one phrase to `...we run the risk to be utilized and contribute to this event...` , but otherwise I'd write it again on a similar occasion.  I cannot tell from the context given in your comment what the purpose of your contribution is.  Our problem here: Once an addition is made, it is permanent.  There is no way to revert it easily, we usually need the authors consent for it.  And if s/he is unwilling, or even disappears from the scene, we are stuck with something like 9 + 10 =/= 21, consuming space and to a small degree maintenance.  I'd rather see our documentation and processes updated, encouraging a "Test" attribute for beginners, with a grace period after which such material can be deleted, if appropriate.

Next is our contributors list.  Everything was said about it, the standpoints are clear, and a decision was made (again).  Such a process is not free of contention, by nature, but this is nothing you need to be bothered about.  Maybe the style of discussion could change, given that it is publicly visible.

Finally there is the problem of a contribution necessary to appear on the author list of GitHub.  This list does not reflect the overall state of Metamath, since authors like FL for example, who left this project before it was hosted on GitHub, are not included.  But okay, it may have its own value.  What I dislike (and currently I do not even know how to do it) is to edit posts on behalf of someone else, assuming the result will meet his expectations.  From my point of view this is not settled, and hopefully I personally get not involved in measures like this.

**Comment by digama0** [comment]
>  What I dislike (and currently I do not even know how to do it) is to edit posts on behalf of someone else, assuming the result will meet his expectations. From my point of view this is not settled, and hopefully I personally get not involved in measures like this.

I do not know what this is a reference to. But I think it is bad form to continue discussion on this point in this PR, so if you would like to bring it up start a new issue or a thread on the mailing list please.

**Comment by jkingdon** [comment]
> I'm not sure how I feel about engaging with this community further. I imagine my initial experience here was unusually bad, and certainly much of that was my own fault.

I would say that 0% of it it was your fault. Your submission was a perfectly normal one and received some warm reactions (which later gave way to what you justifiably call drama, and I'm still a bit baffled about how it took that turn, but whatever it was it was something we did not something you did).

And yes it was super smart to test the waters with something small! We've sometimes had first time contributions which are large collections of proofs and there's a lot to go through in that sort of submission at the same time that we are getting to know a new contributor and they are getting to know the project.

Whether this episode speaks badly of our community, well to some extent obviously it does. I guess all I can do is report that at least for me, despite some struggles with collaboration, I have stayed around. This is due to a large number of positive interactions, some of them truly delightful, including various people helping me prove theorems I couldn't have proved on my own. I would love it if you do the same (while fully understanding if you choose not to, or choose not to just now).

**Pull request merged**
