### PR TITLE
Shorten set.mm proof of fzm1

### PR DESCRIPTION
**Pull request by jkingdon**
This is the proof I came up with for iset.mm and it is
814 characters whereas the previous one was 1043 characters.

I send this as a separate pull request because I don't know whether people are interested when I find somewhat shorter proofs as part of intuitionization. There might be more lurking in iset.mm but I didn't really make a list (and some of them might depend on theorems not in set.mm, which isn't an issue for this one) or in many cases even measure the length.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
If it's a shorter proof that doesn't require additional axioms we've generally accepted the shortening. I don't see why this would be different. Hooray for shorter proofs!

**Comment by jkingdon** [comment]
> If it's a shorter proof that doesn't require additional axioms we've generally accepted the shortening. I don't see why this would be different. Hooray for shorter proofs!

Seems to be the same axioms.

Before:

```
MM> show proof fzm1/size
The proof source for "fzm1" has 1043 characters.
MM> show trace_back fzm1/axioms/essential/match ax-*
Statement "fzm1" assumes the following axioms ($a statements):
  ax-mp ax-1 ax-2 ax-3 ax-gen ax-4 ax-5 ax-6 ax-7 ax-8 ax-9 ax-10 ax-11 ax-12
  ax-13 ax-ext ax-sep ax-nul ax-pow ax-pr ax-un ax-cnex ax-resscn ax-1cn ax-icn
  ax-addcl ax-addrcl ax-mulcl ax-mulrcl ax-mulcom ax-addass ax-mulass ax-distr
  ax-i2m1 ax-1ne0 ax-1rid ax-rnegex ax-rrecex ax-cnre ax-pre-lttri ax-pre-lttrn
  ax-pre-ltadd ax-pre-mulgt0
```

After:
```
MM> show proof fzm1/size
The proof source for "fzm1" has 814 characters.
MM> show trace_back fzm1/axioms/essential/match ax-*
Statement "fzm1" assumes the following axioms ($a statements):
  ax-mp ax-1 ax-2 ax-3 ax-gen ax-4 ax-5 ax-6 ax-7 ax-8 ax-9 ax-10 ax-11 ax-12
  ax-13 ax-ext ax-sep ax-nul ax-pow ax-pr ax-un ax-cnex ax-resscn ax-1cn ax-icn
  ax-addcl ax-addrcl ax-mulcl ax-mulrcl ax-mulcom ax-addass ax-mulass ax-distr
  ax-i2m1 ax-1ne0 ax-1rid ax-rnegex ax-rrecex ax-cnre ax-pre-lttri ax-pre-lttrn
  ax-pre-ltadd ax-pre-mulgt0
```

**Comment by david-a-wheeler** [comment]
@jkingdon - sounds like a winner! Nice job!

**Comment by jkingdon** [comment]
> @jkingdon - sounds like a winner! Nice job!

For extra credit, write a script that compares identically-stated theorems between set.mm and iset.mm, finds the ones where the iset.mm proof is shorter, finds which ones of those would work in set.mm (that is, do not depend on statements which set.mm doesn't have), finds which ones do not introduce new axioms, and prints out the list.

No, I'm not volunteering :grin:

**Comment by nmegill** [comment]
> I don't know whether people are interested when I find somewhat shorter proofs as part of intuitionization.

Yes, definitely.

BTW you are welcome to add "(Proof shortened by...)" if you wish, but it is optional.  Often we also keep the original as *OLD for interesting shortenings so they can be studied by others more easily.

**Comment by jkingdon** [comment]
> BTW you are welcome to add "(Proof shortened by...)" if you wish, but it is optional.

I might have submitted a few of these but on the whole I find them kind of hard to maintain and.... well just tend to not exercise that option.

> Often we also keep the original as *OLD for interesting shortenings so they can be studied by others more easily.

OK. I guess I won't declare this one to be interesting, but if anyone wants to add an *OLD for it, I wouldn't object either.

**Pull request merged**
