### PR TITLE
janitorial work

### PR DESCRIPTION
**Pull request by wlammen**
1. shorten nfv;
2. consistent naming of theorems;
3. duplicated theorems;
4. update history of theorems (still incomplete);
5. group OLD theorems for a. better comparison b. less disruptive experience for normal users;
6. restore some OLD theorems that went lost, but are suitable for comparison'.

### CODE REVIEW

**Comment by benjub** [comment]
I think wnfOLD can also be removed, since it is identical to wnf (what's important is df-nfOLD).

**Comment by benjub** [comment]
Also, the labels I had given to nftht0, nfntht, nfntht2 are not very good... Maybe @nmegill or @digama0 have better suggestions?

**Comment by wlammen** [comment]
> I think wnfOLD can also be removed, since it is identical to wnf (what's important is df-nfOLD).

I am not sure here.  I think you cannot define the same thing twice.  If I remember right, it was mmj2 that complains about that and rejects the idea.  Growling sth like 'Definitions are not sound'.

In a situation where you compare two directly competing ideas like df-nf vs nf5, I think a full and enforced separation is a good idea.  This leaves open, what to do, if two competing theories share a common base. This leads to the concept of interfaces, something I know from my profession.  Here is headroom for improvement and relaxation of rules.

In the case of not-free could one have allowed a common usage of the symbol? Because you can demonstrate equivalence in BOTH cases, no matter what definition you pick?  Well, actually only, if the axioms up to ax-12 are in full effect. Before you are on unsafe grounds.

**Comment by wlammen** [comment]
I added yet another commit to this pull request, but it wouldn't show up.  Did I surpass some internal counter limit?  My private copy on github shows a total count of 16 commits, but only 15 are transmitted here.  Anyway, I will leave it at that, and create another PR once this one is accepted.

**Comment by wlammen** [comment]
@benjub I am pretty sure I overlooked some details. In the end, it was a massive change, at least compared to my usual contributions.  I work full time in a job that is neither related to Metamath, or mathematics or science in general. Which puts some stress on me in a situation like this, where others possibly wait for me to finish. Feel free to correct anything you spot without bothering to ask for permission.

**Pull request merged**
