### PR TITLE
Add scripts/check-raw-html and use it in .travis.yml

### PR DESCRIPTION
**Pull request by david-a-wheeler**
This adds a check of "raw" html files to detect markup problems.

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
For this commit to *work* as expected, the metamath at http://us.metamath.org/downloads/metamath.tar.bz2 will need to be updated to include the markup command.

**Comment by nmegill** [comment]
OK, metamath.tar.bz2 is on the us server.

On 30 Dec 2016 we talked about a download of just the program without *.mm, which I made and is called metamath-program.zip (which I also put on the us server).  I thought it was going to be used for Travis; if so, has that idea been abandoned?

**Comment by david-a-wheeler** [comment]
> On 30 Dec 2016 we talked about a download of just the program without *.mm, which I made and is called metamath-program.zip (which I also put on the us server). I thought it was going to be used for Travis; if so, has that idea been abandoned?

I didn't remember that you did it.  I will chalk that up to "it was the end of the year and I was confused".

I will make a pull request so that Travis uses that instead.  It'll save some time and bandwidth.

**Comment by david-a-wheeler** [comment]
We can't switch to metamath-program.zip right now because it's missing the configure.ac file.  Can you please add that?  I created a separate issue to track this: https://github.com/metamath/set.mm/issues/687

**Pull request merged**
