### PR TITLE
Add new pre-image theorems

### PR DESCRIPTION
**Pull request by glacode**
- Reduced $d constraints by replacing them with 'effectively not free' hypotheses.
- Improves theorem usability and simplifies certain dependencies.

- mathboxonly

### CODE REVIEW

**Review by sctfn — APPROVED** [review]

**Review by icecream17 — APPROVED** [review]

**Comment by wlammen** [comment]
If you use the revision tag, please note the reason for the revision.  Here you sort of singled out common proof steps, and then reused that in the original theorems.  Such a reuse can be seen as an automatic minimization, which does not require an extra tag.

**Comment by glacode** [comment]
Thank you for your comment. Can you please write the label of a theorem with an example of such a note for a revision?

**Comment by wlammen** [comment]
[ralrimi](https://us.metamath.org/mpeuni/ralrimi.html) and [hbralrimi](https://us.metamath.org/mpeuni/hbralrimi.html) is an example from Dec-2019, where this is still visible in the comments.

**Comment by glacode** [comment]
Thank you for the example. I see that the note is placed between the ContributedBy and RevisedBy tags.
After reviewing other examples in set.mm, I'll adopt this style for future PRs.

**Pull request merged**
