### PR TITLE
Definition of r for AKS Lemma,

### PR DESCRIPTION
**Pull request by metakunt**
I need some help with the definition of R In the AKS formalisation effort given the paper https://www3.nd.edu/~andyp/notes/AKS.pdf

In lemma 4.1 I just have defined r to be the smallest integer not dividing A and I just have shown that r is a natural number smaller than B.

Does my proof of aks4d1p4 sufficiently formalise this statement in the paper:
" We conclude that some element of {1, . . . , B} does not divide A, so r ≤ B, as claimed."?

### CODE REVIEW

**Comment by metakunt** [comment]
I have tried to sketch the following formalisation in @tirix blueprint repo here: https://github.com/tirix/metamath-blueprints/issues/12

**Comment by metakunt** [comment]
Maybe to briefly sketch my end goal of lemma 4.1. I want to prove the following statement:
```
( ph -> E. r e. ( 1 ... B ) ( ( N gcd r ) = 1 /\ ch ) )
```
where ch is the formalised order inequality in the paper, I'd have to look up the definition, but by that point I'd have discharged A from the proof context successfully.

**Comment by metakunt** [comment]
I assume that the existence statement (lemma 4.1) is necessary to prove theorem 2.2 from theorem 6.1, as it needs existence. I don't yet see the detailed reason why.

**Comment by tirix** [comment]
Hi @metakunt !
I'm sorry I've been really busy lately and I'm taking some time to answer.
As stated right now in this PR, the `R` variable is not the same as in the proof of statement 4.1.
Instead of 
```
$e |- R = inf ( { r e. ( 1 ... B ) | -. r || A } , RR , < )
```
I would write:
```
$e |- R = inf ( { r e. NN | -. r || A } , RR , < )
```
And the first goal is to prove:
```
$p |- ( ph -> R <_ B )
```

**Comment by metakunt** [comment]
No worries about that, I am in no hurry and we have lots of time to formalise this beast :)

Ah, thanks for the input. I have looked at the proof and it won't generalise that well. I remember now why I've defined R the way that I did. Basically your definition was my first draft of a definition, but then I've realised that I've proven a stronger existence statement in https://us.metamath.org/mpeuni/aks4d1p3.html.
Basically I'd like to keep the definition of R and A for the following few statements which will then disappear with eqid.

I think that Theorem 4.1 states that there is a natural number r (different from R) smaller than B such that gcd(n,r)= 1 and $$lb^2(n)<ord_r(n)$$. This so far has not much to do with my R except that I want to use 

https://github.com/tirix/metamath-blueprints/issues/12 here is the issue for crosslinking. 

Basically I want to use https://us.metamath.org/mpeuni/rspcedvd.html in the final theorem with the following context:
Fixup for order function necessary
```
|- ( ph -> R e. ( 1 ... B ) )
|- ( ( ph /\ r = R ) -> ( ( (r gcd N ) = 1 /\ ( od ` r ) < B )<->( (R gcd N ) = 1 /\ ( od ` R ) < B ) ) )
|- ( ph -> (R gcd N ) = 1 /\ ( od ` R ) < B) ) )
______
|- ( ph -> E. r e. ( 1 ... B ) ( (r gcd N ) = 1 /\ ( od ` r ) < B ) )
```
Do you now see that it does not matter how I've defined R, as I would use eqid in that proof anyways?
Similarly with A, both A and R disappear in that proof.

I am left to prove the following two statements now.
```
|- ( ph -> ( R gcd N ) = 1 )
|- ( ph -> ( N od R ) < B )  /// Todo @metakunt find the correct order function to finish proof.
```

**Comment by tirix** [comment]
> Basically I'd like to keep the definition of R and A for the following few statements which will then disappear with eqid.
> 
Yes, I think that would work too.

> I think that Theorem 4.1 states that there is a natural number r (different from R) smaller than B such that gcd(n,r)= 1 and l b 2 ( n ) < o r d r ( n ) . This so far has not much to do with my R except that I want to use.
> 
My understanding of the proof of Theorem 4.1 is that it is actually constructive, i.e. the $r$ defined in the proof actually exhibits properties of Theorem 4.1, so it is actually the same $r$. 

In the following, it does not matter how that $r$ was obtained, only its existence with the `gcd` and `od` properties matter, so any other proof works.

> Do you now see that it does not matter how I've defined R, as I would use eqid in that proof anyways? Similarly with A, both A and R disappear in that proof.
> 
Yes, `A` disappears (it is only used in the construction of `R`), and `R` disappears too as it just becomes an `E. r ...`.

**Comment by metakunt** [comment]
Ok cool, I have worked a little bit on the proof context. Here are the relevant steps.
```
h50::aks4d1p5.1    |- ( ph -> N e. ( ZZ>= ` 3 ) )
h51::aks4d1p5.2    |-   A
                      = ( ( N ^ ( |_ ` ( 2 logb B ) ) )
                          x.
                          prod_ k
                          e.    ( 1
                                  ...
                                  ( |_ ` ( ( 2 logb N ) ^ 2 ) ) )
                                ( ( N ^ k ) - 1 ) )
h52::aks4d1p5.3    |-   B
                      = ( |^ ` ( ( 2 logb N ) ^ 5 ) )
h53::aks4d1p5.4    |-   R
                      = inf
                        (   { r e. ( 1 ... B ) | -. r || A }
                        ,   RR
                        ,   < )
139::              |- (  ( ph /\ 1 < ( N gcd R ) )
                      -> -. ( R / ( N gcd R ) ) || A )
qed:164,190:pm2.61dan  |- ( ph -> ( N gcd R ) = 1 )
```
I've left out all the already proven substeps.
This atleast corresponds to the substep: "From this, we see that r/ gcd(n, r) must also not divide A."

Now I'm struggling trying to find a fitting theorem to prove this statement.

It appears to boil down to the following statement.
If every prime divisor of r also divided n, then this would imply that r divided A.
contradicting our choice of r. 

I assume I can cleverly split 139 into two statements by contradiction, one is 
```
R || A 
```
and the second is 
```
-. R || A 
```
The second statement is a hypothesis, so I should be left to show that R || A.
But populating the proof context is quite hard and I can't wrap my head around it.

My head is cooking and I'm dizzy. If someone has a formalised lemma that clarifies what I need to prove I'd be happy.
I'm not really struggling with the proofs per se, I'm more struggling with the fact that I don't know how to break the theorem down such that formalisation is easier.

**Comment by tirix** [comment]
> How to break the theorem down such that formalisation is easier?

You could go along the proof sentences. We can use the prime count function `pCnt` to express the first one:
If $p$ is a prime divisor of $r$ and $p^k$ is the maximal power of $p$ dividing $r$, then since $p^k ≤ r ≤ B$ we must have $k ≤ \lfloor{\log{B}}\rfloor$
```
$e |- ( ph -> P e. Prime ) $.
$e |- ( ph -> P || R ) $.
$e |- K = ( P pCnt R ) $.
$p |- ( ph -> K <_ ( |_ ` ( 2 logb B ) ) ) $.
```
Then you could use this lemma to start a contradiction along:
If every prime divisor of $R$ also divided $N$, then this would imply that $R$ divided $N^{\lfloor \log B \rfloor}$
```
$e |- ( ( ph /\ p e. Prime /\ p || R ) -> p || N ) $.
$p |- ( ph -> R || ( N ^ ( |_ ` ( 2 logb B ) ) ) $.
```
What works well for me for such contradiction proofs is `pm2.65da`:
```
|- ( ( ph /\ A. p e. Prime ( p || R -> p || N ) ) -> R || ( N ^ ( |_ ` ( 2 logb B ) ) ) ) $.
|- ( ( ph /\ A. p e. Prime ( p || R -> p || N ) ) -> -. R || ( N ^ ( |_ ` ( 2 logb B ) ) ) ) $.
|- ( ph -> -. A. p e. Prime ( p || R -> p || N ) ) $.
```
Where the first assertion comes from the lemma above, the second from the hypothesis (`-. R || A`), and the last step uses `pm2.65da`.

This should lead to:
```
|- ( ph -> E. p e. Prime ( p || R /\ -. p || N ) ) $.
```

> `|- ( ph -> ( N od R ) < B )`  /// Todo @metakunt find the correct order function to finish proof.

I think that this `( N od R )` would be the ``( O ` N )`` I define in [the 6.1 blueprint](https://tirix.github.io/metamath-blueprints/AKS%20(PRIMES%20is%20in%20P)/aks61.html):
```
$e |- G = ( Z/nZ ` R ) $.
$e |- O = ( od ` G ) $.
$e |- L = ( O ` N )  $.
```
Where `L` represents the paper's $\ell$.

**Comment by metakunt** [comment]
Ok thank you very much. I was also debating on using the prime counting function in some capacity as I assumed that the fundamental theorem of arithmetic is proven.
I wanted to use https://us.metamath.org/mpeuni/1arith2.html to write it as a finite product of prime powers and then work on that, but I guess I'll study your approach a bit more to understand it better

**Comment by metakunt** [comment]
Here is the first formalised statement:
```
  ${
    aks4d1p6.1 $e |- ( ph -> N e. ( ZZ>= ` 3 ) ) $.
    aks4d1p6.2 $e |- A = ( ( N ^ ( |_ ` ( 2 logb B ) ) ) x. prod_ k e.
     ( 1 ... ( |_ ` ( ( 2 logb N ) ^ 2 ) ) ) ( ( N ^ k ) - 1 ) ) $.
    aks4d1p6.3 $e |- B = ( |^ ` ( ( 2 logb N ) ^ 5 ) ) $.
    aks4d1p6.4 $e |- R = inf ( { r e. ( 1 ... B ) | -. r || A } , RR , < ) $.
    aks4d1p6.5 $e |- ( ph -> P e. Prime ) $.
    aks4d1p6.6 $e |- ( ph -> P || R ) $.
    aks4d1p6.7 $e |- K = ( P pCnt R ) $.
    aks4d1p6 $p |- ( ph -> K <_ ( |_ ` ( 2 logb B ) ) ) $= ? $.
  $}
```

If everything looks fine to you I'll start formalising this one.
It will be done in a separate PR to keep things going, so after this is ok, this pr may be merged.

**Comment by tirix** [comment]
> If everything looks fine to you

Yes this looks good to me!
This single step should not be too hard, I believe.

**Review by tirix — APPROVED** [review]
Oh actually, you were faster proving the statement than I was answering your message!

**Comment by metakunt** [comment]
Yeah, this is good enough for the current pr. Your hint was very helpful, the proof work was as easy as a hot knife going through butter.
In the upcoming draft PR I'll get the statements ready first and then once that looks good working on proving them.

**Pull request merged**
