### PR TITLE
Add a Skip command at the beginning of the set-class.mm part

### PR DESCRIPTION
**Pull request by benjub**
This is in order to make that part verifiable as a standalone when using the 'split' form.  This fixes Issue #2792 with the fix proposed by @amelieled.

I have to say that this splitting mechanism with "Skip" & co. seems to get a bit complex when having mixed adjacent and nested inclusions.  For instance, I couldn't make set-tarskigeom.mm verify even when adding one or several Skip commands.

By the way: @tirix , @avekens : do you really need to subdivide your mathboxes using this method ? This creates a lot of files:
```
Reading source file "set.mm"... 2866 bytes
Reading included file "set-header.mm"... 9033 bytes
Reading included file "set-main.mm"... 20375094 bytes
Reading included file "set-pred.mm"... 1010227 bytes
Reading included file "set-class.mm"... 878794 bytes
Reading included file "set-tarskigeom.mm"... 812142 bytes
Reading included file "set-graphth.mm"... 1566025 bytes
Reading included file "set-deprec.mm"... 392180 bytes
Reading included file "set-typeset.mm"... 279136 bytes
Reading included file "set-hilsp.mm"... 1034075 bytes
Reading included file "set-mbox.mm"... 11799550 bytes
Reading included file "set-mbox-ta.mm"... 207134 bytes
Reading included file "set-mbox-ta-basics.mm"... 257077 bytes
Reading included file "set-mbox-ta-xdiv.mm"... 11845 bytes
Reading included file "set-mbox-ta-prime.mm"... 12092 bytes
Reading included file "set-mbox-ta-algtop.mm"... 443035 bytes
Reading included file "set-mbox-ta-ucm.mm"... 1405 bytes
Reading included file "set-mbox-ta-rrhom.mm"... 62168 bytes
Reading included file "set-mbox-ta-man.mm"... 3822 bytes
Reading included file "set-mbox-ta-logb.mm"... 1939 bytes
Reading included file "set-mbox-ta-ind.mm"... 13331 bytes
Reading included file "set-mbox-ta-esum.mm"... 105304 bytes
Reading included file "set-mbox-ta-ofc.mm"... 8189 bytes
Reading included file "set-mbox-ta-meas.mm"... 261254 bytes
Reading included file "set-mbox-ta-itgm.mm"... 47991 bytes
Reading included file "set-mbox-ta-eulerpart.mm"... 71837 bytes
Reading included file "set-mbox-ta-fibonacci.mm"... 23068 bytes
Reading included file "set-mbox-ta-proba.mm"... 77083 bytes
Reading included file "set-mbox-ta-ballot.mm"... 77939 bytes
Reading included file "set-mbox-ta-signum.mm"... 11352 bytes
Reading included file "set-mbox-ta-signs.mm"... 103434 bytes
Reading included file "set-mbox-ta-geom.mm"... 24073 bytes
Reading included file "set-mbox-ai.mm"... 106125 bytes
Reading included file "set-mbox-bj.mm"... 315583 bytes
Reading included file "set-mbox-ml.mm"... 77791 bytes
Reading included file "set-mbox-sn.mm"... 2977 bytes
Reading included file "set-mbox-oai.mm"... 673 bytes
Reading included file "set-mbox-so.mm"... 715924 bytes
Reading included file "set-mbox-jp.mm"... 23138 bytes
Reading included file "set-mbox-av.mm"... 478 bytes
Reading included file "set-mbox-av-2reu.mm"... 17596 bytes
Reading included file "set-mbox-av-afv_aov.mm"... 58385 bytes
Reading included file "set-mbox-av-aux.mm"... 162473 bytes
Reading included file "set-mbox-av-nt.mm"... 128113 bytes
Reading included file "set-mbox-av-even-odd.mm"... 178128 bytes
Reading included file "set-mbox-av-graph.mm"... 45531 bytes
Reading included file "set-mbox-av-matrix.mm"... 660021 bytes
Reading included file "set-mbox-ew.mm"... 55296 bytes
```

### CODE REVIEW

**Comment by avekens** [comment]
I did not work within my mathbox for a long time, therefore I cannot really tell if I (still) need the splitting of my mathbox into several files. I can remember that it was useful as I worked on graph theory: I had opened set-mbox-av-graph.mm only in my editor, and it was quite handy. If this causes problems, however, the intermediate "breaks" can be removed.

**Review by avekens — APPROVED** [review]

**Comment by benjub** [comment]
Since there is no big risk of merge conflict, I'm waiting a bit before merging. Maybe @david-a-wheeler, who is more versed in the computer aspects, has remarks to make regarding these splitting matters.

**Comment by david-a-wheeler** [comment]
I know how to spell "computer" :-), but I've never used the splitting system & I've forgotten what I used to know.

The ability to split things into multiple smaller files does seem useful; set.mm has gotten pretty big. If there's a better way to handle it, discussion seems reasonable.

If it's something we want to support long-term, we should probably test it in our CI tests.

**Comment by benjub** [comment]
Thanks @david-a-wheeler, our great computer wizard !  I'm going to merge this PR, but modularity is definitely something we will need to work on.

Let's warn @amelieled that the `split` method is not the most robust feature of metamath.c... If set.mm is too large, maybe you're better off simply making manually a file set0.mm which is an initial segment of set.mm, and work on it without `split`. By the way: are you using Metamath in conjunction with $\lambda\Pi$-calculus ? (Gilles D. was my teacher !)

**Pull request merged**
