### PR TITLE
Graph Theory - minor changes

### PR DESCRIPTION
**Pull request by avekens**
Changes:
* ~clwwlksnwwlksn moved up
* ~clwwlksnlbonbgr1 added

About Git: no chance, I performed several resets, rebases, pushes and pulls with various parameters, but I got not rid of the commits starting in December 2021. So either I have to delete my fork and start from the very beginning, or this PR is merged without squash...

### CODE REVIEW

**Review by benjub — APPROVED** [review]

**Comment by benjub** [comment]
Approved, and can be merged by someone who knows the implications of "squash and merge" versus "rebase and merge" better than me (@tirix, @digama0, @jkingdon ?).

**Comment by digama0** [comment]
Squash and merge will do just fine here, and is arguably the best way to clean up the mess, at least on our end. @avekens might need to do some more work to get back in a sensible state; I'm not sure what the state of their branch is.

**Comment by digama0** [comment]
Observation: you are trying to merge `avekens/develop` into `metamath/develop`, this is bad practice. You should always create a new branch before PR'ing it to set.mm, because your develop branch is already tracking `metamath/develop`, so every time you pull you will end up putting more commits on this PR.

**Comment by digama0** [comment]
My suggestion to clean up the situation: I will squash and merge this now, resulting in `metamath/develop` moving forward by one commit. This should bring your `develop` branch up to parity in terms of contents with `metamath/develop`, but if you try to pull it will create yet another merge commit. Instead, you should `git fetch` and then `git reset origin/develop`, which will move your `develop` branch to the latest. If by any chance there are still some lingering differences, they will not be lost by this operation but will end up in your staging area and you can decide whether you want to PR them (on a new branch!) or not. Finally, you should `git push -f` to update your github fork to match (which will discard all those old merged commits).

**Pull request merged**
