### PR TITLE
Analog vs. analogue

### PR DESCRIPTION
**Pull request by avekens**
See #1908: Agreement to use "analogue" for the noun and "analogous" for the adjective:
* "analog" replaced by "analogue" resp. "analogous"
* convention to use "analogue" for the noun and "analogous" for the adjective added

AV's mathbox:
* Some rearrangements and minor changes/corrections in the comments in section "extended nonnegative integers"

### CODE REVIEW

**Comment by wlammen** [comment]
In some places you separate the reference marker ~ from the theorem/definition name, as done with ~ df-xr. To my knowledge, the Metamath translation process will not render the name as a hyperlink anymore, and you cannot access the originating theorem entry by just clicking. This is within your mathbox, so maybe, there was good reason to do so. But just in case this was not intended, I notify you hereby.

**Comment by avekens** [comment]
@wlammen I got an email with a comment for this PR (about the usage of ~) - but it does not appear here (anymore).
@nmegill Indeed, it seems that for a tilde ~ followed by a token a link in the HTML output is created no matter if there is a blank between ~ and the token or not. Both variants are used in set.mm (e.g. ~ax6e2nd and ~ ax6e). Which is the preferred way? I think it is the variant with the blank between ~ and the token. Should this become a convention?

**Comment by nmegill** [comment]
> @nmegill Indeed, it seems that for a tilde ~ followed by a token a link in the HTML output is created no matter if there is a blank between ~ and the token or not. Both variants are used in set.mm (e.g. ~ax6e2nd and ~ ax6e). Which is the preferred way? I think it is the variant with the blank between ~ and the token. Should this become a convention?

Even though  "\~ax6e2nd" works, the variant "\~ ax6e" has been our convention which is used in 99+% of cases.  Historically I chose that so a match to " ax6e " can be used to make global label changes in a text editor without having to use a regex.  I suppose "verify markup" should complain when the space is missing to make sure we're consistent; I'll put it on my list.

**Comment by wlammen** [comment]
@avekens I thought for a moment a tilde must precede a theorem name immediately to form a valid link. Before finally posting to this respect, I checked the set.mm file and learned I used the space myself. An incoming message distracted me then, and sometime later I accidentally hit the send button of the prepared post. Although I deleted the message immediately afterwards, it was online visible for a couple of seconds. And that was apparently sufficient to notify you of this event.

So I was simply mistaken, and there is no need to care about the contents.

**Comment by benjub** [comment]
There are a few cases remaining. I fixed the three occurrences of "analog\n" (end of lines) and the single occurrence of "analog," in #2380. There are 298 occurrences of "analog.". Probably, most of them are nouns (so have to be changed to "analogue.", but we have to check whether some of them are adjectives (so have to be changed to "analogous."). I'll fix them when things are quieter (to avoid merge conflicts), if @avekens agrees.

**Pull request merged**
