### PR TITLE
add more finite set theorems to iset.mm

### PR DESCRIPTION
**Pull request by jkingdon**
This is part of the section "Finite sets" and the rest of the section "Miscellaneous theorems about integers". Some of this intuitionizes, much does not which is duly noted in mmil.html.

The pull request also considers http://us.metamath.org/mpeuni/ssfi.html . Bauer rhetorically asks "No sane mathematician would reject the fact that a subset of a finite sets is finite, right?" The implication being that this is one of the "boxer's fists" that Hilbert would not deny to a mathematician.

You may see where this is going - ssfi implies excluded middle which is proved in this pull request as ssfiexmod .

### CODE REVIEW

**Comment by nmegill** [comment]
I'll mention that the "W3C HTML validation" link in the lower right of http://us.metamath.org/ileuni/mmil.html shows a number of minor errors that you may want to address at some point, probably not urgent since they don't appear to affect the display.  (You can open a formal issue if you think it's necessary, or just fix them informally in a future PR.)

**Comment by jkingdon** [comment]
> I'll mention that the "W3C HTML validation" link in the lower right of http://us.metamath.org/ileuni/mmil.html shows a number of minor errors that you may want to address at some point, probably not urgent since they don't appear to affect the display. (You can open a formal issue if you think it's necessary, or just fix them informally in a future PR.)

I've made a pull request for this at #1661 

In the process of looking into this I noticed:

1. there are two validation errors in mmset.html

2. it would be nice to run validation as part of travis, to prevent these problems creeping back in, and

3. there seems to be a newer validator at https://validator.w3.org/unicorn/ . We'd need to update our HTML but that isn't necessarily a bad thing.

**Comment by david-a-wheeler** [comment]
Switching to Unicorn is possible, but it would require serious changes to the html, including a mass switch to css. There are 515 unicorn errors on set.mm. Here are just the first ones:

~~~~
 Errors (515)
URI: http://us.metamath.org/mpegif/mmset.html		
a
			Legacy encoding “windows-1252” used. Documents must use UTF-8. 	
a
1 		<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <HTML 	Almost standards mode doctype. Expected “”. 	
a
9 		le=1.0"> <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1"> <TITL 	Bad value “text/html; charset=iso-8859-1” for attribute “content” on element “meta”: “charset=” must be followed by “utf-8”. 	
a
57 		</HEAD> <BODY BGCOLOR="#FFFFFF" STYLE="padding: 0px 8px"> <TAB 	The “bgcolor” attribute on the “body” element is obsolete. Use CSS instead. 	
a
59 		px 8px"> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="100%"> <T 	The “cellspacing” attribute on the “table” element is obsolete. Use CSS instead. 	
a
59 		px 8px"> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="100%"> <T 	The “cellpadding” attribute on the “table” element is obsolete. Use CSS instead. 	
a
59 		px 8px"> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="100%"> <T 	The “width” attribute on the “table” element is obsolete. Use CSS instead. 	
a
59 		px 8px"> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="100%"> <T 	The “border” attribute on the “table” element is obsolete. Use CSS instead. 	
a
61 		"> <TR> <TD ALIGN=LEFT VALIGN=TOP><A HRE 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
61 		"> <TR> <TD ALIGN=LEFT VALIGN=TOP><A HRE 	The “valign” attribute on the “td” element is obsolete. Use CSS instead. 	
a
62 		dex.html"><IMG SRC="mm.gif" BORDER=0 ALT="Metamath Home" TITLE="Metamath Home" HEIGHT=32 WIDTH=32 ALIGN=TOP STYLE="margin-bottom:0px"></A> 	The “align” attribute on the “img” element is obsolete. Use CSS instead. 	
a
67 		</TD> <TD ALIGN=CENTER VALIGN=TOP><FONT 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
67 		</TD> <TD ALIGN=CENTER VALIGN=TOP><FONT 	The “valign” attribute on the “td” element is obsolete. Use CSS instead. 	
a
68 		ALIGN=TOP><FONT SIZE="+3" COLOR="#006633"><B>Met 	The “font” element is obsolete. Use CSS instead. 	
a
70 		</TD> <TD NOWRAP ALIGN=RIGHT VALIGN=TOP><FONT 	The “nowrap” attribute on the “td” element is obsolete. Use CSS instead. 	
a
70 		</TD> <TD NOWRAP ALIGN=RIGHT VALIGN=TOP><FONT 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
70 		</TD> <TD NOWRAP ALIGN=RIGHT VALIGN=TOP><FONT 	The “valign” attribute on the “td” element is obsolete. Use CSS instead. 	
a
72 		ALIGN=TOP><FONT SIZE=-2 FACE=sans-serif> <A HR 	The “font” element is obsolete. Use CSS instead. 	
a
78 		R> <TR> <TD COLSPAN=3 ALIGN=LEFT VALIGN=TOP><FONT 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
78 		R> <TR> <TD COLSPAN=3 ALIGN=LEFT VALIGN=TOP><FONT 	The “valign” attribute on the “td” element is obsolete. Use CSS instead. 	
a
79 		ALIGN=TOP><FONT SIZE=-2 FACE=sans-serif> 	The “font” element is obsolete. Use CSS instead. 	
a
112 		LE> --> <HR SIZE=1 NOSHADE> <FON 	The “size” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
112 		LE> --> <HR SIZE=1 NOSHADE> <FON 	The “noshade” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
114 		NOSHADE> <FONT SIZE=-1><FONT 	The “font” element is obsolete. Use CSS instead. 	
a
114 		T SIZE=-1><FONT COLOR="#006633">The al 	The “font” element is obsolete. Use CSS instead. 	
a
116 		A> </FONT><FONT COLOR="#006633">).</FO 	The “font” element is obsolete. Use CSS instead. 	
a
118 		.</FONT> <HR NOSHADE SIZE=1> <FON 	The “noshade” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
118 		.</FONT> <HR NOSHADE SIZE=1> <FON 	The “size” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
120 		SIZE=1> <FONT SIZE=-1><FONT 	The “font” element is obsolete. Use CSS instead. 	
a
120 		T SIZE=-1><FONT COLOR="#006633"> This 	The “font” element is obsolete. Use CSS instead. 	
a
124 		e Page</A><FONT COLOR="#006633"> for a 	The “font” element is obsolete. Use CSS instead. 	
a
130 		></FONT> <HR NOSHADE SIZE=1> <TAB 	The “noshade” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
130 		></FONT> <HR NOSHADE SIZE=1> <TAB 	The “size” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
132 		SIZE=1> <TABLE BORDER=0 WIDTH="100%"><TR><T 	The “width” attribute on the “table” element is obsolete. Use CSS instead. 	
a
132 		SIZE=1> <TABLE BORDER=0 WIDTH="100%"><TR><T 	The “border” attribute on the “table” element is obsolete. Use CSS instead. 	
a
132 		100%"><TR><TD VALIGN=TOP WIDTH="50%"> <B><F 	The “valign” attribute on the “td” element is obsolete. Use CSS instead. 	
a
132 		100%"><TR><TD VALIGN=TOP WIDTH="50%"> <B><F 	The “width” attribute on the “td” element is obsolete. Use CSS instead. 	
a
133 		"50%"> <B><FONT COLOR="#006633">Conten 	The “font” element is obsolete. Use CSS instead. 	
a
151 		oms</A> <FONT SIZE=-1>(<A HR 	The “font” element is obsolete. Use CSS instead. 	
a
164 		sses</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
164 		ed</FONT> <FONT SIZE=-1><I>13- 	The “font” element is obsolete. Use CSS instead. 	
a
177 		nbsp; <FONT SIZE=-1>(<A HR 	The “font” element is obsolete. Use CSS instead. 	
a
179 		more</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
179 		ed</FONT> <FONT SIZE=-1><I>22- 	The “font” element is obsolete. Use CSS instead. 	
a
203 		ables</A> <FONT SIZE=-1>(<A HR 	The “font” element is obsolete. Use CSS instead. 	
a
206 		)</FONT> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Revise 	The “font” element is obsolete. Use CSS instead. 	
a
206 		ed</FONT> <FONT SIZE=-1><I>21- 	The “font” element is obsolete. Use CSS instead. 	
a
236 		2018</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
236 		ed</FONT> <FONT SIZE=-1><I>26- 	The “font” element is obsolete. Use CSS instead. 	
a
265 		ENU> </TD> <TD VALIGN=TOP> <B><F 	The “valign” attribute on the “td” element is obsolete. Use CSS instead. 	
a
268 		N=TOP> <B><FONT COLOR="#006633">Relate 	The “font” element is obsolete. Use CSS instead. 	
a
283 		Style</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
284 		ed</FONT> <FONT SIZE=-1><I>15- 	The “font” element is obsolete. Use CSS instead. 	
a
294 		tion</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
295 		ed</FONT> <FONT SIZE=-1><I>7-F 	The “font” element is obsolete. Use CSS instead. 	
a
297 		></FONT> <FONT SIZE=-1>(<A HR 	The “font” element is obsolete. Use CSS instead. 	
a
299 		ules</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
300 		ed</FONT> <FONT SIZE=-1><I>9-F 	The “font” element is obsolete. Use CSS instead. 	
a
317 		tures</A> <FONT SIZE=-2 FACE="Comic Sans MS" COLOR=ORANGE>Added< 	The “font” element is obsolete. Use CSS instead. 	
a
318 		ed</FONT> <FONT SIZE=-1><I>24- 	The “font” element is obsolete. Use CSS instead. 	
a
340 		MENU> <B><FONT COLOR="#006633">Extern 	The “font” element is obsolete. Use CSS instead. 	
a
356 		</MENU> <FONT SIZE=-1><B><FO 	The “font” element is obsolete. Use CSS instead. 	
a
356 		IZE=-1><B><FONT COLOR="#006633">To sea 	The “font” element is obsolete. Use CSS instead. 	
a
361 		org". <B><FONT COLOR="#006633">More e 	The “font” element is obsolete. Use CSS instead. 	
a
371 		ABLE> <P><HR NOSHADE SIZE=1><A NAM 	The “noshade” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
371 		ABLE> <P><HR NOSHADE SIZE=1><A NAM 	The “size” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
371 		w"></A><B><FONT COLOR="#006633">Metama 	The “font” element is obsolete. Use CSS instead. 	
a
396 		> --> <P><CENTER><FONT 	The “center” element is obsolete. Use CSS instead. 	
a
396 		P><CENTER><FONT COLOR="#006633"><I>Fro 	The “font” element is obsolete. Use CSS instead. 	
a
408 		> --> <P><CENTER><TABLE 	The “center” element is obsolete. Use CSS instead. 	
a
408 		P><CENTER><TABLE WIDTH="90%"><TR><T 	The “width” attribute on the “table” element is obsolete. Use CSS instead. 	
a
408 		"90%"><TR><TD ALIGN=CENTER> <TABL 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
408 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “cellspacing” attribute on the “table” element is obsolete. Use CSS instead. 	
a
408 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “cellpadding” attribute on the “table” element is obsolete. Use CSS instead. 	
a
408 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “bgcolor” attribute on the “table” element is obsolete. Use CSS instead. 	
a
408 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “border” attribute on the “table” element is obsolete. Use CSS instead. 	
a
409 		FFFA"><TR><TD ALIGN=CENTER> David 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
493 		how. <P><HR NOSHADE SIZE=1><A NAM 	The “noshade” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
493 		how. <P><HR NOSHADE SIZE=1><A NAM 	The “size” attribute on the “hr” element is obsolete. Use CSS instead. 	
a
493 		s"></A><B><FONT COLOR="#006633">How Me 	The “font” element is obsolete. Use CSS instead. 	
a
497 		sp; <P> <CENTER><FONT 	The “center” element is obsolete. Use CSS instead. 	
a
497 		> <CENTER><FONT COLOR="#006633"><I>A m 	The “font” element is obsolete. Use CSS instead. 	
a
539 		> --> <P><CENTER><TABLE 	The “center” element is obsolete. Use CSS instead. 	
a
539 		P><CENTER><TABLE WIDTH="90%"><TR><T 	The “width” attribute on the “table” element is obsolete. Use CSS instead. 	
a
539 		"90%"><TR><TD ALIGN=CENTER> <TABL 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
539 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “cellspacing” attribute on the “table” element is obsolete. Use CSS instead. 	
a
539 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “cellpadding” attribute on the “table” element is obsolete. Use CSS instead. 	
a
539 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “bgcolor” attribute on the “table” element is obsolete. Use CSS instead. 	
a
539 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “border” attribute on the “table” element is obsolete. Use CSS instead. 	
a
540 		FFFA"><TR><TD ALIGN=CENTER><IMG S 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
544 		sp;&nbsp; <FONT COLOR="#F7941D"> <B>Re 	The “font” element is obsolete. Use CSS instead. 	
a
559 		> <P> <B><FONT COLOR="#006633">What y 	The “font” element is obsolete. Use CSS instead. 	
a
586 		. --> <P><FONT SIZE="-1">[Note 	The “font” element is obsolete. Use CSS instead. 	
a
595 		> <P> <B><FONT COLOR="#006633">How it 	The “font” element is obsolete. Use CSS instead. 	
a
603 		rems. <P><CENTER><TABLE 	The “center” element is obsolete. Use CSS instead. 	
a
603 		P><CENTER><TABLE WIDTH="90%"><TR><T 	The “width” attribute on the “table” element is obsolete. Use CSS instead. 	
a
603 		"90%"><TR><TD ALIGN=CENTER> <TABL 	The “align” attribute on the “td” element is obsolete. Use CSS instead. 	
a
603 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “cellspacing” attribute on the “table” element is obsolete. Use CSS instead. 	
a
603 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “cellpadding” attribute on the “table” element is obsolete. Use CSS instead. 	
a
603 		N=CENTER> <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=5 BGCOLOR="#EEFFFA"><TR><T 	The “bgcolor” attribute on the “table” element is obsolete. Use CSS instead. 	
a
603 	
~~~~

**Comment by nmegill** [comment]
> * there are two validation errors in mmset.html

Yes, I'll be fixing those.  There's also mpeuni's mmascii.html (auto generated) that has an apparently valid entity code that the validator won't accept (validator bug?), so I'll change the htmldef in set.mm to use the cryptic hexadecimal name.  (mmascii.html in ileuni is fine.)

> * it would be nice to run validation as part of travis, to prevent these problems creeping back in, and

I suppose, although I'm not sure how it would be done - would we scrape the web page response from the validator?  That would be a little ugly.  Maybe there's a better way.  If someone wants to look into that, that's fine.

In general, though, I don't think many people take passing the validator too seriously.  I'm almost shocked if a web page on any other site passes validation since probably 99.9% don't.  The main purpose for me is that it is an easy way to quickly check my editing for things like broken tables, and to do that it's nice to have the insignificant errors and warnings cleaned up so as not to have to ignore the "noise".  AFAIK the errors in mmil.html that you fixed didn't have any effect on the display, so it was essentially just a cosmetic syntax cleanup to make future use of the validator a little easier.

Now and then the validator changes what it requires without notice.  A change several years ago required that each image HREF have an ALT field even if there was also a TITLE present (for tool tip), apparently for accessibility reasons, so I had to change every image htmldef in set.mm to include both TITLE and ALT with duplicate information.

> * there seems to be a newer validator at https://validator.w3.org/unicorn/ . We'd need to update our HTML but that isn't necessarily a bad thing.

Unicorn requires HTML5, and as David suggested, that is a pretty major change, with little or no benefit for what we use our web pages for.  I don't have any immediate plans to do that, as discussed here:
https://groups.google.com/d/msg/metamath/fghKk1HsCe4/uu8Jt0GfAgAJ
In the very unlikely event a major browser announces plans to drop HTML4, then of course we'd have to reconsider.

**Comment by digama0** [comment]
> In general, though, I don't think many people take passing the validator too seriously. I'm almost shocked if a web page on any other site passes validation since probably 99.9% don't.

Indeed. I haven't seen a validator link anywhere else since the early 2000s. The web has moved on to other technologies for validation because we don't write raw HTML anymore. You don't analyze compiled code for style, it doesn't make sense (unless you are testing the compiler).

That said, most of the things that Unicorn is noticing are good points, i.e. UTF-8 and using CSS. I certainly am not opposed to modernizing the metamath web pages (and maybe adding a bit of interactivity while we're at it?).

**Comment by david-a-wheeler** [comment]
It would probably make sense to modernize the HTML. There's a huge amount of duplicate statements that could be captured in CSS, for example. It would be work! Probably the big question is, is it okay to move formatting to CSS? I think it'd be good, and we could do it incrementally, but we'd have to agree to do it.

Interactivity is great, but I would prefer JavaScript to be optional if reasonable.

**Comment by jkingdon** [comment]
> I suppose, although I'm not sure how it would be done - would we scrape the web page response from the validator?

At least for the HTML5 validator used in unicorn we'd presumably download the validator from https://validator.github.io/validator/ and run it in travis the way we run mmj2 or any of the others. I don't know whether the HTML4 validator is similarly packaged or not.

> [a validator] is an easy way to quickly check my editing for things like broken tables

Yeah, there's a sales pitch at https://validator.w3.org/nu/about.html#why-validate and I guess in the abstract validators seem like a good idea to me. Whether the value outweighs the effort, I don't know if I have an especially strong opinion.

I suppose I have a somewhat similar lack of strong opinion about HTML4 versus HTML5. Working on the metamath HTML does feel like I'm entering a time machine and I'm maybe vaguely worried about whether it is a learning curve and a set of pitfalls (e.g. not using UTF-8 can be kind of counterintuitive when you paste in characters and they don't work). But on the flip side I didn't join the metamath project for the HTML (I get enough of that in my day job) and so I'm not sure my urge to upgrade is strong enough to outweigh the sense that maybe the status quo isn't causing enough problems to worry about it.

**Comment by nmegill** [comment]
> (e.g. not using UTF-8 can be kind of counterintuitive when you paste in characters and they don't work).

In a \*.raw.html file, UTF-8 could be corrupted by 'markup' because the metamath.exe string functions assume 8 bits/character.  It would be a rather large project to rewrite all the string functions (most of which are custom written, not part of the C library).  Sometimes characters are retrieved directly from a string array via an array index for speed, and sometimes string functions are used to manipulate arbitrary byte arrays, complicating matters.

In any case, I would prefer not to use UTF-8 at the source code level, because you can't necessarily tell what a character is by looking at it on the screen.  Every editor seems to have a different way to enter a non-ASCII character from the keyboard.  Copy/paste or selection from a menu can be used but interrupts the flow of typing.  Terminal windows are ASCII-oriented and may display garbage or question marks depending on the shell, the program, and the OS.

As for converting everything to HTML5 (even without using UTF-8 extended characters), it seems pointless until there is an actual need for some feature that HTML4 doesn't have.  As the saying goes, "if it ain't broke, don't fix it."  Of course new projects can use HTML5 if people want, but I don't see the benefit of rewriting the metamath.exe HTML generation code.  Most of what is generated is never touched by the user anyway, with a few exceptions like \*.raw.html.

**Comment by digama0** [comment]
I see zero issues with moving to UTF-8, because everything metamath is US-ASCII as far as I can tell. No one is (as yet) advocating using any unicode characters directly in source.

**Comment by nmegill** [comment]
Right.  I was referring to use of the extended Unicode characters.

**Pull request merged**
