### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by benjub**
Very small PR:
* Several automatic minimizations (in a separate commit; I only used some `MINIMIZE_WITH` commands).
* Fix a reference, permitted by https://github.com/metamath/metamath-exe/pull/98 as explained in https://github.com/metamath/metamath-exe/pull/98#discussion_r968154539.

### CODE REVIEW

**Comment by benjub** [comment]
It looks like the CI does not run the latest Metamath version (looking at https://github.com/metamath/set.mm/actions/runs/7378794531/job/20074350326).

It looks like it correctly downloads the latest version (https://github.com/metamath/set.mm/actions/runs/7378794531/job/20074350326#step:4:34) but does not run it (it runs a 0.198 whereas when I compile locally the file downloaded at that address, I correctly have a 0.199.pre version).

So probably it uses a cached version. This may be due to the error in the script (see https://github.com/metamath/set.mm/actions/runs/7378794531/job/20074350326#step:5:5 : error since the needed line above has been commented out).

**Comment by avekens** [comment]
> It looks like the CI does not run the latest Metamath version (looking at https://github.com/metamath/set.mm/actions/runs/7378794531/job/20074350326).
> 
> It looks like it correctly downloads the latest version (https://github.com/metamath/set.mm/actions/runs/7378794531/job/20074350326#step:4:34) but does not run it (it runs a 0.198 whereas when I compile locally the file downloaded at that address, I correctly have a 0.199.pre version).
> 
> So probably it uses a cached version. This may be due to the error in the script (see https://github.com/metamath/set.mm/actions/runs/7378794531/job/20074350326#step:5:5 : error since the needed line above has been commented out).

Which is the official latest version of metamath.exe? The latest designated in https://us.metamath.org/mpeuni/mmrecent.html is 0.198, but on https://us.metamath.org/index.html, 0.199pre is available for a download (unfortunately, no version is mentioned in the text). The suffix "pre", however, seems to indicate that this is not an official/stable version...

**Comment by benjub** [comment]
It looks like the workflow file used (https://github.com/metamath/set.mm/actions/runs/7378794531/workflow?pr=3734)is still the old one, and not the one from #3738). I don't know how to update that.

**Comment by tirix** [comment]
The workflow used is probably the one from this branch, which does not have the changes from the `develop` branch yet.
So maybe you should first rebase your branch [`benjub:misc`](https://github.com/benjub/set.mm/tree/misc) with `develop`'s latest changes.

**Review by avekens — APPROVED** [review]

**Review by tirix — APPROVED** [review]

**Pull request merged**
