### PR TITLE
Finite and Infinite complex products moved from SF's mathbox to main

### PR DESCRIPTION
**Pull request by glacode**
Finite and Infinite complex products moved from SF's mathbox to main
As discussed here
https://groups.google.com/forum/#!searchin/metamath/product$20fenton%7Csort:date/metamath/JsNryVZhFRU/yrFHc5PuCwAJ

### CODE REVIEW

**Comment by arpie-steele** [comment]
@glacode You seem to have turned on the "executable" bits on set.mm when committing this change. Permission bits 0644 (base 8) refers to a file which is readable by all and read-writeable by owner. While 0755 refers to a file which is in addition executable as a script or binary (machine dependent) by all, which is likely a mistake for set.mm.

#1565 set.mm 37544032 bytes were read into the source buffer.
#1565 set.mm The source has 176635 statements; 2505 are $a and 35157 are $p.

#1566 set.mm 37552195 bytes were read into the source buffer.
#1566 set.mm The source has 176664 statements; 2505 are $a and 35157 are $p.

So set.mm has grown by 8163 bytes and 29 non-$a and non-$p statements.
But Scott Fenton's entire mathbox is 14685 lines which doesn't really explain the diff which shows 281,581 lines were deleted or moved.

**Comment by glacode** [comment]
> So set.mm has grown by 8163 bytes and 29 non-$a and non-$p statements.

There are 103 "move" comments added at the beginning of the file that could amount to 8163 bytes

> But Scott Fenton's entire mathbox is 14685 lines which doesn't really explain the diff which shows 281,581 lines were deleted or moved.

Unfortunately, the diff algorithm "understands" the single block move as a sequence of "block substitutions". You will see that every (shown as) removed block is (shown as) added below, but it then triggers another fictitious "remove/add": this process continues well beyond the area where the 103 theorems have been moved (the whole section is moved at the end of "5.9  Elementary limits and convergence", and just before "Elementary trigonometry" ).

Any suggestion about how to avoid such behaviour from the diff algorithm, is appreciated.

**Comment by arpie-steele** [comment]
> Any suggestion about how to avoid such behaviour from the diff algorithm, is appreciated.

That's it exactly. Literally specifying the algorithm **does** reduce the diff by a factor of 100, eliminating the weirdness.

```
$ git diff --stat develop glacode/cproducts
 set.mm | 563286 ++++++++++++++++++++++++++++++------------------------------
 1 file changed, 281705 insertions(+), 281581 deletions(-)
$ git diff --patience --stat develop glacode/cproducts 
 set.mm | 4882 ++++++++++++++++++++++++++++++++------------------------------
 1 file changed, 2503 insertions(+), 2379 deletions(-)
$ git diff --minimal --stat develop glacode/cproducts
 set.mm | 4882 ++++++++++++++++++++++++++++++++------------------------------
 1 file changed, 2503 insertions(+), 2379 deletions(-)
```
In addition to the huge block for products and the move notices, pnpncand, fzp1nel, and fprodefsum were moved to appropriate places outside Scott Fenton's Mathbox.

**Comment by glacode** [comment]
Thank you very much, arpie-steele, for letting me know about the --patience --minimal --stat options, I'm going to read the manual... (I spend a lot of time in mmj2, but I rarely use git/github and often with large commits; this PR is in fact a prerequisite for a pretty large update to my Mathbox; in the future I plan to move to a "commit early, commit often strategy", I promise :-) )

> In addition to the huge block for products and the move notices, pnpncand, fzp1nel, and fprodefsum were moved to appropriate places outside Scott Fenton's Mathbox.

pnpncand and fzp1nel were used by theorems in the product sections, so I put them in an appropriate position in the main part.
fprodefsum is a result about the product of exponentials, but the exponential is defined in the following section, so I placed it just after efadd, that's the exact "same" result for the (binary) multiplication

Thanks again for all your help (I hope to be able to move the complex product sections to the main part, so I can publish some new results, that could be of general interest).

**Comment by glacode** [comment]
> That's it exactly. Literally specifying the algorithm **does** reduce the diff by a factor of 100, eliminating the weirdness.

> $ git diff --patience --stat develop glacode/cproducts 
>  set.mm | 4882 ++++++++++++++++++++++++++++++++------------------------------

I've just tried
git diff --patience origin/develop..HEAD
and it returns exactly what I was expecting.

Thank you so much! This "weird" diff result has been driving me crazy for the last couple of days

Glauco

**Comment by arpie-steele** [comment]
I would still recommend repairing the file permissions.
On a MacOS/UNIX/Linux system this is similar to editing the file so the commands would be (in a workspace where the the `cproducts` branch has been checked out):
`chmod 0644 set.mm ; git add set.mm ; git status`
Alternatively `chmod a-x set.mm` would also work.

While on a Windows machine, file permissions work differently and there is no chmod command by default, so I think the steps are:
```
git update-index --chmod=-x set.mm
git status
```
It will look like set.mm is both ready for commit and not ready.
Source: http://blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html
There are reports that the  "git desktop" GUI doesn't understand update-index --chmod and fails to commit.
You also might want to consider if you need to configure your git workspace to ignore the filesystem permissions in the future, especially if your workspace is on a shared drive or used with cygwin: https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode

In both cases you would follow up with a commit and push as normal.

**Comment by glacode** [comment]
@arpie-steele I've done a new commit that clears the executable bits
As I understand it, there's no need for a new pull request, it's automatically "added" to the current pull request, isn't it?

Thanks for all your help

Glauco

**Comment by arpie-steele** [comment]
Yes. A same-branch push will update the state of pending pull requests for that branch because your pull request lives on your GitHub repository and the pull request (PR) is a pointer to the branch on that repository.

If you visit your pull request at https://github.com/metamath/set.mm/pull/1566 you will see that not only is the new change tracked, but a green checkmark to the right of the newest change means automation has already run tests against it to ensure that your cumulative changes don't break the various tests for consistency and correctness which have been setup. Ideally, it does this for each push (not necessarily each commit) but the integration of GitHub and the Travis CI build system is complicated and we had a short breakdown of communication between them in March.

In my experience, everyone on this project is trying to help everyone, so as a relative latecomer I thought it was my turn to lend some aid. I'm happy that I did so without offending seriously.

**Pull request merged**
