### PR TITLE
Discouraged theorems replaced

### PR DESCRIPTION
**Pull request by glacode**
The use of discouraged theorems has been fixed.
A couple of theorems have been renamed (for naming consistency).
Two lemmas for wallispi2 have been moved to the proper position and wallispi lemmas have been renamed accordingly.
Some weird spacing for statements has been fixed.
(thanks to Mario for his stylistic comments)

### CODE REVIEW

**Comment by glacode** [comment]
As I read the Travis trace, all Discouraged have the "-" sign in front, but the exit code is still 1 (may be it doesn't discriminate between removed and added references?)

**Comment by digama0** [comment]
It doesn't. This is fine for merging, and I think Norm will soon be
following up with cleanup of other mathboxes and updating the discouraged
file, which will fix the Travis errors.

**Comment by digama0** [comment]
By the way, if you are still looking for something to do, I will point out that `stirlingr` is not quite as strong as it should be. The real reason `~~>r` is a separate notation is because it deals with convergence of "sequences" that are indexed by real numbers, not just integers. For integer-indexed sequences, `~~>` and `~~>r` are equivalent, as `rlimclim` attests.

The continuous version is not exactly trivial. Although `n !` is discrete, it is being approximated by
 ` ((√(2𝜋𝑛)  ((𝑛/e) ↑ 𝑛)))` which has a continuous extension if you replace `^` with `^c`. In fact, if you are careful, you will probably find that the bounds used in the original proof will still apply when everything is a real number. This is what I did for PNT, which utilizes real numbers throughout even though it concerns an integer sequence.

**Comment by nmegill** [comment]
All complex number ax vs. ax- were cleaned up in develop commit 59ad750, and 'discouraged' was updated.  Everything passes Travis now.

Note that wrapping of proofs may have changed since ax- takes one more character.  (I ran 'save proof */c/f' to rewrap them.)

Norm

**Comment by glacode** [comment]
Mario, once I completed the proof for the Stirling's formula, I thought 
it would have been elegant to state the same result, but using 
convergence of sequences in the reals (w.r.t. the standard topology).

~~>r came up in my searches for ~~> and looking at the label (rlim vs 
clim) and reading the description I interpreted it as convergence for 
sequence of reals. What's even worse, I was able to prove in half an 
hour exactly the theorem I needed, so I didn't look back.

After reading your email, I took a look at the actual definition and 
clearly it is not what I had thought. And I guess it's unusual to 
misinterpret a constant in metamath and nonetheless be "lucky" enough to 
proof the exact statement you needed...

With a quick search on the site, I can't find a metamath constant for 
the limit of a sequence of reals in the reals. I understand that clim 
does the job from a practical standpoint, but a dedicated constant, say 
"~~>re", and a simple equivalence theorem "for a sequence of reals F, F 
~~>re A iff F ~~> A ", may be worthwhile (just to allow you to emphasize 
the topology you are referring to).

Do you know if we have a definition for convergence of sequences in the 
real (w.r.t. the standard topology) ? Otherwise I will simply remove the 
stirlingr theorem (and of course I'll keep stirling, that's exactly as 
intended)

Thanks for this precious feedback.


Glauco

**Comment by digama0** [comment]
I'm actually trying to cut back on the number of these special-use constants, so given that `~~>` also captures convergence of sequences of reals exactly, I wouldn't want to also have `~~>re`. That said, there is a _more_ general limit relation that allows you to specify the range of the sequence and its topology. In terms of that, limits of real sequences is `` ( ~~>t ` ( topGen ` ran (,) ) )``. (I see the equivalence of these has not been proven, but all the building blocks are already on the table.) Still more general is `fLimf`, which also allows the provision of a filter on the domain to specify the sense of convergence, so that both real and integer-indexed sequences can be expressed.

In the future, I would like to invest more in these generalized relations and move away from special cases, because a lot of work must be duplicated between the different limiting relations. `clim` sticks around because of bootstrapping reasons and because it's also extremely common, similar to `-cn->`, which is just a special case of `Cn` but is less verbose if you aren't doing general topology.

**Comment by digama0** [comment]
I should point out that we heavily capitalize on ZFC's ability to handle subtypes well so that we don't need additional operations for each type. That is, even though we are (probably) primarily concerned with adding real numbers, or maybe even just integers, `+` is defined on complex numbers, and we use this constant instead of a dedicated one to state `2 + 2 = 4`. This is the same sort of thing which happens for real limits of real sequences - `F ~~> A` is understood to be real convergence simply because `F` is composed of real numbers and `A` is real.

**Comment by digama0** [comment]
Also, it's probably a good idea not to take me up on the offer to extend `stirling` to real numbers - it's not true! `n!` grows considerably in each unit, so if you use ``! ` ( |_ ` n )`` to extend the factorial, it will fall well behind `sqr(2 pi n) (n/e)^n`. When I plot this function, it looks like it oscillates between `0` and `1` indefinitely, so the limit does not hold.

The *real* continuous extension of this theorem requires a proper continuous extension of the factorial as well, namely the Gamma function. Little has been done with `Gamma` since its definition, and I haven't even shown that Gamma extends the factorial, so that would be no small project.

**Comment by glacode** [comment]
Hi Mario,

I didn't come across ~~>t before, and at first sight it looks to be 
exactly what I needed (and may be I will need it for future proofs, also).

Thanks for the feedback.

Glauco

**Pull request merged**
