### PR TITLE
Theorems moved to the main part of set.mm : supadd , inisegn0 , ad4an…

### PR DESCRIPTION
**Pull request by glacode**
Theorems moved to the main part of set.mm : supadd , inisegn0 , ad4ant* and ad5ant*

### CODE REVIEW

**Comment by glacode** [comment]
I can't find Travis progress... it's been a while since my last PR, did something change?

**Comment by david-a-wheeler** [comment]
I think Travis or the Travis/ GitHub connection had a problem. Please make a trivial tweak, say in a comment, and push an update to this branch. If that doesn't fix it, we will have to investigate.

**Comment by avekens** [comment]
The same problem with my PR - Travis is not started...

**Comment by david-a-wheeler** [comment]
@avekens - you're right. Weird. I'll check it out.

**Comment by david-a-wheeler** [comment]
Huh. Sometimes Travis starts, sometimes it doesn't.

There's a more recent Travis build in progress for pull request #1770:
https://travis-ci.org/github/metamath/set.mm/builds/718384146

I don't understand why it works sometimes but not others.

**Comment by david-a-wheeler** [comment]
On further investigation - it looks like Travis gets run, but doesn't report *back* its results.

Below are details, in the hopes that it might help...

===

I went here to look at the list of CI tests for set.mm started by pull requests:
https://travis-ci.org/github/metamath/set.mm/pull_requests

I found two Travis runs specifically for this pull request #1769; both succeeded. In reverse chronological order:

* PR #1769 - Theorems moved to the main part of set.mm : supadd , inisegn0 , ad4an… - avatar glacode - #5829 passed - eb49830 - 8 min 27 sec - about an hour ago https://travis-ci.org/github/metamath/set.mm/builds/718372420
* PR #1769 - Theorems moved to the main part of set.mm : supadd , inisegn0 , ad4an… - avatar glacode - #5828 passed
db5eb48 - 8 min 6 sec - 3 hours ago - https://travis-ci.org/github/metamath/set.mm/builds/718349052

Note that *both* builds completely passed the tests. They have this pull request. One oddity: The commit ids appear to be different. I don't understand that, though that may be a weird artifact (maybe something is reporting a tree id instead of a commit?).

**Comment by david-a-wheeler** [comment]
@glacode - it looks like a communication problem between GitHub & Travis. But #1770 's last change *did* have Travis display things.

Would you mind doing another tweak? If that works, it was some intermittent problem on the GitHub or Travis end, which has hopefully now be resolved.

**Comment by david-a-wheeler** [comment]
@glacode - thank you! That triggered a Travis run *and* this fact is visible in GitHub. I'm hopeful that the problem has now been resolved.

**Comment by glacode** [comment]
Thank you, David

**Comment by nmegill** [comment]
@glacode A conflict arose after I merged PR #1768 most likely due to the label list at the top of set.mm.

**Comment by nmegill** [comment]
@glacode Actually I misread; PR #1768 didn't add to the label list at top, so I'm not sure what caused the merge conflict.  However, PR #1770 does add to the label list at top, so be aware of that too when you fix the conflict.  Thanks.

**Comment by glacode** [comment]
It may be easier to redo from scratch... :-)

**Pull request closed without merging**
