### PR TITLE
rename mpt2->mpo from cnmpt2pc to mpt2cti

### PR DESCRIPTION
**Pull request by jkingdon**
This gets us partway into the mathboxes.

### CODE REVIEW

**Review by wlammen — COMMENTED** [review]
The changes are ok and consistent with previous ones.  Given the consent of the affected Mathbox owner this is an approval.

**Comment by jkingdon** [comment]
> The changes are ok and consistent with previous ones. Given the consent of the affected Mathbox owner this is an approval.

Not sure that's needed for this kind of maintenance edit but in this case we can just ask @tirix whether there's any issue.

**Review by avekens — APPROVED** [review]
I think @tirix does not object, but he should have a chance to give his explicit approval.

**Review by tirix — APPROVED** [review]
No objection, we should keep the same conventions throughout, and Git does a good job at managing merges.

**Comment by jkingdon** [comment]
> I think @tirix does not object, but he should have a chance to give his explicit approval.

Sounds good. I'll give people the chance, and if we don't hear from them (e.g. they aren't active)we'll worry about that then. For this reason, I'll break the remaining pull requests on mathbox boundaries.

**Pull request merged**
