### PR TITLE
Wallis' product for Pi and Stirling's approximation formula for n factorial

### PR DESCRIPTION
**Pull request by glacode**
The main results in this commit are the Wallis' product for Pi and Stirling's approximation formula for n factorial. Stirling's formula is #90 in the 100 theorems list.
I've proven two versions of Wallis' product and two versions of Stirling's formula: stirling proves the formula w.r.t. the topology on complex numbers,
and stirlingr proves the formula w.r.t. the standard topology on the reals.

Some previous comments in my Mathbox have been improved, thanks to Gérard Lang for the precious feedback

### CODE REVIEW

**Comment by glacode** [comment]
I see a bunch of "New usage is discouraged" errors in Travis...

I wonder if I can setup mmj2 to avoid those in the first place (both in searches and in autocomplete feature)

**Comment by david-a-wheeler** [comment]
On June 30, 2017 12:32:03 PM EDT, glacode <notifications@github.com> wrote:
>The main results in this commit are the Wallis' product for Pi and
>Stirling's approximation formula for n factorial. Stirling's formula is
>#90 in the 100 theorems list.
>I've proven two versions of Wallis' product and two versions of
>Stirling's formula: stirling proves the formula w.r.t. the topology on
>complex numbers,
>and stirlingr proves the formula w.r.t. the standard topology on the
>reals.

That sounds fantastic! I'm waiting to hear from Norm or Mario, but if all seems okay, this will put Metamath ahead of Coq and one behind Mizar. And it's a cool result.


--- David A.Wheeler

**Comment by david-a-wheeler** [comment]
On June 30, 2017 12:32:03 PM EDT, glacode <notifications@github.com> wrote:
>The main results in this commit are the Wallis' product for Pi and
>Stirling's approximation formula for n factorial. Stirling's formula is
>#90 in the 100 theorems list.
>I've proven two versions of Wallis' product and two versions of
>Stirling's formula: stirling proves the formula w.r.t. the topology on
>complex numbers,
>and stirlingr proves the formula w.r.t. the standard topology on the
>reals.

I presume that "stirling" is the primary proof you want referenced as the proof for #90, correct?


--- David A.Wheeler

**Comment by glacode** [comment]
Hi David,

yes, I thought about it and I believe stirling should be the primary 
result for a couple of reasons:

- the notation for convergence ~~> instead of ~~>r should be more 
intuitive for the newcomer

- I've developed all theorems with respect to the complex topology and 
then got stirlingr as a simple corollary from striling

Thanks for all the work you do for the metamath project.


Glauco

**Comment by glacode** [comment]
Thank you Mario,

before moving to some other proof, I will read carefully your 
suggestions and improve the proofs I've submitted.

I will also start a thread on the Metamath Group asking for hints on a 
good workflow for changing existing proof signatures in set.mm (I mean, 
removing a redundant hypothesis and other changes that impact the 
"caller" theorems).

With regard to the weird spacing, I recall there is a mmj2 parameter for 
creating the .mmt file with a "nice" spacing: I used it a couple of 
months ago, but I rebuilt my virtual machine and moved to latest mmj2 
version (so cool!) and I'm afraid I didn't set that parameter anymore (I 
have a script that concats all .mmt files in the folder, producing a 
single .mmt file that I then copypaste in my mathbox in set.mm).

Thanks again for all the work you've done and still do for the project.
Glauco

**Comment by nmegill** [comment]
Shall we go ahead and merge this?  The Travis errors and Mario's suggestions can be handled with a future pull request; they aren't a big deal.  I'll let Mario merge it if he agrees so I can update the us2 site.
Norm

**Comment by digama0** [comment]
@nmegill I'm on board with merging this with no changes - all the suggestions are minor things, and the travis errors are due to some deprecated axiom usage, which should be fixed but are not a big deal. My computer isn't set up to do merging and cleanup work ATM though, so if you could handle this one that would be great.

**Comment by david-a-wheeler** [comment]
On July 1, 2017 10:25:54 AM EDT, glacode <notifications@github.com> wrote:
>Hi David,
>
>yes, I thought about it and I believe stirling should be the primary 
>result for a couple of reasons:
>
>- the notation for convergence ~~> instead of ~~>r should be more 
>intuitive for the newcomer
>
>- I've developed all theorems with respect to the complex topology and 
>then got stirlingr as a simple corollary from striling
>
>Thanks for all the work you do for the metamath project.
>
>
>Glauco
>
>
>On 01/07/2017 04:26, David A. Wheeler wrote:
>> On June 30, 2017 12:32:03 PM EDT, glacode <notifications@github.com>
>wrote:
>>> The main results in this commit are the Wallis' product for Pi and
>>> Stirling's approximation formula for n factorial. Stirling's formula
>is
>>> #90 in the 100 theorems list.
>>> I've proven two versions of Wallis' product and two versions of
>>> Stirling's formula: stirling proves the formula w.r.t. the topology
>on
>>> complex numbers,
>>> and stirlingr proves the formula w.r.t. the standard topology on the
>>> reals.
>> I presume that "stirling" is the primary proof you want referenced as
>the proof for #90, correct?
>>
>>
>> --- David A.Wheeler
>>
>>
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/metamath/set.mm/pull/113#issuecomment-312434959

Excellent! When I get back to my laptop I plan to add this to the Google docs sheet & create a proposed update to the metamath 100 page. Great stuff!!

--- David A.Wheeler

**Comment by nmegill** [comment]
I started a build on us2 which will finish at about 11pm EDT (about 10.5 hours from this post).  I'm now going off-line from several hours to several days as I try to reinstall Windows 7 on a bigger disk; wish me luck...

**Comment by david-a-wheeler** [comment]
The Google docs spreadsheet now has the new value, so the growth & authors list graph are up-to-date:
https://docs.google.com/spreadsheets/d/1jcLOp_jF4sPrVPdPedL_ZWebXp8oYEQOSmbWb168YHE

**Comment by david-a-wheeler** [comment]
I updated mm_100.html and emailed it to Norm and Mario.

**Comment by glacode** [comment]
Hi Mario,

the parameter that's needed in order to avoid weird spacing (for 
formulas in .mmt files) is

TheoremLoaderStoreMMIndentAmt,2

otherwise mmj2 creates the .mmt file keeping the spacing you had in the 
.mmp file (I'm always in "ctrl + r" mode with indentation "enabled").

As a side note: when the proof is finally generated, at the bottom of 
the .mmp file it is /compressed (it seems to be the default now, I 
believe I had to set a parameter in old versions) but the .mmt generated 
is not compressed (and the same behavior I had with the old version, 
even when I set up the parameter that generated the /compressed proof at 
the bottom of the .mmp file).
Not a big problem for me, because I build and run a metamath.exe script 
that compresses all my latest proofs (after I've copied them in set.mm 
from the .mmt files).

Glauco

**Pull request merged**
