### PR TITLE
added ~ xlimlimsupleliminf:

### PR DESCRIPTION
**Pull request by glacode**
A sequence of extended reals converges if and only if its superior limit is smaller than or equal to its inferior limit.

### CODE REVIEW

**Comment by glacode** [comment]
mathbox only

**Review by wlammen — APPROVED** [review]

**Review by tirix — COMMENTED** [review]
Wouldn't it be more practical to go one step more and prove the equality?

**Comment by glacode** [comment]
> Wouldn't it be more practical to go one step more and prove the equality?

it should be the theorem just above, isn't it?  (I use it in the trivial proof of this one)

This one is just to "skip" the obvious part of the equality (often times I've seen video lectures where the teacher proves convergence by proving that limsup <= liminf)

**Comment by avekens** [comment]
~xlimlimsupleliminf is just the combination of ~xlimliminflimsup (which is about equality) and ~liminfgelimsupuz.

**Review by avekens — APPROVED** [review]

**Review by tirix — APPROVED** [review]

**Pull request merged**
