### PR TITLE
Graph theory - closed walks as word (16) 

### PR DESCRIPTION
**Pull request by avekens**
**Summary:**
* Improvement of the proof of ~extwwlkfab ("_The set of closed walks having a fixed length N greater than one and starting at a fixed vertex X with the last but two vertex being identical with the first (and therefore last) vertex can be constructed from the set of closed walks on X with length smaller by 2 than the fixed length by appending a neighbor of the last vertex and afterwards the last vertex (which is the first vertex) itself ("walking forth and back" from the last vertex)._") by restructuring and removing many superflous lemmas.
* Provision of ~numclwlk1 ("_If n > 1, then the number of closed n-walks v(0) ... v(n-2) v(n-1) v(n) from v = v(0) = v(n) with v(n-2) = v is kf(n-2)_") as generalisation of ~numclwwlk1 (statement in Huneke's proof for the friendship theorem), matching Huneke's original statement (esp. covering the case n=2, which is not needed for the proof of the friendship theorem). This was possible by formulating the theorem using the general definition of (closed) walks instead of using the representation of (closed) walks as words, and by transforming already existing proofs for theorems using the representation of (closed) walks as words into corresponding theorems using the general definition, making use of (new) theorems showing the equinumerosity of corresponding sets for both representations.

**Details:**

General:
* new theorems ~subeluzsub, ~swrds2m, ~rabssrabd added

Graph theory - closed walks
* new theorems ~~s2elclwwlknon2, ~clwlkcompbp added
* theorems ~clwwlkccat, ~clwwlknccat, ~clwwlknonccat moved up
* theorem ~extwwlkfablem renamed ~clwwnrepclwwn and proof shortened (by extracting ~2clwwlklem)
* theorem ~2clwwlk2clwwlklem2 renamed ~2clwwlk2clwwlklem and proof shortened (by extracting ~clwwnonrepclwwnon)
* many superfluous lemmas removed
* proof of ~extwwlkfab shortened
* some comments improved
* theorems ~clwlkclwwlkf1o and ~clwlkclwwlken (bijection between the nonempty closed walks and the closed walks as word) and auxiliary theorems added
* ~clwwlkbij replaced by ~clwwlken
* revision of theorems ~clwlknf1oclwwlkn and ~clwlkssizeeq (bijection between the set of closed walks as words of length N and the set of closed walks of length N), auxiliary theorems removed or replaced
* theorems ~clwwlknonclwlknonf1o and ~clwwlknonclwlknonen (bijection between the two representations of closed walks of a fixed positive length on a fixed vertex) and auxiliary theorems added
* theorems ~dlwwlknondlwlknonf1o and ~dlwwlknondlwlknonen (bijection between the two representations of "double loops" of a fixed length on a fixed vertex ) and auxiliary theorems added
* new theorems ~wlkl0 and ~clwlknon2num added
* generalisation ~numclwlk1 of ~numclwwlk1, matching the statement in [Huneke]

### CODE REVIEW

**Review by jkingdon — APPROVED** [review]

**Comment by jkingdon** [comment]
I'll refrain from merging this myself for this another day or so in case someone wants to review in more detail than I did. But if such a review isn't forthcoming, I think we can go ahead and merge it. There's no reason that people can't offer suggestions after it is merged.

**Comment by wlammen** [comment]
I am sorry @avekens .  You approve my contributions, but I feel simply at a loss when looking at your theorems.  I cannot decide whether this is done appropriately due to my lack of knowledge.  I wished it would be different.

**Comment by jkingdon** [comment]
> I am sorry @avekens . You approve my contributions, but I feel simply at a loss when looking at your theorems. I cannot decide whether this is done appropriately due to my lack of knowledge. I wished it would be different.

Hey we appreciate all you do contribute @wlammen .

**Comment by avekens** [comment]
I do not expect that anybody reviews the graph theory stuff completely and thoroughly. Of course anybody can do it, if she/he has time or is interested. Especially in this case, where nothing is realy new: I just want to improve the theorems needed to prove the friendship theorem, which I formulated and proved without much care (and experience!) to achieve the mai  goal - the proof of the friendship theorem.

It would be fine, however, if somebody would have a look at the basic theorems, either the general ones or for graph theory, and just only skim the rest (if at all). If this results in no objection or need for clarification, the PR should be approved. I must admit that I also do not understand everything completely regarding intuistic logic, but I approve mostly Jim's PRs after I had a quick look at it at least. I think the main contributors can trust each other up to a certain level (as Norm did, I assume).

**Pull request merged**
