### PR TITLE
Adjustment of references to [Huneke]

### PR DESCRIPTION
**Pull request by avekens**
* new key word "claim" used
* statements numbered as they occur in the paper
* general unification of the references

### CODE REVIEW

**Comment by avekens** [comment]
The travis check faioled becuse "claim" is still not recognized as keyword, e.g. in ~frgrancvvdeq:
"... claim 1 in [Huneke] p. 1 ..."

Either the new version of metamath.exe is not working as intended/announced, or it has to be integrated into the Travis job.

**Comment by arpie-steele** [comment]
The Travis build does not download from git or even the development server. Instead it fetches source code from a zip file on the main "us" site, http://us.metamath.org. That file is still being advertised as (version 0.181 12-Feb-2020). Additionally, the download URL in the script `download-metamath` is http://us.metamath.org/downloads/metamath-program.zip (0.181) which is not the same zip which is linked to by the index.html page ( http://us.metamath.org/downloads/metamath.zip , 0.182 ). So there might be a delay as the logistics are worked out.

**Comment by nmegill** [comment]
Oops, I had forgotten that I took its regeneration out of the build script, otherwise the sha256 changes every site update.  I just regenerated it by hand and uploaded it to http://us.metamath.org/downloads/metamath-program.zip .  I couldn't find a restart button on the Travis pages, but if anyone knows how to restart it, you can try it again.

**Comment by david-a-wheeler** [comment]
I restarted it, it should finish soon.

**Comment by nmegill** [comment]
> I restarted it, it should finish soon.

Thanks, it passes now.  What is the procedure for doing that?

**Comment by david-a-wheeler** [comment]
@nmegill - I cannot reproduce the steps exactly, since now it is okay. The basic ideas you click on the step that isn't working out, which will bring you to Travis. You then need to log into Travis using your GitHub account. That will authenticate you as someone who's allowed to restart the process. Then select rebuild, it will be a button a little down from the top. That's it.

**Pull request merged**
