### PR TITLE
Clean up intuitionistic biconditional.

### PR DESCRIPTION
**Pull request by jkingdon**
- use the correct definition in comments
- replace bijust with biijust which matches the intuitionistic df-bi
- say that dfbi1 and dfbi3 are classical, not intuitinistic
- better describe how dfbi2 relates to the intuitionistic df-bi
- remove dfbi because (unlike in the classical case) it is identical to df-bi
- better comment for df-or (similar to df-an)

### CODE REVIEW

**Comment by digama0** [comment]
As a PR, I think this is fine and can be merged. But Travis has no idea what it's doing, and this is a very old branch. Probably we should rethink how to handle version control on `iset.mm`. @nmegill

**Comment by nmegill** [comment]
Hi Jim,

There were a couple of problems.  The :intuit branch is out of date; the 
iset.mm there that you edited is dated 9-Feb-2015 (21MB) compared to 
21-Jul-2015 (1MB) for the one on the "official" one on the metamath 
site.  The 21-Jul-2015 version has the set theory stripped out and some 
other cleanup.

As I did with mmil.html, I added the iset.mm to the develop branch, and 
you can take it from there for future changes.

I updated the 21-Jul-2015 version with all of your changes.  I also 
updated it to conform to our current markup standards, so that it passes 
"verify markup */f".  You can do that manually in the future.

Right now iset.mm isn't checked by Travis.  We can consider Travis 
later, but I don't think it's high priority at the moment.  In the 
meantime just make sure you run "verify proof *" and "verify markup */f" 
before submission.

Many of the theorems are not intuitionistic (414 of them out of 1850); 
you can see them with "show usage ax-3/recursive" in metamath.exe.  I 
put "(New usage is discouraged.)" in ax-3 so that it won't be used 
accidentally, but at some point we should decide what to do with its 
uses:  either delete them or put "(New usage discouraged.)" in them.

Thanks for your interest in maintaining this file.

Norm

**Comment by nmegill** [comment]
On 11/25/17 6:50 PM, N Megill (please reply to nm@alum.mit.edu) wrote:
> Many of the theorems are not intuitionistic (414 of them out of 1850); 
> you can see them with "show usage ax-3/recursive" in metamath.exe.  I 
> put "(New usage is discouraged.)" in ax-3 so that it won't be used 
> accidentally, but at some point we should decide what to do with its 
> uses:  either delete them or put "(New usage discouraged.)" in them.

I should have said "at least 414".  I don't know the intuitionistic 
status of the predicate calculus axioms.

Norm

**Comment by jkingdon** [comment]
Hey, thanks for getting the current version of iset.mm into version control and your other changes.

Thanks for the  `verify proof *` and `verify markup */f` tip: someday we'll want to get them into travis, but doesn't have to be right now.

As for the sections on classical logic, I've been wondering about that too. Moving it to a separate issue at https://github.com/metamath/set.mm/issues/160 so we can figure out what to do.

With respect to "intuitionistic status of the predicate calculus axioms", I'm not completely sure either whether we have correctly combined how intuitionistic predicate logic is supposed to work with the specific issues of metamath (lack of syntactic freeness and all). But I haven't found any problems with the intuitionistic predicate logic axioms in iset.mm yet either.

In any event, the biconditional changes are merged and look good in the iset.mm on the develop branch, so I'm closing this pull request.

**Pull request closed without merging**
