### PR TITLE
shorten 19.21h, stdpc5, hbimd, hbim, 19.23t, 19.23h, exlimih, nfan, hban, hb3an, nfim, nfim1

### PR DESCRIPTION
**Pull request by wlammen**

### CODE REVIEW

**Comment by wlammen** [comment]
IN addition rearranged part of ax-11 section to cluster related theorems for synergy effects and moved fundamental theorems up

**Comment by wlammen** [comment]
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 9207caa3-7546-4929-bdb8-bd6959bc7c1a@1.i-0225a52-production-2-worker-org-ec2.travisci.net
version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101
instance: 2908cdd travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 873.694983ms
travis_fold:end:worker_info
[0Koci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

disk full

**Comment by wlammen** [comment]
Now the checks seem to hang. No result after more than half an hour...

**Comment by nmegill** [comment]
It looks like they are having some issues:

https://www.traviscistatus.com/

Errors on sudo: required and sudo: false infrastructures

Update - We continue the investigation of the build issues. 
Jan 1, 20:40 UTC

Investigating - We are seeing high numbers of requeues for GCE-based sudo: required jobs as well as high numbers of errors for EC2-based sudo: false jobs. We are looking into it. 
Jan 1, 19:34 UTC

**Pull request merged**
