### PR TITLE
restructure AND: rel. to bicond & impl, basic adant*, simpl*

### PR DESCRIPTION
**Pull request by wlammen**
1. The relation between AND and implication is expressed by variations of df-an.  These theorems are not used in the development of AND-only.  In fact the only applications of df-an occur in ex and imp, otherwise AND-only is fully self-contained.  So there is some freedom where to put these theorems.  Since they are variants of df-an, I left them in its vicinity.  If one later wants to prop up these theorems (using the commutative law e.g.), moving to a different location is an option.
2. Shorten imp5a
3. Rearrange the import/export section.  Theorems that indicate from hypotheses and conclusion, that both importation/exportation is needed are moved more to the end.  Proofs before may use both imp/ex as long as the effects annihilate, though.
4. The relation between bi-conditional and AND: start with a rewrite of df-bi and give basic support.  It is intended that from here on theorems differing just in the operation type (->, <->) in many instances can be kept together, because there is a common infrastructure.
5. The first layer of simp* and adant* theorems.  Higher levels use sylan* support that needs to be developed in parallel.
6. Delete some outdated OLD theorems.

### CODE REVIEW

**Comment by benjub** [comment]
I think it's ok. I haven't checked carefully, though.
If proof shortenings and OLD deletions were in a separate commit, that would help (if one commit is only moving theorems around, then the indication on the github page "629 lines added, 629 lines deleted", like in the previous PR, is already reassuring).

**edit**: so, to be clear, either someone (@jkingdon ? @avekens ?) has time to review, or else @wlammen is sure that everything is ok and he can merge.  Sorry but I don't have much time this week (hiking takes time!).

**Comment by wlammen** [comment]
OK, next time there will be smaller commits.
ad 1. This is about iman and imnan.  Both are not needed in the AND-only section (actually this section would be provable from imp and ex alone, if they replaced df-an).  The question is now: where shall we put these theorems?  For one they are on the application side (seen from AND), so they should appear late.  On the other hand, where does a less initiated user look for them? I decided to have them right at the beginning.  For me they are an answer to how AND is embedded in implication.
ad 2. compare imp5a and imp5aOLD for verification. The number of proof bytes decreased from 19 to 17.
ad 3. This is fine tuning.  How can I present the whole set of imp exp theorems, so that an infrequent visitor somehow knows where to look?  I decided to have plain importation and exportation, where a chain of implications is fully or partially transformed to/from ANDed antecedents.  In addition, these plain transformations have traditionally been accompanied by theorems where, an imported version is transformed to a different imported one.  These theorems are more on the application level, and have less principle value.  So let them appear after the pure ones.
ad 4.  dfbi2 is a version of df-bi, that uses AND for a less complex expression.  I tried to move it to an early position, so theorems employing <-> have easy access to them.  The bi-conditional is actually not a necessary concept to develop AND (apart from df-an, of course).  I see theorems using <-> as convenience extensions.  And it is convenient to have them adjacent to corresponding -> like theorems.
ad 5.  simp* and adantr* are wide-spread in short proofs.  The upcoming theorems are no exceptions.  So introduce them as early as possible.
ad 6. All deleted OLD theorems are located far from the AND section.  They appear later in the database.  For verification read the comments attached to the OLD theorems.
>  wlammen is sure that everything is ok 

Well, I am sure I can come up with a fairly decent solution.  But some decisions are a compromise.  A trade-off between easy random usage using 'nearby theorems' and a conceptional thorough idea, that pleases from a theoretical point of view.  And then I must remind you that I have no education in logic or math, so some of my ideas may not stand up to expert review.

**Review by avekens — APPROVED** [review]
Unfortunately, I did not fully get a feeling about the restructurings. I will have a look at them after this PR is merged and the theorems are shown on the web page.

As for the deletion of the OLD theorem: these are mostly about issue #2118, which I planned for September. It does not matter, however, that some of these OLD proofs are removed earlier.

**Comment by benjub** [comment]
Thanks Wolf. I'd say you can merge and follow your judgement for the points
you raised.

Le mar. 2 août 2022 à 20:24, Wolf Lammen ***@***.***> a
écrit :

**Comment by wlammen** [comment]
Thanks for your support.

**Pull request merged**
