### PR TITLE
Test metamath-knife

### PR DESCRIPTION
**Pull request by BTernaryTau**
The [verify action for my fork](https://github.com/BTernaryTau/set.mm/actions/runs/10149896452/job/28065810533) is failing with a compile error for metamath-knife:

```
error[E0282]: type annotations needed for `Box<_>`
Error:   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.21/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

I'm creating this PR to confirm if this is also an issue for the main repository.

### CODE REVIEW

**Comment by BTernaryTau** [comment]
Alright, looks like this repository is currently unaffected since the develop branch has the build cached, whereas the new branch for my fork does not.

```
Run actions/cache@v3
Cache Size: ~8 MB (8358386 B)
/usr/bin/tar -xf /home/runner/work/_temp/029a86a1-858b-4829-b3f2-215938b5f378/cache.tzst -P -C /home/runner/work/set.mm/set.mm --use-compress-program unzstd
Cache restored successfully
Cache restored from key: Linux-build-cache-knife
```

```
Run actions/cache@v3
Cache not found for input keys: Linux-build-cache-knife
```

**Comment by BTernaryTau** [comment]
Created https://github.com/metamath/metamath-knife/issues/165.

**Review by icecream17 — APPROVED** [review]
although this is a test, this would actually be approved

**Comment by jkingdon** [comment]
What I have been seeing is that the builds which are kicked off on commits - for example https://github.com/jkingdon/set.mm/actions/runs/10151331738/job/28070374850 - are failing with this rust compliation error.

If the reason tests are passing is "the develop branch has the build cached", then this probably won't last forever - eventually the cache will expire (or however those things work on github) and we'll see this failure elsewhere.

**Comment by tirix** [comment]
I've opened [metamath-knife#166](https://github.com/metamath/metamath-knife/pull/166), it might help.

**Comment by digama0** [comment]
I pushed a fix to metamath-knife master, it would be good to confirm that set.mm is also working.

**Comment by jkingdon** [comment]
> I pushed a fix to metamath-knife master, it would be good to confirm that set.mm is also working.

The fix is working for me. https://github.com/jkingdon/set.mm/actions/runs/10192854039 is passing, to contrast with for example https://github.com/jkingdon/set.mm/actions/runs/10157007758/job/28086373236 which had been failing due to the metamath-knife compilation error.

**Comment by BTernaryTau** [comment]
I'm going to close this since the fix works for me as well.

(I'll revisit the ax-rep changes at a later date.)

**Pull request closed without merging**
