### PR TITLE
Mathbox fake associativity

### PR DESCRIPTION
**Pull request by arpie-steele**
Renamed two, added two principle proofs, added two corollaries.

### CODE REVIEW

**Comment by arpie-steele** [comment]
"added two principle proofs" -- Hmm, this seems right on the dividing line between "principal" and "principle"

**Comment by avekens** [comment]
I think changes in mathboxes should not be documented in the history at the top of set.mm.

**Comment by nmegill** [comment]
@avekens is right, we don't normally document changes inside mathboxes, since often they are work in progress that is expected to change anyway.  They aren't intended to be used by others unless they are exported to the main set.mm (and we do document the exportation).  Could you remove them from the top of set.mm?  Thanks.

**Comment by arpie-steele** [comment]
@avekens @nmegill Thanks for the tip. Those lines have been removed.

**Pull request merged**
