### PR TITLE
Regen from raw

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This branch updates scripts/regen-from-raw, and then switches mmnf.html to use mmnf.raw.html instead.

**Comment by david-a-wheeler** [comment]
Build failed, not sure why.  WIll try to check later.

**Comment by david-a-wheeler** [comment]
@nmegill ... please merge!

**Comment by nmegill** [comment]
A minor issue is that the ~'s in the original mmnf.html weren't escaped with ~~ in mmnf.raw.html.  For example, http://math.boisestate.edu/~holmes/holmes/nf.html should be http://math.boisestate.edu/~~holmes/holmes/nf.html, otherwise the 'markup' command thinks 'holmes...' is a label in nf.mm and gives an error message since it doesn't exist.  I fixed these by hand in mmnf.raw.html in commit 06727e0.

**Pull request merged**
