### PR TITLE
Shorten proofs of tpid3 and tpid3g

### PR DESCRIPTION
**Pull request by jamesjer**
I removed the comment about the tpid3g proof being generated automatically, because this is no longer that proof.  I do not know if that is the right thing to do.  Let me know if not.

### CODE REVIEW

**Comment by nmegill** [comment]
Nice work.  Yes, your change to the comment is fine.

However, there is one other thing we do for shortened proofs so that the web site visitor can compare the old and new.  We rename the original with an OLD suffix and add "Obsolete version of ~ xxx as of dd-mmm-yyyy." to the old version's comment.  We delete the \*OLD version after a year, and the "Obsolete..." comment lets us find which ones are older than a year.  In addition, we add "(New usage is discouraged.) (Proof modification is discouraged.)" to the comment of the \*OLD to prevent it from being used accidentally by other proofs or its proof being shortened to a 1-step reference to ~ tpid3g in this case.  We place the \*OLD version after the new one.  So for your tpid3g, the new set.mm should look like:
```
  $( Closed theorem form of ~ tpid3 .  (Contributed by Alan Sare, 24-Oct-2011.)
     (Proof shortened by JJ, 30-Apr-2021.) $)
  tpid3g $p |- ( A e. B -> A e. { C , D , A } ) $=
    ( wcel ctp wceq w3o eqid 3mix3i eltpg mpbiri ) ABEACDAFEACGZADGZAAGZHOMNAIJ
    ACDABKL $.

  ${
    $d x A $.  $d x B $.  $d x C $.  $d x D $.  $d x ps $.
    $( Obsolete proof of ~ tpid3g as of 30-Apr-2021.  Closed theorem form of
       ~ tpid3 .  This proof was automatically generated from the virtual
       deduction proof ~ tpid3gVD using a translation program.  (Contributed by
       Alan Sare, 24-Oct-2011.)  (New usage is discouraged.)
       (Proof modification is discouraged.) $)
    tpid3gOLD $p |- ( A e. B -> A e. { C , D , A } ) $=
      ( vx wcel cv wceq wex ctp elisset w3o cab wi 3mix3 a1i abid syl6ibr dftp2
      eleq2i eleq1 mpbidi exlimdv mpd ) ABFZEGZAHZEIACDAJZFZEABKUEUGUIEUGUFUHFZ
      UIUEUEUGUFUFCHZUFDHZUGLZEMZFZUJUEUGUMUOUGUMNUEUGUKULOPUMEQRUHUNUFECDASTRU
      FAUHUAUBUCUD $.
  $}
```
After you do this, set.mm should be reformatted and the "discouraged" file regenerated per the procedures given at https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md

One other favor, if you could:  I just noticed that ~ cnvssOLD added by @KyleWyonch doesn't contain "Obsolete proof of ~ cnvss as of 27-Apr-2021." in its comment.  Could you add that for him while you're in there?  Thanks.

**Comment by benjub** [comment]
And maybe add tpid1g and tpid2g and prove tpid1, tpid2 from them ?

**Comment by nmegill** [comment]
> And maybe add tpid1g and tpid2g and prove tpid1, tpid2 from them ?

Well, let's not do that as part of this PR.  There isn't anything that needs them right now.

**Comment by nmegill** [comment]
@jamesjer Will you be able to make the changes I suggested?  If not, let us know so I or someone else can do it. Thanks.

**Comment by jamesjer** [comment]
Sorry for the delay.  I have made the requested changes.  Does everything look okay now?

**Comment by nmegill** [comment]
Yes, thanks.

**Pull request merged**
