### PR TITLE
Convention for characters to be used for labels

### PR DESCRIPTION
**Pull request by avekens**
Convention for characters to be used for labels added (see also issue #1671).

In addition to the convention about the usage of "." as discussed in #1671, I added that the usage of underscore " _ " is also not recommended. There are currently only four labels (for $p statements) using " _ ": ~r19.29_2a, ~tghilbert1_1, ~tghilbert1_2 and ~log_val - should those be changed?

Additional minor changes (in AV's mathbox):
* Header comment of section "Even and odd numbers" adjusted
* Some theorems about even/odd numbers rearranged

### CODE REVIEW

**Comment by digama0** [comment]
Ooh, banning underscore sounds nice, because MM0 uses underscore in place of hyphen and without a rule like this we can get more name collisions.

**Comment by nmegill** [comment]
I agree w/ this convention.  I also agree that the existing labels should be changed.  Their contributors are @tirix and @david-a-wheeler; could they acknowledge their approval?  The non-mathbox ones should have the label changes documented at the top of set.mm of course.
```
MM> sea *_*,mathbox contr/c
9096 r19.29_2a $p "...wo restricted quantifiers (Contributed by Thierry Arn..."
99893 tghilbert1_1 $p "...axiom I.1 for geometry. (Contributed by Thierry A..."
99894 tghilbert1_2 $p "...axiom I.2 for geometry. (Contributed by Thierry A..."
112232 mathbox $p "...n_.) A "mathbox" is a user-contributed section that i..."
147950 df-log_ $a "...gested by Mario Carneiro. (Contributed by David A. Wh..."
```
It also looks like the r19.29_2a comment is missing a period after "quantifiers". :)

This could be enforced with a 'verify markup' warning.  Should we go that far?  Maybe we should if it prevents label collisions in MM0.

**Comment by david-a-wheeler** [comment]
I've been thinking about removing `df-log_`. At the time it wasn't clear if it or logb would be best, but logb turned out to be nicer and is now in the main section. I might try to rescue its one use, because it's an interesting example of currying, but it's not clear it's worth it.

**Comment by tirix** [comment]
The "2" in "r19.29_2a" is because this is a double-quantifier version, but if I sticked it together with the rest of the label, it would have resulted in "r19.292a" which suggests a reference to a non-existing chapter 19.292. Do you have any better proposal?
For double-quantifier versions, sometimes one letter is doubled (like in ~ ralrimivva), and sometimes a "2" is appended (like in ~ cbvral2v). Shall we also have a convention about which one is preferred?

**Comment by avekens** [comment]
@tirix There is already the convention that vv should be used if there are two distinct variables. Since this is the case with r19.29_2a, I think it can be renamed r19.29vva. This would also correspond to ~r19.28v. If you don't disagree, I would change it (also changing tghilbert1_1 -> tghilberti1 and tghilbert1_2 -> tghilberti2).
@david-a-wheeler I would rename df-log_ to df-logbALT, at least temporarily.

**Comment by tirix** [comment]
@avakens I'm fine with r19.29vva!

I think this "suffix doubling" would be worth mentioning [on our conventions page](http://us2.metamath.org:88/mpeuni/conventions.html) (chapter "Label Naming Conventions", section "Suffixes"). Actually it would be nice if there was a full list of suffixes and the order in which to expect them...

**Pull request merged**
