### PR TITLE
New symbols/tokens for df-defat/df-afv

### PR DESCRIPTION
**Pull request by avekens**
New symbols/tokens for df-defat/df-afv used, comments adapted/corrected (see https://groups.google.com/forum/#!topic/metamath/cteNUppB6A4)

### CODE REVIEW

**Comment by avekens** [comment]
Hm, I created a new PR with metamath:develop as target, but the Travis checks were not performed again, and conflicts to be resolved are reporeted (which I cannot resolve because of missing permissions). 
Unfortunately, I am not so familiar with Git/Github - so I do not know what to do now...

**Comment by nmegill** [comment]
Because I was unable to resolve this, I transferred Alexander's changes to set.mm by hand into set.mm develop commit 8624629.  I am closing the pull request.



Below is my response of 8/14/17 which didn't post because I seem to have clicked Reply instead of Reply All:

I am not expert enough to understand how to fix this.  The ax13/ax14 Travis errors existed in an old develop release and are corrected in the current release, so Alexander's version is not up-to-date, and I'm concerned that it might revert everything since the ax13/ax14 fix.

In particular, I'm confused about
https://github.com/metamath/set.mm/pull/134/files
At the top of that page it says "avekens wants to merge 1 commit into metamath:develop from avekens:develop".  But it seems that it merely shows Alexander's changes since his previous pull request and does not show the differences between his pull request and the latest develop set.mm.  This didn't seem right, so after downloading his version, diff with the latest develop set.mm produces 3330 lines, most of which weren't included in the Githup difference.  How can I figure out what is happening?

It would be useful if someone could write a "how to" for the process for new contributors to make pull requests specifically for set.mm in the develop branch.  Unfortunately I don't have enough experience to do this myself.  I don't even know how to create a pull request since I'm authorized to bypass it and thus have never done it.  I'll mention that Wolf Lammen has been sending me set.mm patches by email since he gave up trying to figure out how to "create a pull request on Github as a non-registered contributor", so he would also benefit from such a write-up.

Norm

**Comment by david-a-wheeler** [comment]
On August 19, 2017 1:18:46 PM EDT, nmegill <notifications@github.com> wrote:

>It would be useful if someone could write a "how to" for the process
>for new contributors to make pull requests specifically for set.mm in
>the develop branch.  Unfortunately I don't have enough experience to do
>this myself.  I don't even know how to create a pull request since I'm
>authorized to bypass it and thus have never done it.  I'll mention that
>Wolf Lammen has been sending me set.mm patches by email since he gave
>up trying to figure out how to "create a pull request on Github as a
>non-registered contributor", so he would also benefit from such a
>write-up.

There are many writeups about using Github. Here is one; this uses the command line mostly:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

The big difference is that in set.mm, you usually want to start with the "develop" branch, not the "master" branch.

We could point people to some useful writeups until we create our own.


--- David A.Wheeler

**Comment by avekens** [comment]
Hi Norman,
thank you very much for merging my changes manually into the development branch. I really do not know what got wrong with my commit. And I would really appreciate a "how to" which describes exactly what to do: until now it was almost only try & error what I did to put changes to the repository in a hopefully acceptable way. I used the "GitHub Desktop"-Tool, which is easy to use, but at the cost of control and overview. 

As David wrote, there are many writeups about how to use git/github, but they almost never fit exactly to our situation. So a "how to" for metamath/set.mm would really be great.

Best regards,
Alexander

**Pull request closed without merging**
