### PR TITLE
Additions related to uniform spaces and ordered fields.

### PR DESCRIPTION
**Pull request by tirix**
This is for merging recents changes, only in my mathbox in set.mm (plus regeneration of "discouraged" to fix the travis check which failed on develop).
The diff seems to be huge, I guess it's not due to changes on the Proba branch, but to one single commit on the develop branch: 356d6da1ed06285374b0b2677714cae2358f124a

### CODE REVIEW

**Comment by nmegill** [comment]
Something went very wrong here, I don't understand what.  In particular, you shouldn't be making changes to iset.mm and nf.mm.

**Comment by nmegill** [comment]
In iset.mm, your pull request claims to make the following change:

-$( iset.mm - Version of 9-Jan-2018
+$( iset.mm - Version of 21-Jan-2018

Yet the latest iset.mm ca2449f already has 21-Jan-2018.  It seems like it is trying to update an old version of iset.mm, which makes no sense to me.

I hope someone can figure out what went wrong, but if not, email me your mathbox and $t section as attachments (if those are all you changed) and I'll update set.mm by hand.

Norm

**Comment by tirix** [comment]
Hi Norm, indeed, it looks like I did not merge properly. This now looks much better. Could you please have another look?

**Comment by nmegill** [comment]
It looks good.

The annual 'minimize' run, which I'll probably apply to set.mm tomorrow, will affect your mathbox; so after that you probably want to update your proba branch to prevent future merge conflicts.

**Comment by tirix** [comment]
Sure. Thank you!

**Pull request merged**
