### PR TITLE
Theorems for graph theory, Proof of Friendship Theorem

### PR DESCRIPTION
**Pull request by avekens**
Mathbox of AV:
- Theorems for graph theory, especially for walks (represented as words, closed walks) and regular graphs.
- Proof of the Friendship Theorem according to Huneke's proof.

@nmegill : Please move the following theorems from the Mathboxes to the main part, because I use them in my proofs:
-   rabbidva2 (TA)
-   elfzp1b (PC)
-   frabbijd (TA)

### CODE REVIEW

**Comment by avekens** [comment]
Travis not running? No checks were performed...

**Comment by david-a-wheeler** [comment]
Travis was running checks twice, so I tweaked its configuration. It's supposed to be only running checks once, but obviously running checks is 0 times is not an improvement. :-(.

Sorry about that, I will see what I can do about that later today.

**Comment by david-a-wheeler** [comment]
Also, congratulations on this impressive work.

**Comment by david-a-wheeler** [comment]
I'm going to temporarily close this pull request, and then reopen it. That way, it should trigger the Travis build. Believe me, I do not want to close this permanently I have not read every line of it but this sounds extremely impressive.

**Comment by david-a-wheeler** [comment]
Instead of regenerating `discouraged`, you should probably use `simpl` instead of `axia1` within `numclwlk1lem2fo`.

**Comment by david-a-wheeler** [comment]
I briefly looked over the proofs.  In addition to proving a metamath 100 problem, there are a *lot* of general-purpose theorems proved on the way to the destination.  That's fantastic.  I suspect Mario will have some comments/suggestions about some of the theorem names, but that's a minor matter.

**Comment by avekens** [comment]
Problem fixed (I exchanged axia1 by simpl), Trevis checks are green now.

Concerning the theorem names: I know that they are not perfect, and I plan to revise them anyway (see my comment in the Google group). However, suggestions are welcome!

**Comment by david-a-wheeler** [comment]
Congratulations!

**Comment by nmegill** [comment]
@avekens I moved rabbidva2 (TA), elfzp1b (PC), frabbijd (TA) to the main part of set.mm.  The last one was renamed f1oresrab.

**Pull request merged**
