### PR TITLE
Mathbox

### PR DESCRIPTION
**Pull request by benjub**
shortened proof of bj-2upleex and fixed a typo

### CODE REVIEW

**Comment by nmegill** [comment]
@benjub Could you cancel and resubmit this pull request?  I fixed some Travis issues and reran the build, but it seems it is caching old copies of the files I changed.  (There appear to be no errors in your pull request.)

Thanks,
Norm

**Comment by benjub** [comment]
Now, my branch is said to be 37 commits behind develop. Can I do a pull request right now, or do I need to do something like "git pull upstream" before ?

**Comment by nmegill** [comment]
I think you should be able to do it right now.  It was already ready to merge, and the errors in the Travis run were bogus.

**Comment by nmegill** [comment]
It looks good, everything seems fine.

**Pull request closed without merging**
