### PR TITLE
Revert "(DON'T MERGE YET, typos need fixing) Add "Reflexive" etc. definition to Wheeler's mathbox"

### PR DESCRIPTION
**Pull request by nmegill**
Reverts metamath/set.mm#1286

### CODE REVIEW

**Comment by benjub** [comment]
@nmegill @david-a-wheeler I think this can be closed/cancelled since this was taken care of in PR #1286 .

**Comment by nmegill** [comment]
@benjub - this reverts #1286 because I accidentally merged it when I overlooked that the title was changed to "(DON'T MERGE YET...".  It looks like the title of #1286 was changed again, so I'm confused.  I'll wait for @david-a-wheeler to merge or cancel this PR.

**Comment by jkingdon** [comment]
`Reflexive` is now in the mathbox, and that is OK per https://github.com/metamath/set.mm/pull/1286#issuecomment-562078377

So there doesn't seem to be anything to do here, so I'll take the liberty of closing this pull request so it doesn't clutter up the list of open pull requests. Feel free to re-open if there is anything more to do (or, perhaps more likely, make a new issue or pull request, but either way is fine with me).

**Comment by benjub** [comment]
From the above discussion, I conclude I can delete this branch.

**Pull request closed without merging**
