### PR TITLE
Add nnnotnotr to iset.mm

### PR DESCRIPTION
**Pull request by jkingdon**
This is similar to [nnexmid](https://us.metamath.org/ileuni/nnexmid.html) but for double negation elimination.

It is in response to https://mathstodon.xyz/@MartinEscardo/113347067805719864

### CODE REVIEW

**Review by sctfn — APPROVED** [review]
Cool!

**Review by avekens — APPROVED** [review]

**Comment by jkingdon** [comment]
As suggested in the follow up post https://mathstodon.xyz/@MartinEscardo/113350015536512508 I have reduced the axiom usage in the solution (so it only references implication and negation, not conjunction or disjunction).

**Review by sctfn — APPROVED** [review]

**Comment by benjub** [comment]
That statement is https://us.metamath.org/ileuni/bj-nnst.html (although the latter proves it from nndc, so uses other connectives too -- not a big deal by the separation theorem). Escardo's statement mentioning "implicational calculus" is misleading, since the statement cannot be proved in minimal calculus as proved in the comment of https://us.metamath.org/mpeuni/bj-stabpeirce.html

**Comment by jkingdon** [comment]
> That statement is https://us.metamath.org/ileuni/bj-nnst.html (although the latter proves it from nndc, so uses other connectives too -- not a big deal by the separation theorem).

Ah so it is. It would seem like the proof of bj-nnst is similar to the first one which had been in this pull request (which I kept as a separate commit in case we want to refer to it).

> Escardo's statement mentioning "implicational calculus" is misleading, since the statement cannot be proved in minimal calculus as proved in the comment of https://us.metamath.org/mpeuni/bj-stabpeirce.html

I took that to be a statement about a system which includes explosion (in fact, I think there's a mention of explosion elsewhere in the thread, although I'd have trouble correctly summarizing because the notation and proofs being used are quite different from what I'm used to)

**Comment by benjub** [comment]
I think that "STAB" should be used, since as a rule: we do not introduce many new definitions, but when we do, we should use them (almost) systematically, since any use of a definition renders all other uses less exotic.

I think that `nnst` is a good label.

Maybe you can move it to main, use your proof, and add something like: "Use only axioms of the ` ( -> , -. ) ` -intuitionistic calculus, following a suggestion by Martin Escardo.  (Revised by JK, ...) $)" ?

**Comment by benjub** [comment]
> Maybe you can move it to main, use your proof, and add something like: "Use only axioms of the `( -> , -. )` -intuitionistic calculus, following a suggestion by Martin Escardo. (Revised by JK, ...) $)" ?

To be more precise:
```
$( Double negation of stability of a formula.  Intuitionistic logic refutes
   unstability (but does not prove stability) of any formula.  This theorem
   can also be proved in classical refutability calculus (see set.mm/bj-peircestab)
   but not in minimal calculus (see set.mm/bj-stabpeirce). (Contributed by BJ,
   9-Oct-2019.)  Use only axioms of the `( -> , -. )` -intuitionistic calculus,
   following a suggestion by Martin Escardo. (Revised by JK, ...) $)
nnst $p |- -. -. STAB ph $=
```
* Maybe you link to set.mm theorems differently ?  (I am not happy with my method, but don't know if there is something better.)
* Maybe `nnstab` ?  (I have no preference.)

**Comment by jkingdon** [comment]
> I think that "STAB" should be used, since as a rule: we do not introduce many new definitions, but when we do, we should use them (almost) systematically

I'm not sold on this rule in general, and even less in this case.

In fact, I'm not sure I'm sold on the existence of ` STAB `.  For whatever it is worth, the paper cited at https://us.metamath.org/ileuni/cnstab.html uses the notation `For all 𝑥, 𝑦 ∈ R, if ¬¬(𝑥 = 𝑦) then 𝑥 = 𝑦`

Anyway, I could keep going point by point on each of the questions, but I'm kind of losing interest in the topic, and further debate seems like the wrong direction if my interest is waning. Not sure I see a lot of choices other than:

1. Move the theorem in this pull request to my mathbox
2. Close this pull request

I guess maybe I'd lean towards number one because I don't think any of us see a need to use this theorem in other proofs.

**Comment by benjub** [comment]
Don't close it; at worst, put it in your mathbox. But it's a shame: we're one minute away of having one better theorem in Main instead of two theorems in separate mathboxes. If you don't go for the unified theorem, then I'll you use your enhanced proof in "my" theorem, crediting you of course.

**Comment by jkingdon** [comment]
> Don't close it; at worst, put it in your mathbox. But it's a shame: we're one minute away of having one better theorem in Main instead of two theorems in separate mathboxes.

Mathbox it is (at least for now).

Seems like the easiest way to prevent one (or both) of us from being sad about things like notation and comments.

>  If you don't go for the unified theorem, then I'll you use your enhanced proof in "my" theorem, crediting you of course.

Sounds good.

**Pull request merged**
