### PR TITLE
Some theorems moved from mathboxes, to the main part of set.mm

### PR DESCRIPTION
**Pull request by glacode**
Some theorems moved from mathboxes, to the main part of set.mm (my upcoming PR will use those theorems)

I've done a distinct PR to let Norm evaluate the theorems moved to the main part.

### CODE REVIEW

**Comment by benjub** [comment]
Skimming through it, I saw an "Abtract".

**Comment by glacode** [comment]
Thank you for the remark, @benjub . I didn't touch the original author's comments.

I usually use a lot of ctrl+c > find > ctrl+v in order to move theorems around.
May I ask you if I could rather build a metamath script? Is there a metamath command that sounds like "move theorem x just after theorem y" ? 
I spend all my time in mmj2 and I guess I should re-read the metamath.exe manual myself (just asking if you can point me in the right direction... :-) )

BR
Glauco

**Comment by nmegill** [comment]
Merging @avekens PR seems to conflict with yours.

**Comment by nmegill** [comment]
> Thank you for the remark, @benjub . I didn't touch the original author's comments.
> 
> I usually use a lot of ctrl+c > find > ctrl+v in order to move theorems around. May I ask you if I could rather build a metamath script? Is there a metamath command that sounds like "move theorem x just after theorem y" ? I spend all my time in mmj2 and I guess I should re-read the metamath.exe manual myself (just asking if you can point me in the right direction... :-) )
> 
> BR Glauco

Unfortunately there are no metamath.exe tricks that I know of to do this.  I use the same ctrl+c/ctrl+v method.

**Comment by avekens** [comment]
I assume the conflicts are in the history at the top, which are usually easy to resolve.

**Comment by glacode** [comment]
Conflicts are at the top, but unfortunately they are also "distributed". I guess my best bet is to close this PR and redo the steps in a clean branch (a bit late here, I'll do it in the coming days)

Thanks everybody for the support

Glauco

**Pull request closed without merging**
