### PR TITLE
iset/mathbox minor corrections

### PR DESCRIPTION
**Pull request by benjub**
@jkingdon :
* In this PR, I changed the conclusion of bj-d0clsepcl from |- ( ph \\/ -. ph ) to |- DECID ph
It looks clearer, and since we have a definition, we could as well use it. Maybe do the same with acexmid and friends ?
* I added to my mathbox closed forms of notbid and dcbid.  I know deduction form is sufficient and easier to manipulate in longer proofs, but with fundamental operators like -. and DECID, having a closed form has the potential to minimize many proofs. Can I move them to main and do the minimizations ?

### CODE REVIEW

**Comment by benjub** [comment]
Fixed top date... again... Having two different conventions for the main two databases is confusing.

**Comment by jkingdon** [comment]
>     * I changed the conclusion of bj-d0clsepcl from |- ( ph \/ -. ph ) to |- DECID ph
>       It looks clearer, and since we have a definition, we could as well use it. Maybe do the same with acexmid and friends ?

I thought about this when I first introduced `acexmid` and the like. And I guess my reasoning was that it is clearer to say `ph \/ -. ph` than "ph is decidable" when this isn't as familiar a concept as many others. And `DECID ph` is worse yet, as this is not found in any works except iset.mm as far as I know. Now if people want to make the case for the other choice, we can consider it. But at least in the works I've been reading, I don't see "xxx is decidable" all that often.

>     * I added to my mathbox closed forms of notbid and dcbid.

Definitely should add bj-notbi because set.mm has http://us.metamath.org/mpeuni/notbi.html and I'll believe you that it would minimize multiple proofs. I guess we should name it `notbiim` (by analogy to `imanim`, `annimim`, `oranim` and probably other cases where set.mm has a biconditional and we just have one direction).

As for `bj-dcbi`, I don't object to having a closed form but that seems to be a bit thornier in terms of naming (as you already noticed). The thing about http://us.metamath.org/ileuni/dcbi.html is that we also have http://us.metamath.org/ileuni/dcim.html , http://us.metamath.org/ileuni/dcor.html , etc. I suppose these also might be better stated in imported rather than exported form (for example, `( ( DECID ph /\ DECID ps ) -> DECID ( ph \/ ps ) ) )` rather than `( DECID ph -> ( DECID ps -> DECID ( ph \/ ps ) ) )` although that's more of an aside, not something we'd necessarily consider at the same time we consider the naming conflict over `dcbi`.

**Comment by jkingdon** [comment]
> Fixed top date... again... Having two different conventions for the main two databases is confusing.

Yeah, I too mix this up even though I know about both conventions. I haven't tried to raise a stink because.... well, Norm spends a lot more time doing things like merging so I'm willing to go with what he finds convenient.

**Comment by nmegill** [comment]
> Fixed top date... again... Having two different conventions for the main two databases is confusing.

OK, let's add /top_date_skip to the 'verify markup' run so they will be the same.  @jkingdon I think you did a PR for this that wasn't merged, could you do it again?  Thanks.

**Pull request merged**
