### PR TITLE
Draft: add two proofs of FALSE

### PR DESCRIPTION
**Pull request by benjub**
Do not merge. Just checking if it passes CI.

First proof uses yesterday's definition from #3334 and second proof uses simplest possible definition.

### CODE REVIEW

**Comment by benjub** [comment]
Ok. So mmj2 detects a problem with df-fake:
```
I-PA-0205 Axiom df-fake has failed the definitional soundness check. Non-set dummy variable found, and no justification theorem is available.
```
but not with df-ich. Note that the version of mmj2 I use, which is the one proposed for download on the metamath website, does not detect it, so that bugfix might be recent.

**Comment by benjub** [comment]
The third definition is detected too:
```
 I-PA-0206 Axiom df-fake has failed the definitional soundness check. Dummy variables [x] are possibly free in the definiendum, and no justification is available.
```
I'll stop here the experimentations (I cannot experiment locally since my version of mmj2 seems to be different: it does not detect any unsoundness). The first definition is still not detected.

**Comment by digama0** [comment]
you should report this on mmj2 repo so I don't forget

**Comment by benjub** [comment]
Reported as https://github.com/digama0/mmj2/issues/70 so closing this PR.

**Pull request closed without merging**
