### PR TITLE
more axiom saves with functions

### PR DESCRIPTION
**Pull request by icecream17**
changes:
+ ssrel3 (moved to main), relco (moved up) -> cotrg, 3albii (moved to main) -> dffun2
+ dffun6 (moved up, revised) -> dffun3
+ funmo, funimaexg revised

(cotrgOLD uses relco through autominimization)

unrelated:
use vopelopabsb to shorten difopab and isarep1

---

theoretically, ax-11 could be removed from cotrg and dffun2 (alcomiw), but I found no satisfying way to do this

<details><summary>axiom graph</summary>

image

```py
SHELL_CAN_PRINT_UNICODE = True # for windows this is False by default

if __name__ != '__main__':
    raise EnvironmentError("needs to be run as a program")


def ascii_d(density):
    if density == 1:
        return "#"
    if 0.1 > density > 0:
        return "."
    return str(density)[2]

    """
    if density > 0.97:
        return "█"
#    if density > 0.9:
#        return "#"
    if density > 0.85:
        return "▓"
#    if density > 0.5:
#        return "≡"
    if density > 0.35:
        return "▒"
    if density > 0.1 or not SHELL_CAN_PRINT_UNICODE:
        return "░"
    return " "
    """

c = 0

usage = {}
total = 0
sections = []
factor = 0
GRAPH_COLUMNS = 39 #329 # minimum: 12

with open("~ax.txt", "r") as file:
    text = file.read()
    lines = text.splitlines()
    total = len(lines) # all lines are theorems
    factor = total // GRAPH_COLUMNS

    for (i, line) in enumerate(lines):
        section = i // factor
        if section == len(sections):
            sections.append({})
            sections[section]["length"] = 1
            sections[section]["head"] = line.split()[0]
        else:
            sections[section]["length"] += 1

        for word in line.split():
            if word.startswith("ax-"):
                if word in usage:
                   usage[word] += 1
                else:
                   usage[word] = 1

                if word in sections[section]:
                   sections[section][word] += 1
                else:
                   sections[section][word] = 1

#for (i, section) in enumerate(sections):
#    print(i, section["head"])
#    print(f"axiom          [{"-" * i}")

print(f"{total} total theorems")
print(f"axiom          [{"-" * (GRAPH_COLUMNS//2 - 6)} usage graph {"-" * (len(sections) - GRAPH_COLUMNS//2 - 7)}] usage% | total uses")
for word in usage:
    print(f"{word:<14} "
          f"[{"".join([(ascii_d(section[word]/section["length"]) if word in section else " ") for section in sections])}]"
          f" {usage[word]/total:6.2%} | {usage[word]:5} total")
```

</details>

### CODE REVIEW

**Comment by BTernaryTau** [comment]
> theoretically, ax-11 could be removed from cotrg and dffun2 (alcomiw), but I found no satisfying way to do this

Yeah, I looked at this in the context of dftr5, and the best I could do while avoiding ax-10 through ax-13 was to create an alcomw with two implicit substitution hypotheses, one for the forward implication and one for the reverse implication. I'd be interested to know if that's all that is possible, or if there's a better option I missed.

**Review by avekens — APPROVED** [review]

**Comment by benjub** [comment]
> theoretically, ax-11 could be removed from cotrg and dffun2 (alcomiw), but I found no satisfying way to do this

@icecream17 : actually, these dependencies on ax-11 show that the natural statements for cotrg and dffun2 are rather:
```
cotrg |- ( ( A o. B ) C_ C <-> A. x A. z A. y ( ( x B y /\ y A z ) -> x C z ) )
dffun2 |- ( Fun A <-> ( Rel A /\ A. y A. z A. x ( ( x A y /\ x A z ) -> y = z ) ) )
```
(It is also natural that the innermost quantified variable, y in the first line and x in the second, is the one that does not appear in the consequent: it is the "most bound" variable".)

For these two reasons, these formulations look better. Could you make the change. (Then, if one wanted for some reason the original formulations, alcomiw (and its converse with another hypothesis, as @BTernaryTau mentions) could be applied to these, its hypothesis being proved in the standard way -- but I think the original formulations are not worth keeping; usages can probably be adapted, even though this may require some tedious work.)

**Comment by benjub** [comment]
As for dftr5, I think it would be worth proving a commuted form of dftr2, say
```
$( Variant of dftr2 with commuted quantifiers. Choose the variant ~ dftf2 or ~ dftr2c that makes
   for a proof not requiring ax-11, or if this does not discriminate, for the shorter proof. $)
dftr2c |- ( Tr A <-> A. y A. x ( ( x e. y /\ y e. A ) -> x e. A ) )
```
Looking at some usages, it would remove ax-11 from many theorems.

@glacode (**edit:** sorry, I meant @icecream17) or @BTernaryTau can you do it ?

**Comment by BTernaryTau** [comment]
> Looking at some usages, it would remove ax-11 from many theorems.

Yep, that's why I was looking at it before.

> @BTernaryTau can you do it ?

Yeah, I can handle that, though I still think it's worth creating an alcomw so it's more straightforward to mark alcom as discouraged. I'm fine to do that too, or if @icecream17 prefers to handle that part then that also works.

**Comment by benjub** [comment]
> Yeah, I can handle that, though I still think it's worth creating an alcomw so it's more straightforward to mark alcom as discouraged. I'm fine to do that too, or if @icecream17 prefers to handle that part then that also works.

Applying alcomiw twice, or creating alcomw, as you prefer.  In any case, we would prefer its use over alcom, but not to the point of adding a discouragement tag to alcom, which would make life more difficult for users trying to prove more complex theorems where ax-11 usage is not a concern. I think a similar remark was made by another contributor a few months ago on a related topic.

**Comment by BTernaryTau** [comment]
> In any case, we would prefer its use over alcom, but not to the point of adding a discouragement tag to alcom, which would make life more difficult for users trying to prove more complex theorems where ax-11 usage is not a concern.

I thought the plan would be to mark all theorems depending on ax-10 through ax-12 as discouraged once the unnecessary dependencies on those axioms throughout the database have been removed, similar to what was done with ax-13 (and the same as has already happened with theorems like abeq2).

**Comment by icecream17** [comment]
@BTernaryTau you can do it
and +1 on alcomw

---
abeq2w vs abeq2 is a lot less convenient than adding dvs as with ax-13.

Enough theorems far ahead use these earlier theorems and would need to be changed, that I don't see theorems like ~ etransc avoiding ax-10 to 12 even though it is probably technically possible

Well, it could happen if more automation develops in metamath and it becomes trivial

I think there were comments about this axiom save https://us.metamath.org/mpeuni/nnne0.html being too much effort/not being worth it

**Pull request merged**
