### PR TITLE
Constructed outer measures are countably sub-additive.

### PR DESCRIPTION
**Pull request by tirix**
And other changes which were pending in my mathbox.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
Hi! Sorry I didn't comment, I teach graduate classes and I'm in the middle of the end of semester rush.

**Comment by savask** [comment]
@tirix Nice work on outer measures! Judging by the table of contents in Bogachev's book, it is near the end of the chapter on constructions and extensions of measures. Are you looking forward to formalizing the Lebesgue integral next? :-)

Also I wanted to comment on your Morley theorem statement. As discussed in #1509, the statement is not correct for "flat" triangles. Maybe it makes sense to add the requirement that points A, B and C are not collinear? As far as I understand, one could add ```( phi -> L = ( LineG ` G ) )``` and `( phi -> -. ( A e. ( B L C ) \/ B = C ) )` to the statement.

**Comment by tirix** [comment]
@savask Thanks! I'm not quite done yet though but I'd like to continue all the way to Caratheodory's Extension Theorem. Better than formalizing Lebesgue integral, my goal has been to formalize Bochner's integral (which is merely a generalization of Lebesgue integral to any Banach space ;-) ). You can find it in my Mathbox: [df-sitg](http://us.metamath.org/mpeuni/df-sitg.html) and following theorems, and the (commented out) ~ df-itgm. Both goals complement each other, since Caratheodory's extension can provide measures to use in the Bochner (or Lebesgue) integral. Unfortunately I'm stalled on that track, my attention moves easily!

You're of course right about the non-collinear condition for the statement, I need to add it!
BTW, if you're interested, Gérard pointed me to [a recent Arxiv submission](https://arxiv.org/abs/2005.08723) with a new proof of that Theorem!

**Comment by tirix** [comment]
As a note, I've added the condition that A, B, and C are not collinear in Morley's theorem as part of #1658.

**Comment by savask** [comment]
> Better than formalizing Lebesgue integral, my goal has been to formalize Bochner's integral (which is merely a generalization of Lebesgue integral to any Banach space ;-) )

Now that you mentioned it, I remember the idea being discussed in the google group years ago. It's good to know that it wasn't abandoned. Hopefully your work on measures will finally enable us to define area on CC properly, so we can replace df-area.

> BTW, if you're interested, Gérard pointed me to a recent Arxiv submission with a new proof of that Theorem!

It looks really nice, but the proof still involves some angle-arithmetic ("angle chasing" as they call it). I'm not sure how easy these kinds of arguments are in Tarski geometry, but the proof indeed is very short.

**Pull request merged**
