### PR TITLE
Thanks to all helping rename syl5eq to eqtrid

### PR DESCRIPTION
**Pull request by wlammen**
Many thanks to those who helped out with the huge task of renaming syl5eq to eqtrid.  Your timely checking and approvals of all individual pieces is highly appreciated.

This Pull request is not meant to be merged, just a notification.  It will be closed after some time.

### CODE REVIEW

**Review by wlammen — COMMENTED** [review]
Do not approve

**Comment by ProgramCrafter** [comment]
It'd be better to make this PR a draft then, so that it isn't mergeable?
(Also, in my experience people mostly used issues for gratitude so PR is an interesting choice :smile: )

**Comment by jkingdon** [comment]
> It'd be better to make this PR a draft then, so that it isn't mergeable? (Also, in my experience people mostly used issues for gratitude so PR is an interesting choice 😄 )

Fair points, but I'll accept the thanks in whatever form.

And thanks above all to @wlammen for making all those changes.

**Comment by wlammen** [comment]
The reason I chose this Pull Request as a platform for saying "Thank you" is that all those participating in this month-long journey looked HERE to find available pieces to confirm.  I do not intend or recommend to proceed alike in any other odd task.  This is from my perspective a very rare exception.  I'm not going to justify, or discuss the principles of this once in a couple of years event any more HERE.  That's indeed a case for a new issue (should someone find it worth an extensive discussion).

**Pull request closed without merging**
