### PR TITLE
Add smetamath (in Rust) as 3rd Travis metamath validator

### PR DESCRIPTION
**Pull request by david-a-wheeler**
This modifies .travis.yml (the configuration file for running Travis)
so that changes will also be checked by smetamath.
The smetamath tool (aka smetamath-rs and smm3) is a high-speed
metamath verifier written in Rust by Stefan O'Rear that can use multiple cores.

This means that set.mm is now checked by three
independently-implemented metamath verifiers in three different languages:
metamath (in C), mmj2 (in Java), and smetamath (in Rust).
These are also all written by different people.
This use of diverse verifiers greatly descreases the likelihood
that a code defect in a verifier might result in
incorrect validation of metamath proofs.

My thanks to Stefan O'Rear, both for the tool and for various tweaks
that make this work.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This branch (travis-smm3-2) is a squash merge of branch travis-smm3, which got absurdly messy.  This just shows the final proposed changes, which are much cleaner.

**Comment by digama0** [comment]
Could you add grep checking for ":Warning:" as well as ":Error:"? Looking at the build log, it obviously found a problem in set.mm but travis thinks it's okay.

**Comment by sorear** [comment]
@digama0 FYI, this is the same problem I emailed you about on May 28.

**Comment by digama0** [comment]
I figured as much. It's a good thing I didn't fix it, since it's a good test and evidence of usefulness of adding another verifier, which looks at different things. I'll patch it once the travis stuff is all working.

**Comment by david-a-wheeler** [comment]
Sure!  I'm not at my computer, I plan to do that tomorrow.

**Comment by david-a-wheeler** [comment]
As expected, it now fails with:

> ./set.mm:443151-443153:Warning:This comment marker must be the first token in the comment to be effective

Who will fix this?

**Pull request merged**
