### PR TITLE
Aristotelian syllogisms

### PR DESCRIPTION
**Pull request by benjub**
* remove ax-5,6,7,12 from most barbara-like syllogisms, so that now, all of them are proved in the smallest normal modal logic (K).
* streamline proofs by proving syllogisms from others as much as possible
* add a lemma for the syllogisms having an existential assumption

This might be of interest to @david-a-wheeler (in particular, maybe that not all ALT proofs should be kept).

### CODE REVIEW

**Comment by benjub** [comment]
In case this helps, here is the output given by `metamath.c`:
```
MM> SHOW TRACE_BACK barbara~bamalip / MATCH ax-*
The proof of statement "barbara" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "celarent" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "darii" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "dariiALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "ferio" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "barbarilem" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "barbari" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "barbariALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "celaront" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "cesare" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "cesareALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "camestres" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "camestresALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "festino" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "festinoALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "baroco" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "barocoALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "cesaro" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "cesaroALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "camestros" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "camestrosALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "datisi" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "datisiOLD" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "disamis" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "disamisALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "ferison" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "bocardo" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "darapti" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "daraptiALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "felapton" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "calemes" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "calemesALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "dimatis" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "dimatisOLD" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "fresison" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "fresisonOLD" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "calemos" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "calemosOLD" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "fesapo" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
The proof of statement "fesapoALT" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax-6($a) ax-7($a) ax-12($a)
The proof of statement "bamalip" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a)
```

**Comment by david-a-wheeler** [comment]
Interesting! I like `barbarilem`, it's short but it simplifies other things, and that's great. We generally try to minimize the number of axioms that the "main" statement depends on, so this direction makes complete sense to me.

I think we should keep the ALT forms. They require more axioms, but they're shorter, and Aristotelian logic is historically very important (it's really the start of logic as its own field). We often keep theorems that are "shorter but need more axioms" as ALT theorems.

The proofs I created generally worked unchanged in iset.mm (intuitionistic logic). I'm curious, is that still true? That's not a requirement for merging, I'm just curious.

**Comment by benjub** [comment]
> The proofs I created generally worked unchanged in iset.mm (intuitionistic logic). I'm curious, is that still true?

Probably: the contrapositions I used are the two intuitionistic contrapositions, and I don't recall using other suspicious results. They probably hold in minimal calculus as well. Of course, a fine study of the required axioms would be easier with the axiom system I described in https://github.com/metamath/set.mm/issues/756#issuecomment-877045990

To add to my above comment: it is important to have proved them in modal (K), the weakest normal modal logic, since it shows that the results (and proofs) hold for the usual interpretations of modalities: for some/for all, possible/necessary, allowed/mandatory, believe/know, sometimes/always, ...

**Comment by david-a-wheeler** [comment]
A minor comment: `barbarilem` is quite general, and is reused in multiple theorems. I think it should have a standalone name; we usually call something a "lemma" if it's used in just one other proof.

Not sure what its name should be, especially since `exan` is already taken. Maybe `exexan` ?

We could do the rename later, no need to delay this PR for a rename.

**Comment by david-a-wheeler** [comment]
I looked more closely at `darii` and `dariiALT` and I *definitely* think we should retain the ALT versions and merge this. Theorem `dariiALT` is significantly shorter/simpler, while this new `darii` reduces the number of axioms it uses. So by our usual conventions, the "short" name minimizes the number of theorems, and an "ALT" version is kept for some other reason (such as simpler proofs).

Thanks for doing this!

**Comment by benjub** [comment]
> A minor comment: `barbarilem` is quite general, and is reused in multiple theorems. I think it should have a standalone name; we usually call something a "lemma" if it's used in just one other proof.
> 
> Not sure what its name should be, especially since `exan` is already taken. Maybe `exexan` ?

It could be labeled `alexan`, but there is a glitch: if a standalone, in order to follow the style of neighboring theorems it would typically be stated as
```
|- E. x ph & |- ( ph -> ps ) => |- E. x ( ph /\ ps )
```
(which is useless for barbari et al.) instead of `|- E. x ph & |- A. x ( ph -> ps ) => |- E. x ( ph /\ ps )`. A possibility would be to prove a (semi)closed form, e.g.
```
|- E. x ph => |- ( A. x ( ph -> ps ) -> E. x ( ph /\ ps ) )
```
or
```
|- ( A. x ( ph -> ps ) -> ( E. x ph -> E. x ( ph /\ ps ) ) )
```
which would probably be best.
**edit:** this is aleximi applied to ancl, so I guess I'm going to add it.

**Comment by benjub** [comment]
Last commit: added ~alexan (see above comment), but kept ~barbarilem since without it, the proofs that were using it would use ~alexan directly and would double in size.
(It is really a lemma, even if used for several theorems.)

**Comment by david-a-wheeler** [comment]
@benjub - sounds good!

**Review by david-a-wheeler — APPROVED** [review]

**Comment by benjub** [comment]
@david-a-wheeler : now that it's on the website, we can see proofs better. Recall that the ALT proofs below use more axioms but were kept as ALT because they are shorter... or so I thought, but it turns out not all of them are. So I propose to deprecate (i.e., relabel to OLD) the following ones:
1. more steps and more essential steps: cesaroALT, camestrosALT
2. fewer steps but more essential steps: calemesALT, fesapoALT
3. fewer steps but as many essential steps: camestresALT, cesareALT, disamisALT

I think (1.) is uncontroversial (I actually should have made them OLD already but missed them), and (2.) should be removed, and also (3.) (though maybe you may object to (3.)?).

There would remain a few ALT syllogisms, and their method of proofs are very similar, so I think having too many of them does not add much information. To give more information, I could add to the comment of the first such (dariiALT) something like:
> One sees how the use of ~spi may shorten some proofs of the Aristotelian syllogisms, even though this adds axiom dependencies (note that ~spi is the inference form of the axiom (T) of modal logic).

**Comment by benjub** [comment]
@david-a-wheeler : I'll do what I proposed above early next week unless you comment otherwise.

**Comment by david-a-wheeler** [comment]
@benjub :

> 1. more steps and more essential steps: cesaroALT, camestrosALT
> 2. fewer steps but more essential steps: calemesALT, fesapoALT
> 3. fewer steps but as many essential steps: camestresALT, cesareALT, disamisALT
> I think (1.) is uncontroversial (I actually should have made them OLD already but missed them), and (2.) should be removed, and also (3.) (though maybe you may object to (3.)?).
> There would remain a few ALT syllogisms, and their method of proofs are very similar, so I think having too many of them does not add much information. To give more information, I could add to the comment of the first such (dariiALT) something like:
>> One sees how the use of ~spi may shorten some proofs of the Aristotelian syllogisms, even though this adds axiom dependencies (note that ~spi is the inference form of the axiom (T) of modal logic).

I agree with you, that makes sense. I think it's important to have at least one alternate simpler example like `dariiALT` and include some text about `spi` - just as you've suggested. Thanks so much!

**Pull request merged**
