### PR TITLE
Minimize proofs in Main containing idi

### PR DESCRIPTION
**Pull request by wlammen**

### CODE REVIEW

**Comment by benjub** [comment]
Did you do a "minimize *" on the output of "show usage idi" ? I think you can do the same with all such theorems, including those in mathboxes.  Proofs are not systematically minimized when there are moved from mathboxes to Main, so this would take care of them preemptively.

**Comment by wlammen** [comment]
No, I limited minimize to Main.  The idea was better not interfere with some work in progress.  Mathboxes have about 15 more containing idi.

**Review by david-a-wheeler — APPROVED** [review]
Removing idi makes sense to me, unless they were examples to show the use of idi.

**Review by jkingdon — APPROVED** [review]
I'm operating under the assumption that it is always OK to run minimize and I don't see any reason why these should have "proof modification is discouraged" on them.

**Comment by wlammen** [comment]
See the proof of jccil to see a valid reason for a "Proof modification is discouraged" tag

**Comment by tirix** [comment]
I am the contributor for ~ opphllem2 and as far as it is concerned, no objection to remove the `idi`. 
Thanks for noticing and fixing it!

**Review by tirix — APPROVED** [review]

**Pull request merged**
