### PR TITLE
Rename syl6eqr to eqtr4di

### PR DESCRIPTION
**Pull request by jkingdon**
This is in set.mm and iset.mm

### CODE REVIEW

**Comment by jkingdon** [comment]
I have rebased this pull request and resolved conflicts.

**Review by wlammen — APPROVED** [review]
Reviewing means overlooking the files and excluding that something was "smuggled in".  I suggest to merge this as soon as possible to avoid merge conflicts elsewhere.

**Comment by tirix** [comment]
Note: I do have uses of `syl6eqr` in #4049, so issues will occur, depending which PR is merged first.

**Comment by jkingdon** [comment]
> Reviewing means overlooking the files and excluding that something was "smuggled in". I suggest to merge this as soon as possible to avoid merge conflicts elsewhere.

After my conflict resolution I also looked over the files, looking that each change was a single line and that this pull request didn't accidentally undo part of #4046 .

As for the merge conflicts, people may have to rebase pull requests, or branches not yet turned into pull requests, as `sql6eqr` had a lot of usages.

**Comment by jkingdon** [comment]
> Note: I do have uses of `syl6eqr` in #4049, so issues will occur, depending which PR is merged first.

Thanks for noticing. I've merged this rename so you should be able to update #4049 for the rename now.

**Comment by tirix** [comment]
> you should be able to update https://github.com/metamath/set.mm/pull/4049 for the rename now.

Yes, done already!

**Pull request merged**
