### PR TITLE
Strengthen dcapncf from apartness to equality

### PR DESCRIPTION
**Pull request by jkingdon**
This is in iset.mm.

Rename to dceqnconst and change the antecedent from decidable apartness (analytic LPO) to decidable equality for real numbers (analytic WLPO).

There's probably more to do on this topic ( see https://github.com/metamath/set.mm/issues/3757#issuecomment-2229600853 ) but I wanted to start with the low hanging fruit.

### CODE REVIEW

**Review by tirix — APPROVED** [review]

**Review by icecream17 — APPROVED** [review]

**Comment by benjub** [comment]
Hi @jkingdon , a few questions/remarks:
* I think this would have deserved that the OLD version stays a while in order to compare the proofs in a human-readable format. If this is not too much work, it may be useful to put it back, even in a mathbox.
* I don't remember which reals are used in iset.mm (?), but as we both know there are several interesting versions in constructive analysis, some of them included in others. Therefore, it may be interesting to formulate this theorem for arbitrary $A$, typically included in $\mathbb{R}$ and containing 0. This way, the theorem would apply when $A$ is another kind of reals included in $\mathbb{R}$.
* As a general rule, when an existence is proven by constructing a witness (which is always doable, and practically often done, in constructive math), it may be useful to formulate the strong form of the theorem.

Combining the last two remarks, this would give something like:
```
phi -> A. x e. A DECID x = 0
phi -> 0 e. A
phi -> F = ( y e. A |-> if(y = 0, 0, 1) )
=>
phi -> ( F : A --> NN0 /\ ( F(0) = 0 /\ A. z e. ( A \cap RR_+) F(z) \neq 0 ) )
```
(where I strengthened by taking NN0 as codomain and where I avoided the triple conjunction by using a natural parenthesization).

**Comment by jkingdon** [comment]
> Hi @jkingdon , a few questions/remarks:
> 
> I think this would have deserved that the OLD version stays a while in order to compare the proofs in a human-readable format. If this is not too much work, it may be useful to put it back, even in a mathbox.

OK with me. I can put this in my next pull request. I'll bring back `dcapncf`, with the previous proof. In addition, that pull request will have a few theorems which say that analytic LPO implies analytic WLPO so I'll add a bit of text (or, probably, an ALT proof) saying that would be another way to prove `dcapncf`.

In the meantime one way to see the previous proof is to use git to get an older iset.mm and run `SHOW STATEMENT dcapncf/ALT_HTML` using a local copy of metamath.exe.

> I don't remember which reals are used in iset.mm (?), but as we both know there are several interesting versions in constructive analysis, some of them included in others. Therefore, it may be interesting to formulate this theorem for arbitrary A, typically included in R and containing 0. This way, the theorem would apply when A is another kind of reals included in R.

My next pull request will add the following paragraph to the section header which describes the iset.mm construction of the reals:

> When working without excluded middle, there are several possible definitions
of real numbers.  Here we adopt the most common definition, as two-sided
Dedekind cuts with the properties described at ~ df-inp .  The Cauchy reals
(without countable choice) fail to satisfy ~ ax-caucvg and the MacNeille
reals fail to satisfy ~ axltwlin , and we do not develop them
here.  For more on differing definitions of the reals, see the
introduction to Chapter 11 in [HoTT] or section 1.2 of [BauerHanson].

In addition to the two sources cited there, there's a really nice exposition at https://mathoverflow.net/a/453340/489586 by Andrej Bauer.

As for how/whether to develop the other reals further in iset.mm, I'm not too sure. Working with a subset of the Dedekind reals immediately raises the question of what closure properties the subset has, and the MacNeille reals are a superset.

> As a general rule, when an existence is proven by constructing a witness (which is always doable, and practically often done, in constructive math), it may be useful to formulate the strong form of the theorem.

We do this in some cases, like https://us.metamath.org/ileuni/ctssdccl.html . I guess my instinct is to do so where we have a concrete need to use it in a proof.

It definitely is a good technique to keep in mind, as you do correctly point out that sometimes we need the witness and not just existence.

**Comment by benjub** [comment]
Thanks for restoring the other proof and for your answer.  As for the comments to add to the database itself, I'm not sure how much of standard math should be repeated in the database (but your proposal above looks nice and the references are certainly welcome).  I guess that simply writing in https://us.metamath.org/ileuni/df-r.html "Define the set of Dedekind reals." instead of simply "Define the set of reals." would already help a lot.  (Actually, that's the first page I checked while writing the above post, and I didn't go further.)

So, the proposal to make the theorem more generic with a class `A` as defined above still stands, especially since the $\mathbb{R}_{Dedek}$ of the database is among the larger kinds of reals.  Hopefully, one day, some version of the Cauchy reals or the HOTT reals will also be studied in the database !

**Comment by jkingdon** [comment]
> I'm not sure how much of standard math should be repeated in the database (but your proposal above looks nice and the references are certainly welcome)

It is a good caveat. As a general matter I don't think we do a very good job when we try to go too far beyond the actual theorems we prove.

I guess if this text looks good we can keep it, though (basically, if it looks like a brief literature reference more so than "repeat standard math without formalized proofs").

I hope to make a pull request tonight with the material I have discussed. Timing will depend on how quickly I make progress on finishing the one proof which  is needed to complete this pull request.

**Comment by jkingdon** [comment]
> I hope to make a pull request tonight with the material I have discussed.

In case it isn't obvious, that was a reference to what I submitted as https://github.com/metamath/set.mm/pull/4100

**Pull request merged**
