### PR TITLE
Add bijective sticks and stones

### PR DESCRIPTION
**Pull request by metakunt**
A truly horrendous proof...

### CODE REVIEW

**Comment by avekens** [comment]
> A truly horrendous proof...

Would it be possible to extract some lemmas from the proofs to shorten them?

**Comment by metakunt** [comment]
It already is shortened by extracting the mapping proof of F and G first.
Most of the proof actually benefits from the shared context in previous statements, so I'm not quite sure if that would help that much.

On a different note, maybe there exists some helper theorem which application could "carry" context, yet I think the most helpful thing would actually be to just use deduction form theorems coupled with good autocomplete, which is sadly out of scope of this PR.

All in all I think a typescript for metamath would kinda be nice, i.e. a language which transpiles "typemath" (basically semantically knowledgable metamath with tactics) to metamath which had some basic tactics like SAT solving and simple tactics like conv and rw. But sadly there is no consensus in moving to that direction. Even simpler things like libraries and minimal (stable) API's are out of reach.

I've already tried to write a transpiler that certain natural number operations automatically and generates a valid metamath proof. It was actually pretty fun to do but ultimately pointless.

**Comment by benjub** [comment]
> ...maybe there exists some helper theorem[s]...

That would be nice to spot them and use them.

> ...which application could "carry" context [...] use deduction form theorems

Exactly.

> language which transpiles "typemath" (basically semantically knowledgable metamath with tactics) to metamath which had some basic tactics like SAT solving and simple tactics like conv and rw.

That would be nice, but probably Metamath proofs produced that way would be longer (which is not necessarily a deterrent).

> there is no consensus in moving to that direction.

Using automation tools to produce proofs is encouraged, and it would be great to have more automation.  The actual proofs stored in the .mm databases still have to be genuine Metamath proofs, however.  In other words: automation to help produce proofs, but not to do away with storing the full proofs.

> I've already tried to write a transpiler that certain natural number operations automatically and generates a valid metamath proof. It was actually pretty fun to do but ultimately pointless.

Hopefully it will become point-full at some point.

As for the present MR: it would be nice to split lemma 12, which currently has a very very long proof.

**Review by icecream17 — APPROVED** [review]
For future purposes, it might be helpful to distinguish the lemmas (edit: in comments), ie ~ s...s9 is for the K = 0 case and ~ s...s10 is for the K e. NN case

**Review by avekens — APPROVED** [review]

**Pull request merged**
