### PR TITLE
Add ax6b.

### PR DESCRIPTION
**Pull request by georgydunaev**
Theorem ax6b proves logical redundancy of ax-6.
ax6blem is a version of hbnt. 
ax6blem is independent of ax-6.

### CODE REVIEW

**Comment by nmegill** [comment]
To Jim Kingdon:  This looks like a nice result and I don't see any issues with it, so I am merging it.  You may want to look it over and make any changes that you want.  In set.mm we have moved redundant or obsolete axioms to a special section called "Predicate calculus with equality: Older axiomatization" that has "(New usage is discouraged.)" tags on all $a's and $p's, and "(Proof modification discouraged.)" tags on all $p's.

Norm

**Comment by nmegill** [comment]
Georgy - you applied this to the master, not develop.  I applied it to develop for you.  In the future, please make all pull requests against develop, not master.

Thank you,
Norm

**Comment by georgydunaev** [comment]
Yes, I will.


On Jan 28, 2018 4:55 AM, "nmegill" <notifications@github.com> wrote:

Georgy - you applied this to the master, not develop. I applied it to
develop for you. In the future, please make all pull requests against
develop, not master.

Thank you,
Norm

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metamath/set.mm/pull/288#issuecomment-361029059>, or mute
the thread

**Comment by jkingdon** [comment]
@nmegill Thanks! Glad to see this merged. And thanks to @georgydunaev for the proof.

At the moment I'm focused on figuring out whether the iset.mm axioms are even sufficient (in the sense of being able to prove all the predicate logic theorems which should be provable), so I haven't been thinking too hard about how to organize whatever we end up with. But I encourage people who want to work on that to do so, and I'd be glad to weigh in if my opinions are needed.

(Oh, and by the way, if you mention me by name with an at-sign, like @jkingdon, I'll get an email so I can look at whatever it is. In this case, I stumbled across this pull request kind of by accident).

**Comment by nmegill** [comment]
"(Oh, and by the way, if you mention me by name with an at-sign, like @jkingdon, I'll get an email so I can look at whatever it is. In this case, I stumbled across this pull request kind of by accident)."

I didn't know that; good to know!  I'll do it in the future.
Norm

**Pull request merged**
