### PR TITLE
Expand apartness comments in iset.mm

### LINKED ISSUE #1498: iset.mm should briefly explain why apartness is needed
In iset.mm I see that `#` is defined using `#RR`, and `#RR = { <. x , y >. | ( ( x e. RR /\ y e. RR ) /\  ( x < y \/ y < x ) ) }`. But I didn't see any text in comments that explain *why* iset.mm needs to use "apartness" as something different from "not equal to". I guess I shouldn't be surprised that "not" causes complications, but I don't see any text briefly explaining the issue.

I think there should be a little text in iset.mm that explains iset.mm needs "apartness" to be different from "not equal". I'm sure the cited texts go into a lot of detail, but a hint within the text of iset.mm itself would be helpful.

This probably really a request for @jkingdon - but others are welcome to pipe in :-).

### PR DESCRIPTION
**Pull request by jkingdon**
Although we do cite some sources which describe this in more
detail, it is helpful to summarize with links to the relevant
theorems in iset.mm.

Fixes #1498

### CODE REVIEW

**Comment by benjub** [comment]
@jkingdon Maybe you can add to that second comment that in intuitionistic logic, one cannot prove ( -. x = y -> x # y ) , contrary to classical logic ?

[Maybe you will even formalize one day that this implication would imply excluded middle or something like that?]

**Comment by david-a-wheeler** [comment]
Excellent, thanks for the explanation!

So where possible, ideally we'd prove that things are true when they are merely "not equal", since that is a weaker claim than "apart", but in many situations you need the stronger statement "apart". Is that right?

**Comment by jkingdon** [comment]
> @jkingdon Maybe you can add to that second comment that in intuitionistic logic, one cannot prove ( -. x = y -> x # y ) , contrary to classical logic ?

I think this is covered for now by "Apartness implies negated equality, as seen at ~ apne , and the converse would also follow if we assumed excluded middle."
> 
> [Maybe you will even formalize one day that this implication would imply excluded middle or something like that?]

Don't know if it would be me or someone else but yeah maybe someone will contribute this, or some other proof that it cannot be proven. Not sure I particularly know how one would go about this, although it sort of does remind me of Remark 2.19 in [Geuvers].

**Comment by jkingdon** [comment]
> "not equal" . . . is a weaker claim than "apart", but in many situations you need the stronger statement "apart". Is that right?

Not sure I follow the entire sentence, but the part I quoted here is correct.

**Pull request merged**
