### PR TITLE
use elab2gw in eliun, eliin, elopab

### PR DESCRIPTION
**Pull request by icecream17**
continuation of https://github.com/metamath/set.mm/pull/4015

---

there are few applications of elab2gw left; elrab2gw is a plausible continuation, though at some point ax-10 through ax-12 isn't very important

Note that brabga depends on ax-10 through ax-12 by both opelopabga > (elopab, copsex2g); this removes one condition

**edit**: copsex2ga, copsex2gb show copsex2g is provable without ax-10 through ax-12

### CODE REVIEW

**Review by GinoGiotto — APPROVED** [review]

**Comment by benjub** [comment]
> Note that brabga depends on ax-10 through ax-12 by both opelopabga > (elopab, copsex2g); this removes one condition

What "removes one condition" ? What condition for what ?

**Comment by icecream17** [comment]
the word "condition" is inaccurate, I meant I removed one... upstream usage of ax-10 through ax-12

**Comment by benjub** [comment]
> the word "condition" is inaccurate, I meant I removed one... upstream usage of ax-10 through ax-12

Ok, I see. And your "edit" above implies that the second use is also removable. It would be nice if you can do it when you have time.

**Review by benjub — APPROVED** [review]

**Review by tirix — APPROVED** [review]

**Comment by benjub** [comment]
> > the word "condition" is inaccurate, I meant I removed one... upstream usage of ax-10 through ax-12
> 
> Ok, I see. And your "edit" above implies that the second use is also removable. It would be nice if you can do it when you have time.

@icecream17 : or write a TODO in a non-displayed comment just before the comment of brabga and/or copsex2g.

**Pull request merged**
