### PR TITLE
More geometry

### PR DESCRIPTION
**Pull request by tirix**
- Added definition of 2D geometry, lower and upper axioms,
- Completed chapter 6 and started chapter 7 of [Schwabhauser]
- Moved 4 theorems from my mathbox into the main part of set.mm

### CODE REVIEW

**Comment by benjub** [comment]
While I'm here... could you move your snunioc to the main part, right after snunico ?

**Comment by tirix** [comment]
@benjub added snunioc !

**Comment by tirix** [comment]
Note that I believe I shall create extra definitions for "midpoint" and "point mirroring/point reflexion/point inversion", as I assume they may be widely used in the future.

I've originally used "point mirroring" because this is the direct translation of the reference text (Punktspiegelung), however I see it the Wikipedia page prefers "point inversion".

I'll probably propose "midG" for midpoint and "invG" for point inversion.

**Comment by benjub** [comment]
"central symmetry" sounds less old-fashioned

**Comment by tirix** [comment]
It looks like "central symmetry" would rather be the property of a set of points to be invariant under such a transformation...

**Pull request merged**
