### PR TITLE
Improve .travis.yml: Use cache, optimizations, and report time

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This caches the Rust compilation for an hour - so if you make a bunch of changes in a row, the later ones will be sped up.

A lot of other small improvements, e.g., metmath is now compiled with "-O2" which significantly improves its verification time.

**Comment by sorear** [comment]
Any reason I shouldn't just post a binary artifact for smetamath 3.0.0?

**Comment by david-a-wheeler** [comment]
The CI test process takes ~ 2min 20 sec when the Rust program is in the cache this pull request creates (see https://travis-ci.org/metamath/set.mm/builds/140670044 ).

The CI test process takes ~ 4 min 3 sec when it has to regenerate the Rust program (see https://travis-ci.org/metamath/set.mm/builds/140672484).

So if you're doing a bunch of CI test processes in a row, caching can almost halve the time.

**Comment by david-a-wheeler** [comment]
I don't see the big harm in recompiling.  The real problem is when you have a bunch of CI tests in a row, which caching solves.

**Comment by digama0** [comment]
@sorear Once you have a stable version, you should upload a pre-built binary to us2. This will make it easier for others to use, and also gives a source for Travis to download. Norm gave me a little web space at us2.metamath.org/ocat/ which I have been using to host versions of mmj2; you're welcome to that, or Norm can work something else out.

**Pull request merged**
