### PR TITLE
Remove an unnecessary DV condition from axsep

### PR DESCRIPTION
**Pull request by benjub**
Remove an unnecessary DV condition from axsep and moot DV conditions from ax-sep and axsep2.
(minimal simplification, as promised in https://github.com/metamath/set.mm/pull/3567#pullrequestreview-1677931284)

### CODE REVIEW

**Comment by benjub** [comment]
Ah, the DV conditions of `axeee $p` and `ax-eee $a` are probably required to be identical:
```
 ?Warning: The mandatory distinct variable pairs for statements "ax-sep" and
  "axsep" are different or have a different order.
```
and
```
Run metamath-knife/target/release/metamath-knife --verify \
warning: Invalid axiom restatement
     --> ./set.mm:46740:5
      |
46740 |     axsep $p |- E. y A. x ( x e. y <-> ( x e. z /\ ph ) ) $=
      |     ----- This ax* theorem does not match the corresponding ax-*
      |
     ::: ./set.mm:46754:5
      |
46754 |     ax-sep $a |- E. y A. x ( x e. y <-> ( x e. z /\ ph ) ) $.
      |     ------ note: Axiom ax-* here
      |
1 diagnostics issued.
Error: Process completed with exit code 1.
```
Maybe the best solution would be that the metamath-exe and metamath-knife requirements be to have an inclusion of DVs, and not an equality ?

**Comment by sctfn** [comment]
Personally, I’d rather have it be exact, even if it’s not strictly necessary from a proof point of view. On Oct 18, 2023, at 5:59 PM, Benoit ***@***.***> wrote:﻿
Ah, the DV conditions of axeee $p and ax-eee $a are probably required to be identical:
 ?Warning: The mandatory distinct variable pairs for statements "ax-sep" and
  "axsep" are different or have a different order.

and
Run metamath-knife/target/release/metamath-knife --verify \
warning: Invalid axiom restatement
     --> ./set.mm:46740:5
      |
46740 |     axsep $p |- E. y A. x ( x e. y <-> ( x e. z /\ ph ) ) $=
      |     ----- This ax* theorem does not match the corresponding ax-*
      |
     ::: ./set.mm:46754:5
      |
46754 |     ax-sep $a |- E. y A. x ( x e. y <-> ( x e. z /\ ph ) ) $.
      |     ------ note: Axiom ax-* here
      |
1 diagnostics issued.
Error: Process completed with exit code 1.

Maybe the best solution would be that the metamath-exe and metamath-knife requirements be to have an inclusion of DVs, and not an equality ?

**Comment by GinoGiotto** [comment]
An alternative idea could be to rename [axsep](https://us.metamath.org/mpeuni/axsep.html) into something else (like `axsepg` since it's more general?). Notice that not all axioms have their corresponding identical theorem. For example [ax-ext](https://us.metamath.org/mpeuni/ax-ext.html) doesn't have one, and there is also a similar case here where [axext3](https://us.metamath.org/mpeuni/axext3.html) is a generalization of [ax-ext](https://us.metamath.org/mpeuni/ax-ext.html) because of the elimination of a DV condition.

Then I would also rename [axsep2](https://us.metamath.org/mpeuni/axsep2.html) into `axsepgALT` since with the changes in this PR [axsep](https://us.metamath.org/mpeuni/axsep.html) and [axsep2](https://us.metamath.org/mpeuni/axsep2.html) would become exacly identical, with the proof being the only difference between the two. Currently the comment of [axsep2](https://us.metamath.org/mpeuni/axsep2.html) states `A less restrictive version of the Separation Scheme axsep`, but with this PR it wouldn't be less resctrictive anymore, so the comment [axsep2](https://us.metamath.org/mpeuni/axsep2.html) should be updated as well.

**Comment by sctfn** [comment]
Given that axsep is provable, though, we should really include the exact statement. This is a case where we’re trying to match the literature to verify the literature, so we can and should be pedantic. On Oct 18, 2023, at 7:41 PM, GinoGiotto ***@***.***> wrote:﻿
An alternative idea could be to rename axsep into something else (like axsepg since it's more general?). Notice that not all axioms have their correspoding identical theorem. For example ax-ext doesn't have one, and there is also a similar case here where axext3 is a generalization of ax-ext because of the elimination of a DV condition.
Then I would also rename axsep2 into axsepgALT since with the changes in this PR axsep and axsep2 would become exacly identical, with the proof being the only difference between the two. Currently the comment of axsep2 states A less restrictive version of the Separation Scheme axsep, but with this PR it wouldn't be less resctrictive anymore, so the comment axsep2 should be updated as well.

**Comment by digama0** [comment]
> Maybe the best solution would be that the metamath-exe and metamath-knife requirements be to have an inclusion of DVs, and not an equality ?

I'd rather we didn't. The purpose of the check is to ensure that it is indeed a restatement of the axiom, and it should be as strict as we can practically make it (including e.g. variable names) so as to make it as easy as possible for readers to agree that it is indeed the same theorem.

**Comment by benjub** [comment]
Ok, then let's keep `axsep` identical to `ax-sep`, including DVs.

I'll update the MR to have the theorem without DV relabeled as, `sepfromrep`, then prove its instance `axsep` in one line from it, and also relabel `axsep2` to `axsepg`.

The reason I'd like to have `sepfromrep` is that we are currently saying "this proof actually proves the more general statement xxx", which is a very common thing to do in the math literature, but here, in Metamath, the main principle is to be explicit in what we do, so instead of saying "we can prove xxx", we just do it.

**Comment by GinoGiotto** [comment]
> I'll update the MR to have the theorem without DV relabeled as, `sepfromrep`, then prove its instance `axsep` in one line from it, and also relabel `axsep2` to `axsepg`.

Maybe I would name it `sepgfromrep`, or maybe we could imitate what has been done for ax-6, whose weakened version was derived from ax-sep in [ax6vsep](https://us.metamath.org/mpeuni/ax6vsep.html) (so following this analogy our case would be `axsepgrep` -> "derive a more general version of ax-sep from ax-rep").

**Comment by benjub** [comment]
I added ~axsepgfromrep (it's ok to have a longer label since it won't be used much). I also adapted the comments of ~axsep, ~ax-sep, ~axsepg with care, in order to make the terminology more uniform and add some precisions, with minimal changes.

**Review by avekens — APPROVED** [review]

**Pull request merged**
