### PR TITLE
Mathbox: generalized class abstractions.

### PR DESCRIPTION
**Pull request by benjub**

### CODE REVIEW

**Review by sctfn — APPROVED** [review]

**Comment by benjub** [comment]
@tirix @digama0 There is an error detected by metamath swiss-knife in lines that haven't changed.

This might be due to my introduction of the syntax axiom
```
  bj-cgab $a class { A | x | ph } $.
```
which does not make the grammar ambiguous, but probably requires a larger look-ahead ?

**edit:** well, it looks like there are unbounded ambiguous prefixes now, so maybe a simple fix won't suffice.  I can still add a new token `{{` if necessary.

**Comment by CatsAreFluffy** [comment]
In the comment of ~ bj-pm11.53vw, "theorem" is misspelled as "theorme".

**Comment by benjub** [comment]
> @tirix @digama0 There is an error detected by metamath swiss-knife in lines that haven't changed.
> 
> This might be due to my introduction of the syntax axiom
> 
> ```
>   bj-cgab $a class { A | x | ph } $.
> ```
> 
> which does not make the grammar ambiguous, but probably requires a larger look-ahead ?
> 
> **edit:** well, it looks like there are unbounded ambiguous prefixes now, so maybe a simple fix won't suffice. I can still add a new token `{{` if necessary.

@tirix @digama0 : I finally decided to use new tokens `{{` and `}}` to permit parsing and to merge this MR, but the "problem" (I think it is one?) of metamath swiss-knife remains.

**Comment by digama0** [comment]
As the error message says, this is an unimplemented part of the algorithm. I will leave it to @tirix to see whether a `garden_path` directive can resolve the issue, or whether code changes are necessary. (LALR parsers will not help here, set.mm is not LALR(k).)

**Pull request merged**
