### PR TITLE
Add intuitionization section to mmil.html

### PR DESCRIPTION
**Pull request by jkingdon**
This is the text which has been hanging out at #594 for a while.

@david-a-wheeler Do you have any comments on how to format this? I know you've been doing things with `.raw.html` files but I didn't fully understand how to work with them.

There's also a small change to add a few entries to the list of sample theorems.

### CODE REVIEW

**Comment by nmegill** [comment]
Nice writeup!

**Comment by jkingdon** [comment]
> Nice writeup!

The perfectionist in me keeps wanting to tweak it (maybe make it more explicit in places, maybe more references to examples in others). But on the whole, I agree, I'm relatively satisfied with this as a summary. I'd be glad to hear reactions, especially from people who are trying to use it to write proofs.

**Comment by nmegill** [comment]
@jkingdon Since you have a lot of labels mentioned in your writeup, you may want to use @david-a-wheeler 's scripts (that are run once) to convert mmil.html to mmil.raw.html, then use the 'markup' command in metamath.exe to create mmil.html from it, keeping mmil.raw.html as the master.  David did this for mmset.html, letting us maintain with \` math \` and ~ label markup, and 'markup' will also make sure all labels and math symbols are consistent with iset.mm.  I'm sure you'll find mmil.html much easier to maintain with this, as I did for mmset.html (e.g. the recent axiom renumbering).

The 'linkify.py' script will convert existing label hyperlinks to ~ label.  David, what is the script to convert math symbols to \` ... \` ?  I notice that mmil.html uses Unicode symbols; does it work for them?  (If not, it shouldn't be too hard to do manual search and replace, but existing ones can be left as-is I suppose, at least temporarily.  An advantage to converting is that it will use the same XITS font as on the theorem pages.)

**Comment by jkingdon** [comment]
> @jkingdon Since you have a lot of labels mentioned in your writeup, you may want to use @david-a-wheeler 's scripts (that are run once) to convert mmil.html to mmil.raw.html

I've made a stab at this at https://github.com/metamath/set.mm/pull/740

**Pull request merged**
