### PR TITLE
1kp2ke3k

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Add a new proof to David A. Wheeler's mathbox: 1kp2ke3k, 1000+2000=3000.

### CODE REVIEW

**Comment by sorear** [comment]
I advocate squash merges for things like this.  It'll be less of an issue once we have multiple files but for now we need to watch the number of commits which are generated.

**Comment by digama0** [comment]
I squash merged this using GitHub's built in web interface. David, be sure that you don't keep working on the old commits after a squash merge into develop, though.

**Comment by david-a-wheeler** [comment]
Sure.  I thought it'd be helpful to keep the old pre-minimized version, but no worries.

**Comment by digama0** [comment]
The arithmetic algorithm now built into mmj2 yields a significantly shorter proof:

      1kp2ke3k $p |- ( ; ; ; 1 0 0 0 + ; ; ; 2 0 0 0 ) = ; ; ; 3 0 0 0 $=
        ( c1 cc0 cdc c2 c3 1nn0 0nn0 deccl 2nn0 eqid 2cn ax-1cn 2p1e3 addcomli 00id
        decadd ) ABCZBCZBDBCZBCZBEBCZBCBRBCZTBCZQBABFGHZGHGSBDBIGHZGHGUBJUCJQBSBUAB
        RTUDGUEGRJTJABDBEBQSFGIGQJSJDAEKLMNOPOPOP $.

Since it's a same day revision, which confuses the dating, as well as possibly changing the comment, I'll let you decide how to apply the change.

**Comment by david-a-wheeler** [comment]
I'll do it tomorrow so the dates differ.

**Comment by david-a-wheeler** [comment]
> The arithmetic algorithm now built into mmj2 yields a significantly shorter proof:

Hmm. Looks like I need to update my version of mmj2.

--- David A.Wheeler

**Pull request merged**
