### PR TITLE
Added inner product to the "image structure" imas and "product struct…

### PR DESCRIPTION
**Pull request by tirix**
This pull request changes the ~ df-imas and ~ df-prds definitions to also construct the inner product fields.

The idea is to be able to use this to advance towards #52 : the development of RR^n.
I had to move gsum and 0g all the way up before ~ df-prds is defined. Is that an issue? Any hint about how to avoid that this kind of definitions land far away from the chapter they belong to?

### CODE REVIEW

**Comment by tirix** [comment]
I realise now my definition of the inner product for the structure image does not make any sense. 
I may update it by requiring < f(p) | f(q) > = < p | q >, i.e. that f is an isometry.

**Comment by tirix** [comment]
This pull request is now fixed and can be merged from my point of view, but review is welcome!

**Comment by benjub** [comment]
@tirix Skimming through your changes, I noticed that the term "scalar product" is sometimes used for "scalar multiplication".  There are many occurrences of "scalar product" in set.mm, sometimes to mean "inner product" (it is a legit synonym), and sometimes, ambiguously, to mean "scalar multiplication".  Maybe we should retain from using "scalar product", and use only "inner product" and "scalar multiplication".  Do @nmegill and @digama0 agree ?

**Comment by benjub** [comment]
@tirix As for the image structure: inner products, being forms, are things that you "pull back", not that you "push forward", so you can define the inverse image but not the direct image.  I don't know what metamath requires for inner products, but for instance, the pullback of a definite form is definite if and only if the function f is injective.  In particular, if f is a linear bijection, then you can also define the direct image (pullback by the inverse of f).

**Comment by tirix** [comment]
@benjub I see, thanks! Actually, the reason why I also changed the "image structure" is that the theorem ~ imasvalstr is used both both for the image structure and the product structure, because both structure have the same arguments.
I thought it would be best to keep the parallel. If it does not make sense, I can roll back the changes for the image product (df-imas). The theorem ~ imasval will have to be duplicated for the product structure.

**Pull request merged**
