### PR TITLE
Hull

### PR DESCRIPTION
**Pull request by benjub**
Add to mathbox:
* finite summation in commutative monoids,
* field of real numbers, class of real vector spaces.

### CODE REVIEW

**Comment by tirix** [comment]
@benjub I believe we already have ` CMnd ` for the commutative monoids.

I did not read your finite sum in detail. Why couln't ` gsum ` be used for that?

**Comment by benjub** [comment]
@tirix I did use CMnd (I had added ComMnd in an intermediate commit because I had missed CMmnd, but then I saw it and used it in subsequent commits).
As for df-gsum, I missed it (I google-searched "site/us.metamath.org monoid" and things like that but did not find it).  I'll have to have a look. It should be equivalent (the goal is indeed the same) but df-gsum looks harder to understand...

**Comment by tirix** [comment]
Great! 
I think ` gsum ` is a bit more general, as it handles both commutative and non-commutative monoids.

Also, maybe you could also consider using ` CVec ` for your ` RRVec `. There are already many theorems which can be reused.

(PS. Yes, I also saw you backed up on the ` CMnd ` , and edited my comment!)

**Comment by nmegill** [comment]
> As for df-gsum, I missed it (I google-searched "site/us.metamath.org monoid" and things like that

I assume you meant "site:us.metamath.org monoid" which gives much better results.

Also, in metamath.exe you can type "search * monoid /comment" which gives about 250 results, the 2nd of which is df-gsum.

**Pull request merged**
