### PR TITLE
Add scripts/typeset.py

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Add a simple script to apply an mmfile typeset rules to an arbitrary file.

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by nmegill** [comment]
Is this meant to replace the 'markup' command we discussed for metamath.exe?  Do you still want that command?

**Comment by david-a-wheeler** [comment]
It *was* meant to replace the markup command.  However, I've now realized that mmset.html does a lot more than this. In particular, in its display of this:

~~~~
2p2e4 <- 2cn <- 2re <- 1re <- axrrecex <- recexsr <- sqgt0sr <- pn0sr <- distrsr <- dmaddsr <- addclsr <- addsrpr <- enrer <- addcanpr <- ltapr <- ltaprlem <- ltexpri <- ltexprlem7 <- ltaddpr <- addclpr <- addclprlem2 <- addclprlem1 <- ltrnq <
~~~~

It uses backquotes (yikes) and refers to summarized titles.

I think typeset.py is useful... but if we want *that* information, a little Python script won't cut it. Hmm.  Thinking.

**Comment by nmegill** [comment]
These are just a blind copy of the truncated description to display in the tooltip, to give the user a quick hint about the linked theorem.  There is no attempt to translate the markup, nor do we have any plans to do that.

You can just permanently change them to ' (regular quote), before adding any markup, so as not to interfere with the markup translation.  When I regen the 2+2 trivia list I'll just have to remember to do that.

Norm

**Comment by david-a-wheeler** [comment]
Oh, I see. Instead of hand doing it, I suggest copying that part into a file.  We can then translate pieces and concatenate them all together. That way it can be done automatically.

I think for my test cases I should start with something simpler than mmset.html. That is a big file.

**Pull request merged**
