### PR TITLE
Addmathbox

### PR DESCRIPTION
**Pull request by emmett-w**
I would like to add my mathbox to the metamath repository. This is my first time publishing my mathbox, so please let me know if there are any conventions I need to follow that I'm not following already.

Thank you!

### CODE REVIEW

**Comment by nmegill** [comment]
Thank your for your contribution.  There are a few small changes we would like you to make.

We have been placing the mathboxes in alphabetical order by last name, so your mathbox should go before David A. Wheeler's.

Some of your proofs aren't in compressed format.  To make sure all proofs in your mathbox are compressed, you can do
```
MM> save proof nfintd~elpg /compressed
```

You should then run the commands shown at
https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md ,
specifically,
```
./metamath
MM> read set.mm
MM> write source set.mm /rewrap
MM> erase
MM> read set.mm
MM> save proof */compressed/fast
MM> verify markup */file_skip/top_date_skip
MM> verify proof *
MM> write source set.mm
MM> quit
```
This will ensure a standard formatting for set.mm so that future PRs by others won't result in large reformatting changes in your mathbox.  In particular, make sure that the "verify markup" command does not produce any warnings, which would cause the CI to fail.  (Note that the `/fast` qualifier on `save proof *` above does not actually re-compress - which takes a longer time and we assume was done previously - but just reformats existing proofs, whether compressed or not, into compressed style to ensure a standard indentation and wrapping.)

Thanks!

**Comment by emmett-w** [comment]
This seems to have no markup errors, but the verify markup command on my computer aborts even on the set.mm file without my addition.

In the middle of "Checking bibliographic comments...", I get an error message saying "Illegal instruction: 4." I think this is an issue with something else on my computer though and not the set.mm file.

Please let me know if I need to change anything else or if you happen to know how to fix the error. Thank you!

**Comment by nmegill** [comment]
> This seems to have no markup errors, but the verify markup command on my computer aborts even on the set.mm file without my addition.
> 
> In the middle of "Checking bibliographic comments...", I get an error message saying "Illegal instruction: 4." I think this is an issue with something else on my computer though and not the set.mm file.

I haven't seen this error message before.  It isn't an error message produced from within metamath.exe.  I tried this with your set.mm on both the lcc (precompiled) and gcc versions of metamath (version 0.198 7-Aug-2021) and couldn't reproduce it.  Does it seem to depend on previous commands run in the metamath session?  Did you use the precompiled Windows version, or did you use gcc and if so what platform and compilation options?

If you can find a reproducible test case, that would be great, since it sounds like a serious bug if it is not a hardware issue.

> Please let me know if I need to change anything else or if you happen to know how to fix the error. Thank you!

The CI run failed because nfsetrecs has an incomplete proof.  That will need to be fixed (by completing the proof or commenting it out).

**Comment by david-a-wheeler** [comment]
What operating system (OS), OS version, computer, and CPU are you using?

I did a Google search on the error. This appears to be a problem on MacOS at least, where the OS cannot run the binary for some reason. One potential cause is compiling on MacOS with one version, and then trying to run the resulting binary on an older version of the operating system (you may need to rerun the compiler, or add flags, to make that work). For some discussion see:

> https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

**Comment by nmegill** [comment]
set.mm itself has now passed the CI, but there was a mismatch in the "discouraged" file.  You should regenerate it per the instructions at https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md

**Comment by emmett-w** [comment]
> set.mm itself has now passed the CI, but there was a mismatch in the "discouraged" file. You should regenerate it per the instructions at https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md

I'm using Mac OS, and the instructions at that link didn't change the set.mm file. Is there something I need to do differently on a Mac?



> What operating system (OS), OS version, computer, and CPU are you using?
> 
> I did a Google search on the error. This appears to be a problem on MacOS at least, where the OS cannot run the binary for some reason. One potential cause is compiling on MacOS with one version, and then trying to run the resulting binary on an older version of the operating system (you may need to rerun the compiler, or add flags, to make that work). For some discussion see:
> 
> > https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

That sounds like it could definitely be what's causing the error on my computer. I'm using macOS Big Sur version 11.0.1. The processor is a 1.1 GHz Quad-Core Intel Core i5. Thank you again for your help.

**Comment by nmegill** [comment]
> > set.mm itself has now passed the CI, but there was a mismatch in the "discouraged" file. You should regenerate it per the instructions at https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md
> 
> I'm using Mac OS, and the instructions at that link didn't change the set.mm file. Is there something I need to do differently on a Mac?

No, there should be nothing different on a Mac.  The commands under "Regenerating the discouraged file" do not affect set.mm.  They generate a file whose name is "discouraged", that needs to checked in along with set.mm.  The purpose of the file is to allow easier identification of usage or proof modification for statements with "is discouraged" tags in their comments, so the user can make sure that the usage or proof modification was intentional and not accidental.

Normally metamath.exe and mmj2 will prevent the accidental usage or proof modification of "is discouraged" statements unless (in metamath.exe) a `/override` qualifier is present:
```
MM> prove imp4aOLD
>>> ?Error: Modification of this statement's proof is discouraged.
>>> You must use PROVE ... / OVERRIDE to work on it.
MM> prove imp4aOLD /override
Entering the Proof Assistant.  HELP PROOF_ASSISTANT for help, EXIT to exit.
You will be working on statement (from "SHOW STATEMENT imp4aOLD"):
1924 imp4.1 $e |- ( ph -> ( ps -> ( ch -> ( th -> ta ) ) ) ) $.
1927 imp4aOLD $p |- ( ph -> ( ps -> ( ( ch /\ th ) -> ta ) ) ) $= ... $.
Note:  The proof you are starting with is already complete.
>>> ?Warning: Modification of this statement's proof is discouraged.
MM-PA>
```

**Comment by emmett-w** [comment]
Got it, thank you.

**Pull request merged**
