### PR TITLE
Expand extended reals in iset.mm

### PR DESCRIPTION
**Pull request by jkingdon**
This is the section "Infinity and the extended real number system (cont.)" from set.mm. Most parts of the section are intuitionized (or not) on their own merits theorem-by-theorem, but we omit pretty much all theorems related to addition and multiplication, but merely add those to the missing theorems list in mmil.html (with a note saying why).

### CODE REVIEW

**Comment by jkingdon** [comment]
The travis build is failing because of problems on the `develop` branch. Once those are fixed on `develop`, I can rebase this branch to get those fixes.

**Comment by jkingdon** [comment]
Looks like the fix has already been submitted as #1553 so it should just be a matter of merging that.

**Comment by arpie-steele** [comment]
The Travis PR builds weren't updating GitHub 8-9 hours ago, so those failures were hard to navigate to. Everything seems to be working now.

**Comment by nmegill** [comment]
The Travis link seems to be working again, and Travis check failed.  It might have been due to an earlier PR without a Travis check, but could you fix it anyway?  Thanks.

**Comment by jkingdon** [comment]
> The Travis link seems to be working again, and Travis check failed. It might have been due to an earlier PR without a Travis check, but could you fix it anyway? Thanks.

Yes, now that the fix for #1553 is merged I needed to rebase this branch to include those changes. I have done so and Travis is now passing.

**Pull request merged**
