### PR TITLE
Rename syl6eq to eqtrdi

### PR DESCRIPTION
**Pull request by jkingdon**
This is in set.mm and iset.mm

### CODE REVIEW

**Review by tirix — APPROVED** [review]
I did not check all 5000 lines, just blindly trusting Jim here.

**Review by GinoGiotto — APPROVED** [review]
Checked by creating a copy with VS Code search and replace feature. The diff was zero.

**Comment by tirix** [comment]
That's much better!

**Comment by wlammen** [comment]
I checked all lines by shortly glancing at it, to see whether something unexpected was pushed.

This pull request could have been split in two halves, by moving syl6eqr unchanged to the end of main, and then perform the replacement in the first half first, and proceed with the rest in a second PR.

**Review by wlammen — APPROVED** [review]

**Comment by jkingdon** [comment]
Thanks to all the reviewers.

As for splitting it, I guess maybe I will if there is another one this big. I haven't checked the size of the remaining proposed changes but I suppose some of them are probably also large.

**Pull request merged**
