### PR TITLE
shortenings of proofs

### PR DESCRIPTION
**Pull request by avekens**
* many proofs were shortened using the theorems moved to main with PR #3034 (see the first 7 commits), using the minimize script (no new axiom dependencies created).
* some proofs (only in AV's mathbox) were shortened according to Igor's list in the Google group (https://groups.google.com/g/metamath/c/B9_PEy8YjU4/m/JCJPdz_RAQAJ), see the last 2 commits. There are, however, some proofs in his list which are not shorter than the original (at least not after storing them in compressed format by metamath.exe - there are actually differences in the representations!).

### CODE REVIEW

**Comment by benjub** [comment]
> * There are, however, some proofs in his list which are not shorter than the original (at least not after storing them in compressed format by metamath.exe - there are actually differences in the representations!).

This is why I did #3046 before we go into that list.

The cases you mention in that quoted sentence are not part of this MR, correct ?

**Comment by avekens** [comment]
> The cases you mention in that quoted sentence are not part of this MR, correct ?

Yes, only proofs which are actually shortened are part of this PR.

**Comment by benjub** [comment]
Can you try and merge `develop` into your branch (without wasting time on resolving conflicts) ?  The difffs look huge, probably because of merging other PRs in the meantime.

**Comment by avekens** [comment]
> Can you try and merge `develop` into your branch (without wasting time on resolving conflicts) ? The difffs look huge, probably because of merging other PRs in the meantime.

The differences ARE huge, there are a lot of shortened proofs. Here is a summary (of the comments of the single commits):
* 179 proofs shortened using ~fvmptd3, saving 6020 bytes in total.
* 60 proofs shortened using ~xpexd, saving 944 bytes in total.
* 7 proofs shortened using ~fassraddsubd, saving 75 bytes in total.
* 3 proofs shortened using ~addgtge0d, saving 100 bytes in total.
* 30 proofs shortened using ~mvrladdd, saving 928 bytes in total.
* 110 proofs shortened using ~rexlimdva2, saving 1412 bytes in total.
* 71 proofs shortened using ~1xr, saving 559 bytes in total.

These changes are purely the results of the minimize script. My branch is based on a very recent (I think actually the latest) develop-branch.

**Comment by benjub** [comment]
Thanks for these details. If I understand correctly, then apart from the 2 commits related to Igor's work, everything was done by `minimize_with` so did not introduce new axiom dependencies ? Only Igor's shortenings have to be checked ? Did you do it ?

More generally (to e.g. @digama0, @tirix): how easy/useful would it be to have the CI check/warn if dependencies were added in any proof in an MR ? (by comparing the outputs of `show trace xxx /axioms` for all `xxx` modified by the PR) ?

**Comment by avekens** [comment]
> Thanks for these details. If I understand correctly, then apart from the 2 commits related to Igor's work, everything was done by `minimize_with` so did not introduce new axiom dependencies ?

Yes, that's true.

> Only Igor's shortenings have to be checked ? Did you do it ?

I modified proofs of/in my mathbox only, where I do not care about axiom dependencies. I think only formal stuff shall be checked in the last commits, if at all. This should be possible with little effort (for a reviewer).

**Review by benjub — APPROVED** [review]
Approved. This is because I "trust" Alexander that he did these minimizations properly.

I think in the future it would be nice to have a way to "have the CI check/warn if dependencies were added in any proof in an MR (by comparing the outputs of `show trace xxx /axioms` for all `xxx` modified by the PR) " as I wrote above.

**Comment by avekens** [comment]
> I think in the future it would be nice to have a way to "have the CI check/warn if dependencies were added in any proof in an MR (by comparing the outputs of `show trace xxx /axioms` for all `xxx` modified by the PR) " as I wrote above.

In principle, this is a good idea, but we have to consider cases in which it is intended to add/modify the dependencies. See also the discussion about modifications in mathboxes  elsewhere.

**Comment by benjub** [comment]
> In principle, this is a good idea, but we have to consider cases in which it is intended to add/modify the dependencies. See also the discussion about modifications in mathboxes elsewhere.

The idea is to have the information, so that for instance for the present PR, I would run the tool, I would see that no axiom dependencies were added, and I would more confidently approve the request.

**Comment by wlammen** [comment]
I checked all proofs in main (but not the mathboxes) from the first commit.  In all cases the number of proof lines shrank by at least 1 line, and the axiom usage did not change.

I created web pages from both the current develop branch and the one given by this PR.  I viewed all affected theorems by overlapping web pages of corresponding theorems in the branches, and rapidly flipping between them.  Since the beginning and end of a page in this procedure are in the same location on the screen, differences catch the eye.  So this is an effective means of ensuring:
1. Hypotheses did not change;
2. DV conditions did not change;
3. Proof line count differs (This is only a strong indication of a true shortening, so I randomly checked a couple of byte counts as well);
4. The axiom list did not change.

This method is effective enough to spot differences in the Syntax list.  For example, the old version of lcmfval uses cmpt in its proof, the new one not.

This is about what I can achieve within 2 hrs.  Hopefully this helps a bit in deciding how to proceed with this PR.  It would be helpful for review (at least for me) if this PR was split into smaller portions.

**Comment by benjub** [comment]
I wish I could put two "thumbs up" to @wlammen's above comment ! Thanks a lot.

**Comment by avekens** [comment]
> This is about what I can achieve within 2 hrs. Hopefully this helps a bit in deciding how to proceed with this PR. It would be helpful for review (at least for me) if this PR was split into smaller portions.

Thank you very much, Wolf, for your thorough review. To spend 2 h, however, seems to be a lot for such a technical PR. Especially because most of the changes were performed automatically by the minimize script. I expected that only the smaller commits at the end needed to be reviewed, and I could have separated them out in another PR. But this would not have solved the problem that a reviewer had to "trust me": that I actually run the script only. Therefore, tool support as discussed by @benjub and @tirix, would be helpful.

**Comment by david-a-wheeler** [comment]
We definitely need better tooling for this. The verifiers currently only look at "current state" instead of comparing state. There's probably a way to do that, I just haven't checked.

I tip my hat to @wlammen - that was a lot of work for those reviews! Thank you, profusely!

**Pull request merged**
