### PR TITLE
Switch from +c to |_| from djulepw  to pwdjudom

### PR DESCRIPTION
**Pull request by jkingdon**
This is pretty similar to other pull requests in this series.

I guess the main thing which this one has is a number of cases where the use of `+c` can be removed, because we have enough of the `|_|` theorems and we're starting to get to theorems which use the disjoint union within the proof but not in the result.

### CODE REVIEW

**Review by wlammen — APPROVED** [review]
All revised theorems seem now be free of +c.  I tried my best to check this.

**Comment by jkingdon** [comment]
> All revised theorems seem now be free of +c. I tried my best to check this.

The discouragement tags should also help track this, but thanks for looking as well.

**Comment by wlammen** [comment]
Couldn't it sneak in, as part of a used theorems proof not exposing this operation on the outside (hypothesis / conclusion)?

**Comment by jkingdon** [comment]
> Couldn't it sneak in, as part of a used theorems proof not exposing this operation on the outside (hypothesis / conclusion)? 

I guess so (depending on various assumptions about whether I miss a theorem to mark and how we look at the diff to the discouraged file).

**Pull request merged**
