### PR TITLE
Add apdiff to iset.mm mathbox

### PR DESCRIPTION
**Pull request by jkingdon**
This is a way of characterizing irrationals as exactly those reals that are a different distance from every rational:

```
    apdiff $p |- ( A e. RR -> ( A. q e. QQ A =//= q <-> A. q e. QQ A. r e. QQ
        ( q =/= r -> ( abs ` ( A - q ) ) =//= ( abs ` ( A - r ) ) ) ) ) $=
```

### CODE REVIEW

**Review by tirix — APPROVED** [review]
NIce! Would it make sense to have a set.mm version?

**Comment by jkingdon** [comment]
> NIce! Would it make sense to have a set.mm version?

I'm working on one. Might be another few days as my idea is to make a more streamlined proof than is possible in iset.mm.

**Comment by jkingdon** [comment]
Oh I should also mention the post where I saw this theorem stated: https://mathstodon.xyz/@ColinTheMathmo/112455490217662534

**Review by avekens — APPROVED** [review]

**Comment by tirix** [comment]
> Might be another few days as my idea is to make a more streamlined proof than is possible in iset.mm.

Can we merge this first?

**Comment by jkingdon** [comment]
> > Might be another few days as my idea is to make a more streamlined proof than is possible in iset.mm.
> 
> Can we merge this first?

Merging this one now sounds good to me.

**Pull request merged**
