### PR TITLE
Minor changes in my Mathbox (former "eqbrrdv2 to the main")

### PR DESCRIPTION
**Pull request by mazsa**
from the Mathbox of Rodolfo Medina. I'd need this to my Mathbox-only #3301 PR. Cf. https://github.com/metamath/set.mm/pull/3301#issuecomment-1643795997 of @wlammen

### CODE REVIEW

**Comment by benjub** [comment]
As @wlammen wrote in https://github.com/metamath/set.mm/pull/3301#issuecomment-1643795997 it would probably be better to prove the "standard" (according to our conventions in set.mm) deduction forms of both eqrel... and eqbrr... and remove the other forms. No need to have a plethora of very similar theorems at this more advanced stage of set.mm. The labels could probably be simplified too. Since this is really extensionality, labels could be as simple as ~extrel and ~extbr.

**Comment by mazsa** [comment]
Oh I've quite misread that https://github.com/metamath/set.mm/pull/3301#issuecomment-1643795997 : it is clear but I simply didn't succeed to parse it fully because of my predisposition to push this theorem to the main, sorry @wlammen . @benjub thank you for the second chance.

Ad extensionality: I'm interested in it. I have some theorems and comments around this concept, some of them are even public (cf. ~ extid , ~ extep , ~ extssr and the comment of ~ df-ssr . I have even  ~ eqrel2 , related to ~ eqrel... above). But I'm not yet ready to define it / a more general concept (of course in a way which is aware of ~  axext4 ), and, based on that, rethink, reorganize and perhaps even relabel the related theorems in the main. The problem is that I didn't find the main theorem yet that could ex post justify/verify my related definitions. But I will return to this task as soon as I am ready for it.

And in the short term, I'll take one of Wolf's suggestions. And I will withdraw this pull request in 1-2 days (I will wait a bit to see if there is any reaction).

**Comment by jkingdon** [comment]
> And in the short term, I'll take one of Wolf's suggestions. And I will withdraw this pull request in 1-2 days (I will wait a bit to see if there is any reaction).

I guess my reaction is just that we should have some version of https://us.metamath.org/mpeuni/eqbrrdiv.html (a theorem currently in main) which is in closed or deduction form.

Not sure I have an especially strong opinion about which way(s) to do this.

**Comment by mazsa** [comment]
I think I'm ready. I left a clean commit history (did not squash and merge commits but rebased PRs merged in between) in order to reveal what happed: I deleted my first and second commit, reproved and shortened erim2 in my Mathbox based on a theorem, eqbrrdv, which was already in the main, and deleted the superfluous temporary eqbrrdv2TEMP from my Mathbox. 

Net changes: nothing outside of my Mathbox. Perhaps it needs a mathbox only label before merging.

To do: https://github.com/metamath/set.mm/pull/3304#issuecomment-1644457149 if and when I'm (or anybody is) ready to reorganize (and perhaps further develop) theorems related to extensionality.

**Review by wlammen — APPROVED** [review]

**Comment by jkingdon** [comment]
> I left a clean commit history (did not squash and merge commits but rebased PRs merged in between) in order to reveal what happed: I deleted my first and second commit, reproved and shortened erim2 in my Mathbox based on a theorem, eqbrrdv, which was already in the main, and deleted the superfluous temporary eqbrrdv2TEMP from my Mathbox.

So usually people merge with "Squash and merge" so a single pull request ends up being a single commit when it is merged.

Sometimes I merge with "Rebase and merge" (or talk other people into doing so) but I haven't been doing that to show the kind of history you describe above (which is largely a history of paths not taken) but in order to break down the changes (for example, maybe individual theorems rather than a whole section).

I guess I'll "Squash and merge" this in a while if there is no objection.

**Comment by mazsa** [comment]
[ @jkingdon I'm experimenting with these. I broke https://github.com/metamath/set.mm/pull/3301 PR down into functional commits in order to facilitate sequential parsing (I think @wlammen wrote somewhere that he prefers smaller commits/PRs which he can review even in his free time of a quarter of an hour). In case of this PR it was more important that for everybody who already went deeper into the story I needed to be transparent what happened to the original "eqbrrdv2 to the main" PR: this was the reason of the less functional more historic organization of the commits. Interesting that we can present entirely different approaches / "storylines" with our commits. ]

**Comment by jkingdon** [comment]
> I'm experimenting with these.

It's all good. There is no universal consensus about how to use git, and all the more so with metamath, where people range from using git all the time, to not having seen it before contributing to metamath. Experiment away!

**Pull request merged**
