### PR TITLE
Cramer's rule

### PR DESCRIPTION
**Pull request by avekens**
- Mathbox for TA: Theorems ovif, ovif2, ovif12 moved to main part
- Mathbox for SO: Theorems from SO's determinants-1 branch added
- Mathbox for AV: Proof of Cramer's rule (~ cramer ) and other theorems for matrices and their determinants.

### CODE REVIEW

**Comment by nmegill** [comment]
Congratulations on achieving this!  I added an item to the Most Recent Proofs page that will show up after the site rebuild in ~4 hours.

@david-a-wheeler could you update mm_100.html (it is in GitHub set.mm now)?  Thanks.

**Comment by david-a-wheeler** [comment]
@avekens - CONGRATS!

@nmegill - I'll add it to mm_100.html with pleasure :-) !

**Comment by david-a-wheeler** [comment]
I've added this to the mm_100.html file and the related Google docs graph, and have also sent an email to Freek to let him know. Nice job!!

**Comment by nmegill** [comment]
@david-a-wheeler I need a pull request for mm_100.html so I can upload it to the site.

**Comment by david-a-wheeler** [comment]
@nmegill ... it's ready for you, see #763  !

**Pull request merged**
