### PR TITLE
fix download-metamath script for github changes

### LINKED ISSUE #3444: CI can't download symbols.tar.gz
Something appears to have changed which is breaking the master build: https://github.com/metamath/set.mm/actions/runs/6005609380/job/16288830886

I believe the issue is https://github.com/orgs/community/discussions/65227 .

### PR DESCRIPTION
**Pull request by digama0**
fixes #3444

### CODE REVIEW

**Review by benjub — APPROVED** [review]

**Comment by benjub** [comment]
I think it's good, although I'm not sure if TLS 1.2 is "secure enough" or should be replaced with TLS 1.3.

**Review by jkingdon — APPROVED** [review]

**Comment by jkingdon** [comment]
> I think it's good, although I'm not sure if TLS 1.2 is "secure enough" or should be replaced with TLS 1.3.

I guess `TLSv1_3` would make sense although `TLSv1_2` is clearly an improvement over the default.

I'm looking at https://github.com/orgs/community/discussions/65227#discussioncomment-6846944

**Comment by jkingdon** [comment]
Seemed worth merging now to get things passing again.

**Comment by david-a-wheeler** [comment]
I'm hoping in the long-term we can find a better solution - maybe changing the header to say "I'm not wget". But working is better than not-working.

**Pull request merged**
