### PR TITLE
Graph theory - closed walks as word (15)

### PR DESCRIPTION
**Pull request by avekens**
General:
* ~rabrab and ~fz1ssfz0 moved from mathboxes
* new theorems ~rabeqc, ~swrdfv0, ~ccatval21sw, ~fzoun added

Graph theory - closed walks:
* comments improved
* ~extwwlkfablem revised (setvar variable replaced by class variable)
* theorems ~numclwwlkovg (renamed ~2clwwlk), numclwwlkovgel (renamed ~2clwwlkel), ~numclwwlkovh, ~numclwwlk2lem1, ~numclwlk2lem2f, ~numclwlk2lem2fv, ~numclwlk2lem2f1o, ~numclwwlk2lem3, ~numclwwlk2, ~numclwwlk3lem revised
* new theorems ~clwwlknonex2e, ~2clwwlk2clwwlklem1, ~2clwwlk2clwwlklem2lem1, ~2clwwlk2clwwlklem2lem2,  ~2clwwlk2clwwlklem2, ~clwwlkccatlem, ~clwwlkccat, ~clwwlknccat, ~clwwlknonccat, ~2clwwlk2clwwlk, ~numclwwlkovh0, ~numclwwlk3lemlem added
* theorem ~extwwlkfab2 removed

### CODE REVIEW

**Comment by avekens** [comment]
There are 32 proofs which can be shortened using ~fz1ssfz0! I will do it in a follow-up PR.

**Comment by avekens** [comment]
Could anybody review/merge this PR, please? 

It is essentially about using the new definition ClWWalksNOn for closed walks of fixed length on a fixed vertex (introduced by PR #2533) in local definitions C (double loops of fixed length on a fixed vertex) and H ("closed n-walks v(0) ... v(n-2) v(n-1) v(n) from v = v(0) = v(n) ... with v(n-2) =/= v" according to definition 7 in [Huneke]).

In addition, some theorems for concatenated walks by concatenating two words representing walks are provided (~clwwlknonex2e, ~clwwlkccat, clwwlknccat, ~clwwlknonccat, ~2clwwlk2clwwlk).

**Review by tirix — APPROVED** [review]
Looks good to me!
I've been busy lately, I'm not as responsive as I used to...

**Comment by avekens** [comment]
@tirix  thanks a lot for acceptinmg my PR. I did not want to pu pressure on you (or anybody else), but I may have some time the next days which I can use to "improve" set.mm.

**Pull request merged**
