### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by benjub**
Mainly typos.
The set.mm diff is huge because the standard reformatting done by the "canonical" command indicated in https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md :
> ./metamath 'read set.mm' 'write source set.mm /rewrap' erase 'read set.mm' 'save proof */compressed/fast' 'verify markup */file_skip/top_date_skip' 'verify proof *' 'write source set.mm' quit

rewrapped most of @glacode 's recent theorems (I advise you to run this command before any PR).

### CODE REVIEW

**Comment by nmegill** [comment]
@glacode Will this be a problem for you?

**Comment by glacode** [comment]
> @glacode Will this be a problem for you?

Hi Norm,

I can't see the diff (github says it is too large).

I run the command

./metamath 'read set.mm' 'write source set.mm /rewrap' erase 'read set.mm' 'save proof */compressed/fast' 'verify markup */file_skip/top_date_skip' 'verify proof *' 'write source set.mm'

for each iteration of the candidate set.mm and after that, a further 'verify markup' that returns no warning. And even Travis (for the pull request) returned no markup error.

So I don't understand which further reformatting could have been applied.

Isn't passing Travis checks an indication of the formatting being fine?

Anyway, if benjub's update does just a (more) canonical formatting, of course I have no objection (as I wrote, I can't see the diff: as far as I understand, github doesn't show the diff because it is too large).

Best regards
Glauco

**Comment by benjub** [comment]
The reformatting is really "cosmetics", and both versions are correct. An example of what it does:
```
fourierdlem59 $p |- ( ph -> ( RR _D H ) e. ( ( A (,) B ) -cn-> RR ) ) $=
-      ( cr co wcel cc cdv cioo ccncf wf cdm wss cv caddc cfv cmin cdiv wa
-      elioore adantr adantl readdcld ffvelrnd resubcld eqcom biimpi simpl
-      eqeltrd adantll cc0 wceq ad2antrr pm2.65da neqned redivcld fmptd ioossre
-      dvfre syl2anc cmpt wn a1i cof cvv ovex recnd simpr eqidd offval2 eqcomd
-      3eqtrd oveq2d cpr reex prid1 eqid csn cdif wne eldifsn sylanbrc cncff syl
-      fourierdlem28 cxr clt cres wbr ioogtlb syl3anc ltadd2dd iooltub eliood
-      wb ioosscn ssid constcncfg rexrd idcncfg addcncf cncffvrn mpbird
-      ax-resscn fssd cncfcompt ccnfld ctopn crn ctg iooretop tgioo2 eleqtri
-      sseldi dvmptconst 0cn dvsubcncf c1 dvmptidg crest ax-1cn dvdivcncf fdm
-      feq2d mpbid ) 
```
is turned into
```
fourierdlem59 $p |- ( ph -> ( RR _D H ) e. ( ( A (,) B ) -cn-> RR ) ) $=
+      ( cr co wcel cc cdv cioo ccncf wf cdm wss cv cfv cmin cdiv adantr elioore
+      caddc wa adantl readdcld ffvelrnd resubcld cc0 eqcom biimpi simpl eqeltrd
+      wceq adantll wn ad2antrr pm2.65da neqned redivcld fmptd ioossre a1i dvfre
+      syl2anc cmpt cof ovex recnd simpr eqidd offval2 eqcomd 3eqtrd oveq2d reex
+      cvv cpr prid1 eqid csn cdif wne eldifsn sylanbrc cres cncff fourierdlem28
+      syl cxr rexrd clt ioogtlb syl3anc ltadd2dd iooltub eliood wb ioosscn ssid
+      wbr constcncfg idcncfg addcncf cncffvrn mpbird ax-resscn cncfcompt ccnfld
+      fssd ctopn crest crn ctg iooretop tgioo2 eleqtri dvmptconst 0cn dvsubcncf
+      sseldi c1 dvmptidg ax-1cn dvdivcncf fdm feq2d mpbid ) AQFUARZBCUBRZQUCRSZ

```

**Comment by glacode** [comment]
I agree, it's much better (maybe I used a slightly different command or I didn't launch it on the final version).

Absolutely, thumb up for the change!

Thanks Benjub
Glauco

**Pull request merged**
