### PR TITLE
Pare back proposed renames for syl

### PR DESCRIPTION
**Pull request by jkingdon**
With #4329 and #4320 we seem to be getting to the end of the currently proposed uncontroversial `syl` related renames. Therefore it seems good to have another round of discussion about what we want to do about the rest.

At issue are various theorems in the syl , syl5 and syl6 families.  The proposals being removed here seem like they don't fit naming patterns especially well and so it isn't clear that the proposals are really better than existing names.

Perhaps the hardest are syl , syl5 , and syl6 .  These were proposed to be renamed by Norm, and could very readily fit a naming convention ( imtri , imtrid , and imtrdi , respectively).  The biggest arguments for keeping the names syl , syl5 , and syl6 seem to be tradition and the question of whether we would be renaming every theorem whose name is built off those three (especially for syl it seems likely that we'll have theorems with syl in the name, as we haven't even talked about syl7 , syl9 , syl11 , the sylan* family, and various other cases).

For what it is worth the original proposal from Norm was:

```
proposed  syl       imtri       (analogous to *bitr*, sstri, etc.)
proposed  sylib     imbitri     etc.
proposed  sylbid    biimtrd     etc.
proposed  sylbird   biimtrrd    etc.
proposed  syl5*     *trid       (syl5bi -> biimtrid; syl5eqel -> eqeltrid;etc.)
proposed  syl6*     *trdi
```

### CODE REVIEW

**Comment by benjub** [comment]
I'm in favor of these changes. Furthermore, `syl` is traditionally used (outside of Metamath) to denote the closed form, and not the current `~syl`.

**Comment by jkingdon** [comment]
Let me more explicitly list the renames in question (in four groups):

1. Already underway or "obvious":

```
proposed  syl5bb    bitrid      compare to bitri or bitrd
proposed  syl5eq    eqtrid      compare to eqtri or eqtrd (in progress)
underway  sseldi    sselid      compare to sselii or sseldd
```

2. Proposed to be kept (and if this pull request is accepted, we'd expect to proceed with renaming them without the expectation of further discussion):

```
proposed  syld      imtrd
proposed  sylbi     biimtri
proposed  sylib     imbitri
proposed  sylibr    imbitrri
proposed  sylbir    biimtrri
proposed  sylibd    imbitrd
proposed  sylbid    biimtrd
proposed  sylibrd   imbitrrd
proposed  sylbird   biimtrrd
proposed  syl5bi    biimtrid
proposed  syl5bir   biimtrrid
proposed  syl5ib    imbitrid
proposed  syl5ibr   imbitrrid
proposed  syl6ib    imbitrdi
proposed  syl6ibr   imbitrrdi
proposed  syl6bi    biimtrdi
proposed  syl6bir   biimtrrdi
```

3. Now in changes-set.txt but this pull request would remove them as proposed renames (and presumably keep their current names):

```
proposed  syldc     imtrdcom
proposed  syldd     imtrdd
proposed  sylbb     bitriim
proposed  sylbbr    bitrriim
proposed  sylbb1    bitr3iim
proposed  sylbb2    bitr4iim
proposed  syl5com   imtridcom
proposed  syl56     imtridi
proposed  syl5d     imtridd
proposed  syl5ibcom imbitridcom
proposed  syl5ibrcom imbitrridcom
proposed  syl6com   imtrdicom
proposed  syl6d     imtrdid
```

4. The cans of worms. To be kicked down the road until the others have been dealt with. (Or if the English there is too idiomatic, the difficult cases that we may choose to tackle but only after we've handled the easier cases).

```
proposed  syl       imtri       (analogous to *bitr*, sstri, etc.)
                                there is less agreement on renaming syl
                                than others here
proposed  syl5      imtrid      alternate proposal: sylid
proposed  syl6      imtrdi      alternate proposal: syldi
```

**Comment by sctfn** [comment]
IMO, keep them all. Emphasizing transitivity seems a net win to me. Syl* seems like a massive abuse of the original meaning of syllogism.

**Comment by david-a-wheeler** [comment]
@sctfn - by "keep" do you mean "do a rename" or "don't change the names"? I'm guessing you meant "do a rename"?

**Comment by sctfn** [comment]
Sorry, yeah, I meant do a rename.

**Comment by jkingdon** [comment]
Would love to get a few more reactions. Also especially for group 3 above, suggestions for alternate names if we want to rename them but to something other than the current proposals.

So far sentiment seems to be in favor of closing this pull request unmerged and continuing with all the renames currently proposed (I guess groups 1,2,3,4 in that order), which is fine with me I just would love to get ideas especially if someone is smarter than me about the best names for the doubtful cases.

**Comment by wlammen** [comment]
I'm indifferent to the used naming scheme, as I have no theoretic background in logic, and so no built-in preferences or dislikes in this regard.  The Wikipedia page on [syllogism](https://en.wikipedia.org/wiki/Syllogism), as I understand it, is not exactly opposing the name syl.  On the other hand, I used [imtrdi](https://us.metamath.org/mpeuni/wl-luk-imtrdi.html)  already back in 2018, obviously in anticipation of a pending  immediate name change.

**Comment by icecream17** [comment]
I think the question of whether to change syl, syl5, or syl6 is in tandem with syld, syl5d, and syl6d, so by this logic group 4 would be in the same status as group 3 (or some of group 3 becomes part of group 4)

**Comment by jkingdon** [comment]
The discussion here seems to be in favor of all the proposed renames (groups 1, 2, 3, and 4).  Therefore, I will close this pull request, leave the proposed renames in `changes-set.txt` (they are already there), and plan on continuing to carry them out.

If people want to fine-tune this plan, please open a github issue, send a message to the mailing list, or send a pull request for specific proposals (probably in the form of edits to the proposals in `changes-set.txt`).

**Pull request closed without merging**
