### PR TITLE
unineqg

### PR DESCRIPTION
**Pull request by mazsa**

### CODE REVIEW

**Comment by icecream17** [comment]
Is unineqg going to be used?

**Comment by mazsa** [comment]
> Is unineqg going to be used?

Yes, I'll use it directly to show that
|- (  ( dom R = dom S /\ ran R = ran S ) -> ( ( ( dom R X. ran R ) \ R ) = ( ( dom S X. ran S ) \ S ) <-> R = S ) ) etc.

**Review by icecream17 — APPROVED** [review]

**Comment by mazsa** [comment]
@icecream17 I have changed the status of this PR to Draft, because I made a cut&paste mistake and gave the wrong answer to your question.

What I can prove with this is unfortunately not what I wrote (and would need), but

|- ( ( Rel R /\ Rel S ) -> ( ( ( dom R X. ran R ) \ R ) = ( ( dom S X. ran S ) \ S ) ->
      ( ( dom R X. ran R ) = ( dom S X. ran S ) <-> R = S ) ) )

(via my ~ relundmrn  |- ( Rel R -> ( R u. ( dom R X. ran R ) ) = ( dom R X. ran R ) ) )

The generalization is still valid and this still shows that there may be a use case for it, but it is far from what I intended it to be used for. What do you suggest what should happen next with this PR?

**Comment by icecream17** [comment]
If it's not going to be used, I guess closing or moving to a mathbox would be fine. It could always be added later

**Comment by mazsa** [comment]
@icecream17 thanks for your advice. I decided to close this, because I also do not like to see free floating theorems, even in my Mathbox.

**Pull request closed without merging**
