### PR TITLE
Move eldifpr and eldiftp from David A. Wheeler's mathbox to main body

### PR DESCRIPTION
**Pull request by david-a-wheeler**
These theorems handle elements of differences with two and three
elements removed.  There is already an existing eldifsn for singletons;
this commit adds the related theorems for pairs and triples.
Theorem eldifpr is actually by Mario Carneiro (as is noted in the comments).

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by tirix** [comment]
I would actually vote for moving those to the main part, they are possibly useful and are non-trivial.

**Comment by david-a-wheeler** [comment]
Sounds good to me, let's hear from Norm.

Merging this will require some trivial fixes now, because things have changed since I made this pull request, but those will be easy.

**Comment by nmegill** [comment]
OK, I'll go along with it.

**Comment by david-a-wheeler** [comment]
There are some merge conflicts.

I suspect it'll be easiest to redo this and create a new pull request. When I get a chance (probably tomorrow evening) I'll probably close this & create another pull request that does it.

**Comment by david-a-wheeler** [comment]
It appears this was already done by a different pull request. Presumably someone else wanted to use those theorems & pulled them in?  Anyway, it's already done, so I'll close this.

**Comment by avekens** [comment]
Thanks to everybody involved in cleaning up the "hanging" pull requests.
Maybe it was me who moved the two theorems (on12-Oct-18), I've been using ~eldifpr in my mathbox (~rexdifpr) since 2018.

**Comment by benjub** [comment]
Given the comment explaining the closing of this PR, I also delete the branch.

**Pull request closed without merging**
