### PR TITLE
Revert "add elovolmlem and automatic minimization of 11 proofs, each by about…"

### PR DESCRIPTION
**Pull request by wlammen**
Reverts metamath/set.mm#2705 if merged.

Please visit https://github.com/metamath/set.mm/pull/2705 to follow the original conversation and see the diff. I mistakenly merged that PR, and created this one later to allow an approval process again. Sorry for any inconvenience.

**You should merge this PR only, if #2705 is not approved. Otherwise just close it**

### CODE REVIEW

**Comment by wlammen** [comment]
Please visit #2705 to follow the conversation.  I mistakenly merged that PR, and reverted it later to allow normal procedures again.  Sorry fr any inconvenience.

**Comment by wlammen** [comment]
### @benjub introductionary comment:


Add elovolmlem, corresponding to the line

    35 0 ["reex","reex","xpex","inex2","nnex","elmap"]

in @savask's list at https://gist.github.com/savask/dce5b48b7317e8144635fda09e983fae (see thread https://groups.google.com/g/metamath/c/aXvD9rs36Ps). Automatic minimization of 11 proofs, each by about 40 bytes.

@savask : is there a way to update that list ? or maybe turn it into an Issue here, with checkboxes ?

**Comment by wlammen** [comment]
@benjub comment to commit [b69d193](https://github.com/metamath/set.mm/pull/2705/commits/b69d1935d3f19b6d398dc4ea2681d094a201a8d0), that was part of the original PR:

remove a duplicate from the list at https://github.com/metamath/set.mm/issues/2128.

**Comment by savask** [comment]
@benjub 

>is there a way to update that list ? or maybe turn it into an Issue here, with checkboxes ?

I assume you want to keep track of lemmata which were added in set.mm? I could turn it into an issue, but 120 checkboxes is too many, in my opinion, especially since we do not plan to add all of the suggested lemmata into set.mm.

I've added a comment to my gist mentioning which theorems ended in set.mm (right now it's only `toponrestid` as far as I understand). I will update the comment if I'm pinged in the pull request.

>remove a duplicate from the list at https://github.com/metamath/set.mm/issues/2128.

Great that you still remember about duplicates, it seems that issue was somehow abandoned.

**Comment by avekens** [comment]
What exactly was reverted to what, resp. was it successful? I had a look at the changed files, and it seems that Benoît's modifications are eliminated now (state before #2705). @benjub please check and clarify with @wlammen if necessary.

**Comment by avekens** [comment]
> I've added a comment to my gist mentioning which theorems ended in set.mm (right now it's only `toponrestid` as far as I understand). I will update the comment if I'm pinged in the pull request.

@savask I just added a comment that no. 34 and no. 48 will **not** be added to set.mm. Is this OK?

**Comment by savask** [comment]
>I just added a comment that no. 34 and no. 48 will not be added to set.mm. Is this OK?

Yes, sure.

**Comment by wlammen** [comment]
I checked out the iset.mm file in develop on github.  Line 86647 following look like this
```
  ${
    $d N f i j $.
    $( Elements of ` NN+oo ` corresponding to natural numbers.  The natural
       number ` N ` corresponds to a sequence of ` N ` ones followed by zeroes.
       Contrast to a sequence which is all ones as seen at ~ infnninf .
       Remark/TODO: the theorem sill holds if ` N = _om ` , that is, the
       antcedent could be weakened to ` N e. suc _om ` .  (Contributed by Jim
       Kingdon, 14-Jul-2022.) $)
    nnnninf $p |- ( N e. _om ->
        ( i e. _om |-> if ( i e. N , 1o , (/) ) ) e. NN+oo ) $=
```
That is, PR #2705 appears as merged.  So the PR was not reverted, but this one prepares this step.

**You should merge this PR only, if it is not approved.  Otherwise just close it**

If necessary, I merge this one and create a new PR and git cherry-pick the commits of #2705.  But a 3rd PR seems to be a pain, too, moving the discussion again.  So let's see and wait whether this is really necessary.  Sorry for this mess.  I hope this won't happen again.

**Comment by avekens** [comment]
I would have accepted the former PR #2705, therefore it can remain merged for my part. No further actions should be taken to revert something, because I fear that will produce more confusion. But @benjub should decide.

**Comment by benjub** [comment]
@savask : you're right, having that many checkboxes and updating it at every change would be too much work.  Do what you think is best and not too demanding on your part.  Maybe a general Issue with a link to the list ?  That way, we can link to it everytime we deal with one of these theorems, and the PR appears (as a "cross-link") in the Issue.

**Comment by benjub** [comment]
Converted to draft so that we do not merge it accidentally.

I did a `$ git log -2` on the current HEAD of `upstream/develop` and it seems all is fine.  @wlammen : can you confirm we can close this one ? (**edit:** I did reread everything, and you stated clearly that I can close it, so I will.)

**Comment by benjub** [comment]
> > I just added a comment that no. 34 and no. 48 will not be added to set.mm. Is this OK?
> 
> Yes, sure.

Thanks to @avekens's work around these, if you ran your program again, I guess that lines 34 and 48 would not appear anymore ?

**Comment by savask** [comment]
>Maybe a general Issue with a link to the list ? That way, we can link to it everytime we deal with one of these theorems, and the PR appears (as a "cross-link") in the Issue.

I could do that, but what would be the condition for closing the issue? When every suggestion from the list was either incorporated into set.mm or discarded?

>if you ran your program again, I guess that lines 34 and 48 would not appear anymore ?

No, they still appear in the list, but no. 34's score lowered from 120 to 106 and no. 48's from 87 to 69.

**Comment by benjub** [comment]
> I could do that, but what would be the condition for closing the issue? When every suggestion from the list was either incorporated into set.mm or discarded?

@savask: Good point... After thinking about it, I think the advantage of having an Issue that we can link to from every PR dealing with it outweighs the drawback of having to close it maybe somewhat arbitrarily when there is consensus we are done with it.

**Pull request closed without merging**
