### PR TITLE
Add metamath-knife to automated checks

### LINKED ISSUE #3250: Proposal: be able to declare forbidden axioms for a proof
Many theorems have comments saying that they are proved without certain axioms, for example https://us.metamath.org/mpeuni/sbth.html says that it avoids https://us.metamath.org/mpeuni/ax-inf.html and https://us.metamath.org/mpeuni/ax-ac.html , and https://us.metamath.org/mpeuni/equsb1v.html says that it avoids https://us.metamath.org/mpeuni/ax-13.html

However, we have no way to check that such claims remain true, despite this being easy to automate in principle. In the past we have had multiple problems where axiom usage gets accidentally re-introduced and although our mechanisms to prevent this have gotten better, they aren't perfect and in some cases are more manual than needed.

Proposal:

* Add a `$j usage` directive, for example for these examples it would be:
```
$j usage 'sbth' avoids 'ax-inf' 'ax-ac';
$j usage 'equsb1v' avoids 'ax-13';
```

* Although this would probably generally be used for axioms, I had in mind saying that any usage of the specified statement, when traced back recursively, would be an error. This would be well defined for theorems as well as axioms. Although I don't have a concrete example of using it for theorems I am thinking of something like "this is an elementary proof which does not require Bézout's identity" (or something sorta like that).

* We would need a tool to check this. I assume it would look a bit like https://github.com/david-a-wheeler/metamath-knife/pull/107 (with various changes to parse the $j comments and so on, as well as presumably being a crate on top of the metamath-knife library crate since we are talking about breaking apart metamath-knife like that).

* We'd want the set.mm automated tests to download this tool and run it, which should be fairly similar to the existing checks.

Open questions:

* I'm not attached to this syntax, perhaps people have ideas about syntax
* Of course someone has to write the checker. I might be volunteering especially if the crate separation in metamath-knife is done first, but if someone else gets to it before me that's great too.

### PR DESCRIPTION
**Pull request by jkingdon**
This is mostly for the usage check, but while we're here run a verify too.

The result is that metamath-knife runs and gives the same result I'm seeing locally.  Which I think means that https://github.com/david-a-wheeler/metamath-knife/pull/118 has a bug, or exposes a bug which was there, or something. Once we can figure out what is going on there and fix it, we should be able to get passing tests on this pull request.

Fixes #3250.

### CODE REVIEW

**Comment by tirix** [comment]
That's interesting!
I've created [a PR](https://github.com/david-a-wheeler/metamath-knife/pull/120) to fix this specific issue, but this will not help in the case of definitional checks.

**Comment by tirix** [comment]
The re-run passed with the new version of metamath-knife, and I've logged [an issue](https://github.com/david-a-wheeler/metamath-knife/issues/121) in metamath-knife to track the strange behaviour.

**Comment by jkingdon** [comment]
> I've logged [an issue](https://github.com/david-a-wheeler/metamath-knife/issues/121) in metamath-knife to track the strange behaviour.

I saw different strange behavior with iset.mm but apparently the same fix dealt with it (with respect to `--verify-usage` anyway: as you point out, the problem may still be there for the definitional checks).

**Review by tirix — APPROVED** [review]
Three remarks:
- this check covers the same thing, with the same implementation, as smm3 (smetamath-rs), so the smm3 check could/should be removed.
- metamath-knife includes a `discouraged` file generation which is waaay faster than metamath-exe's. It would ease github's server loads and accelerate our CI to move it.
- metamath-knife has also `-t` and `-m` options, for typesetting and markup checks. They are also fast, and cover a bit more than other checkers. You could add it to the `-v` of this PR.

**Comment by jkingdon** [comment]
I guess I'll merge this now and leave the door open for future pull requests for those other issues. They all sound reasonable to me (not that I really know enough about metamath-knife to know whether any of them would be controversial or present any difficulties). But I don't see any particular need to do everything at once.

**Pull request merged**
