### PR TITLE
Add toponrestid to set.mm

### PR DESCRIPTION
**Pull request by jkingdon**
This is a convenience theorem from @savask - not sure whether "no reference to me or the list is needed" means that you prefer to be anonymous or just that you are just saying that credit is not
required.

I tried to minimize everything using `restid`, `toponuni`, or `toponunii` but apparently my `min.cmd` skills aren't very good because I didn't get any minimizing that way. I did get success with `scripts/minimize cncfcn1 set.mm` so it must have just been something I did wrong running min.cmd. I thought I was following the instructions with `substitute 1.tmp xxx toponrestid a ""` put in where directed, but maybe someone can advise on what I might have been doing wrong?

### CODE REVIEW

**Comment by benjub** [comment]
I used `scripts/min.cmd` to minimize with `toponrestid` theorems using ` toponunii, restid` (the main theorems used in its proof). Log below. There are instructions within the file `min.cmd` (so I typed: open log 1.tmp; show usage toponunii,restid; close log; submit "scripts/min.cmd"; tools; substitute 1.tmp xxx topolrestid a ""; exit; open log log.txt; submit 1.tmp; close log").

```
Proof of "abelth" decreased from 4404 to 4370 bytes using "toponrestid".
Proof of "cdivcncf" decreased from 472 to 425 bytes using "toponrestid".
Proof of "cncfcn1" decreased from 172 to 104 bytes using "toponrestid".
Proof of "cncfmpt2f" decreased from 357 to 312 bytes using "toponrestid".
Proof of "cnlimc" decreased from 511 to 464 bytes using "toponrestid".
Proof of "cnrehmeo" decreased from 975 to 929 bytes using "toponrestid".
Proof of "cxpcn" decreased from 824 to 779 bytes using "toponrestid".
Proof of "cxpcn2" decreased from 557 to 514 bytes using "toponrestid".
Proof of "cxpcn3" decreased from 4770 to 4737 bytes using "toponrestid".
Proof of "cxpcncf1" decreased from 684 to 624 bytes using "toponrestid".
Proof of "cxpcncf2" decreased from 662 to 604 bytes using "toponrestid".
Proof of "dvacos" decreased from 2132 to 2084 bytes using "toponrestid".
Proof of "dvaddbr" decreased from 4164 to 4116 bytes using "toponrestid".
Proof of "dvasin" decreased from 7043 to 6999 bytes using "toponrestid".
Proof of "dvatan" decreased from 4697 to 4616 bytes using "toponrestid".
Proof of "dvcjbr" decreased from 1755 to 1681 bytes using "toponrestid".
Proof of "dvcn" decreased from 582 to 535 bytes using "toponrestid".
Proof of "dvcnp2" decreased from 2658 to 2619 bytes using "toponrestid".
Proof of "dvcobr" decreased from 3468 to 3427 bytes using "toponrestid".
Proof of "dveflem" decreased from 4247 to 4205 bytes using "toponrestid".
Proof of "dvexp3" decreased from 2723 to 2660 bytes using "toponrestid".
Proof of "dvidlem" decreased from 1209 to 1164 bytes using "toponrestid".
Proof of "dvlipcn" decreased from 6036 to 5975 bytes using "toponrestid".
Proof of "dvlog" decreased from 1978 to 1920 bytes using "toponrestid".
Proof of "dvlog2" decreased from 870 to 822 bytes using "toponrestid".
Proof of "dvloglem" decreased from 2382 to 2301 bytes using "toponrestid".
Proof of "dvmulbr" decreased from 5643 to 5596 bytes using "toponrestid".
Proof of "dvnres" decreased from 2099 to 2049 bytes using "toponrestid".
Proof of "dvply1" decreased from 3109 to 3059 bytes using "toponrestid".
Proof of "dvrec" decreased from 2937 to 2896 bytes using "toponrestid".
Proof of "dvtan" decreased from 2376 to 2310 bytes using "toponrestid".
Proof of "dvtaylp" decreased from 4662 to 4585 bytes using "toponrestid".
Proof of "efopnlem2" decreased from 1817 to 1773 bytes using "toponrestid".
Proof of "ftalem3" decreased from 2866 to 2817 bytes using "toponrestid".
Proof of "ftc1cn" decreased from 1178 to 1098 bytes using "toponrestid".
Proof of "ftc1cnnc" decreased from 4812 to 4747 bytes using "toponrestid".
Proof of "knoppcnlem10" decreased from 1160 to 1091 bytes using "toponrestid".
Proof of "knoppcnlem11" decreased from 1149 to 1065 bytes using "toponrestid".
Proof of "lhop1lem" decreased from 11160 to 11119 bytes using "toponrestid".
Proof of "logcn" decreased from 1959 to 1870 bytes using "toponrestid".
Proof of "logtayl" decreased from 8962 to 8880 bytes using "toponrestid".
Proof of "psercn" decreased from 3524 to 3482 bytes using "toponrestid".
Proof of "pserdv" decreased from 2075 to 1982 bytes using "toponrestid".
Proof of "pserdvlem2" decreased from 9554 to 9467 bytes using "toponrestid".
Proof of "resqrtcn" decreased from 1306 to 1258 bytes using "toponrestid".
Proof of "sqrtcn" decreased from 848 to 800 bytes using "toponrestid".
Proof of "taylthlem2" decreased from 7740 to 7693 bytes using "toponrestid".
```

**Comment by jkingdon** [comment]
> There are instructions within the file `min.cmd`

Ah, I see what I did wrong. I forgot the last two steps (`write source set.mm /rewrap` and `close log`) because I got distracted while the time consuming step ran.

I'll update this pull request once I get a clean run. Maybe later tonight or tomorrow.

**Comment by jkingdon** [comment]
This pull request now contains the results of a min.cmd run which produced the following:

```
Proof of "abelth" decreased from 4404 to 4370 bytes using "toponrestid".
Proof of "cdivcncf" decreased from 472 to 425 bytes using "toponrestid".
Proof of "cncfmpt2f" decreased from 357 to 312 bytes using "toponrestid".
Proof of "cnlimc" decreased from 511 to 464 bytes using "toponrestid".
Proof of "cnrehmeo" decreased from 975 to 929 bytes using "toponrestid".
Proof of "cxpcn" decreased from 824 to 779 bytes using "toponrestid".
Proof of "cxpcn2" decreased from 557 to 514 bytes using "toponrestid".
Proof of "cxpcn3" decreased from 4770 to 4737 bytes using "toponrestid".
Proof of "cxpcncf1" decreased from 684 to 624 bytes using "toponrestid".
Proof of "cxpcncf2" decreased from 662 to 604 bytes using "toponrestid".
Proof of "dvacos" decreased from 2132 to 2084 bytes using "toponrestid".
Proof of "dvaddbr" decreased from 4164 to 4116 bytes using "toponrestid".
Proof of "dvasin" decreased from 7043 to 6999 bytes using "toponrestid".
Proof of "dvatan" decreased from 4697 to 4616 bytes using "toponrestid".
Proof of "dvcjbr" decreased from 1755 to 1681 bytes using "toponrestid".
Proof of "dvcn" decreased from 582 to 535 bytes using "toponrestid".
Proof of "dvcnp2" decreased from 2658 to 2619 bytes using "toponrestid".
Proof of "dvcobr" decreased from 3468 to 3427 bytes using "toponrestid".
Proof of "dveflem" decreased from 4247 to 4205 bytes using "toponrestid".
Proof of "dvexp3" decreased from 2723 to 2660 bytes using "toponrestid".
Proof of "dvidlem" decreased from 1209 to 1164 bytes using "toponrestid".
Proof of "dvlipcn" decreased from 6036 to 5975 bytes using "toponrestid".
Proof of "dvlog" decreased from 1978 to 1920 bytes using "toponrestid".
Proof of "dvlog2" decreased from 870 to 822 bytes using "toponrestid".
Proof of "dvloglem" decreased from 2382 to 2301 bytes using "toponrestid".
Proof of "dvmulbr" decreased from 5643 to 5596 bytes using "toponrestid".
Proof of "dvnres" decreased from 2099 to 2049 bytes using "toponrestid".
Proof of "dvply1" decreased from 3109 to 3059 bytes using "toponrestid".
Proof of "dvrec" decreased from 2937 to 2896 bytes using "toponrestid".
Proof of "dvtan" decreased from 2376 to 2310 bytes using "toponrestid".
Proof of "dvtaylp" decreased from 4662 to 4585 bytes using "toponrestid".
Proof of "efopnlem2" decreased from 1817 to 1773 bytes using "toponrestid".
Proof of "ftalem3" decreased from 2866 to 2817 bytes using "toponrestid".
Proof of "ftc1cn" decreased from 1178 to 1098 bytes using "toponrestid".
Proof of "ftc1cnnc" decreased from 4812 to 4747 bytes using "toponrestid".
Proof of "knoppcnlem10" decreased from 1160 to 1091 bytes using "toponrestid".
Proof of "knoppcnlem11" decreased from 1149 to 1065 bytes using "toponrestid".
Proof of "lhop1lem" decreased from 11160 to 11119 bytes using "toponrestid".
Proof of "logcn" decreased from 1959 to 1870 bytes using "toponrestid".
Proof of "logtayl" decreased from 8962 to 8880 bytes using "toponrestid".
Proof of "psercn" decreased from 3524 to 3482 bytes using "toponrestid".
Proof of "pserdv" decreased from 2075 to 1982 bytes using "toponrestid".
Proof of "pserdvlem2" decreased from 9554 to 9467 bytes using "toponrestid".
Proof of "resqrtcn" decreased from 1306 to 1258 bytes using "toponrestid".
Proof of "sqrtcn" decreased from 848 to 800 bytes using "toponrestid".
Proof of "taylthlem2" decreased from 7740 to 7693 bytes using "toponrestid".
```

**Comment by savask** [comment]
@jkingdon 
>not sure whether "no reference to me or the list is needed" means that you prefer to be anonymous or just that you are just saying that credit is not required.

Yes, I meant that credit is not required.

I'm glad that the theorem actually minimizes something (I wish there was a way to see the total number of bytes saved, to compare it with the "score" from the list).

**Comment by avekens** [comment]
> I'm glad that the theorem actually minimizes something (I wish there was a way to see the total number of bytes saved, to compare it with the "score" from the list).

I evaluated the log output given above with Excel, and I got a saving of 2577 bytes in total.

**Review by benjub — APPROVED** [review]

**Comment by jkingdon** [comment]
> Yes, I meant that credit is not required.

Well, I'd be glad to change the Contributed line from "Contributed by Jim Kingdon" to point to you instead, since I didn't really do much. (you'd have to tell me how to identify you, though, since I think I only know you as "savask").

You can also drop the subject, I'm not trying to make this a burden.

**Comment by benjub** [comment]
@jkingdon : have you had a look at my comment at https://groups.google.com/g/metamath/c/aXvD9rs36Ps/m/B5XxjxvOBAAJ ? What do you think ?  I guess it's too late now to revert this commit to see if the other theorem would have been more useful. But this is a cautionary tale for us (since I approved this PR as well) for further theorem additions.

**Comment by jkingdon** [comment]
> @jkingdon : have you had a look at my comment at https://groups.google.com/g/metamath/c/aXvD9rs36Ps/m/B5XxjxvOBAAJ ? What do you think ? I guess it's too late now to revert this commit to see if the other theorem would have been more useful. But this is a cautionary tale for us (since I approved this PR as well) for further theorem additions.

Shouldn't be too late. Might be as simple as `git revert 6ee1e09ab869a4633442ef4ff5c229dfcfb2cf57`. Then you could try the other proposed theorem followed by a min.cmd run.

I mean it is an interesting episode about how looking for local maxima might not find the shortest proof (especially given what the minimizer can and can't do), but I hope it doesn't make us too scared to try anything.

**Pull request merged**
