### PR TITLE
shorten cbvalv

### PR DESCRIPTION
**Pull request by wlammen**
Clean up. The previous version of cbvalv used very elementary steps to point out where each axiom kicks in. This version optimizes on proof length again, as usual.
Prove cbval2v, cbvex2v, cbvaldva, cbvexdva without ax-10.

### CODE REVIEW

**Comment by wlammen** [comment]
Clean up. The previous version used very elementary steps to point out where each axiom gets in. This version minimizes on proof steps again.

**Comment by benjub** [comment]
Is there a reason for the final "a" in cbvaldva and cbvexdva ?

**Comment by wlammen** [comment]
An abbreviation for the and in the hypothesis?

**Comment by nmegill** [comment]
> Is there a reason for the final "a" in cbvaldva and cbvexdva ?

As @wlammen said, it is due to the "and" in the hypothesis.  This is an old convention going back to at least 1997 to distinguish e.g. rexbidva (added in 1997; 326 uses) from the weaker rexbidv (added in 1994; 950 uses), although it has also been used for cases where only the "a" version exists.  For newer, lesser-used deductions (which rarely justify both "a" and non-"a" versions) we would usually omit the "a" (and even the "v" when a non-"v" version would have little use).  Later on we also tend to omit the "d" for new theorems in more advanced set theory that use Mario's deduction method.

**Comment by nmegill** [comment]
In the cases of cbvaldva and cbvexdva, a non-a version would have the awkward hypothesis  |- ( ph -> ( x = y -> ( ps \<-\> ch ) ) ), which is unlikely to be useful.  For theorems of this form, I think we could remove the "a".  Maybe the "a" should be used only with theorems like  rexbidv/rexbidva with non-equivalent weak and strong forms.

**Pull request merged**
