### PR TITLE
mmset.raw.html: Add getting started link

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Nowhere on the set.mm front page do we provide a hint of
how to start contributing something else.  That should be fixed.

This adds a single link on the top right to the GitHub page on
"Getting started with contributing (to Metamath set.mm)".
That will at least help people find that information.

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by nmegill** [comment]
We already have a link at the top on the page saying, "If you wish to contribute your own proofs to the Metamath project, see 'How can I contribute to Metamath?'"  Is that not sufficient?

**Comment by benjub** [comment]
In addition to the link 'How can I contribute to Metamath?' that @nmgeill
added recently, I also added recently the link "GitHub repository (contains
the database as well as help on contributing)" (and I created the "External
links" list for that purpose).

**Comment by nmegill** [comment]
@david-a-wheeler Given the comments above, do you think this is still necessary?

Also, if we do add a your link, it should go in the "External links" section because it directs to a site outside of metamath.org.

**Comment by david-a-wheeler** [comment]
@nmegill - I didn't notice that sentence earlier, which suggests to me that perhaps it's not enough :-).  I think the link of major links should also note it.  You're right that it should be an "external links" entry if we use my text.

However, now that I see "How can I contribute to Metamath?", I think we should simply add *that* in our list of big links.

**Comment by nmegill** [comment]
OK, I suggest you use the "How can I contribute to Metamath?" link to replace the link you added.  It can stay in the "Related pages" area since it links to a metamath.org page.

**Pull request merged**
