### PR TITLE
rename mpt2 to mpo in ML's mathbox

### PR DESCRIPTION
**Pull request by jkingdon**
`icorempt2` is quite straightforward - just change `mpt2` to `mpo`.

`csbmpt22g` is a touch trickier as I'm not quite sure how the current name is supposed to be parsed. But it seems like `csbmpo12` makes sense by analogy to https://us.metamath.org/mpeuni/csbmpt12.html

As usual, will see if we can get an approval from @ml-2

### CODE REVIEW

**Comment by tirix** [comment]
> `csbmpt22g` is a touch trickier as I'm not quite sure how the current name is supposed to be parsed. But it seems like `csbmpo12` makes sense by analogy to https://us.metamath.org/mpeuni/csbmpt12.html

I would even use `csbmpo123`, since we're acting on all 3 classes in the formula (`Y`, `Z` and `D`) in
```
    csbmpo12 $p |- ( A e. V -> [_ A / x ]_ ( y e. Y , z e. Z |-> D )
           = ( y e. [_ A / x ]_ Y , z e. [_ A / x ]_ Z |-> [_ A / x ]_ D ) )
```

**Comment by ml-2** [comment]
I am happy with these changes. @tirix's suggestion is also good but either is fine with me. Thank you @jkingdon!

**Comment by avekens** [comment]
> > `csbmpt22g` is a touch trickier as I'm not quite sure how the current name is supposed to be parsed. But it seems like `csbmpo12` makes sense by analogy to https://us.metamath.org/mpeuni/csbmpt12.html
> 
> I would even use `csbmpo123`, since we're acting on all 3 classes in the formula (`Y`, `Z` and `D`) in
> 
> ```
>     csbmpo12 $p |- ( A e. V -> [_ A / x ]_ ( y e. Y , z e. Z |-> D )
>            = ( y e. [_ A / x ]_ Y , z e. [_ A / x ]_ Z |-> [_ A / x ]_ D ) )
> ```

I would also prefer `csbmpo123`, as @tirix proposed, especially when looking at the mto counterparts `csbmpt2`and `csbmpt12`.

**Comment by jkingdon** [comment]
> I would also prefer `csbmpo123`, as @tirix proposed, especially when looking at the mto counterparts `csbmpt2`and `csbmpt12`.

Agreed. I've changed the pull request to use `csbmpo123` and plan on merging once the tests pass.

**Pull request merged**
