### PR TITLE
sqr-->sqrt in some labels having escaped the global relabeling

### PR DESCRIPTION
**Pull request by benjub**
As the title says. I did not write it in the history since these are either a lemma or $e statements.

### CODE REVIEW

**Review by jkingdon — APPROVED** [review]
Thank you. I noticed it a while ago but I'm glad to see that you not only noticed it but also did something about it.

**Comment by benjub** [comment]
I'm reviewing your PR and it might conflict at that point... Which do you recommend to merge first ?

**Comment by jkingdon** [comment]
> I'm reviewing your PR and it might conflict at that point... Which do you recommend to merge first ?

Oh I merged the other one before I read this comment. But you want me to try a post hoc rationale for something which already happened for completely different reasons? Perhaps "merge the larger one first, because it is easier to fix conflicts on the smaller one"? But don't take me entirely seriously because as I say this isn't a principled statement (at least in this case).

**Review by avekens — APPROVED** [review]

**Comment by benjub** [comment]
@avekens : I fixed a few: as sum --> as a sum.  I hope it's good for you, and then I'll merge.

**Comment by avekens** [comment]
> @avekens : I fixed a few: as sum --> as a sum. I hope it's good for you, and then I'll merge.

It's fine, thanks.

**Review by jkingdon — APPROVED** [review]

**Pull request merged**
