### PR TITLE
More n-dimensional measurable sets (section 115 is now complete)

### PR DESCRIPTION
**Pull request by glacode**
- continuity of the finite product operator

- measures are continuous from below

- measures are continuous from above

- n-dimensional open intervals are measurable (and their measure value)

- n-dimensional closed intervals are measurable (and their measure value)

- countable sets are measurable and have zero measure

### CODE REVIEW

**Comment by glacode** [comment]
Norman, please notice I've moved nnct (NN is countable) from TA's mathbox to the main part.
I can easily avoid using it explicitly, but it keeps coming up in my proofs, and it seemed a nice theorem to have in common.
Please, let me know if it's fine.

Glauco

**Comment by nmegill** [comment]
> Norman, please notice I've moved nnct (NN is countable) from TA's mathbox to the main part.

This is fine.

I noticed that you haven't done the reformatting given at https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md
(in particular, the "save proof */compressed/fast").  Could you do that and resubmit?  This will prevent unnecessary large diffs in the next PR.  Thanks.

**Comment by glacode** [comment]
Hi Norm,

I didn't see a large diff w.r.t. the previous version (diff shown only the lines I actually changed).

I've now launched this command

/home/mionome/Documents/metamath/metamath 'open log "/home/mionome/Desktop/provashare/log/log.txt"' 'read "/home/mionome/Documents/git/set.mm/set.mm"' 'write source "/home/mionome/Documents/git/set.mm/set.mm" /rewrap' erase 'read "/home/mionome/Documents/git/set.mm/set.mm"' 'save proof */compressed/fast' 'verify markup */file_skip/top_date_skip' 'verify proof *' 'write source "/home/mionome/Documents/git/set.mm/set.mm"' quit

I hope it did the job, please, let me know (diff seems pretty much the same as before, but it may be I'm missing something simple, here).

BR
Glauco

**Comment by glacode** [comment]
May be I got it: anybody who will reformat with the next commit, would reformat my lines also and it would add unwanted diffs to their commit.

**Comment by benjub** [comment]
> May be I got it: anybody who will reformat with the next commit, would reformat my lines also and it would add unwanted diffs to their commit.

Exactly.

When in the directory of your set.mm, simply paste:
`./metamath 'read set.mm' 'write source set.mm /rewrap' erase 'read set.mm' 'save proof */compressed/fast' 'verify markup */file_skip/top_date_skip' 'verify proof *' 'write source set.mm' quit`

**Pull request merged**
