### PR TITLE
remove top date and adapt preamble

### PR DESCRIPTION
**Pull request by benjub**
After yet another merge conflict due to the top date, I decided to go on and remove it, since, as mentioned several times, git permits good version control.  I adapted a bit the preamble. What do you think about this proposal ? (most important is to keep the preamble short, in my opinion). The part about the licence and "principal curator" will have to be changed too, but I do not know to what. You may propose the modification here so that I'll do it, or you can do a PR later.

### CODE REVIEW

**Review by sctfn — APPROVED** [review]

**Comment by wlammen** [comment]
rewrap issues a warning
?Warning: The "Version of" date 22-Dec-2020 at the top of file "set.mm" is less
    recent than the date 20-Dec-2021 in the description of statement
    "rpsqrtcn".
if the date does not match certain criteria. 
Removing the date may produce unwanted results in the script, or render part of metamath.exe invalid
'verify markup' seems to be affected.

**Comment by david-a-wheeler** [comment]
I think the metamath.exe script can be tweaked to ignore the top date, but it'll be a little while before I can dig into it. It should be "obvious" :-).

**Comment by wlammen** [comment]
mmcmds.c line 5413 seems to be a good starting point
line 5396 shows that the date check in verifyMarkup can be deactivated by the caller
metamath.c line 8054 set flag i fix to 1

In fact: changing line 8054 to
      i = 1; /* i = (switchPos("/ DATE_SKIP") != 0) ? 1 : 0 ; */ // WL 22-12-2021 deactivate date check
removes the date check.

**Comment by wlammen** [comment]
Test: replace first line in set.mm with
$( This is the Metamath database set.mm. $)

TODO Metamath version should be updated, and modifications comments be added

`./rewrap`
`Metamath - Version 0.198 7-Aug-2021           Type HELP for help, EXIT to exit.`
`MM> read set.mm`
`Reading source file "set.mm"... 42507502 bytes`
`42507502 bytes were read into the source buffer.`
`The source has 198899 statements; 2638 are $a and 39430 are $p.`
`No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *`
`if you want to check them.`
`MM> write source set.mm /rewrap`
`The input file will be renamed set.mm~1.`
`Writing "set.mm"...`
`198899 source statement(s) were written.`
`MM> erase`
`Metamath has been reset to the starting state.`
`MM> read set.mm`
`Reading source file "set.mm"... 42507498 bytes`
`42507498 bytes were read into the source buffer.`
`The source has 198899 statements; 2638 are $a and 39430 are $p.`
`No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *`
`if you want to check them.`
`MM> save proof */compressed/fast`
`Reformatting and saving (but not recompressing) all proofs...`
`Remember to use WRITE SOURCE to save changes permanently.`
`MM> verify markup */file_skip`
`Checking statement label conventions...`
`Checking latexdef, htmldef, althtmldef...`
`Checking statement comments...`
`?Warning: The label token "tgoldbachgtd" (referenced in comment of statement`
`"hgt750lem") is not a $a or $p statement label.`
`Checking section header comments...`
`Checking bibliographic references...`
`Checking mathbox independence...`
`MM> verify proof *`
`0 10%  20%  30%  40%  50%  60%  70%  80%  90% 100%`
`..................................................`
`All proofs in the database were verified in 3.40 s.`
`MM> write source set.mm`
`The input file will be renamed set.mm~1.`
`Writing "set.mm"...`
`198899 source statement(s) were written.`
`MM> quit`

**Comment by benjub** [comment]
Of course, I should have anticipated that metamath.c would complain !
@wlammen : isn't it the "topdateskip" flag that we should modify, and not the "dateskip" flag ?

**Comment by wlammen** [comment]
I'll give it a try.
Yes, same result for topdateskip.  Good catch.

**Comment by benjub** [comment]
Thanks Wolf.
metamath.c shoud be modified only with great care, so I'll let people more experienced than me check Wolf's proposal.
Maybe it's also possible to keep metamath.c untouched and simply add the option /TOP_DATE_SKIP to the CI process (verifiers.yml) ? A third option: modify metamath.c minimally to make "top_date_skip" the default option of "verify markup", and add the modifier "/top_date_check" to make that check ?

**Comment by david-a-wheeler** [comment]
I'm busy at work, but a quick note: as a quick hack, you could tweak the test script to modify the *database* and re-insert the date. Then it would be fine :-).

**Comment by wlammen** [comment]
Here is the diff:
```
diff` metamath.c metamath_198.c

60,63c60
< #define MVERSION "0.199 22-Dec-2021"
< /* 0.199 WL 22-Dec-2021 metamath.c - disable the top date check.
<    TODO:  For now a flag is hardcoded, but remove the disabled code from
<    sources */
---
> #define MVERSION "0.198 7-Aug-2021"
8058,8060c8055
<       /* WL 22-Dec-2021: hardcode TOP_DATE_SKIP to 1, so top date checks are
<         disabled */
<       j = 1; /* j = (switchPos("/ TOP_DATE_SKIP") != 0) ? 1 : 0;*/
---
>       j = (switchPos("/ TOP_DATE_SKIP") != 0) ? 1 : 0;
```

**Comment by wlammen** [comment]
The code should follow the development of the database.  It is not only pointless to have code supporting outdated features, a sloppy coding style will backfire sooner or later, because over time it will become more and more difficult to read and maintain.
https://www.evoketechnologies.com/blog/code-review-checklist-perform-effective-code-reviews/

**Comment by wlammen** [comment]
For Review: mmcmds.c line 5900 - 5940 are disabled by the hard coded flag.

**Comment by wlammen** [comment]
Rewrap issues a warning 
?Warning: The label token "tgoldbachgtd" (referenced in comment of statement
"hgt750lem") is not a $a or $p statement label.
The correct label is "tgoldbachgtde".  Perhaps one can fix this here too.

**Comment by benjub** [comment]
> Rewrap issues a warning
> ?Warning: The label token "tgoldbachgtd" (referenced in comment of statement
> "hgt750lem") is not a $a or $p statement label.
> The correct label is "tgoldbachgtde". Perhaps one can fix this here too.

I just noticed it and fixed it in #2394, although I used "~~?" (since "show usage" returned "None"). We'll let @tirix see what to do with it.

As for your previous comment: set.mm is not the only database that metamath.c may check, but I tend to agree with you that the top_date stuff can probably be removed/commented out.  I'll let more seasoned programmers see what is best.

**Comment by sctfn** [comment]
Who has permissions to that repo? I can give it a look, but I don't have
commit rights there.

**Comment by digama0** [comment]
Do you mean https://github.com/metamath/metamath-exe ? I have owner rights on the repo, so I can merge PRs, or appoint others. (Unfortunately, it seems v0.199 was lost, since Norm mentioned working on this but he didn't commit anything to the repo. We can merge this later and renumber the versions if we find it.) But I don't think there is any particular reason to avoid making modifications to metamath.exe, although we need to update the CI to produce automatic releases and either put them on the web site or modify set.mm CI to download from github instead.

**Comment by jkingdon** [comment]
The proposed set.mm changes look good to me (and I'd support doing much the same for iset.mm). When I tried making a pull request for this, I too ran into some issues with /TOP_DATE_SKIP and when I tried looking at the metamath.exe source I got a bit puzzled by what I was seeing and would have needed to spend more time with it to understand. So if we can fix the tools we appear to be agreed on removing the top date.

**Comment by wlammen** [comment]
I printed out the help within metamath regarding verify markup.  Obviously you need to add the option / TOP_DATE_SKIP to every VERIFY MARKUP call in metamath invocations to ignore the version line at the top of a .mm file.  This is sufficient within the CI process.  Still, there might be unaware users of metamath.exe possibly running home-brewed scripts that will run into trouble, if the source is not upgraded.

Short term it might be sufficient to adjust the CI process and the built in help to reflect the modifications to set.mm and other files.

Mid term I'd like to change the C sources in a separate project.  The astute reader will notice that I
- mistook the DATE_SKIP first, before being pointed to the TOP_DATE_SKIP option;
- the built-in help needs to be adjusted, but that was overseen so far;
- the changelog has the contributer's name spelled out (including myself in 2013). Only Norm appears as nm.  This is necessary since my shorthand WL is declared in set.mm only.

This should be seen as a warning to take your time for any change.

The C source needs some clean up.  In particular, the files and function implementations are too long.  Variables are declared often in outer scopes, instead of inner blocks.  The memory allocation is not fully automatic (i.e handled by the compiler).

In 2013 I modified small parts, under the supervision of Norm.  My intention then was to transfer the source into a library, so external software has access to primitive operations.  I abandoned the idea, since I had little time then, and the transition turned out to be complex.  Now the situation has completely changed.  This software needs to be maintained, and adapted to modern coding style, or it won't be of use in a couple of years.

Another issue is the maintainer situation.  There should be a backup, just in case (Corona, accident, and so on).

```
Syntax:  VERIFY MARKUP <label-match> [/ DATE_SKIP] [/ TOP_DATE_SKIP]
            [/ FILE_SKIP] [/ UNDERSCORE_SKIP] [/ MATHBOX_SKIP] [/VERBOSE]

This command checks comment markup and other informal conventions we have
adopted.  It error-checks the latexdef, htmldef, and althtmldef statements
in the $t statement of a Metamath source file.  It error-checks any `...`,
~ <label>, and [bibref] markups in statement descriptions.  It checks that
$p and $a statements have the same content when their labels start with
"ax" and "ax-" respectively but are otherwise identical, for example
ax4 and ax-4.  It verifies the date consistency of "(Contributed by...)",
"(Revised by...)", and "(Proof shortened by...)" tags in the comment
above each $a and $p statement.  See HELP SEARCH for <label-match> rules.

Optional qualifiers:
    / DATE_SKIP - This qualifier will skip date consistency checking,
        which is usually not required for databases other than set.mm
    / TOP_DATE_SKIP - This qualifier will check date consistency except
        that the version date at the top of the database file will not
        be checked.  Only one of / DATE_SKIP and / TOP_DATE_SKIP may be
        specified.
    / FILE_SKIP - This qualifier will skip checks that require
        external files to be present, such as checking GIF existence and
        bibliographic links to mmset.html or equivalent.  It is useful
        for doing a quick check from a directory without these files
    / UNDERSCORE_SKIP - This qualifier will skip warnings for labels
        containing underscore ("_") characters.  Although they are
        legal per the Metamath spec, they may cause ambiguities with
        certain translators (such as to MM0) that convert "-" to "_".
        bibliographic links to mmset.html or equivalent.  It is useful
        for doing a quick check from a directory without these files
    / MATHBOX_SKIP - This qualifier will skip checking for mathbox
        independence i.e. that no mathbox proof references a statement
        in another (earlier) mathbox.
    / VERBOSE - Provides more information.  Currently it provides a list
        of axXXX vs. ax-XXX matches.

See also HELP LANGUAGE, HELP HTML, HELP WRITE THEOREM_LIST, and
HELP SET DISCOURAGEMENT for more details on the markup syntax.
See the 11-May-2016 ("is discouraged"), 14-May-2017 (date format), and
21-Dec-2017 (file inclusion) entries in
http://us.metamath.org/mpeuni/mmnotes.txt for further details on several
kinds of markup.  See HELP WRITE THEOREM_LIST for format of section headers.

For help with modularization tags such as "$( Begin $[ set-header.mm $] $)",
see the 21-Dec-2017 entry in http://us.metamath.org/mpeuni/mmnotes.txt .
```

**Comment by digama0** [comment]
FWIW I'm completely on board with aggressive cleanup of the C sources. I have never contributed nontrivially to metamath-exe precisely because the code is very messy, so if I were to start working on it, cleanup and refactoring would be at the top of the to do list. I think if you do undertake such a project you should push your work to the metamath-exe repo, possibly in a branch if you are worried about breakage. (And if you do, you will also become de-facto maintainer, which is good since it is maintainerless right now.)

**Comment by benjub** [comment]
I agree with the previous messages regarding metamath.c maintenance and development. Regarding the set.mm/iset.mm preambles, I followed @jkingdon's advice to have similar preambles. I also added the creation dates for each database.

Regarding the licencing part, set.mm reads:
```
Principal curator:  Norman Megill   http://us.metamath.org/email.html
```
and iset.mm reads:
```
Maintainer and default contributor:

NM  Norman Megill - http://us.metamath.org/email.html
```
I would propose something like:
```
Maintainer: Mario Carneiro - http://us.metamath.org/email.html
```
and
```
Maintainer: Jim Kingdon - http://us.metamath.org/email.html
```
respectively, if everyone (and particularly @digama0 and @jkingdon) agree. The webpage http://us.metamath.org/email.html should be updated (and maybe renamed contact.html ?). Or maybe there is a better option to give contact information ?

**Comment by digama0** [comment]
LGTM. (We don't need the "default contributor" part anymore, that got eliminated a few years back when we started enforcing contribution credits for everyone including Norm.)

**Comment by savask** [comment]
>Short term it might be sufficient to adjust the CI process and the built in help to reflect the modifications to set.mm and other files.

I think it's a good idea to change the CI first _without_ removing the top date. That will allow more people to update their metamath-exe version, saving some potential confusion in a situation when a person uses old metamath-exe with current set.mm.

>The C source needs some clean up. In particular, the files and function implementations are too long. Variables are declared often in outer scopes, instead of inner blocks. The memory allocation is not fully automatic (i.e handled by the compiler).

Last time I looked at metamath sources, I had an impression that it's worthwhile to rewrite it into C++, at least because of its containers library. It would be interesting to hear from people more knowledgeable in metamath internals, if it's worth the effort.

**Comment by benjub** [comment]
It passes all checks ! Actually, verifiers.yml was already using the option --top_date_skip, but it runs scripts/verify, and the latter passed the option incorrectly.  My latest commit fixes this, and also adds the metamath command "set echo on" to give a more explicit output (that helped me debug it, and it may help in the future). Letting our script wizard @david-a-wheeler know.

Also, I changed @tirix's dfpval2 (in a comment) to dpval2. I hope it's correct, and again it is strange that it passed CI last time.

**Review by avekens — APPROVED** [review]

**Comment by wlammen** [comment]
The file scripts/mass-rename also contains a suspicious verify markup command

**Comment by wlammen** [comment]
@digama0 ok let's start refactoring then.
@savask C++ is fine with me.  Possible downside: Fewer systems supporting that language.

**Comment by benjub** [comment]
@wlammen Can you open an issue at https://github.com/metamath/metamath-exe/issues that sums up our discussion here, and go from there ?

As for the language, I'm not sure it would be worth or even beneficial to switch to C++. We can have all bells and whistles in the projected "community verifier/proof assistant" (I think Rust was chosen for it), and have a stable, portable, good old ISO C verifier.

**Comment by jkingdon** [comment]
> As for the language, I'm not sure it would be worth or even beneficial to switch to C++. We can have all bells and whistles in the projected "community verifier/proof assistant" (I think Rust was chosen for it), and have a stable, portable, good old ISO C verifier.

I was wondering about that myself. About whether massive cleanups and big changes in the name of maintainability would be better directed towards something built on top of metamath-knife , maybe structured as multiple tools rather than trying to put all the verification, web page generatation, proof assistant, etc into one codebase like metamath.exe does.

But I will gladly defer to people who have time and energy to work on this. Although my day job is as a software developer, I have never quite figured out how to make working on proof software a hobby the same way I have made a hobby out of writing proofs (I won't bore you with my failed attempts to work on proof software - just will say that "oh this is software and I know how to write software" was not sufficient at least for me).

**Review by jkingdon — APPROVED** [review]

**Comment by digama0** [comment]
> I was wondering about that myself. About whether massive cleanups and big changes in the name of maintainability would be better directed towards something built on top of metamath-knife , maybe structured as multiple tools rather than trying to put all the verification, web page generatation, proof assistant, etc into one codebase like metamath.exe does.

I agree that we should try to migrate essential functionalities to metamath-knife eventually, but it will take a while to reach parity. I don't think we should significantly change the user-visible behavior of metamath.exe though; I'm thinking of refactoring more or less at the level I did to mmj2 after I took over from ocat: formatting and file organization, comments, extracting and renaming functions, maybe a code style linter like `clang-format` / `clang-tidy`. I consider this the bare minimum for being able to easily service small change requests like changing the behavior of `/top_date_skip`.

**Comment by jkingdon** [comment]
> formatting and file organization, comments, extracting and renaming functions, maybe a code style linter

Is it too ambitious to add "make sure there at least a few unit/regression tests?" Starting with https://github.com/david-a-wheeler/metamath-test if that isn't already integrated, but perhaps more importantly covering things like rewrapping, web page generation, the minimizer, etc. This would be a "one step at a time" thing but perhaps going from zero to something for each major piece of functionality would be high payoff in terms of making it easier to refactor with confidence.

**Comment by benjub** [comment]
@jkingdon and @digama0 : do I have your approval regarding the latest commit about maintainers ? Feel free to merge.

Hopefully someone will open an issue on https://github.com/metamath/metamath-exe/issues to summarize (and link to) the present PR, so that we can go from there and merge and close this PR.

**Comment by jkingdon** [comment]
> @jkingdon and @digama0 : do I have your approval regarding the latest commit about maintainers ? Feel free to merge.

I thought we were just going to remove that line.

I mean, I hope I'm not overcomplicating things, I just don't want to be a bottleneck or single point of failure for iset.mm any more than necessary.

**Comment by benjub** [comment]
> > @jkingdon and @digama0 : do I have your approval regarding the latest commit about maintainers ? Feel free to merge.
> 
> I thought we were just going to remove that line.

I thought @digama0's remark was about the non-necessity of having a "default contributor", as opposed to a "maintainer". But maybe none are needed, and pointing to http://us.metamath.org/email.html is enough ? Or not even that ?  Let's hear from him.

**Comment by tirix** [comment]
> directed towards something built on top of metamath-knife , maybe structured as multiple tools rather than trying to put all the verification, web page generatation, proof assistant, etc into one codebase like metamath.exe does.

FYI, a few weeks ago I have started [metamath-web](https://github.com/tirix/metamath-web), which is just a small program serving metamath pages, using metamath-knife as a library. It still outputs formulas in raw metamath code format (no HTML formatting), but it might be an interesting start.

For now, its output looks like this:
image

**Review by tirix — APPROVED** [review]

**Comment by savask** [comment]
> C++ is fine with me. Possible downside: Fewer systems supporting that language.

>As for the language, I'm not sure it would be worth or even beneficial to switch to C++. We can have all bells and whistles in the projected "community verifier/proof assistant" (I think Rust was chosen for it), and have a stable, portable, good old ISO C verifier.

@wlammen @benjub I guess I agree with you. I was just thinking that C++ might ease up memory management a little bit (see, for example, memory pool management in mmdata.c), but perhaps maintainability of metamath-exe is the main concern. In any case, I will be glad to offer some help if someone starts the refactor.

**Comment by wlammen** [comment]
I'd like to redirect the discussion about Metamath software here https://github.com/metamath/metamath-exe/issues/8

**Comment by benjub** [comment]
> FYI, a few weeks ago I have started [metamath-web](https://github.com/tirix/metamath-web), which is just a small program serving metamath pages, using metamath-knife as a library. It still outputs formulas in raw metamath code format (no HTML formatting), but it might be an interesting start.

@tirix Interesting !  Can you briefly explain in the README.md there how to use it ?

**Comment by tirix** [comment]
> @tirix Interesting ! Can you briefly explain in the README.md there how to use it ?

Sure: done!
Feel free to open issues there if you'd like to discuss further!

**Pull request merged**
