### PR TITLE
Implement requests from PR 1989

### PR DESCRIPTION
**Pull request by wlammen**

### CODE REVIEW

**Comment by benjub** [comment]
Thanks for the PR. Maybe equviniv and equviniva can be deprecated (in favor of equvinv) ?

Let's move wl-hbnaev to Main ?

**Comment by nmegill** [comment]
@wlammen AV's merge caused a conflict in yours, not sure where the conflict is.

**Comment by wlammen** [comment]
If you look at the users of equviniva, you will note, that they depend on the reversed order of equalities. Proofs become awkward, when you reverse them inline.  It is used in the very basic lemma axc9lem1, and I like the idea to input at this stage just what is needed there.  So this convenience theorem is justified enough, I think.  I am opposed to removing it.  As for equviniv. well, it captures one half of the proof of equvinv, making that proof more readable.  I cannot say much more in favour of that theorem, so, if you like, go ahead and remove it.
wl-hbnaev is more a reminder of a proof technique for me than anything else, with a possible application in hbn1fw. Without a concrete application, I wonder whether it is worth keeping it.  I see it as a tentative result.
@nmegill I think the conflict is in the lines recording name changes where AV added his moves.  I will locally resolve the merge conflict, and update the pull request then.

**Comment by nmegill** [comment]
@wlammen While you are fixing this, could you also update the contributor list with this:
```
DA  David Abernethy      SJ  Szymon Jaroszewicz    JO  Jason Orendorff
SA  Stefan Allan         BJ  Benoit Jubin          JPP Jon Pennant
TA  Thierry Arnoux       JK  Jim Kingdon           RP  Richard Penner
JA  Juha Arpiainen       ML  ML                    SP  Stanislas Polu
JB  Jonathan Ben-Naim    WL  Wolf Lammen           JP  Josh Purinton
GB  Gregory Bush         GL  Gerard Lang           SR  Steve Rodriguez
MC  Mario Carneiro       BL  Brendan Leahy         ATS Andrew Salmon
FC  Filip Cernatescu     RL  Raph Levien           AS  Alan Sare
PC  Paul Chapman         FL  Frederic Line         ES  Eric Schmidt
DF  Drahflow             RFL Roy F. Longton        GS  Glauco Siliprandi
GD  Georgy Dunaev        GM  Giovanni Mascellani   SS  Saveliy Skresanov
SF  Scott Fenton         JM  Jeff Madsen           JU  Jarvin Udandy
JGH Jeff Hankins         RM  Rodolfo Medina        AV  Alexander van der Vekens
AH  Anthony Hart         NM  Norman Megill         DAW David A. Wheeler
DH  David Harvey         DM  David Moews           RW  Roger Witte
CH  Chen-Pang He         MM  Mykola Mostovenko     KW  Kyle Wyonch
JH  Jeff Hoffman         MO  Mel L. O'Cat          JY  Jonathan Yan
AI  Asger C. Ipsen       OA  OpenAI                FZ  Fan Zheng
JJ  Jerry James          SO  Stefan O'Rear
```

Thanks.

**Comment by wlammen** [comment]
@nmegill What is ML standing for? Shall I keep it as is?

**Comment by nmegill** [comment]
> @nmegill What is ML standing for? Shall I keep it as is?

I don't know.  He or she contributed last year but only provided the initials "ML".  So that is what we have to use until we are provided with more information.

**Pull request merged**
