### PR TITLE
2a1

### PR DESCRIPTION
**Pull request by Uslery**
The number of steps of 2a1 is shortened.

### CODE REVIEW

**Comment by jkingdon** [comment]
I'm not an expert on how we measure proof size but I think it is often by the size of the compressed proof, so `AABCADE` versus `ACADBACEF` in this example.

**Comment by Uslery** [comment]
> I'm not an expert on how we measure proof size but I think it is often by the size of the compressed proof, so `AABCADE` versus `ACADBACEF` in this example.

1. Execute metamath.exe and read set.mm (Refer to 'metamath.exe' in https://us.metamath.org/)
2. Type 'show trace_back 2a1 /essential /count_steps'. If you want to see the number of steps including syntax definition, omit '/essential'. You can compare original set.mm and mine.

**Comment by Uslery** [comment]
Should I write '(Proof shortened by My Name, DD-MMM-YYYY.)'?

**Comment by wlammen** [comment]
Your suggestion requires a change in the metrics by which we compare proofs.  The current rules are written here https://us.metamath.org/mpeuni/conventions.html, in the paragraph **Acceptable shorter proofs**.

**Comment by avekens** [comment]
>     2. Type 'show trace_back 2a1 /essential /count_steps'. If you want to see the number of steps including syntax definition, omit '/essential'. You can compare original set.mm and mine.

'show trace_back' _lists all statements that the proof of the $p statement(s) specified by <label-match> depends on_. And the option 'count_steps' _counts the number of steps the proof would have if fully expanded back to axioms_, not the steps of the proof.  Therefore, the proposed proof has more steps (2 essential, 9 all) than the current proof (2 essential, 7 all) and a longer compressed size (31 characters compared with 25 characters). Therefore, it does not fulfil the criteria for a shorter proof. The number of steps the proof would have if fully expanded back to axioms is not a criterion for the proof size.

**Review by avekens — CHANGES_REQUESTED** [review]
see my latest comment

**Comment by avekens** [comment]
If this proof should serve as an example for an alternate/additional criterion for a "shorter proof", it could be added as 2a1ALT to main set.mm with the tags "(Proof modification is discouraged.)" and "(New usage is discouraged.)" and an explanation of this criterion.

**Comment by benjub** [comment]
> If this proof should serve as an example for an alternate/additional criterion for a "shorter proof", it could be added as 2a1ALT to main set.mm with the tags "(Proof modification is discouraged.)" and "(New usage is discouraged.)" and an explanation of this criterion.

I don't see a reason for adding an *ALT variant here.

**Comment by GinoGiotto** [comment]
I believe metamath-solitaire included a database of the shortest known proofs for propositional calculus:
 https://us.metamath.org/mmsolitaire/pmproofs.txt

I think it's interesting from a theoretical point of view, but it would probably deserve its own research branch.

**Comment by tirix** [comment]
Could this be moved in a (new) mathbox for @Uslery?

**Comment by jkingdon** [comment]
> Could this be moved in a (new) mathbox for @Uslery?

Would be OK with me.

**Comment by wlammen** [comment]
There is no reaction from @Uslery on the suggestion or critique made here.  It looks as if this post is abandoned.  If no one sees an advantage in keeping these results I suggest to drop them, instead of assuming the author is somehow impeded, and really wants to have an own mathbox with this post.

**Comment by jkingdon** [comment]
> If no one sees an advantage in keeping these results I suggest to drop them

Yeah, probably time to close this pull request. Always can reopen or make a new one if there is interest in pursuing it further.

**Comment by jkingdon** [comment]
As discussed, closing this. Feel free to reopen or make a new one if there is interest in pursuing it further.

**Pull request closed without merging**
