### PR TITLE
CCbar

### PR DESCRIPTION
**Pull request by benjub**
Main part:
* extract a proof from @digama0's axcnex (and add comment about an alternate proof); I extracted it because I need it in my mathbox.
* move df-tau from @jkingdon's mathbox since I use it in mine

Mathbox: some groundwork for extended and projective real and complex numbers.

### CODE REVIEW

**Comment by benjub** [comment]
@david-a-wheeler : is this due to your recent changes ?
```
Connecting to us.metamath.org (us.metamath.org)|173.255.232.114|:80... failed: Connection refused.
Error: Process completed with exit code 4.
```
**edit:** reran and it's ok. Still, a bit puzzling.

**Comment by jkingdon** [comment]
> * move df-tau from @jkingdon's mathbox since I use it in mine

If our principle is to give people choice in mathboxes, seems like we should put the definition, and whatever theorems would otherwise be duplicated, into main.

**Comment by david-a-wheeler** [comment]
Yes, my fault.  I fixed it soon after. Just rerun.

**Comment by david-a-wheeler** [comment]
> If our principle is to give people choice in mathboxes, seems like we should put the definition, and whatever theorems would otherwise be duplicated, into main.

In general, once more than one person uses something, we move it into main. Does anyone object in this case?

**Review by avekens — CHANGES_REQUESTED** [review]
I had a closer look at the changes in main (everything is fine) and only skimmed through the changes in the mathbox (formally OK).

The only thing to be done is to add df-tau (now in main already) to the list in changes-set.txt.

**Review by avekens — APPROVED** [review]

**Pull request merged**
