### PR TITLE
Cross-link MPE/ILE Schroeder-Bernstein Theorem

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by benjub** [comment]
`$ metamath "r set.mm" "w s set.mm/r" "q"` should fix things.

**Review by benjub — APPROVED** [review]

**Comment by david-a-wheeler** [comment]
[benjub](https://github.com/benjub) - ah yes. I even wrote the `scripts/rewrap` script.

I've rewrapped set.mm and iset.mm.

**Comment by david-a-wheeler** [comment]
I've rewrapped, it passes all checks, it's been approved, it's easily reverted, it only affects comment text, and I think this is a pretty noncontroversial change anyway.

So while I usually wait longer, I'm going to just merge this now so I don't forget :-).

**Comment by jkingdon** [comment]
I don't object, but I will offer one caveat. When we make links within iset.mm or within set.mm, we have tools to detect dead links (so we will remember to update when we rename theorems). Links like the ones here don't have that, so I have somewhat sparingly been using links between the two.

Having said that, I don't want to say we never can do so (none of the links in mm_100 have this kind of checking, for example). Just that I don't do it quite as freely as within set.mm or within iset mm

**Comment by benjub** [comment]
@jkingdon : That's true indeed. Maybe we should think of a way of having such checks among a set of "official databases". The problem may come up more often if/when other databases are added and/or we want to increase modularity (e.g., a "core" database which serves as the base for both set.mm and iset.mm should be able to point to "later" theorems in these two databases).

**Pull request merged**
