### PR TITLE
 Revision of "theorem forms" and suffixes

### PR DESCRIPTION
**Pull request by avekens**
Revision of "Header" comments:
- Item "4. Metamath syntax summary" revised (esp. clarification of terms "token" and "symbol")
- Item "5. Other notes" enhanced by subitems 2. and 3. , esp. link to ~ conventions

Revision of other comments:
- conventions about theorem forms removed completely in section header of "Logical implication" (hint in header item "5. Other notes"  shpould be sufficient)
- conventions about theorem forms removed completely in theorem comment of  ~ a1d (hint in header item "5. Other notes"  shpould be sufficient)
- Item "Theorem forms" in comment of ~ conventions completely  revised (mainly according to the new Metamath book)
- Item "Suffixes" in comment of ~ conventions partially revised

See also issue #949.

### CODE REVIEW

**Comment by avekens** [comment]
@nmegill @david-a-wheeler could you review my changes first, please? Do you know how I can make you official reviewers of a PR in GitHub? There is the title "reviewers" at the right of the comments, but I do not know how to add somebody there (according to the Help of GitHub, there should be something to be clicked, but there isn't anything for me...).

**Comment by david-a-wheeler** [comment]
Nit:

>We prefer to write theorems in "deduction form" and avoid theorems in "inference form".  We call this approach "deduction style".

The antecedent is misleading. The phrase "this approach" seems to refer to inference form, and of course that is not what you meant.

**Comment by david-a-wheeler** [comment]
Overall I like this change however:

> In contrast, we avoid theorems in "inference form".

Seems a little strong. We try to avoid using inference form when that leads us to use the deduction theorem. Other than that, there certainly isn't a Prohibition against using inference form, and there are clearly many theorems in that form. Indeed, I think the week deduction theorem is kind of interesting, so I would hate to see its loss entirely.

So I would tweak that to say

> In contrast, we usually avoid theorems in "inference form" when that would end up would require us to use the deduction theorem.

**Comment by avekens** [comment]
I changed the texts a little bit, according to David's remarks. The "deduction style" should have been related to both: preferring (deduction form) AND avoiding (inference form). But if this is misleading, I agree with changing it (as I have done already).
Concering "avoiding the inference form": "to avoid" does not mean "to forbid", so it would still be allowed to use the inference form. Since in most cases, however, we do not know _in advance_ that we have to use the deduction theorem (as soon as we want/have to use the theorem in deduction form), the deduction form should be proven instead of the corresponding inference form. I made the experience several times (and Jon made the same experience recently, see Google group https://groups.google.com/d/msg/metamath/DDN4noc0TYU/GTq6zioxBwAJ ) that I needed an existing theorem to proof a new theorem but this existing theorem is only available in inference form, so that I could not use it immediately. Therefore, the inference form should only be used if there are good reasons for it (e.g. week deduction theorem).

**Comment by nmegill** [comment]
I am fine with these changes.

**Comment by david-a-wheeler** [comment]
@avekens - thanks!!

**Pull request merged**
