### PR TITLE
htmldefs althtmldefs latexdefs for my Mathbox

### PR DESCRIPTION
**Pull request by mazsa**
Inserted htmldefs althtmldefs latexdefs for Mathbox of Peter Mazsa.

### CODE REVIEW

**Comment by digama0** [comment]
This should probably be added to #2435, since it references definitions that were added in that PR.

**Comment by mazsa** [comment]
Yes it seems it lacks the c statements and w statements like
$c Rels $. $( The class of all relations $)
crels $a class Rels $.
Next time before I create a pull request I´ll run metamath.exe locally first. Thank you Mario.

**Comment by jkingdon** [comment]
> This should probably be added to #2435, since it references definitions that were added in that PR.

Yeah, or if we want to break it up into smaller pull requests, break it up in a way so that each one can pass the checks.

**Comment by benjub** [comment]
@mazsa : I suggest as a first PR, you can simply add your mathbox with a single theorem of yours. (The contribution date should probably be the day of the PR.)
```
$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
                Mathbox for Peter Mazsa
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
$)

  ${
    anbi2ri.1 $e |- ( ph <-> ps ) $.
    $( Introduce a left and the same right conjunct to the sides of a logical
       equivalence.  (Contributed by Peter Mazsa, 7-Mar-2020.) $)
    anbi2ri $p |- ( ( ch /\ ph ) <-> ( ps /\ ch ) ) $=
      ( wa anbi2i bian ) CAEBCABCDFG $.
  $}
```
**Edit**: actually, this should be labeled anbi1ci (look at anbi2ci for instance). Prove it with reference only to theorems in Main (that is, no bian).

**Comment by mazsa** [comment]
@jkingdon @benjub ok, I´ll do it, first I´ll learn some git because I want to reverse my changes locally in the appropriate way:)

**Pull request closed without merging**
