### PR TITLE
New theorem iseri; new approach for graph theory (continued)

### PR DESCRIPTION
**Pull request by avekens**
Main set.mm:
* ~iseri and ~iseriALT added, proofs of ~eqer, ~0er, ~ecopover, ~ener, ~gicer, ~phtpcer, ~vitalilem1, ~erclwwlk, ~erclwwlkn shortened
* ~elqsecl added

AV's Mathbox:
* ~clwwlksnbprop, ~clwwlksnwrd added
* proof of ~erclwwlks shortened
* revision of additional theorems for closed walks as words

### CODE REVIEW

**Comment by avekens** [comment]
There seems to be something wrong with http://us.metamath.org/mpegif/mmbiblio.html - Benoît's PR failed also because of this reason.

**Comment by avekens** [comment]
http://us.metamath.org/ is not accessible!

**Comment by benjub** [comment]
The error was triggered by 
> wget -N -q http://us.metamath.org/downloads/checkmm.cpp

and
> wget -N -q http://us.metamath.org/mpegif/mmbiblio.html

I have two questions (not related to us.metamath.org being down, but seeing these lines just made me wonder):
* maybe we should replace all "mpegif" with "mpeuni" (probably no big difference, but now mpeuni is the default) ?
* since the PRs are done to us2, maybe one should replace all "us" with "us2" ?

Maybe our continuous-integration wizard @david-a-wheeler can chime in !

**Comment by nmegill** [comment]
It looks like every mirror is down. 

us.metamath.org was temporarily pointed to at.metamath.org, when the real one was shut down due to a false virus positive.  But now at.metamath.org is down.

So I pointed us.metamath.org to the computer at my house for now.  It may take a few hours for the DNS to propagate.

**Comment by avekens** [comment]
OK, the checks are working again now...

**Comment by david-a-wheeler** [comment]
This is not the first time a problem with metamath.org has caused check failures.

Maybe we should set things up so that the checks will download everything from GitHub?

**Pull request merged**
