### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Achaemenid**
Since I copied from develop, I'm not sure why the one in the base branch is showing up as different?  But eh, it looks like the version I posted is newer... than the one I just downloaded... somehow.

### CODE REVIEW

**Comment by Achaemenid** [comment]
...aaaand I don't have the first clue why this failed.

**Comment by tirix** [comment]
Metamath is a bit picky with the formatting. 
For ~ dvreasin , you should move the distinct variables above the comment, so that the comment immediately precedes the theorem's $p statement.
For ~ areacirclem6 , it's the antecedents you have to move up, so that the comment with the "contributed by" is immediately before.
There seem to be tabs in your contribution, you should remove them.
Finally you'd have to change the date at the top of the file, but that's minor.

**Comment by Achaemenid** [comment]
Okay, I've fixed the issues, but now it's not being checked at all?

**Comment by digama0** [comment]
Okay, this PR is a bit mangled. Rather than try to sort it out within the PR, I've added it to a branch https://github.com/metamath/set.mm/tree/Achaemenid-develop for now, on which you can PR anything additionally and which I will clean up and merge shortly.

**Comment by david-a-wheeler** [comment]
Mario - thanks for doing that.

I'm looking forward to seeing these additions merged!

**Comment by digama0** [comment]
@david-a-wheeler Done f32ee2e

**Comment by digama0** [comment]
@Achaemenid The theorems have been added to the web site. I have to say, it's really a nice proof, not a lot of wasted work and good use of the library theorems. One suggestion: `areacirclem4` proves that the function in `areacirclem1` is continuous, from which `areacirclem1` follows trivially from `cniccibl`.

**Comment by Achaemenid** [comment]
I hadn't seen that one; I'm on it.  I'll move the lemma without renaming
it, since it's already been posted.

**Pull request closed without merging**
