### PR TITLE
Ceva's theorem

### PR DESCRIPTION
**Pull request by savask**
I've formalized Ceva's theorem, which is number 61 in the "Metamath 100" list. The proof is a "standard" one and can be seen, for example, in [wikipedia](https://en.wikipedia.org/wiki/Ceva%27s_theorem#Proof_of_the_theorem). It uses the concept of signed area (`sigar`), so some properties of it are proven. One of the most important is `sigarcol` which gives a way to test collinearity of points by computing a certain signed area, and I'm using that fact to restate the theorem of Ceva (`cevath`) in that language. Theoretically one could use `sigarcol` to state Ceva's theorem without signed area, but I guess it is already very convincing :-) I should also note that the final statement doesn't use absolute value of a complex number to express distances - it turns out that the identity in question can be written purely in "complex" form, so I decided to leave that small generalization.

Unfortunately the proof is not very short, so I decided to create a mathbox for myself and store the theorem there. I'm not sure if I got the order of mathboxes right, so I will be glad if someone would move it to a correct place, if I mixed things up.

And finally, this time I faithfully did a `metamath 'read set.mm' 'save proof */c/f' 'write source set.mm/rewrap'` incantation, but for some reason theorem statements are still longer than 79 symbols. I left it as is, I hope it is not very impudent of me :-)

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
Congrats! I will wait for Norm or Mario to confirm, and if so, update the metamath 100 info.

**Comment by nmegill** [comment]
On 9/24/17 6:01 AM, savask wrote:
> I've formalized Ceva's theorem, which is number 61 in the "Metamath 100" 
> list. The proof is a "standard" one and can be seen, for example, in 
> wikipedia 
> <https://en.wikipedia.org/wiki/Ceva%27s_theorem#Proof_of_the_theorem>. 
> It uses the concept of signed area (|sigar|), so some properties of it 
> are proven. One of the most important is |sigarcol| which gives a way to 
> test collinearity of points by computing a certain signed area, and I'm 
> using that fact to restate the theorem of Ceva (|cevath|) in that 
> language. Theoretically one could use |sigarcol| to state Ceva's theorem 
> without signed area, but I guess it is already very convincing :-) I 
> should also note that the final statement doesn't use absolute value of 
> a complex number to express distances - it turns out that the identity 
> in question can be written purely in "complex" form, so I decided to 
> leave that small generalization.
> 
> Unfortunately the proof is not very short, so I decided to create a 
> mathbox for myself and store the theorem there. I'm not sure if I got 
> the order of mathboxes right, so I will be glad if someone would move it 
> to a correct place, if I mixed things up.
> 
> And finally, this time I faithfully did a |metamath 'read set.mm' 'save 
> proof */c/f' 'write source set.mm/rewrap'| incantation, but for some 
> reason theorem statements are still longer than 79 symbols. I left it as 
> is, I hope it is not very impudent of me :-)

Thank you for this submission, and congrats on your work!

The /rewrap qualifier currently wraps only the text in the comment that 
directly precedes a $a or $p statement, and only if the comment doesn't 
have an <HTML> tag.  It used to wrap the math content as well, but there 
were complaints because the wrapping was "dumb" and produced bad line 
breaks, whereas a human can break and format the line for better 
readability.

Although there is no standard, I typically like to break lines at 
outermost connectives when possible, and also put the connective at the 
beginning of the next line, like:

|- ( ph
    -> ps )

|- ( 2 + 2 )
     = 4

|- ( 2
    + 2 ) = 4   [assuming that ( 2 + 2 ) overflows the line]

and indent according to the connective level:

|- ( 2
       + 2 )
     = 4

There is no standard for the number of indentation spaces per level.  I 
sometimes use 4 spaces for shorter expressions and 2 spaces for very 
long ones.  Tabs are discouraged because tab stops can't be guaranteed, 
and if tabs are used we will convert them to equivalent spaces assuming 
8 columns per tab stop (so a tab at column 5 will turn into 3 spaces).

Note that the too-long lines will be detected by 'verify markup */f', 
which you should do before submitting.  The Travis run failed for this 
reason.

I will fix the lines this time, but you can keep the above note for 
future submissions.

Norm

**Comment by savask** [comment]
@nmegill Okay, thank you very much!

For some reason I thought that maybe I screwed up the `/rewrap` command somehow so it didn't correct the statements automatically. From now on I will manually take care of my lines fitting in.

By the way, I'm not sure if it's a good place to state this, but shouldn't issues 89 and 86 be closed now? Corresponding theorems were formalized some time ago.

**Comment by david-a-wheeler** [comment]
Excellent! I will be updating the metamath 100 files.

**Comment by nmegill** [comment]
On 9/24/17 1:29 PM, David A. Wheeler wrote:
> Excellent! I will be updating the metamath 100 files.
> 

us2 has been updated, and I put the single file cevath.html on 
us.metamath.org in mpegif and mpeuni there to prevent a broken link. 
The full update on us.metamath.org will be in a day or so.

Maybe you can also change mpegif to mpeuni there while you are at it, to 
start the official transition to Unicode as the default.

Norm

**Comment by david-a-wheeler** [comment]
Norm: Will do! Great minds think alike, I was about to ask if you wanted me to switch to Unicode as the link reference.

@savask : congrats!

**Comment by nmegill** [comment]
One other Travis failure (that I've fixed) was the use of the theorem 
ax1cn, detected by the "discouraged" file.  ax1cn is a final theorem of 
the complex number construction and shouldn't be referenced directly; 
instead we should use ax-1cn.  I changed it to ax-1cn - you don't have 
to do anything.  Both metamath.exe and mmj2 now honor the "discouraged" 
tags, so perhaps you were using an old version of one of them.

I'm actually glad this happened because it showed that the discouraged 
file is doing its job and is our first "test case".  The fix was of 
course trivial so it's no big deal.

On 9/24/17 1:13 PM, savask wrote:
> @nmegill <https://github.com/nmegill> Okay, thank you very much!
> 
> For some reason I thought that maybe I screwed up the |/rewrap| command 
> somehow so it didn't correct the statements automatically. From now on I 
> will manually take care of my lines fitting in.
> 
> By the way, I'm not sure if it's a good place to state this, but 
> shouldn't issues 89 and 86 be closed now? Corresponding theorems were 
> formalized some time ago.

David, these are yours, do you want to close them out?

Norm

**Comment by david-a-wheeler** [comment]
I closed 89 and 86, thanks for reminding me!

**Pull request merged**
