### PR TITLE
Simplify ex-natded9.26; adds 19.8ad

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
I think this is a significant improvement in ex-natded9.26.  It adds a new deductive form of 19.8a, which I've named "19.8ad"; this addition creates a direct mapping of one of the rules of natural deduction, and thus is a more general improvement.

**Comment by digama0** [comment]
I wouldn't suggest doing it this way. 19.8a is not one of the rules of ND,
it is a special case of one of them. If you want a more exact translation,
you should use a4esbcd (which is the real translation of E.-I), together
with sbcid (with doesn't exist but is the sbc version of sbid, proven with
sbid and sbsbc). This makes it more obvious which substitution is being
used.

Perhaps we could come up with a different example theorem that uses
non-identity substitutions in E.-I and A.-E?

**Comment by david-a-wheeler** [comment]
I disagree.  It's a special case, but it's an *extremely* common special case, and it's clearly one that the author intends to apply directly (since he does).  In addition, the rule I added (19.8ad) is one that I think we should have anyway.

Perhaps most importantly, doing it this way provides a very clean one-for-one match between the ND proof and the metamath proof.  For someone new to the relationship of ND and metamath, this is a clearer and simpler map than the previous one, and I think it really helps.  Take a look at the resulting table - it's striking how clean the mapping is between the ND proof and the Metamath proof.

> Perhaps we could come up with a different example theorem that uses non-identity substitutions in E.-I and A.-E?

I think that's a good idea, but I think it should be an *additional* example.  People learn from having many examples. In addition, I would like to contrast "use this special case rule for this common case" vs. "here's the general rule, but it will require multiple steps".  From a pedagogical point of view, it's not hard to explain "here's a common special case, and here's the general case"... it can even clarify things.

The only quantifier examples in Daniel Clemente Laboreo's document are on the last page, 9.23 - 9.26, and we've already done 9.26 Do any of the others (9.23 through 9.25) have this property when rewritten in Metamath?

**Comment by david-a-wheeler** [comment]
Hmm, I had expected you to make a few comments & then pull it.  I don't agree with you that we should ignore this "special" case - I believe this is an extremely common case.  And the alternativ you mention doesn't even exist in set.mm.

I think the best way forward is to try out different approaches to ex-natded9.26 and put them all in one file.  Then we can do a clearer comparison.  In addition, we should do a few other examples.

However, it's a pain to create alternatives to ex-natded9.26 while it's in the main body.  mmj2 quickly notices that it's already proved, and "proves" alternatives by using what's in the main body.  So I intend to temporarily move ex-natded9.26 back into my mailbox.  We can then try out various alternatives to our hearts' content.

I'll close this pull request (without merging) once I've pulled it apart.

**Pull request closed without merging**
