### PR TITLE
Improve ordinal topology

### PR DESCRIPTION
**Pull request by jdh8**
As ~eltg3i is proven, the previously proved ~unieltg is no longer needed.

In antecedents, every applicable `A e. On` is changed to `Ord A` becuase the
latter forms a stronger theorem.

Whether an ordinal topology is T<sub>0</sub>, T<sub>1</sub>, or Hausdorff is proved.

### CODE REVIEW

**Comment by digama0** [comment]
Remarks: The usual terminology for this topology is not "order topology" (which is the topology generated by open intervals, in main set.mm as 'ordTop'), but rather "left order topology" (generated by left-unbounded intervals (+oo, x)), and it is applicable generally to any order. (I am working on a new version of order theory development, after that we might want to consider a 'leftOrdTop' definition and relate it to your ordinals-as-topologies work.)

It is good that we have specific results on 2o as a topology, because that is a nice short way to specify a space homeomorphic to the Sierpinski topology (although usually 1 is taken as the open set, not 0). Perhaps you might want to see how many of the properties on Wikipedia follow as special cases of your theorems.

**Comment by jdh8** [comment]
Should I change the name to “[ordinal space](https://en.wikipedia.org/wiki/Order_topology#Ordinal_space)”?

Sierpiński topology is homeomorphic to 3<sub>o</sub>, as the set of all open sets.  We can define *the* Sierpiński topology as (Clsd ‘ 3<sub>o</sub>).

I can also start proving theorems for 3<sub>o</sub> like we did for 2<sub>o</sub>.  There is no theorem referencing [df-3o](http://us.metamath.org/mpegif/df-3o.html) yet.  These theorems may also shorten ~onint1 as it contains “suc 2<sub>o</sub>”.

**Comment by sorear** [comment]
These aren't ordinal spaces either; the ordinal spaces are always Hausdorff.  `` ( ordTop ` [_ ( aleph ` 1o ) / a ]_ { x e. a , y e. a | x C_ y } ) `` would be a standard example of an ordinal space in the sense Wikipedia uses the term.

**Comment by jdh8** [comment]
Oops, you are right; I am confused.  I thought that not only **points** but also **the space** is ordinal, so I work on (On ∩ Top). (I have not proved this yet.)

Let's rename this section to *ordinals as topology*, shall we?

By the way, because (A ∩ B) is A or B when A and B are ordinals (the intersection version of [ordequn](http://us.metamath.org/mpeuni/ordequn.html)), ℘On ⊆ TopBases. This is the most general case.

**Pull request merged**
