### PR TITLE
minor edits of gource-captions.txt and OTHER-DATABASES.md

### PR DESCRIPTION
**Pull request by benjub**
Edits of gource-captions.txt following (and closing) #2396.

Edits of OTHER-DATABASES.md: alphabetical sort, addition of all databases mentioned in #2384 (@naipmoro's and @tirix's second), removal of the tilde in front of "@sctfn" (I hope it's ok), and modification of the description of @sorear's database (I hope it's ok too). There remains the question of the file name (SHOUT-CASING it or not), as indicated by @digama0.

### CODE REVIEW

**Comment by sctfn** [comment]
No worries with tilde removal for me.

**Review by tirix — APPROVED** [review]

**Comment by david-a-wheeler** [comment]
I agree with @digama0 that we should rename it from shout-casing. Feel free to do that in this pull request, or it can be done separately.

**Review by david-a-wheeler — APPROVED** [review]

**Comment by david-a-wheeler** [comment]
@benjub - +1 on renaming those two files from shoutcase. It all looks good to me.

**Comment by david-a-wheeler** [comment]
We have 2 approvals, I'll just merge this.

**Pull request merged**
