### PR TITLE
Prove fineqvrep and fineqvpow

### PR DESCRIPTION
**Pull request by BTernaryTau**
fineqvrep

> If the Axiom of Infinity is denied, then the Axiom of Replacement becomes redundant.

fineqvpow

> If the Axiom of Infinity is denied, then the Axiom of Power Sets becomes redundant.

### CODE REVIEW

**Review by icecream17 — APPROVED** [review]
(mathbox only)

**Review by avekens — APPROVED** [review]
Very interesting results!

**Comment by langgerard** [comment]
It seems that the theorem unifi (8851) also proves that if the Axiom of Infinity is denied, then the Axiom of Union becomes redundant. And I think that it is also the same concerning the Axiom of Choice.

**Comment by BTernaryTau** [comment]
Yes, the Axiom of Choice would also be redundant. I thought set.mm already had a theorem for this, but it looks like all it has is a comment in [fineqv](https://us.metamath.org/mpeuni/fineqv.html), so I'll probably prove that too.

If you look at the page for [unifi](https://us.metamath.org/mpeuni/unifi.html), there's a section below the proof that shows which axioms it relies on. Since [ax-un](https://us.metamath.org/mpeuni/ax-un.html) is present in that list, it cannot be used to prove that the Axiom of Union becomes redundant.

**Review by tirix — APPROVED** [review]

**Comment by jkingdon** [comment]
> Yes, the Axiom of Choice would also be redundant. I thought set.mm already had a theorem for this

This might already be your plan, but ` Fin = _V -> CHOICE ` would be a nice notation.

**Comment by BTernaryTau** [comment]
Yep, I already have a proof in the works using that notation, and I'll probably include a short alternate proof as well since I'm still trying to avoid ax-rep and ax-pow in the first one (which means I can't use any of the nice equivalence theorems).

**Comment by langgerard** [comment]
Notably because fineqv, and also the definition of a finite ordinal, use the Axiom of Union it finally seems that wa cannot hope to prove it from the negation of the Axiom of Infinity.
But maybe we can try to prove the Axiom of Regularity/Foundation as follows.
Because (/) is in Fin=V and also the power set P(x) if x is in V, every finite iteration of the power set operation applied to the empty set will be a set in V=Fin.
But such a set will be a finite level of the Cumulative Hierarchy of sets. So that every Class R1’(n) will be a set in V, and that the union of these, being R1’(Omega) will be a class included in V (but not a set, because then its power set would be a set a Omega would be a set in Fin. We then have that the class R1(Omega) is included in V=Fin, so that every finite ordinal n is also a set R1’(Omega).
Also, the size of the set P^n(0) will be /P^0((0)/ = 0 and /P^n(0)/ = 2^(n-1) for n > 0, so will be a finite ordinal. But as every set in R1’(Omega) is included in a set P^n(0), such a set will be bijective with some finite ordinal, so will be a member of the class Fin=V. So that finally Fin = V = R1’(Omega) and ax-reg will be valid on  V.

**Pull request merged**
