### PR TITLE
Banach and Hilbert spaces

### PR DESCRIPTION
**Pull request by benjub**
Everyone, and especially @avekens : this is a heads up that I'm going to split the subsection "Banach & Hilbert".

In this first commit, I saw that some labels do not respect the convention(?) cxxx/df-xxx for the syntax/definition labels
```
cxmt/df-xmet
cme/df-met
cxme/df-xms
cmt/df-ms
ctmt/df-tms
cca/df-cau
cms/df-cmet
chs/df-hil
```
I propose to relabel to:
```
cxmet/df-xmet
cmet/df-met
cxms/df-xms
cms/df-ms
ctms/df-tms
ccau/df-cau
ccmet/df-cmet
chil/df-hil
```

### CODE REVIEW

**Review by avekens — APPROVED** [review]

**Comment by benjub** [comment]
For the latest commit: let's pretend that the revision and the shortening were just one thing.

**Comment by benjub** [comment]
Good with you, @avekens ? (since there are global changes, I'm a bit worried of merge conflicts, so the sooner we merge, the better)

**Comment by avekens** [comment]
What is the meaning of the label change "chil-->chba"? There are a lot of changes in the commit.

**Comment by benjub** [comment]
> What is the meaning of the label change "chil-->chba"? There are a lot of changes in the commit.

What used to be `chil` was the syntax axiom for the definition `df-hba`, and I needed to "free" that label in order to give that label to the syntax axiom for the definition `df-hil` (which was `chs`).

**Comment by benjub** [comment]
> There are a lot of changes in the commit.

`chba` is the first label of `PART 19  COMPLEX HILBERT SPACE EXPLORER (DEPRECATED)` so it is basically used everywhere in that part (its last usage is in `cdj3i`, which is the last statement of that part).

**Review by avekens — APPROVED** [review]
Because there are so many changes, I could not check everything in detail. But what I checked is OK.

**Comment by benjub** [comment]
> Because there are so many changes, I could not check everything in detail. But what I checked is OK.

Thanks. The changes are large, but each commit is the result of an automatic "search and replace", and I was careful (case sensitive, keyword preceded and followed by a space).

**Pull request merged**
