### PR TITLE
2reu1-2reu8

### PR DESCRIPTION
**Pull request by avekens**
analogons to 2eu1 up to 2eu8 for double restricted existential uniqueness, and supporting theorems (in Mathbox for Alexander van der Vekens)

### CODE REVIEW

**Comment by nmegill** [comment]
Hi Alexander,

The Travis check fails "verify markup *" with some simple errors you can fix:

MM> verify markup *
Checking statement label conventions...
?Warning: Line number 435762 has 80 characters (should have 79 or less):
        $( An equivalent expression for restricted existence, analogous to ~...
?Warning: Line number 435768 has 81 characters (should have 79 or less):
        $( An equivalent expression for restricted existence, analogous to ~...
?Warning: Line number 435844 has 80 characters (should have 79 or less):
        $( Rearrange restricted quantifiers with two different restricting c...
?Warning: Line number 436058 has 81 characters (should have 79 or less):
        $( Two equivalent expressions for double restricted existential uniq...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
?Warning: The label token "moanim." (referenced in comment of statement
"rmoanim") is not a $a or $p statement label.
?Warning: The label token "2euex." (referenced in comment of statement
"2reurex") is not a $a or $p statement label. 

Note that to check these yourself, you can use "verify markup * /f"  (the /file_skip means to tolerate GIF files not being present during the htmldef check).

Can you fix these and do another pull request?

Thanks,
Norm

**Comment by avekens** [comment]
Hi Norman,
I have fixed all errors, pull request PR #124 has passed Travis CI build #622 successfully now.
Since this was my first pull request, it was clear that I made errors. However, I learned a lot by these...

Thanks for your patience,
Alexander

**Comment by david-a-wheeler** [comment]
Hi - this commit included a commit of "metamath.exe", which I'm certain was not intended.  I'll fix that.

It also added files "mathbox_av.mm" and "set_wo_mb_av.mm", which almost certainly should not have been added either.

I realize that this was your first pull request, and even experts make mistakes (!).  That said, in the future, please don't add to these git repos any files that aren't intended to be shared by others.

**Comment by avekens** [comment]
Hi David,
yes, sorry for that - I saw this already and hoped it was only on my local "view". Please remove these three files from the git repository wherever it is needed. I will be more careful in the future...

Thanks,
Alexander

**Comment by david-a-wheeler** [comment]
Sure, no trouble. And thanks for your work. As penance, I'm hoping you'll add proofs from the metamath 100 list :-).

**Pull request merged**
