### PR TITLE
Symbol spaces fixed

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
Pull this *instead* of #785 - I simply fixed the merge conflicts.

**Comment by david-a-wheeler** [comment]
@nmegill - merge this instead of #785 .

@benjub - this is just your changes PLUS fixes to the merge conflicts.

**Comment by benjub** [comment]
@david-a-wheeler Thanks a lot.  I'll try to follow your advice in #785.  It sounds like I should create a new branch each time?  How to delete them once the commit is done?  I would like to have as little divergence with metamath/set.mm as possible, and always do single, simple and small commits each time (I would have no use in having parallel branches for two different projects, for example).

**Comment by david-a-wheeler** [comment]
Yes, create a branch each time for each different change.  That makes it much easier to handle them separately (e.g., maybe one is accepted and the other is not).  Branches are basically free in git, so use as many as you want.  You can delete a branch (once merged) using `git branch -d BRANCHNAME` .  To be honest, I often don't bother, but you can certainly do that.

**Comment by david-a-wheeler** [comment]
You can also delete branched in the GitHub API, though that only deletes it on GItHub's end.

**Pull request merged**
