### PR TITLE
Add inference lemmas for natural numbers

### PR DESCRIPTION
**Pull request by metakunt**
Yeah, those will save me headache.

### CODE REVIEW

**Review by wlammen — APPROVED** [review]

**Review by tirix — APPROVED** [review]

**Comment by metakunt** [comment]
Merge it at your leisure, I'll open a new merge request once merged.

**Comment by metakunt** [comment]
I'm happy with that one.

**Comment by wlammen** [comment]
Two reviewers approved this contribution in an early stage, assuming the work was already done.  There is no point in reviewing something that is still in progress, and revisiting the same pull request over and over again -- I want to review a final state.
If you haven't finished your work yet in a pull request already visible here, either don't make long pauses, or mark your pull request as a draft, or add a comment indicating more is about to follow.

**Review by wlammen — APPROVED** [review]

**Comment by metakunt** [comment]
Yeah, good point. I'll keep that in mind in the future.

**Review by tirix — APPROVED** [review]

**Comment by mazsa** [comment]
@metakunt welcome:) Regarding @wlammen comment, and @avekens 's question in https://github.com/metamath/set.mm/pull/3955#pullrequestreview-2021435724 , I think the best solution is to work in a kind of stealth mode on your home at https://github.com/metakunt , i.e. only open a pull request on https://github.com/metamath when you have reached a stage, say a theorem that is at least moderately important to the community. When you reach that stage, the theorem automatically governs what you include in the PR: it may be the best you keep the preparatory theorems that are necessary and sufficient for your significant theorem. I think this rule is not explicit, and if you are deeper in the community you can break this "rule", but you can consider this a nice default.

**Pull request merged**
