### PR TITLE
Proof that 9 + 10 is not equal to 21

### PR DESCRIPTION
**Pull request by BTernaryTau**
> 9 + 10 is not equal to 21. This disproves a popular meme which asserts that 9 + 10 does equal 21. See https://www.quora.com/Can-someone-try-to-prove-to-me-that-9+10-21 for attempts to prove that 9 + 10 = 21, and see https://tinyurl.com/9p10e21 for the history of the 9 + 10 = 21 meme.

### CODE REVIEW

**Comment by avekens** [comment]
That's a nice contribution. Maybe there is a "proof" (under certain conditions) that "9 + 10 = 21" which can be formalized with metamath (and then placed in section 17.2 "Humor"), see, for example, [~topnfbey](https://us.metamath.org/mpeuni/topnfbey.html).

**Comment by wlammen** [comment]
One could use this proof along with https://us.metamath.org/mpeuni/avril1.html to prove (via 2th)  ( Fool <-> ( 9 + 10 = 21) ) . This creates a connection to the "You're stupid" portion of the meme

**Comment by avekens** [comment]
> One could use https://us.metamath.org/mpeuni/avril1.html to prove ( Fool <-> ( 10 + 9 = 21) ) . This creates a connection to the "You're stupid" portion of the meme

Absolutely great! With "Fool" you mean "𝐹∅(0 · 1)", don't you? As part of the proof of avril1, it is shown that ¬𝐹∅(0 · 1) holds.

**Comment by avekens** [comment]
I think ~2false (based on ~2th) can be used for the proof.

**Comment by wlammen** [comment]
Writing a good comment takes perhaps more time than doing the proof.

**Comment by avekens** [comment]
Maybe: "Only a fool (thinks that he) can prove that 10 + 9 = 21".

**Review by tirix — APPROVED** [review]

**Comment by wlammen** [comment]
I added a version wl-fool in my mathbox covering part of the discussion here #3434

**Review by avekens — APPROVED** [review]

**Comment by avekens** [comment]
~9p10ne21 together with wf-fool (maybe as ~9p10e21fool or ~9p10e21stupid) can be moved to main in the context of PR #3434.

**Review by jkingdon — APPROVED** [review]

**Comment by benjub** [comment]
Closing since subsumed by #3439.

**Pull request closed without merging**
