### PR TITLE
Add proofs of Aristotelian logic's Barbara, Celarent, and Darii - DO NOT MERGE

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Add proofs of some Aristotelian logic syllogisms
  to David A. Wheeler's mathbox.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
I'm not sure these are the best way to represent these syllogisms in metamath, and the Darii proof is overlong I'm sure, but it's a start.

**Comment by david-a-wheeler** [comment]
Hmm, the Darii proof could probably be simpler using exim, and I forgot that premise comments aren't included in the HTML.  Still, please pull anyway.  I'd like comments on whether or not the notation used here accurately captures the Aristotelian syllogisms.  There are several ways to write them in Metamath, and I'm not sure what's best.  Many books write them as predicates; it seems to me that mapping predicates to "exists" is a fair mapping, and that dropping unnecessary "for-all" statements makes things simpler.  But maybe others disagree.

**Comment by digama0** [comment]
These expressions seem a bit odd.

* Barbara: I don't understand why "Socrates is a man" is translated to `( x e. S -> x e. M )`. Wouldn't a more faithful rendering be `|- S e. M` & `|- A. x ( x e. M -> x e. R )` => `|- S e. R` (where `S` is Socrates, `M` is "man", and `R` is "mortal"). The proof of this one is easy using ssriv and sselii, although that might use some set theory (mainly for the vtocl application).
* Celarent: Using `S` for "snake", `R` for "reptile", and `F` for "has fur", you could represent the statement as `|- A. x ( x e. S -> x e. R )` & `|- -. E. x ( x e. R /\ x e. F )` => `-. E. x ( x e. S /\ x e. F )`, which directly translates the natural language quantifiers. In this as with Barbara, I would not recommend using the "implicit forall" convention used by metamath since this is not used in conventional logic (unless you are trying to avoid quantifiers altogether, in which case you should be using propositional variables). The amended statement can be proven using mto, eximi, anim1i, a4i.
* Derii: This translation is definitely incorrect; `E. x ( x e. A -> ph )` is almost never a useful statement (recall that ` E. x e. A ph` abbreviates `E. x ( x e. A /\ ph )`, while `A. x e. A ph` means `A. x ( x e. A -> ph )`). I believe this should be `A. x ( x e. R -> x e. F )` & `E. x ( x e. P /\ x e. R )` => `E. x ( x e. P /\ x e. F )`. The statement can be proven using ax-mp, eximi, anim2i, a4i.

**Comment by david-a-wheeler** [comment]
> might use some set theory (mainly for the vtocl application).

I don't see that I can easily avoid it.  I'd like them to be potentially useful, and since so much uses class theory and sets, anything else would be problematic.

> Celarent: Using S for "snake", R for "reptile", and F for "has fur", you could represent the statement as |- A. x ( x e. S -> x e. R ) & |- -. E. x ( x e. R /\ x e. F ) => -. E. x ( x e. S /\ x e. F ), which directly translates the natural language quantifiers. In this as with Barbara, I would not recommend using the "implicit forall" convention used by metamath since this is not used in conventional logic (unless you are trying to avoid quantifiers altogether, in which case you should be using propositional variables).

Ok, good feedback.  My first try used explicit quantifiers, but I dropped them under the theory that this version was simpler.  Trivially restored.

> Darii: This translation is definitely incorrect; E. x ( x e. A -> ph ) is almost never a useful statement...

Whups, quite right. I will blame it on the late time.

> I believe this should be A. x ( x e. R -> x e. F ) & E. x ( x e. P /\ x e. R ) => E. x ( x e. P /\ x e. F ). The amended statement can be proven using ax-mp, eximi, anim2i, a4i

Sensible!
Thanks.

**Comment by david-a-wheeler** [comment]
> Wouldn't a more faithful rendering be |- S e. M & |- A. x ( x e. M -> x e. R ) => |- S e. R (where S is Socrates, M is "man", and R is "mortal")

Sure, that makes sense. I wasn't sure about the best way to represent a predicate.  Some texts use "subset of", but in set.mm "member of" seemed a better match.

**Comment by digama0** [comment]
> Sure, that makes sense. I wasn't sure about the best way to represent a predicate.  Some texts use "subset of", but in set.mm "member of" seemed a better match.

Metamath uses wff metavariables (`ph`, `ps`) to represent predicates. If you are concerned about indicating dependence on `x`, this is done simply by not having a disjointness requirement between `x` and `ph`.

**Comment by david-a-wheeler** [comment]
This is really a question of "how to best model Aristotelian logic in set.mm" - which is a little tricky, because they are really different systems.

I understand the advantages of using class variables and set operations, but I'm starting to think I should just use wff variables.  Using wff variables makes these much more flexible.  Using "e." is potentially annoying if the more natural operation is "=" or "C_". I get the impression that Aristotelian logic users would have used any of "e.", "=", or "C_" and still used terms like "Barbara".  In addition, if I directly use wff variables, then these theorems are very obviously *just* logic, making it much clearer that Aristotelian logic is the precursor to modern predicate logic.

If I did that, it'd be:
* Barbara: |- A. x ( ph -> ps )  & |- A. x ( ps -> ch ) => |- A. x ( ph -> ch ).   Then I could represent "Socrates is a man" as "x = S" (if S=Socrates) and "Socrates is mortal" as "x e. M" (if M is the set of mortal things).
* Celarent: |- A. x ( ph -> -. ps ) & |- A.  x ( ch /\ ph ) => -. E. x ( (ch /\ ps ) : e.g.,, No reptiles have fur. (MeP), All snakes are reptiles. (SaM), therefore No snakes have fur. (SeP)
* Darii: |- A. x ( ph -> ps ) & |- E. x ( ch -> ph ) => |- E. x ( ch /\ ps ) e.g, All rabbits have fur. (MaP),  Some pets are rabbits. (SiM), therefore Some pets have fur. (SiP)

I haven't checked; some of these statements may already be in set.mm (it'd be surprising if they weren't).

**Comment by david-a-wheeler** [comment]
I'll create a new pull request based on this discussion.

**Pull request closed without merging**
