### PR TITLE
Shorten pilem2/pilem3

### PR DESCRIPTION
**Pull request by benjub**
Remove extraneous hypothesis from pilem2 and shorten pilem3, as discussed in #2648.

(to give a rough idea: compressed block in proof of pilem3 shortened from 18 to 16 lines)

### CODE REVIEW

**Comment by savask** [comment]
If it's not too much of a hassle, I suggest running `minimize */allow */no_new ax-*` on each modified proof. It shortens `pilem2` by 2 bytes, and I feel that removing unused hypotheses might open new avenues for minimization in other cases.

**Comment by benjub** [comment]
@avekens or @jkingdon : this PR is pretty straightforward, but for good form, I'd prefer to get an approval before merging. Thanks !

**Comment by jkingdon** [comment]
> @avekens or @jkingdon : this PR is pretty straightforward, but for good form, I'd prefer to get an approval before merging. Thanks !

The delay was that I wanted to do the git branching stuff to look at the web rendering of the new pilem3 proof. Looks quite nice, that the π < 𝑥 condition just goes away from a whole bunch of steps.

**Review by jkingdon — APPROVED** [review]

**Review by avekens — APPROVED** [review]

**Comment by benjub** [comment]
> > @avekens or @jkingdon : this PR is pretty straightforward, but for good form, I'd prefer to get an approval before merging. Thanks !
> 
> The delay was that I wanted to do the git branching stuff to look at the web rendering of the new pilem3 proof. Looks quite nice, that the π < 𝑥 condition just goes away from a whole bunch of steps.

I'm looking forward to seeing it too (that's why I kept the OLD version for comparision), but for that one needs to have it merged first, no ? Or do you mean you downloaded the unmerged branch and generated the html locally ? (just out of curiosity)

**Comment by jkingdon** [comment]
> Or do you mean you downloaded the unmerged branch and generated the html locally ? (just out of curiosity)

That's what I did on this occasion. But agreed that it is simpler to wait for the pull request to be merged. I suppose some day we could build a way to serve web pages from branches at a click, which would be very cool but would presumably involve a fair bit of writing scripts and spinning up servers on demand and the like.

**Pull request merged**
