### PR TITLE
Prove rest of the Stoic indemonstrables in David A. Wheeler's mathbox

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by nmegill** [comment]
Normally, the required format for a reference is "[Sanford] p. 9", not 
"[Sanford] page 9".

There is another issue, though, that you should be aware of:  the bib 
xref mmbiblio.html needs a theorem (or axiom) to cross-reference to.  If 
"[Sanford] p. 9" is in a section header, there is no theorem to link to, 
so it won't appear on the xref page but is only checked for existence in 
mmset.html ref list.  In that case there is no requirement for a page 
number; "[Sanford] page 9" or even "[Sanford] aslkjlj" is legal (passes 
'verify markup *") in a section header since everything after 
"[Sanford]" is ignored.  I would still use "p. 9" and not "page 9" for 
visual consistency with everything else.

You may want to consider moving the refs to theorem/axiom comments 
whenever appropriate in order to appear on the xref page.

**Comment by david-a-wheeler** [comment]
Okay, I added some citations in actual theorems, and changed the page citations to match the expected format.  Thanks for the info!

**Comment by digama0** [comment]
Your checks are failing. Also, could you rename `mpt` -> `mpto`? The `mpt` label fragment is already in use for the mapping operation, and `mpt2` is the two-arg mapping operation.

**Comment by david-a-wheeler** [comment]
Will fix!  (I'm not sure why it's saying "?Warning: Bibliography keyword missing in comment for "mpt1"." - but I imagine it's something trivial.)

New names are just fine.  If you have particular names you'd suggest, please mention them.  I've now learned that there are two slightly different rules that are both called "modus tollendo ponens".  Historically "or" meant "exclusive or", but more recently "or" is interpreted as "inclusive or".  Since both versions are true, both versions ended up with the same name :-(.  I think I'll just prove both versions, and give them "-or" and "-xor" suffixes to differentiate them since set.mm (and most logicians) presumes that "or" means inclusive.

**Comment by digama0** [comment]
Huh? I did suggest a specific renaming: `mpt1` -> `mpto1` and `mpt2` -> mpto2`.

**Comment by nmegill** [comment]
On 7/3/16 11:08 PM, David A. Wheeler wrote:
 > Will fix! (I'm not sure why it's saying "?Warning: Bibliography keyword
 > missing in comment for "mpt1"." - but I imagine it's something trivial.)

See
https://groups.google.com/d/msg/metamath/nw13eXk8gWc/_pKt5DyJCwAJ
https://groups.google.com/d/msg/metamath/nw13eXk8gWc/iAIpOSCNCwAJ

Also, from 'help write bibliography' in the metamath program:


A name in square brackets in a statement's description (the comment
before a $a or $p statement) indicates a bibliographic reference.  The
full reference must be of the form

     <keyword> <identifier> <noise word(s)> [<author>] p. <nnn>

There should be no comma between "[<author>]" and "p.".  Whitespace,
comma, period, or semicolon should follow <nnn>.  Example:

     Theorem 3.1 of [Monk] p. 22,

The <keyword>, which is not case-sensitive, must be one of the following:

     Axiom, Chapter, Compare, Condition, Corollary, Definition, Equation,
Press <return> for more, Q <return> to quit, S <return> to scroll to end...
     Example, Exercise, Figure, Item, Lemma, Lemmas, Line, Lines,
     Notation, Part, Postulate, Problem, Property, Proposition, Remark,
     Rule, Scheme, Section, Theorem

The <identifier> is optional, as in for example "Remark in [Monk] p. 22".

The <noise word(s)> are zero or more from the list:  from, in, of, on.
These are ignored when generating the bibliographic cross-reference.

The <author> must be present in the file identified with the
htmlbibliography assignment (e.g. mmset.html) in the database $t comment,
in the form <A NAME="<author>"></A> e.g. <A NAME="Monk"></A>.  The
<nnn> may be any alphanumeric string such as an integer or Roman numeral.

**Comment by david-a-wheeler** [comment]
@nmegill - thanks for the information. I have done this before, but obviously it's been awhile. I will fix that, my fault.

**Comment by david-a-wheeler** [comment]
Ok, with these additional tweaks, it works without complaint.  I ended up adding an extra theorem, because historically "or" meant "exclusive-or" in Stoic thought, but over time people have used "inclusive-or" for modus tollendo ponens.  I proved both versions, covering all cases.

**Pull request merged**
