### PR TITLE
'MM> save proof * /compressed' on set.mm and iset.mm

### PR DESCRIPTION
**Pull request by benjub**
Done after noticing the problem in https://groups.google.com/g/metamath/c/B9_PEy8YjU4

### CODE REVIEW

**Comment by wlammen** [comment]
As far as I am concerned, this PR is okay.  Since it fiddles with mathboxes, I do not want to override the consent of their owners (in particular GS) here.

**Review by tirix — APPROVED** [review]
Since only `~fvmpt4` is changed, and the change is minor (shortening) I think it's OK.
Pinging @glacode : is this change OK for you?

**Comment by benjub** [comment]
As for automatic modifications in mathboxes, https://us.metamath.org/mpeuni/mathbox.html says:
> [...] occasionally other people may make maintenance edits to your mathbox for things like keeping it synchronized with the rest of set.mm, reducing proof lengths, moving your theorems to the main part of set.mm when needed, and fixing typos or other errors

(but indeed I could have pinged @glacode)

Also, ping @expln since this concerns some theorems for which you found shorter proofs.

(and ping @jkingdon since I moved ~djudom in iset.mm. It didn't find that theorem in set.mm though.)

**Comment by wlammen** [comment]
I yesterday opened the zip file of expln to see what he thinks could be done in my mathbox, and if I remember right, he suggested a shortening of wl-impchain-com-1.2.  While this shortening is possible, the proof layouts of this and similar theorems follow a repetitive pattern I deliberately established, and the shortening simply disturbs this pattern.  The pattern is announced in wl-section-impchain.  Here we have an example where you cannot interfere with the contents of a mathbox from the outside in an automated way.  I don't know how to balance the protection expressed in the idea of an 'own mathbox' against the wish to ease maintenance best.

**Comment by avekens** [comment]
> I yesterday opened the zip file of expln to see what he thinks could be done in my mathbox, and if I remember right, he suggested a shortening of wl-impchain-com-1.2. While this shortening is possible, the proof layouts of this and similar theorems follow a repetitive pattern I deliberately established, and the shortening simply disturbs this pattern. The pattern is announced in wl-section-impchain. Here we have an example where you cannot interfere with the contents of a mathbox from the outside in an automated way. I don't know how to balance the protection expressed in the idea of an 'own mathbox' against the wish to ease maintenance best.

In such cases, the "(Proof modification is discouraged.)" tag should be added to the comment. All automatizations should respect this tag.

**Review by avekens — APPROVED** [review]

**Comment by glacode** [comment]
As far I can see, it just shortens a proof in my mathbox. It's fine for me.

I'm currently not keeping "longer than needed" proofs for particular purposes, so feel free to shorten other proofs in my mathbox, without waiting for my approval.

Of course, please, advise me if any proof "contract" was going to change.

Thanks in advance
Glauco

**Comment by glacode** [comment]
> In such cases, the "(Proof modification is discouraged.)" tag should be added to the comment. All automatizations should respect this tag.

I agree, I would use "(Proof modification is discouraged.)" if any of my proof had to stay as is.

**Comment by wlammen** [comment]
I don't know whether the modification discouraged tags were in place in 2019 when I wrote this series of theorems.  I could have updated my mathbox meanwhile, though.  I still feel uneasy, because my personal expectation is that it is somehow my private area, where I set up the rules.  Then there might be math box owners who abandon their mathbox for a year or so, because they are busy in other projects, and are surprised by the fresh state afterwards.
In the end I don't see a compelling reason why automation tools MUST cover mathboxes.

**Comment by benjub** [comment]
> my personal expectation is that it is somehow my private area, where I set up the rules.

Yes, to the extent described in https://us.metamath.org/mpeuni/mathbox.html.  If you want a closer control, add the `(Proof modification is discouraged.)` tag, and for a totally personal mathbox, https://us.metamath.org/mpeuni/mathbox.html suggests a local branch.

> In the end I don't see a compelling reason why automation tools MUST cover mathboxes.

The parsings, scannings, analyses... done by the CI have to churn the whole file, including mathboxes. Hosting of the website is for (pages generated by) the whole file, including mathboxes. It is therefore consistent that maintenance and other automations are done for the whole file, including mathboxes. Additionally, this allows to reduce computation times and storage space requirements (albeit slightly).

**Comment by jkingdon** [comment]
> and ping @jkingdon since I moved ~djudom in iset.mm. It didn't find that theorem in set.mm though

That move looks fine (don't really know how it ended up under a section header which didn't describe it).

If memory serves there are a number of disjoint union theorems we could move from iset.mm to set.mm, but I suppose that waits until someone gets some inspiration or needs them in set.mm. Some day we might want to revamp cardinal addition to use the disjoint union notation and theorems for example.

**Comment by jkingdon** [comment]
As for mathbox modification, I encourage the kinds of cleanups to my mathbox described at https://us.metamath.org/mpeuni/mathbox.html . Can't speak for anyone else, but at least for me this makes it easier, not harder, for me to pick up up work on these theorems in the future if I do so.

**Comment by benjub** [comment]
> If memory serves there are a number of disjoint union theorems we could move from iset.mm to set.mm, but I suppose that waits until someone gets some inspiration or needs them in set.mm.

Yes, I remember when we did some joint work on disjoint union, and I was worried that we first did a few things in iset.mm that we wanted to port to set.mm, but I haven't got around to doing it yet.

**Comment by wlammen** [comment]
I am not sure whether I am understood here.  The CI process MUST ensure SYNTACTICAL correctness.  At one's option it might execute SEMANTIC changes as well, but since this is an option, it is not compelling any more.
If a process can respect a modification discouraged tag, it can likewise deal with mathboxes, this is an implementation detail.
From the discussion in this thread, I see that many, if not a majority, is in favor of allowing semantic changes in mathboxes, not only by CI, but also by foreign manual interaction, and that the modification discouraged tag is sufficient to prevent the most unwanted side effects.  Well, yes, but this is an option, so open to discussion and evaluation.

**Comment by benjub** [comment]
You're right, there is no strong boundary and these matters are open to discussion and evaluation.

My point is that if our processes take time to read and parse the whole database, and if our website takes space to store theorem pages for the whole database, then it is legitimate to let it also do automatic minimizations, since longer proofs are a burden on both computation times and storage space.

**Pull request merged**
