### PR TITLE
move bj-spvv to main (as spvv)

### PR DESCRIPTION
**Pull request by icecream17**
spvw already exists, it's a version of sp

(add sp : spvw; spv : spvv notes)

auto use spvv in place of spv and bj-spvv
in both cases they were noted in bj's mathbox, so add tags to clarify origin

update bj-ru0 now that + spvv and - ax-13

sidenote: nalset is quite related to ru, through ruv vprc

### CODE REVIEW

**Comment by wlammen** [comment]
The important observation here is that ru, nalset need not depend on ax-13.

Is this a good reason enough to override the instruction of not changing the proof?   In my eyes yes.

**Review by wlammen — CHANGES_REQUESTED** [review]
`$( $j usage 'ru' avoids 'ax-reg'; $)` should include ax-13.

**Review by wlammen — APPROVED** [review]

**Comment by wlammen** [comment]
Still a merge conflict to resolve.

**Comment by tirix** [comment]
@benjub for information.

**Comment by benjub** [comment]
> @benjub for information.

LGTM. Thanks @tirix, @icecream17 and @wlammen

**Review by tirix — APPROVED** [review]

**Pull request merged**
