### PR TITLE
Heron's formula

### PR DESCRIPTION
**Pull request by digama0**
Based on https://groups.google.com/d/topic/metamath/DDN4noc0TYU/discussion . (Not to steal your thunder Jon, but I want to make sure that something comes of this proof.)

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@digama0 - Wait a second - is this [Metamath 100 number 57](http://us.metamath.org/mm_100.html#57)? Looks like it.

Let me know if I understand this correctly.

@nmegill - there may be a metamath 100 update on your way :-).

**Comment by digama0** [comment]
Yes it is. I just finished Jon's proof though, so you should credit it as joint work.

**Comment by david-a-wheeler** [comment]
Awesome! 👍 

@nmegill - I'll wait until this is merged, and I hope that's soon!

**Comment by nmegill** [comment]
@david-a-wheeler I updated heron.html and mmrecent.html on us2.metamath.org and us.metamath.org.  I'll let you do the mm_100.html.

**Pull request merged**
