### PR TITLE
Minimized axiom usage

### PR DESCRIPTION
**Pull request by GinoGiotto**
* Dropped ax-10 and ax-12 from `ceqsexgv` -> automatically dropped ax-10 and ax-12 from ~ceqsrexv, ~ceqsrexbv, ~ceqsrex2v, ~clel3g, ~clel3, ~ceqsrexv2, ~ceqsralv2 as well.

* Dropped ax-8 from `ralab2`.

* Dropped ax-8 from `rexab2`.

* Dropped ax-12 from `sbcbidv` -> automatically dropped ax-12 from ~sbcbii and ~bnj524 as well.

* Dropped ax-10 from ~~`mpteq12i`~~. EDIT: edited proof of  `mpteq12dv` to drop ax-10 and shorten its proof, this automatically drops ax-10 from `mpteq12i` as well.

### CODE REVIEW

**Review by icecream17 — APPROVED** [review]
Though instead of changing mpteq12i, mpteq12dv could use mpteq12df

**Comment by GinoGiotto** [comment]
I can add your credit @icecream17 for that idea, if you want.

**Review by icecream17 — APPROVED** [review]
that's not necessary

**Review by wlammen — COMMENTED** [review]
Is there a reason you don't create OLD versions?

**Comment by GinoGiotto** [comment]
> Is there a reason you don't create OLD versions?

The [conventions webpage](https://us.metamath.org/mpeuni/conventions.html) doesn't state that OLD proofs are required for axioms minimizations, it simply states that shorter proofs with more axioms are labeled with an ALT suffix. Although it is not explicitly mentioned, those ALT proofs are [usually agreed to be restricted](https://github.com/metamath/set.mm/issues/3183#issuecomment-1551713720) for cases where a new proof is significantly longer, and I don't think there are such cases in this PR.

Apart from that, I am available to add OLD/ALT versions upon request. Are there specific theorems where you are interested to keep them?

**Comment by wlammen** [comment]
This is how the paragraph about OLD proofs or versions begins on the mentioned conventions page:
_If a proof, definition, axiom, or theorem is going to be removed, we often stage that change by first renaming its label with an OLD suffix_ 
Exemptions are possible, because of the word _often_ in it.  Actually I used this uncertainty myself, during the development of mo4 for example, that reached its final version only after 4 days, and I did NOT create an OLDOLD, OLDOLDOLD and OLDOLDOLDOLD version just to document all intermediate steps.  But I created an mo4OLD version to mark the starting point.
I think one idea behind the OLD versions are to point out where recent development took place, and in what direction it went.  So a proof idea, or a generalization thereof, can be carried over to other theorems (even other *.mm files), where applicable.  I don't see a good reason to not follow this customs any longer, and also not in this particular instance.

**Comment by GinoGiotto** [comment]
> This is how the paragraph about OLD proofs or versions begins on the mentioned conventions page: _If a proof, definition, axiom, or theorem is going to be removed, we often stage that change by first renaming its label with an OLD suffix_ 

Indeed that's confermation that is not a requirement. In this case it's the reviewer, rather than the conventions, that is requesting OLD proofs, which is not a problem if stated explicitly (bonus points if motivations are provided).

 >_If a proof, definition, axiom, or theorem is going to be removed..._

Are you arguing that old proofs of [ralab2](https://us.metamath.org/mpeuni/ralab2.html) and [rexab2](https://us.metamath.org/mpeuni/rexab2.html) are removed in this PR?

Old proof of [ralab2](https://us.metamath.org/mpeuni/ralab2.html):
<pre>
MM> SHOW PROOF ralab2 / LEMMON / RENUMBER
 1 df-ral        $a |- ( A. x e. { y | ph } ps <-> A. x ( x e. { y | ph } -> ps ) )
 2 nfsab1        $p |- F/ y x e. { y | ph }
 3 nfv           $p |- F/ y ps
 4 2,3 nfim      $p |- F/ y ( x e. { y | ph } -> ps )
 5 nfv           $p |- F/ x ( ph -> ch )
 6 eleq1w        $p |- ( x = y -> ( x e. { y | ph } <-> y e. { y | ph } ) )
 7 abid          $p |- ( y e. { y | ph } <-> ph )
 8 6,7 syl6bb    $p |- ( x = y -> ( x e. { y | ph } <-> ph ) )
 9 ralab2.1      $e |- ( x = y -> ( ps <-> ch ) )
10 8,9 imbi12d   $p |- ( x = y -> ( ( x e. { y | ph } -> ps ) <-> ( ph -> ch ) ) )
11 4,5,10 cbvalv1  $p |- ( A. x ( x e. { y | ph } -> ps ) <-> A. y ( ph -> ch ) )
12 1,11 bitri    $p |- ( A. x e. { y | ph } ps <-> A. y ( ph -> ch ) )
</pre>

New proof of `ralab2`:
<pre>
MM> SHOW PROOF ralab2 / LEMMON / RENUMBER
 1 df-ral        $a |- ( A. x e. { y | ph } ps <-> A. x ( x e. { y | ph } -> ps ) )
 2 nfsab1        $p |- F/ y x e. { y | ph }
 3 nfv           $p |- F/ y ps
 4 2,3 nfim      $p |- F/ y ( x e. { y | ph } -> ps )
 5 nfv           $p |- F/ x ( ph -> ch )
 6 eleq1ab       $p |- ( x = y -> ( x e. { y | ph } <-> y e. { y | ph } ) )
 7 abid          $p |- ( y e. { y | ph } <-> ph )
 8 6,7 syl6bb    $p |- ( x = y -> ( x e. { y | ph } <-> ph ) )
 9 ralab2.1      $e |- ( x = y -> ( ps <-> ch ) )
10 8,9 imbi12d   $p |- ( x = y -> ( ( x e. { y | ph } -> ps ) <-> ( ph -> ch ) ) )
11 4,5,10 cbvalv1  $p |- ( A. x ( x e. { y | ph } -> ps ) <-> A. y ( ph -> ch ) )
12 1,11 bitri    $p |- ( A. x e. { y | ph } ps <-> A. y ( ph -> ch ) )
</pre>

The edit simply replaces [eleq1w](https://us.metamath.org/mpeuni/eleq1w.html) with [eleq1ab](https://us.metamath.org/mpeuni/eleq1ab.html), which both show the **_exact same_** statement in this proof. Everything else is not changed, included proof length. Literally no difference in the HTML proof steps, beside the labels themselves. I think  it's worth keeping OLD proofs where there are actually some chances for them to provide an insight. The "often" in the conventions suggests that they can be left out when it's reasonable, and here calling this a "proof removal" is definitely an overstatement. That's why I was asking (and I ask it again) if there are some specific proofs you are interested keeping.

**Comment by wlammen** [comment]
> Are you arguing that old proofs of [ralab2](https://us.metamath.org/mpeuni/ralab2.html) and [rexab2](https://us.metamath.org/mpeuni/rexab2.html) are removed in this PR?

Yes, of course, what else?

> In this case it's the reviewer, rather than the conventions, that is requesting OLD proofs...

OK, it is my job as a reviewer to watch out for deviations from conventions, and mark them, if I detect one.  While I could be generous in the ralab2 case, there are more and massive changes in this PR without an OLD version.

I do not read the said paragraph such that it is everybody's choice now to include or dismiss OLD versions in his/her contributions at random.  This is not supported by former handling of this topic.  Actually the paragraph was edited by Norm back in (about) 2013, and it was to some extent my contributions then that made him adapt the wording.  I have some ideas about why he wrote it the way he did.

The OLD versions play a role in the system Metamath.  I tried to outline this role in my previous post.  This is not a case-by-case decision.  It only needs to fulfill its purpose on average.  The same as with traffic rules.

**Comment by GinoGiotto** [comment]
> > Are you arguing that old proofs of [ralab2](https://us.metamath.org/mpeuni/ralab2.html) and [rexab2](https://us.metamath.org/mpeuni/rexab2.html) are removed in this PR?
> 
> Yes, of course, what else?

Given the evidence I find such position hard to defend to be honest, but ok, I gave my word that upon request I would provide the OLD proofs, so the ones for `ralab2` and `rexab2` are added as well in the new commit.

**Review by wlammen — APPROVED** [review]

**Comment by wlammen** [comment]
Just for the record: Another role of an OLD version is its backup function.  In https://github.com/metamath/set.mm/issues/3485 we prolonged the duration of OLD versions, because a new idea did not appear matured enough - after almost a year!

**Comment by GinoGiotto** [comment]
Out of curiosity, I can recall several of axiom minimization PRs submitted my me and approved by you without remarks about OLD proofs https://github.com/metamath/set.mm/pull/3365 https://github.com/metamath/set.mm/pull/3359 https://github.com/metamath/set.mm/pull/3355 https://github.com/metamath/set.mm/pull/3274 https://github.com/metamath/set.mm/pull/3222.  Why this sudden change in policy?

**Comment by wlammen** [comment]
In the end I think it was sloppiness.  I should have payed attention to it.

It seems that the OLD versions idea has a lower rank compared to precision in expression, shortage of a proof, axiom footprint and some more.  So you are in the moment in the unfortunate position that it somehow caught my attention again.

Of course, if in the past not only me but other reviewers, too, tended to disregard this aspect of review, then one might raise the question, what this all is about, if barely enforced.  Good for a new issue, I'd say, but nothing to decide here.

**Comment by GinoGiotto** [comment]
> Of course, if in the past not only me but other reviewers, too, tended to disregard this aspect of review, then one might raise the question, what this all is about, if barely enforced. Good for a new issue, I'd say, but nothing to decide here.

I'm pretty sure all my axiom minimization PRs have been approved by multiple reviewers without any comment about OLD proofs so far, only for a few there have been remarks about ALT versions (that's why I was saying it's the reviewer decision). This looks a bit too consistent to just be simple "sloppiness" I'd say.

**Comment by benjub** [comment]
Thank you @wlammen for your careful reviews, as always. It's true that when the change is tiny and there is absolutely no doubt that the older version has nothing to add in terms of insight and we are sure we won't need to revert it, we can do without the OLD version. But most of the time, the OLD version should be created, which will stay for 1 additional year.

**Comment by wlammen** [comment]
I don't know whether I am expected to summarize this thread somehow.  I actually just waited for others in case they wanted to add something.  I can't say this topic is finalized.  There are at least 3 possible goals mentioned determining why and how OLD files are (could be) kept, not necessarily orthogonal.  I recognize 4 mentioned strategies (or policies) to handle them, some dependent on personal view.

If all had gone right, I should have been able to explain my personal stance on this, latest in my third post.  Next time I will be, I think.

The contents are beyond dispute I think, so I am going to merge this PR.

**Pull request merged**
