### PR TITLE
submatrices and determinants

### PR DESCRIPTION
**Pull request by avekens**
- takeover definitions/theorems from SO's determinants-1 branch
- definitions and theorems for submatrices and "minor matrices"
- additional theorems for symmetry groups, transpositions, sign function, matrix algebra, determinants, adjuncts
- improvement of theorem ~m2detleib (Leibniz' Formula for 2x2-matrices)
- main result of contribution: ~ smadiadet

### CODE REVIEW

**Comment by avekens** [comment]
The main result of this contribution was to prove ~ smadiadet , a first step in direction of a very special case of the "Laplace Extension" for determinants of sqare matrices, showing that the determinant of a submatrix of a square matrix obtained by removing a row and a column at the same index equals the determinant of the original matrix with the row replaced with 0's and a 1 at the diagonal position:

( ( ( N \ { K } ) maDet R ) ` ( K ( ( N subMat R ) ` M ) K ) )
          = ( ( N maDet R ) ` ( K ( ( N minMatR1 R ) ` M ) K ) )

The next (probably easy) step would be to replace the 1 at the diagonal position with an arbitrary element of the underlying ring. To show a corresponding result with a nonzero element at another position, however, should be more difficult, but is required to show the "Laplace Extension" in general.

See also issue #85.

To obtain this result, I needed some definitions/theorems from SO's determinants-1 branch. These will be available in the official set.mm by this contribution:

- I copied the definitions and theorems one by one, only changing the comments (see below) and removing the date tag at the end of the proofs 
- many of them had no comment, so I added a comment containing the placeholder "[from SO's determinants-1 branch]" - this placeholder has to be replaced by  a meaningful comment sometime
-- I used the acronym SO within the comments (e.g. "(Contributed by SO, 9-Jul-2018.)") - @sorear: I hope this is OK with you
- I placed two theorems directly into the main part: symgbasf1o, symgbasfi 
- some of them I moved directly into the Mathbox of Stefan
-- this is mainly because the definitions for maDet and maAdju changed. I renamed the old definitions (and related theorems) by appending an OLD (and placing a "(New usage is discouraged.)" within the comment): df-mdetOLD, df-maduOLD, mdetfvalOLD, mdetleibOLD . These could/should be removed sometime.
-- Here a list of the corresponding definitions and theorems:
df-evpm, psgninv  psgnco zrhpsgnmhm zrhpsgninv evpmss psgnevpmb psgnodpm psgnevpm  psgnodpmr zrhpsgnevpm zrhpsgnodpm evpmodpmf1o pmtrodpm mattposcl mattpostpos mdetleib2 mdettpos mdetf
- many of them I placed into my Mathbox (see section "theorems from SO's determinants-1 branch"
-- @sorear: would it be OK if I move them into your Mathbox, too?

**Comment by avekens** [comment]
... unfortunately, the Travis CI build was terminated because of a timeout! Could have anybody a look at it?

**Comment by nmegill** [comment]
@david-a-wheeler Can you figure out what script it is stuck in?  Thanks.

**Comment by avekens** [comment]
You can still see the last outputs in the Details of the Travis build. Here it is again - I guess it's the script "verify"... :

$ scripts/verify --date_skip --extra 'write bibliography mmbiblio.html' set.mm
Metamath - Version 0.172 25-Jan-2019          Type HELP for help, EXIT to exit.
MM> Reading source file "set.mm"... 33883782 bytes
33883782 bytes were read into the source buffer.
The source has 153175 statements; 2196 are $a and 31998 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> 0 10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
..................................................
All proofs in the database were verified in 4.84 s.
MM> The old file will be renamed mmbiblio.html~1.
Reading definitions from $t statement of set.mm...
1386 typesetting statements were read from "set.mm".
3767 references were processed.
2012 table rows were written.
MM> Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by nmegill** [comment]
OK, I was able to reproduce it.  Apparently metamath.exe hangs at "Checking statement comments..."  This is VERY BAD, and I'll try to fix it ASAP.

**Comment by nmegill** [comment]
The problem arises at the comment in psgninv (and subsequent statements) that reads:

``
    $( [from SO's determinants-1 branch] (Contributed by SO, 9-Jul-2018.) $)
``

This should have produced a warning message since square brackets are reserved for bib references.  Instead, there is a bug in the code that hangs trying to parse the page number or keyword.

To fix this, the comment can be changed to:

``
    $( (from SO's determinants-1 branch) (Contributed by SO, 9-Jul-2018.) $)
``

Search for other "$( [" and change them similarly.  You can verify that it no longer hangs by running 'verify markup */f' locally.

I will fix this bug probably today.  In the meantime you can update the comments, which have to be changed anyway to avoid a warning after the metamath.exe bug is fixed.

**Comment by nmegill** [comment]
Suggestion:  You could use "((...))" instead of square brackets.

**Comment by avekens** [comment]
Hi Norman, I fixed the issue with the square brackets, and this is working now. By the way, I checked it with 'verify markup */f' before I pushed it to Git using version 0.164 5-Sep-2018 of metamath.exe, and I had no problems!

However, I have problems with the discouraged file. I do not know exactly what to do for this. 

- The definitions df-mdetOLD and df-maduOLD are tagged with "(New usage is discouraged.)"
- The theorems mdetfvalOLD and mdetleibOLD are tagged with "(New usage is discouraged.) (Proof modification is discouraged.)"
-mdetfvalOLD uses df-mdetOLD
- mdetleibOLD uses mdetfvalOLD

**Comment by nmegill** [comment]
> Hi Norman, I fixed the issue with the square brackets, and this is working now. By the way, I checked it with 'verify markup */f' before I pushed it to Git using version 0.164 5-Sep-2018 of metamath.exe, and I had no problems!
> 

That's a good hint.  I made many changes in that area for the new 'markup' command late last year.

> However, I have problems with the discouraged file. I do not know exactly what to do for this.
> 
> * The definitions df-mdetOLD and df-maduOLD are tagged with "(New usage is discouraged.)"
> * The theorems mdetfvalOLD and mdetleibOLD are tagged with "(New usage is discouraged.) (Proof modification is discouraged.)"
>   -mdetfvalOLD uses df-mdetOLD
> * mdetleibOLD uses mdetfvalOLD

It looks like all these are valid (not accidental).  So you can regenerate the 'discouraged' file with the command in the script (using mmj2) or alternately with metamath.exe using

```
./metamath 'read set.mm' 'set width 9999' 'show discouraged' quit \
    | tr -d '\015' | grep '^SHOW DISCOURAGED.' \
    | sed -E -e 's/^SHOW DISCOURAGED.  ?//' | LC_ALL=C sort > discouraged
```

**Comment by avekens** [comment]
Puh, this was a long way to go this time! But now we can concentrate on mathematics again.

**Pull request merged**
