### PR TITLE
Add checkmm to the set of Travis validators

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by sorear** [comment]
I'm a little bit uneasy about the fact that we're pulling a bunch of things from the Metamath web site (and worse, the us2 site; last I heard, that's physically at @nmegill's house).  Are there real issues here or is it OK?

**Comment by david-a-wheeler** [comment]
Obviously this is *not* really necessary.  However, adding this fourth validator (in C++) doesn't take up that much more time.  This does, however, provide more validation than *any* other system I know of (I don't know of ANY formal math system with 4 independent validators in use)... if there's an error in a validator, or even in 3, the proofs still won't slip through.  This showcases an advantage of metamath - its formal foundations are so simple that there are a lot of validator implementations.

**Comment by david-a-wheeler** [comment]
@sorear: checkmm.cpp is only 39025 bytes.  That is extremely unlikely to cause overloading in any system, even a tiny server.  Especially since once it pulled, it'll stay in memory for a while and just get re-served from there. In short, I don't think there is an issue.

Now in the longer term, for *other* reasons, I think a repo should be created for checkmm. That way, it can be maintained under its own schedule, under version control, enabling easy collaboration.  Then downloading is easy. It doesn't have to be GitHub, though that would work well.  I think Eric Schmidt should be the prime determiner of where it goes, though.

**Comment by david-a-wheeler** [comment]
Note: Nothing even comes *close* to the speed of the validator in Rust, whose under-1-second time is nearing miraculous.  However, while this C++ implementation takes a little more time to validate, it takes almost no time to compile, so it really doesn't add that much more time to the validation process.

**Comment by digama0** [comment]
@sorear We have to download these tools from *somewhere*, and a server under our (well, Norm's) physical control is the best. The us2 server is used because it is the "original"; the others are mirrors of this and are about 2-3 days behind, which make them a poor choice for bleeding edge verification performed by Travis CI. Because of the mirrors, there is no serious danger of lost data should Norm's computer go kaput.

**Comment by sorear** [comment]
> it'll stay in memory for a while and just get re-served from there.

My concerns are directed at network bandwidth and monthly data quotas , not load issues with the server _per se_.  It's probably small in comparison with the mirror rsync traffic, but I'm still uncomfortable pointing any kind of automated process at us2.

**Comment by digama0** [comment]
@sorear The Travis build only occurs when a new commit is pushed to the repo, which means that it is still throttled by human factors (as opposed to, say, re-verifying every 5 minutes). My guess is it's not near to any data limits, but I'm sure @nmegill has more accurate data on this - I know he watches the numbers.

**Comment by nmegill** [comment]
On 6/27/16 1:22 AM, sorear wrote:
> I'm a little bit uneasy about the fact that we're pulling a bunch of
> things from the Metamath web site (and worse, the us2 site; last I
> heard, that's physically at @nmegill <https://github.com/nmegill>'s
> house). Are there real issues here or is it OK?

As far as bandwidth, there are no issues pulling it from us2 (which is 
at my house), except that it occasionally goes down when my ISP's DHCP 
server changes my IP address every few years, or the electricity goes 
off a couple of times a year during storms or occasionally due to an 
exploding transformer that I can hear in the distance.  I no longer have 
UPS because the non-replaceable batteries went bad every few years, and 
I decided it wasn't worth it as well as being bad for the environment. 
Overall us2 is pretty reliable, but not perfect.

Due to the comings and goings of volunteer mirrors that I have no 
control over, I decided to put the us.metamath.org mirror on a 
commercial shared server (ixwebhosting.com) at a $4/month rate I don't 
mind paying for.  While they claim unlimited bandwidth, I've gotten 
warnings from them when a link to us.metamath.org appeared on a 
high-volume site such as reddit, at which point I switched 
us.metamath.org to a volunteer mirror temporarily (with the volunteer's 
permission) until it quieted down.  But the low volume of pulling 
metamath program copies from us.metamath.org should cause no problems 
and is more reliable than my home server even though it may lag a couple 
of days from us2.  AFAIK the us.metamath.org server has never gone down.

All in all, using either server is fine with me.

Norm

**Comment by nmegill** [comment]
The usage statistics for us.metamath.org are found here:
http://us.metamath.org/webalizer/index.html
In the past year, the site usage was 640 GB, so a few pulls by Travis 
would be imperceptible noise.  Also, I can directly update 
us.metamath.org with ftp if there is an urgent update, with no lag.  So 
I would suggest that for Travis.

Also, could someone add "gcc --version" to the script for me?  Thanks.

Norm

**Pull request merged**
