### PR TITLE
Indent section titles

### PR DESCRIPTION
**Pull request by benjub**
A few comment edits and rewraps.

Strangely, the script indenting section titles did not catch them all...

### CODE REVIEW

**Comment by benjub** [comment]
Fixed the script and used it to indent section titles with two spaces.  Content of the file `sedexpr.awk` (from @jamesjer):
```
#!/bin/awk -f

# This program re-indents section titles in Metamath files with two blanks
# Invoke:
#   GNU sed:   sed -i "$(awk -f sedexpr.awk set.mm)" set.mm
#   BSD sed:   sed -i '' "$(awk -f sedexpr.awk set.mm)" set.mm

BEGIN {
    first = 1
    startline = 0
    output = ""
}
END {
    print(output)
}
/^(#\*#\*|####|=-=-|-\.-\.)/ {
    if (startline == 0)
	startline = NR + 1
    else {
	if (startline < NR - 1)
	    addr = sprintf("%d,%d", startline, NR - 1)
	else
	    addr = sprintf("%d", startline)
	if (first == 1) {
	    output = sprintf("%ss/^[[:blank:]]*\\(.*\\)/  \\1/", addr)
	    first = 0
	}
	else
	    output = sprintf("%s;%ss/^[[:blank:]]*\\(.*\\)/  \\1/", output, addr)
	startline = 0
    }
}
```

**Comment by avekens** [comment]
The title of this PR is a little bit misleading: its main purpose is to rewrap all section titles (left alignment).
I can remember that this was discussed, but was it definitely decided? Where? Is this decision documented somewhere? Maybe section "Conventions", bullet point "Comments and layout" would be an adequate place.

**Comment by benjub** [comment]
@avekens : actually, I thought this had been done in #2487 but the script has a bug and only the level-1 and level-2 (I think) titles were indented. This one acts on all levels (1 to 4). This also follows #2262 with Norm's approval and @jamesjer's script.

**Comment by avekens** [comment]
@benjub thank you for the references, there was indeed such an agreement. Nevertheless, it would be helpful if this is documented as "Convention".

**Comment by benjub** [comment]
I am closing this PR because of merge conflicts and I will open two PRs, one of them containing only title indentation.

**Comment by benjub** [comment]
> @benjub thank you for the references, there was indeed such an agreement. Nevertheless, it would be helpful if this is documented as "Convention".

I'm adding a note to review the conventions.  (It would also be nice to adapt the command "write source */rewrap" of metamath.c)

**Pull request closed without merging**
