### PR TITLE
proof of e being Transcendental (#67 in the 100 theorems list)

### PR DESCRIPTION
**Pull request by glacode**
The main result in this commit is ~ etransc, the proof of e being transcendental. This is #67 in the 100 theorems list.
Another theorem that could be of interest, is ~ dvnprod the n-th derivative of a finite product: the formula involves the multinomial coefficient, used in combinatorics, an extension of the binomial coefficient (see ~ mccl for a specific closure theorem)

### CODE REVIEW

**Comment by glacode** [comment]
I'm going to remove the discouraged dependencies

**Comment by david-a-wheeler** [comment]
@glacode - FANTASTIC!

@nmegill - Once this is merged, I plan to update the Metamath 100 list and notify freek.

**Comment by nmegill** [comment]
Great job, @glacode!  @david-a-wheeler could you do this tomorrow morning after I've updated the servers?  Thanks.

**Comment by nmegill** [comment]
@david-a-wheeler I meant postponing emailing Freek until tomorrow, so he doesn't get dead links. I'll let you know when it's ready.  You can submit the mm_100.html update anytime.  Thanks!  Norm

**Comment by david-a-wheeler** [comment]
@nmegill - The commit to update the Metamath 100 page is here: https://github.com/metamath/set.mm/pull/1571

I'll post to the mailing list, and email Freek, once the servers are updated so that everyone can enjoy the results.

Now that we have *e* proved to be Transcendental, I am hoping that result may help to prove Metamath 100 proof 53 (<i>&pi;</i> is Transcendental) and perhaps even proof 56 (The Hermite-Lindemann Transcendence Theorem).

**Comment by david-a-wheeler** [comment]
I've also updated the Metamath 100 graph here: https://docs.google.com/spreadsheets/d/1jcLOp_jF4sPrVPdPedL_ZWebXp8oYEQOSmbWb168YHE/edit#gid=1223303844

**Comment by nmegill** [comment]
@david-a-wheeler mm_100.html is updated on us2 and us, and etransc and its lemmas are on us2 and us (at the moment in the mpeuni directory only, until a full update overnight).  So it is ready to announce.

**Comment by savask** [comment]
@glacode Congratulations!

Do you plan to provide a some sort of high-level comment of this work in the google group? For example, it would be interesting to know why you choose this specific reference for the proof.

I skimmed through descriptions of lemmata for the proof, and noticed several small irregularities (intentional or not):
- in several cases formulae are not typeset inside single quotes (etranslem24, 35, 38 and 41)
- etranslem48's comment says "a large enough prime 𝑝 is chosen: it will be used by subsequent lemmas", yet there are no subsequent lemmata.

**Comment by glacode** [comment]
> * etranslem48's comment says "a large enough prime 𝑝 is chosen: it will be used by subsequent lemmas", yet there are no subsequent lemmata.

Hi @savask ,

~ etranslem48 is the first lemma invoked by ~ etransc and (once p has been "established") lem6 and lem47 are invoked.
Following the "flow" of the proof, you will "reach" every lemma in tree traversal fashion.
Of course, they are all written above lem48, but following the proof you will read them subsequently

Glauco

**Comment by savask** [comment]
Ah, I see. It was a bit confusing at first, but I guess it makes sense if you're reading the proof bottom-to-top.

**Pull request merged**
