### PR TITLE
Shortened proofs 14

### PR DESCRIPTION
**Pull request by GinoGiotto**
Continuation of https://github.com/metamath/set.mm/pull/3127. Proof minimizer executed between the 13501th and the 14000th theorems that don't have a `proof modification is discouraged` label in their comment.

No new axiom dependencies are introduced. Scan my [min-all](https://github.com/GinoGiotto/set.mm/tree/min-all) branch and compare it to my [develop](https://github.com/GinoGiotto/set.mm/tree/develop) branch for evidence. The result of the comparison should correspond to https://github.com/metamath/set.mm/commit/eb061483b6fb87eab898bb65317ff63217a12949 + https://github.com/metamath/set.mm/commit/4e9fa8318df20b2485975d480115d6a38fd859d0.

### CODE REVIEW

**Comment by GinoGiotto** [comment]
Theorem `sumeq2sdv` is identical to `sumeq2ad`, so one of them can be removed.

**Comment by wlammen** [comment]
sumeq2sdv is older and has more applications, but has the longer proof.

So I suggest to proceed as follows:
1. Add a tag (Proof shortened by Glauco Siliprandi, 5-Apr-2020.) to sumeq2sdv.
2. Replace the proof of sumeq2sdv with the shorter one `( wceq ralrimivw sumeq2d ) ABCDEACDGEBFHI $.`
3. Delete theorem sumeq2ad.
4. Do a text search for sumeq2ad and replace each occurrence with sumeq2sdv.
5. Rewrap set.mm.

**Comment by GinoGiotto** [comment]
That's curious. So my understanding is that `/rewrap` works for comments, but not for proofs. To rewrap proofs the command  `SAVE PROOF <label> /COMPRESSED` is needed. Since `sumeq2ad` was used by quite a few theorems, I simply did `SAVE PROOF * /COMPRESSED` to rewrap all proofs in set.mm, but changes show that there are a few rewrapped proofs that don't have a `sumeq2ad` label in it, so they weren't edited by me. So it looks like there were some proofs in set.mm that were not properly rewrapped and went overlooked until now (and not detected by the CI checks).

**Comment by avekens** [comment]
The preferred way to adjust proofs in compressed format (after renaming labels, as in the current case) is "`save proof */compressed/fast`" (or, in short, "`sa p */c/f`").
The option /fast means "The proof is merely reformatted and not recompressed."
If the option "/f" had been used here, maybe some of the modified proofs would not have been changed. I do not know if the compressed format is unique, so that it can be checked by the CI checks (and I assume this is not checked). 

I do not know if this PR can be merged in the current state, but if the proofs are still correct (verified by the CI checks), there should be no problems.

**Comment by GinoGiotto** [comment]
Should I reformat them again? Indeed I didn't use the `/FAST` option, I only ran `SAVE PROOF * /COMPRESSED`. However, upon reviewing modifications, I noticed that this recompression provided some benefits:

This is the list of all theorems in the last commit a7fd4070d8ace98ddbdd43a0404b73b87e9317e2 that don't contain `sumeq2ad`, but were still affected by  `SAVE PROOF * /COMPRESSED`:
* `kerf1ghm` -> shortened by 60 bytes
* `f1ghm0to0` -> shortened by 15 bytes
* `sacgr` -> shortened by 7 bytes
* `dimcl` -> same length, but 1 less step
* `0ellsp` -> same length, but 1 less step
* `lmhmlvec2` -> same length, but 2 less steps
* `kerlmhm` -> same length, but 1 less step

Overall, this recompression either resulted in a reduced number of steps or to a further shortening in the compressed format, which appear like additional improvements to me. Is there a specific reason to discard them?

**Review by icecream17 — APPROVED** [review]
Like above, I don't think there are problems; approve

sidenote:
It seems like not using the `FAST` option is another way to possibly auto-shorten proofs, which is pretty interesting...

There are several ways to represent the same proof in a compressed format, which involve when to use `Z` when using `Z` doesn't lose or save bytes, how to order the proof labels (which determine which label corresponds to which code, the codes go A through T, then UA to UT, VA to VT, etc. YA to YT, UUA to UUT, etc. with base 5-base 20 numbering.)

I've wondered if there were any improvements that could be made in some edge cases. For example, auto-shortening where the bytes are the same but there are less web page tokens. Some complexity in the existing code is: maybe UA is used more often than T, maybe reordering the labels minimizes how early the rewrapping is. I know for certain the latter is optimized.

**Comment by avekens** [comment]
> Should I reformat them again? Indeed I didn't use the `/FAST` option, I only ran `SAVE PROOF * /COMPRESSED`. However, upon reviewing modifications, I noticed that this recompression provided some benefits:
> 
> This is the list of all theorems in the last commit [a7fd407](https://github.com/metamath/set.mm/commit/a7fd4070d8ace98ddbdd43a0404b73b87e9317e2) that don't contain `sumeq2ad`, but were still affected by `SAVE PROOF * /COMPRESSED`:
> 
>     * `kerf1ghm` -> shortened by 60 bytes
> 
>     * `f1ghm0to0` -> shortened by 15 bytes
> 
>     * `sacgr` -> shortened by 7 bytes
> 
>     * `dimcl` -> same length, but 1 less step
> 
>     * `0ellsp` -> same length, but 1 less step
> 
>     * `lmhmlvec2` -> same length, but 2 less steps
> 
>     * `kerlmhm` -> same length, but 1 less step
> 
> 
> Overall, this recompression either resulted in a reduced number of steps or to a further shortening in the compressed format, which appear like additional improvements to me. Is there a specific reason to discard them?

These theorems were added/modified by @tirix recently (in May 2023).  I think he did not reformat the proofs accordingly (and nobody else after his commit(s)). Therefore, I think the changes made by this PR are acceptable.

**Review by avekens — APPROVED** [review]

**Comment by tirix** [comment]
> These theorems were added/modified by @tirix recently (in May 2023).  I think he did not reformat the proofs accordingly (and nobody else after his commit(s)). Therefore, I think the changes made by this PR are acceptable.

These proofs were generated by Yamma, and I did not run 'save proof /compressed' on all of them, but mostly only 'save proof /fast /compressed'. I assume Metamath.exe's compression algorithm is better than Yamma's in that case?

In any case, you can go ahead with the PR.

**Comment by digama0** [comment]
> I do not know if the compressed format is unique, so that it can be checked by the CI checks (and I assume this is not checked).

It is unique (or more precisely, there is a specific algorithm that is implemented by at least metamath-exe, metamath-knife and mmj2 which produces a unique output from a given input step-list-with-backreferences), but I think metamath-exe doesn't always do the full deduplication of the step list (which is also unique from a given input proof) and the `/fast` modifier controls whether it does deduplication.

**Comment by digama0** [comment]
> I've wondered if there were any improvements that could be made in some edge cases. For example, auto-shortening where the bytes are the same but there are less web page tokens. Some complexity in the existing code is: maybe UA is used more often than T, maybe reordering the labels minimizes how early the rewrapping is. I know for certain the latter is optimized.

As you say, the latter is optimized as part of the standardized algorithm that is used for compressed proof formatting. The former is optimized in the sense that Norm tried out several strategies for the base of the step numbering strategy (e.g. to use 20+5 vs 19+6 base encoding for the step numbers) and found that 20+5 was the best on an early version, and last time we checked 19+6 was slightly better on the then-current set.mm, but overall, having a standardized algorithm which is reproducible and minimizes superfluous diffs is more valuable than having a superoptimized result here. I would prefer not to superoptimize the encoding on an individual proof if it will be destroyed by the next `sa p */c` because then we will effectively no longer be able to use this to auto-format proofs.

**Comment by digama0** [comment]
> > These theorems were added/modified by @tirix recently (in May 2023).  I think he did not reformat the proofs accordingly (and nobody else after his commit(s)). Therefore, I think the changes made by this PR are acceptable.
> 
> These proofs were generated by Yamma, and I did not run 'save proof /compressed' on all of them, but mostly only 'save proof /fast /compressed'. I assume Metamath.exe's compression algorithm is better than Yamma's in that case?

In that case, it sounds like the issue is not the compression algorithm but rather the *deduplication* algorithm. There is a very simple deduplication rule I highly encourage you to implement: whenever a statement is proved more than once, refer to the original statement instead of the second copy. You can either take the first one, or be clever about which proof to keep, but in either case the result will have the property that no statement is proved twice in the same proof, and `save proof /compressed` and `save proof /compressed /fast` will have the same result.

**Comment by tirix** [comment]
I've opened [an issue in Yamma's repository](https://github.com/glacode/yamma/issues/7) to track the issue with its compression algorithm.

I will try to run `save proof /compressed` on new proofs to avoid the discrepancy in the future when using Yamma until that issue is resolved.

In the mean time I think we can merge this PR (which is actually not related).

**Comment by glacode** [comment]
> > I do not know if the compressed format is unique, so that it can be checked by the CI checks (and I assume this is not checked).
> 
> It is unique (or more precisely, there is a specific algorithm that is implemented by at least metamath-exe, metamath-knife >and mmj2 which produces a unique output from a given input step-list-with-backreferences), but I think metamath-exe >doesn't always do the full deduplication of the step list (which is also unique from a given input proof) and the `/fast` modifier >controls whether it does deduplication.

Hi everybody,

as I've already written here

https://github.com/metamath/set.mm/issues/2710#issuecomment-1214358302

the compressed proof (built by mmj2 and metamath.exe) is not unique. You can read an example at the linked issue.

Yamma, Metamath and mmj2 produce the same non-compressed proof, but different compressed proofs.

Mmj2 even produces different compressed proofs at the bottom of the .mmp file and in the .mmt file.

Metamath and mmj2 try to format nicely the labels in the proof, but they use different knapsack algorithms and this leads to different sequence of labels and then to different compression strings.

Yamma leaves the order (FIFO) of the uncompressed proof (when the labels' sequence are the same, the compressed strings are the same for both Yamma, mmj2 and Metamath, for what I've seen).

**Comment by glacode** [comment]
> I've opened [an issue in Yamma's repository](https://github.com/glacode/yamma/issues/7) to track the issue with its compression algorithm.
> 
> I will try to run `save proof /compressed` on new proofs to avoid the discrepancy in the future when using Yamma until that issue is resolved.
> 
> In the mean time I think we can merge this PR (which is actually not related).

Hi Thierry,

are you using the "standard formatting" script recommended here?

https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md#formatting-recommendation-prior-to-submitting-a-pull-request

Doesn't it fix the format?

**Comment by tirix** [comment]
> are you using the "standard formatting" script recommended here?

Previously, when using MMJ2 (through my Eclipse plugin), I did not need to use that script. I copy/pasted directly the compressed proof from the MMP into set.mm and it "just worked", with correct indentation and everything.

As-is, that script recommendation will not work because it is the fast method which does not recompute the compressed proof, just reformats it (`SAVE PROOF * /COMPRESSED /FAST`).

As I mentioned, I can just use `SAVE PROOF * /COMPRESSED` (without the `/FAST`), I just need to run it on each of my proofs one by one. It's a bit tedious but it works, and I think the benefits of using Yamma still outweigh that minor issue.

Note also that the proofs generated by Yamma are valid and pass all the checkers - questions will arise if someone runs `SAVE PROOF * /COMPRESSED` and gets a different output.

**Comment by digama0** [comment]
@glacode 

> Hi everybody,
> 
> as I've already written here
> 
> [#2710 (comment)](https://github.com/metamath/set.mm/issues/2710#issuecomment-1214358302)
> 
> the compressed proof (built by mmj2 and metamath.exe) is not unique. You can read an example at the linked issue.

The formatting on that post is broken, so it is difficult to tell whether indentation is the source of the problem. In any case, discrepancies in the algorithm should be treated as bugs and reported to the relevant projects.

EDIT: Here's my reconstruction of your post with fixed formatting:
> ```
> MM> show proof cbviota /compressed
> Proof of "cbviota":
> ---------Clip out the proof below this line to put it in the source file:
>       ( vw vz weq wb wal cab cuni cio wsb nfv nfbi equequ1 bibi12d sbequ12 nfsb
>       nfs1v cbval sbequ sbie syl6bb bitri abbii unieqi dfiota2 3eqtr4i ) ACHJZK
>       ZCLZHMZNBDHJZKZDLZHMZNACOBDOUPUTUOUSHUOACIPZIHJZKZILUSUNVCCIUNIQVAVBCACIU
>       CVBCQRCIJAVAUMVBACIUACIHSTUDVCURIDVAVBDACIDFUBVBDQRURIQIDJZVABVBUQVDVAACD
>       PBAIDCUEABCDGEUFUGIDHSTUDUHUIUJACHUKBDHUKUL $.
> ---------The proof of "cbviota" (336 bytes) ends above this line.
> ```
> the mmj2 proof in the GUI
> ```
> $= ( vw vz cv wceq wb wal cab cuni cio wsb nfv nfbi equequ1 syl6bb
>    nfs1v sbequ12 bibi12d cbval nfsb sbequ sbie bitri abbii dfiota2
>    unieqi 3eqtr4i ) ACJZHJZKZLZCMZHNZOBDJZUOKZLZDMZHNZOACPBDPUSVDU
>    RVCHURACIQZIJZUOKZLZIMVCUQVHCIUQIRVEVGCACIUBVGCRSUNVFKAVEUPVGAC
>    IUCCIHTUDUEVHVBIDVEVGDACIDFUFVGDRSVBIRVFUTKZVEBVGVAVIVEACDQBAID
>    CUGABCDGEUHUAIDHTUDUEUIUJULACHUKBDHUKUM $.
> $)
> ```
> the proof in the .mmt file
> ```
>   ${
>     $d ph w z $. $d ps w z $. $d w x z $. $d w y z $. 
>     cbviota.1 $e           |- ( x = y -> ( ph <-> ps ) ) $.
>     cbviota.2 $e          |- F/ y ph $.
>     cbviota.3 $e           |- F/ x ps $.
>     $( Change bound variables in a description binder. (Contributed by Andrew 
>        Salmon, 1-Aug-2011.) $)
>     cbviota $p       
>                    |- ( iota x ph ) = ( iota y ps ) $=
>       ( vw vz cv wceq wb wal cab cuni cio wsb nfv nfbi equequ1 nfs1v sbequ12
>       nfsb bibi12d cbval sbequ sbie syl6bb bitri abbii unieqi dfiota2 3eqtr4i )
>       ACJZHJZKZLZCMZHNZOBDJZUOKZLZDMZHNZOACPBDPUSVDURVCHURACIQZIJZUOKZLZIMVCUQV
>       HCIUQIRVEVGCACIUAVGCRSUNVFKAVEUPVGACIUBCIHTUDUEVHVBIDVEVGDACIDFUCVGDRSVBI
>       RVFUTKZVEBVGVAVIVEACDQBAIDCUFABCDGEUGUHIDHTUDUEUIUJUKACHULBDHULUM $.
> 
>   $}
> ```

Note that the width of the proof is different: the metamath proof and the mmt proof are 79 chars wide (minus a 6 space indent), while the mmj2 GUI proof is 66 chars (minus a 3 space indent). The indent of a proof in mmj2 is determined from the input file, and the indentation of the right margin (79 chars for set.mm) is determined by a configuration flag. I expect this is the source of your issue, not an algorithm inconsistency.

EDIT 2: Since metamath.exe proof has the indentation parameters as the mmt proof, one would expect them to come up with the same proof, but they still differ and this is because they are actually different proofs: you can see that the metamath proof has a `weq` reference while mmj2 uses `cv wceq` instead. mmj2 does not use syntax theorems ever, because it has a parser and turns the parse trees directly into syntax proofs. metamath.exe uses syntax theorems sometimes just as a result of its heuristic syntax derivation algorithm and sometimes because of MINIMIZE.

**Comment by avekens** [comment]
I think this is not the right place to continue the discussion about compressed proofs. Maybe it can be transferred to and continued at another place. Tomorrow at the latest, I will merge (and thereby close) this PR, because it is accepted by two reviewers and no open issue is reported.

**Comment by glacode** [comment]
> > are you using the "standard formatting" script recommended here?
> 
> Previously, when using MMJ2 (through my Eclipse plugin), I did not need to use that script. I copy/pasted directly the compressed proof from the MMP into set.mm and it "just worked", with correct indentation and everything.

The problem could be that a subsequent PR (from someone else) would run the recommended script, and it should produce many diffs to your mathbox, also (I'm wondering why it didn't happen in the past).

Are you aware of this (old) thread?

Mandatory "standard" formatting prior to submitting a pull request?
https://groups.google.com/g/metamath/c/zZMeeKEC1Dg/m/Xh683K0eCAAJ

**Comment by avekens** [comment]
I think this is not the right place to continue the discussion about compressed proofs. Maybe it can be transferred to and continued at another place. Tomorrow at the latest, I will merge (and thereby close) this PR, because it is accepted by two reviewers and no open issue is reported.

**Comment by tirix** [comment]
> Are you aware of this (old) thread?
> 
> Mandatory "standard" formatting prior to submitting a pull request? https://groups.google.com/g/metamath/c/zZMeeKEC1Dg/m/Xh683K0eCAAJ

Yes, but that thread is about a CI action. 
The action is in place, and my PR have always passed all CI, including the one where I submitted `f1ghm0to0` and the other theorems listed above.

There are two flavours of SAVE PROOF, with or without FAST. Here from MM HELP:
```
    / FAST - The proof is merely reformatted and not recompressed.
```
The recommended formatting is to run the `/FAST` option, so even when following that rule, the non-standard proof is not recompressed.
But here GinoGiotto ran the command without `/FAST`, so when he did, those proofs were actually recompressed.

**Comment by avekens** [comment]
If there are still any problems with the compression, they should be discussed/solved with PR #3202.

**Pull request merged**
