### PR TITLE
Prove dfid2 without ax-10, ax-11, ax-12, ax-13.

### PR DESCRIPTION
**Pull request by GinoGiotto**
Theorem [dfid3](https://us.metamath.org/mpeuni/dfid3.html) does not have DV conditions between setvars, which means that at least ax-13 is likely to be unavoidable there, so a proof for [dfid2](https://us.metamath.org/mpeuni/dfid2.html) should not directly call [dfid3](https://us.metamath.org/mpeuni/dfid3.html) if axiom usage is in our interest.

The new revised proof for [dfid2](https://us.metamath.org/mpeuni/dfid2.html) removes ax-10, ax-11, ax-12 and ax-13 from its dependencies. It appears long, however notice that it is slightly shorter than the one of [dfid3](https://us.metamath.org/mpeuni/dfid3.html) in the compressed format. Further shortenings are of course welcome.

I added `exexw` to shorten the proof of [dfid2](https://us.metamath.org/mpeuni/dfid2.html) to this final length. I can remove it if preferred (by lengthening the proof of [dfid2](https://us.metamath.org/mpeuni/dfid2.html)), but I believe it's likely going to be useful in the future.

Usage of [dfid2](https://us.metamath.org/mpeuni/dfid2.html) is currently discouraged. However, with the revision in this PR, the reasons to keep it discouraged no longer seem as strong to me. Thoughts about this are welcome.

### CODE REVIEW

**Comment by benjub** [comment]
Indeed, dfid2 is unbundled, so we can remove the requirements of auxiliary axioms. There is a shorter proof, and I also give the one for my preferred version of dfid2:
```
  ${
    $d x y z u $.
    dfid2OLD $p |- _I = { <. x , x >. | x = x } $=
      ( vy vz vu cid weq copab df-id cv cop wceq wa wex cab opeq2d eqeq2d exbii
      equcomi bitri df-opab pm5.32ri ax6evr mpbiran2 pm4.71i id opeq12d eqeq12d
      19.42v eqidd anbi12d exexw abbii 3eqtr4i eqtri ) EABFZABGZAAFZAAGZABHCIZA
      IZBIZJZKZUOLZBMZAMZCNUSUTUTJZKZUQLZAMZAMZCNUPURVFVKCVFVJVKVEVIAVEVHVIVEVH
      UOLZBMZVHVDVLBUOVCVHUOVBVGUSUOVAUTUTABROPUAQVMVHUOBMBAUBVHUOBUHUCSVHUQVHU
      TUIUDSQVIUSDIZVNJZKZDDFZLADADFZVHVPUQVQVRVGVOUSVRUTVNUTVNVRUEZVSUFPVRUTVN
      UTVNVSVSUGUJUKSULUOABCTUQAACTUMUN $.

    dfid2 $p |- _I = { <. x , x >. | T. } $=
      ( vy vz vu cid weq copab wtru df-id cv cop wceq wa wex cab equcomi eqeq2d
      exbii bitri df-opab opeq2d pm5.32ri ax6evr 19.42v mpbiran2 id opeq12d tru
      exexw biantru abbii 3eqtr4i eqtri ) EABFZABGZHAAGZABICJZAJZBJZKZLZUNMZBNZ
      ANZCOUQURURKZLZHMZANZANZCOUOUPVDVICVDVFANZANZVIVDVJVKVCVFAVCVFUNMZBNZVFVB
      VLBUNVAVFUNUTVEUQUNUSURURABPUAQUBRVMVFUNBNBAUCVFUNBUDUESRVFUQDJZVNKZLADAD
      FZVEVOUQVPURVNURVNVPUFZVQUGQUISVJVHAVFVGAHVFUHUJRRSUKUNABCTHAACTULUM $.
  $}
```
Writing `{ <. x , x >. | ph }` feels like an abuse of the constructor, so I'm not sure about removing the discouragement tag. Proofs using df-id will use dummy variables anyway, and will be more readable if we use different variables. So I'm not sure the shortenings that would be allowed by using dfid2 are worth it.

**Review by icecream17 — APPROVED** [review]
I wonder if fsplitOLD should become ALT, since it's shorter.

**Comment by avekens** [comment]
> I wonder if fsplitOLD should become ALT, since it's shorter.

I cannot see ~fsplitOLD in this PR...

**Review by avekens — APPROVED** [review]

**Comment by GinoGiotto** [comment]
> There is a shorter proof, and I also give the one for my preferred version of dfid2:

I committed the first shortening. I'd keep the statement of dfid2 as is since otherwise I would have to revise the proof of fsplitOLD (I can put your preferred version in your mathbox tho).

> I cannot see ~fsplitOLD in this PR...

I think he meant that since fsplitOLD is the only theorem that uses dfid2, it could be kept as example about how to use dfid2 to shorten proofs (because fsplitOLD's proof, which uses dfid2, is shorter than fsplit, which uses df-id). Additionally, with this PR, fsplitOLD would have the same axiom usage of fsplit, which means that fsplitOLD should actually be the main proof if we strictly follow the conventions. However, this depends on whether dfid2 should be kept as discouraged (I'm not an expert on soundness issues).

**Comment by benjub** [comment]
> > There is a shorter proof, and I also give the one for my preferred version of dfid2:
> 
> I committed the first shortening. I'd keep the statement of dfid2 as is since otherwise I would have to revise the proof of fsplitOLD (I can put your preferred version in your mathbox tho).

I can do it, but thank you !

> I think he meant that since fsplitOLD is the only theorem that uses dfid2, it could be kept as example about how to use dfid2 to shorten proofs (because fsplitOLD's proof, which uses dfid2, is shorter than fsplit, which uses df-id). Additionally, with this PR, fsplitOLD would have the same axiom usage of fsplit, which means that fsplitOLD should actually be the main proof if we strictly follow the conventions. However, this depends on whether dfid2 should be kept as discouraged (I'm not an expert on soundness issues).

I actually think we should keep the usage discouragement tag on dfid2, for the reason above that I copy below (@digama0 what's your opinion on that?):

Writing { <. x , x >. | ph } feels like an abuse of the constructor, so I'm not sure about removing the discouragement tag. Proofs using df-id will use dummy variables anyway, and will be more readable if we use different variables. So I'm not sure the shortenings that would be allowed by using dfid2 are worth it.

**Comment by digama0** [comment]
I agree, no one should use dfid2 if possible. This theorem causes issues for translation to MM0 and other non-metamath logics because it's not using quantifiers in a normal way. It is cute that it works out, but the interpretation is not at all what you would expect.

**Comment by GinoGiotto** [comment]
Ok, then I think this PR is finished. The conclusion is: dfid2 stays discouraged, fsplitOLD stays OLD since no theorem should use dfid2, and the alternative proposal for dfid2 will be added in a mathbox if desired.

**Review by benjub — APPROVED** [review]

**Pull request merged**
