### PR TITLE
shorten equequ1 and mpto2

### PR DESCRIPTION
**Pull request by wlammen**

### CODE REVIEW

**Comment by nmegill** [comment]
You need to regenerate and commit a new "discouraged" file for Travis to pass, because you added new discouraged tags.  Here is how to regenerate it:

./metamath 'read set.mm' 'set width 9999' 'show discouraged' quit \
     | tr -d '\015' \
     | grep '^SHOW DISCOURAGED.' \
     | sed -E -e 's/^SHOW DISCOURAGED.  ?//' \
     | LC_ALL=C sort > discouraged

The "tr -d '\015'" isn't necessary on Linux but is needed for Cygwin.

**Comment by wlammen** [comment]
I don't know why the diff of the discouraged files fail

**Comment by nmegill** [comment]
Yours has a space in front of each line.

Github mangled the script I posted, so I'll post it again via regular 
email to see if it works:

metamath 'read set.mm' 'set width 9999' 'show discouraged' quit \
| tr -d '\015' \
| grep '^SHOW DISCOURAGED.' \
| sed -E -e 's/^SHOW DISCOURAGED.  ?//' \
| LC_ALL=C sort > discouraged

Norm

**Comment by nmegill** [comment]
Github mangled it again (seriously, why is this so hard for them to get 
right?  Seems like a very dangerous bug.)

Specifically, in 's/^SHOW DISCOURAGED.  ?//' there should be two spaces 
after the period.

Norm

**Pull request merged**
