### PR TITLE
replace "PART 16 GRAPH THEORY" - step 4

### PR DESCRIPTION
**Pull request by avekens**
Task 3 (part 2) of issue #2265: Sections of "Graph theory (revised)" moved from AV's mathbox to main set.mm:

* Trails
* Paths

Additional changes:
* moved from BJ's mathbox: ~sylancl3 (TODO: shorten proofs)
* moved from AV's mathbox: ~rexdifpr, ~pr1eqbg, ~pr1nebg, ~opab0, ~nprrel12, ~brfvopabrbr, ~2f1fvneq, ~prinfzo0, ~elfzo0l, ~elfzr, ~elfzlmr, ~elfz0lmr
* ~fvmptopab1/~fvmptopab2 replaced by fvmptopab
* theorems of the form ( * ` G )= { <. f , p >. | * } and ( F ( * ` G ) P <-> revised by removing not required antecedents  F e. Y , P e. Z and (sometimes even) G e. X.

### CODE REVIEW

**Comment by avekens** [comment]
Now I have to merge ...

**Comment by avekens** [comment]
... great, only two merge conflicts, which were easy to solve!

**Comment by benjub** [comment]
I saw two "inproper" instead of "improper".  Maybe you can search the whole set.mm to see if there are others.

**Edit:** and tails --> trails.

**Comment by glacode** [comment]
When I pull this to my local repo, the script I always launch to "default reformat" (thanks to @benjub for such script) changes the formatting of 4 theorems, but doesn't change all the other theorems nearby that seem to have identical formatting (double space after the date of contribution)

Here's the script
/home/mionome/Documents/metamath/metamath 'open log "/home/mionome/Desktop/provashare/log/log.txt"' 'read "/home/mionome/Documents/git/set.mm/set.mm"' 'write source "/home/mionome/Documents/git/set.mm/set.mm" /rewrap' erase 'read "/home/mionome/Documents/git/set.mm/set.mm"' 'save proof */compressed/fast' 'verify markup */file_skip/top_date_skip' 'verify proof *' 'write source "/home/mionome/Documents/git/set.mm/set.mm"' quit

I recently updated metamath to Version 0.198 , because the above script gave large diffs (with the mm version I had), but with Version 0.198 it worked perfectly again.

Here's my diff after the command (I of course ran it before my last commit and everything was fine).

diff --git a/set.mm b/set.mm
index 2b65040..d331a24 100644
--- a/set.mm
+++ b/set.mm
@@ -648555,55 +648555,55 @@ $)
   ${
     ne0d.1 $e |- ( ph -> B e. A ) $.
     $( If a set has elements, then it is not empty.  (Contributed by Glauco
-       Siliprandi, 23-Oct-2021.)  $)
+       Siliprandi, 23-Oct-2021.) $)
     ne0d $p |- ( ph -> A =/= (/) ) $=
       ( wcel c0 wne ne0i syl ) ACBEBFGDBCHI $.
   $}
 
   ${
-    $d A x $. $d B x $.
+    $d A x $.  $d B x $.
     $( Indexed intersection of intersection.  (Contributed by Glauco
-       Siliprandi, 23-Oct-2021.)  $)
+       Siliprandi, 23-Oct-2021.) $)
     iniin1 $p |- ( A =/= (/) -> ( |^|_ x e. A C i^i B ) = |^|_ x e. A ( C i^i B
        ) ) $=
       ( c0 wne cin ciin iinin1 eqcomd ) BEFABDCGHABDHCGABCDIJ $.
   $}
 
   ${
-    $d A x $. $d B x $.
+    $d A x $.  $d B x $.
     $( Indexed intersection of intersection.  (Contributed by Glauco
-       Siliprandi, 23-Oct-2021.)  $)
+       Siliprandi, 23-Oct-2021.) $)
     iniin2 $p |- ( A =/= (/) -> ( B i^i |^|_ x e. A C ) = |^|_ x e. A ( B i^i C
-       ) )         $=
+       ) ) $=
       ( c0 wne cin ciin iinin2 eqcomd ) BEFABCDGHCABDHGABCDIJ $.
   $}
 
   ${
-    $d A y $. $d B x $. $d ph y $. $d ps x $.
+    $d A y $.  $d B x $.  $d ph y $.  $d ps x $.
     cbvrabv2.1 $e |- ( x = y -> A = B ) $.
     cbvrabv2.2 $e |- ( x = y -> ( ph <-> ps ) ) $.
     $( A more general version of ~ cbvrabv .  (Contributed by Glauco
-       Siliprandi, 23-Oct-2021.)  $)
+       Siliprandi, 23-Oct-2021.) $)
     cbvrabv2 $p |- { x e. A | ph } = { y e. B | ps } $=
       ( nfcv nfv cbvrabcsf ) ABCDEFDEICFIADJBCJGHK $.
   $}

Please, consider that the theorems just below cbvrabv2.2  also have this line
Siliprandi, 23-Oct-2021.)  $)
but the double space is not removed.

Any advice?

Glauco

**Comment by glacode** [comment]
In my comment above, I see that  - + have been converted to dots.
For every couple of dots, the first one is a - and the second one is a +

**Comment by benjub** [comment]
The script I use (the first one following "or in one line, for ease of copypasting:" on https://github.com/metamath/set.mm/blob/develop/CONTRIBUTING.md) correctly removes all double spaces, apparently all 185 of them (I searched `.)  $)` (with a double space instead of the single space due to formatting) in the diff file). Are you using that same script ?

**Comment by avekens** [comment]
In my current version of set.mm (for which I created a PR #2283 already), there are 185 lines with ".)  $)" at the end of a comment (i.e a double space before the closing $.). I am quite sure that I performed a write source set.mm/rewrap, but I had many problems merging the new theorems of Glauco into my version. Performing write source set.mm/rewrap again, will remove the superfluous spaces. 

@glacode we should coordinate who of us will do this clean up. I can do it after my current PR is accepted and merged

**Comment by glacode** [comment]
@benjub  my script seems to be exactly the one "or in one line, for ease of copypasting:"
I've pasted my one line command above: the only difference seems to be I open a log file (and, of course, use my local path to set.mm)
My best guess is that I did the commit before running "your" script (sorry, but I have your name in my bash file :-) )

@avekens  yes, please, go on and try to do the cleanup to my mathbox also, I'll pull the result, run the reformatting script, and hopefully get an empty diff, after that

Thanks everyone

Glauco

**Comment by benjub** [comment]
By the way: the script is due to @nmegill !

**Pull request merged**
