### PR TITLE
reduce axiom usage in exan

### PR DESCRIPTION
**Pull request by wlammen**

### CODE REVIEW

**Comment by benjub** [comment]
I found a proof of exan from ax-1--ax-4. Should I keep yours as OLD or replace it, @wlammen ?

13     simpli.1=bj-exan.1 $e |- ( E. x ph /\ ps )
14   min=simpli         $p |- E. x ph
34       aleximi.1=pm3.21   $p |- ( ps -> ( ph -> ( ph /\ ps ) ) )
35     mpg.1=aleximi      $p |- ( A. x ps -> ( E. x ph -> E. x ( ph /\ ps ) ) )
40       simpri.1=bj-exan.1 $e |- ( E. x ph /\ ps )
41     mpg.2=simpri       $p |- ps
42   maj=mpg            $p |- ( E. x ph -> E. x ( ph /\ ps ) )
43 bj-exan=ax-mp      $a |- E. x ( ph /\ ps )
---------Clip out the proof below this line to put it in the source file:
      ( wex wa simpli wi pm3.21 aleximi simpri mpg ax-mp ) ACEZABFZCEZNBDGBNPHC
      BAOCBAIJNBDKLM $.

**Comment by wlammen** [comment]
@benjub Replace

**Comment by benjub** [comment]
@wlammen Done in #2070 (but I think your 19.41-1 from this PR is worth keeping).

**Comment by nmegill** [comment]
@wlammen There are merge conflicts w/ @benjub's previous PR.

**Comment by wlammen** [comment]
fixed

**Pull request merged**
