### PR TITLE
Move earlier

### PR DESCRIPTION
**Pull request by benjub**
Continuation of #1525 .  I mainly add links/precisions to existing comments. @nmegill : I hope you're ok with this style (see also commit message)?  I plan to continue in the same way.

Can I move from my mathbox to main: bj-eximal, bj-alimex, bj-ala1, bj-exa1. Indeed, they might be useful lemmas (although I haven't tried a global "minimize" with them), and they depend on very few axioms, so they would help me in my next two tasks: 1) removing some axiom dependencies in 19.xx(v) statements, and (later) 2) implement the new definition df-bj-nf.

Also, can I move from Glauco's mathbox pirp2: this is also Jim's pirp (which I had to duplicate at some point as bj-pirp). As for credits, I would write "contributed by @jkingdon , shortened by @glacode " if you see fit and they agree.

### CODE REVIEW

**Comment by jkingdon** [comment]
No need to worry about whether or not I'm listed as a contributor for `pirp`. Especially for things this trivial, I guess I'd lean towards whoever did it first, and no need to mention shortenings? Or whoever did the current/best version, and no need to mention earlier versions? Whatever people decide is OK with me.

**Comment by benjub** [comment]
@nmegill : Can I also move to main 3ax4 / bj-al2im : two contributors arrived independently at the same result, which IIRC is a reason to moving it to main.

bj-19.40b: its comment shows why it is an "omission" from main.

**Comment by nmegill** [comment]
> Continuation of #1525 . I mainly add links/precisions to existing comments. @nmegill : I hope you're ok with this style (see also commit message)? I plan to continue in the same way.

I believe what you are doing is removing the Margaris ref except in the main 19.* theorem, then referencing the main 19.* theorem in each variant.  One reason I put Margaris in each one was so that all variants would appear on the mmbibio.html page, so that the variants of the theorem would be listed along with the main theorem.  However, practically speaking people (myself included) would just use e.g. 'show statement *19.26*' or 'search * 19.26/c' to see the 19.26 variants.  So I guess it's ok what you are doing and will go along with it.

> 
> Can I move from my mathbox to main: bj-eximal, bj-alimex, bj-ala1, bj-exa1. Indeed, they might be useful lemmas (although I haven't tried a global "minimize" with them), and they depend on very few axioms, so they would help me in my next two tasks: 1) removing some axiom dependencies in 19.xx(v) statements, and (later) 2) implement the new definition df-bj-nf.

Go ahead and do this.  It would be interesting to use them for 'minimize' if you have time.

> 
> Also, can I move from Glauco's mathbox pirp2: this is also Jim's pirp (which I had to duplicate at some point as bj-pirp). As for credits, I would write "contributed by @jkingdon , shortened by @glacode " if you see fit and they agree.

Go ahead.

> Can I also move to main 3ax4 / bj-al2im : two contributors arrived independently at the same result, which IIRC is a reason to moving it to main.

Go ahead.

**Comment by wlammen** [comment]
It is possible to reduce the dependencies on 19.41v 19.42v eeanv likewise to finally reduce usage of axioms in theorems like mo2v, too. Have you got plans in that direction?

**Comment by benjub** [comment]
@wlammen Yes, this is my plan. I will first do 19.41v and 19.42v as indicated at https://github.com/metamath/set.mm/pull/1516#issue-385074832 .  I will not look at eu* and mo* yet, but eventually, I plan to look at this. Unless you have plans or have done some things locally ? How do you want to coordinate ?

**Comment by wlammen** [comment]
@benjub I am too busy with my work to contribute anything considerable in near future. I thought about the above mentioned development when I was forced to abandon my own plans wrt axiom usage in January. 19.41v was the next to address after 19.36v then, that's why I asked.

**Pull request merged**
